function [modelPath, referenceResult] = build_battery_rc_simulink_model(...
        outputDirectory, profile, parameters, sampleTime_s)
%BUILD_BATTERY_RC_SIMULINK_MODEL Generate the native battery RC reference.

modelDirectory = fileparts(mfilename('fullpath'));
referenceDirectory = fullfile(modelDirectory, '..', 'battery-rc-model');
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(referenceDirectory);

if nargin < 1 || isempty(outputDirectory)
    outputDirectory = fullfile(tempdir, 'matlab-simulink-energy-lab');
end
if nargin < 2 || isempty(profile)
    profilePath = fullfile(referenceDirectory, 'data', ...
        'pulse_current_profile.csv');
    profile = readtable(profilePath);
end
if nargin < 3 || isempty(parameters)
    parameters = battery_rc_default_parameters();
end
if nargin < 4 || isempty(sampleTime_s)
    sampleTime_s = 1;
end

validate_output_directory(outputDirectory);
referenceResult = simulate_battery_rc_model(...
    profile, parameters, sampleTime_s);
if isempty(ver('simulink')) || ~license('test', 'Simulink')
    error('BatteryRCSimulink:SimulinkUnavailable', ...
        'Building this model requires an available Simulink license.');
end

outputDirectory = char(outputDirectory);
if ~isfolder(outputDirectory)
    [created, message] = mkdir(outputDirectory);
    if ~created
        error('BatteryRCSimulink:OutputDirectory', ...
            'Could not create output directory: %s', message);
    end
end

modelName = 'battery_rc_simulink_model';
modelPath = fullfile(outputDirectory, [modelName, '.slx']);
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if isfile(modelPath)
    delete(modelPath);
end

new_system(modelName);
modelCleanup = onCleanup(@() close_model_if_loaded(modelName));
numberText = @(value) sprintf('%.17g', value);
vectorText = @(value) mat2str(value(:)', 17);
profileText = mat2str([referenceResult.time_s, ...
    referenceResult.current_A], 17);
outputTimesText = vectorText(referenceResult.time_s);
maximumStep_s = sampleTime_s / 20;

set_param(modelName, ...
    'SolverType', 'Variable-step', ...
    'Solver', 'ode45', ...
    'StartTime', '0', ...
    'StopTime', numberText(referenceResult.time_s(end)), ...
    'MaxStep', numberText(maximumStep_s), ...
    'RelTol', '1e-10', ...
    'AbsTol', '1e-12', ...
    'OutputOption', 'SpecifiedOutputTimes', ...
    'OutputTimes', outputTimesText, ...
    'ReturnWorkspaceOutputs', 'on', ...
    'SaveTime', 'on', ...
    'TimeSaveName', 'tout', ...
    'SaveOutput', 'on', ...
    'OutputSaveName', 'yout', ...
    'SaveFormat', 'Dataset');

add_block('simulink/Sources/From Workspace', ...
    [modelName, '/Applied current profile'], ...
    'VariableName', profileText, ...
    'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value', ...
    'ZeroCross', 'on', ...
    'Position', [30, 125, 145, 165]);

add_block('simulink/Math Operations/Gain', [modelName, '/SOC rate'], ...
    'Gain', numberText(-1 / (parameters.capacity_Ah * 3600)), ...
    'Position', [205, 35, 295, 65]);
add_block('simulink/Continuous/Integrator', [modelName, '/SOC'], ...
    'InitialCondition', numberText(parameters.initial_soc), ...
    'LimitOutput', 'on', ...
    'UpperSaturationLimit', '1', ...
    'LowerSaturationLimit', '0', ...
    'Position', [340, 30, 375, 70]);
add_block('simulink/Lookup Tables/1-D Lookup Table', ...
    [modelName, '/OCV lookup'], ...
    'Table', vectorText(parameters.ocv_lookup_V), ...
    'BreakpointsForDimension1', ...
    vectorText(parameters.ocv_soc_breakpoints), ...
    'InterpMethod', 'Linear point-slope', ...
    'ExtrapMethod', 'Clip', ...
    'Position', [425, 25, 535, 75]);

add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Polarization input'], ...
    'Gain', numberText(1 / parameters.c1_F), ...
    'Position', [205, 215, 295, 245]);
add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Polarization balance'], ...
    'Inputs', '+-', ...
    'Position', [340, 205, 370, 265]);
add_block('simulink/Continuous/Integrator', ...
    [modelName, '/RC polarization voltage'], ...
    'InitialCondition', '0', ...
    'Position', [425, 215, 460, 255]);
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Polarization decay'], ...
    'Gain', numberText(1 / (parameters.r1_Ohm * parameters.c1_F)), ...
    'Position', [205, 305, 295, 335]);

add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Ohmic voltage drop'], ...
    'Gain', numberText(parameters.r0_Ohm), ...
    'Position', [205, 125, 295, 155]);
add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Terminal voltage balance'], ...
    'Inputs', '+--', ...
    'Position', [590, 115, 620, 185]);

add_output_and_logger(modelName, 'Current', 'current_A', 1, ...
    [700, 25, 730, 45], [750, 20, 850, 50]);
add_output_and_logger(modelName, 'State of charge', 'soc', 2, ...
    [700, 75, 730, 95], [750, 70, 850, 100]);
add_output_and_logger(modelName, 'Open circuit voltage', 'ocv_V', 3, ...
    [700, 125, 730, 145], [750, 120, 850, 150]);
add_output_and_logger(modelName, 'Polarization voltage', 'v_rc_V', 4, ...
    [700, 215, 730, 235], [750, 210, 850, 240]);
add_output_and_logger(modelName, 'Terminal voltage', ...
    'terminal_voltage_V', 5, ...
    [700, 165, 730, 185], [750, 160, 850, 190]);

add_line(modelName, 'Applied current profile/1', 'SOC rate/1', ...
    'autorouting', 'on');
add_line(modelName, 'SOC rate/1', 'SOC/1', 'autorouting', 'on');
add_line(modelName, 'SOC/1', 'OCV lookup/1', 'autorouting', 'on');
add_line(modelName, 'Applied current profile/1', ...
    'Polarization input/1', 'autorouting', 'on');
add_line(modelName, 'Polarization input/1', ...
    'Polarization balance/1', 'autorouting', 'on');
add_line(modelName, 'Polarization balance/1', ...
    'RC polarization voltage/1', 'autorouting', 'on');
add_line(modelName, 'RC polarization voltage/1', ...
    'Polarization decay/1', 'autorouting', 'on');
add_line(modelName, 'Polarization decay/1', ...
    'Polarization balance/2', 'autorouting', 'on');
add_line(modelName, 'Applied current profile/1', ...
    'Ohmic voltage drop/1', 'autorouting', 'on');
add_line(modelName, 'OCV lookup/1', 'Terminal voltage balance/1', ...
    'autorouting', 'on');
add_line(modelName, 'Ohmic voltage drop/1', ...
    'Terminal voltage balance/2', 'autorouting', 'on');
add_line(modelName, 'RC polarization voltage/1', ...
    'Terminal voltage balance/3', 'autorouting', 'on');

add_line(modelName, 'Applied current profile/1', 'Current/1', ...
    'autorouting', 'on');
add_line(modelName, 'Applied current profile/1', 'Log Current/1', ...
    'autorouting', 'on');
add_line(modelName, 'SOC/1', 'State of charge/1', 'autorouting', 'on');
add_line(modelName, 'SOC/1', 'Log State of charge/1', ...
    'autorouting', 'on');
add_line(modelName, 'OCV lookup/1', 'Open circuit voltage/1', ...
    'autorouting', 'on');
add_line(modelName, 'OCV lookup/1', 'Log Open circuit voltage/1', ...
    'autorouting', 'on');
add_line(modelName, 'RC polarization voltage/1', ...
    'Polarization voltage/1', 'autorouting', 'on');
add_line(modelName, 'RC polarization voltage/1', ...
    'Log Polarization voltage/1', 'autorouting', 'on');
add_line(modelName, 'Terminal voltage balance/1', ...
    'Terminal voltage/1', 'autorouting', 'on');
add_line(modelName, 'Terminal voltage balance/1', ...
    'Log Terminal voltage/1', 'autorouting', 'on');

set_param(modelName, 'SimulationCommand', 'update');
save_system(modelName, modelPath);
clear modelCleanup pathCleanup;
end

function add_output_and_logger(modelName, outputName, variableName, ...
        portNumber, outputPosition, loggerPosition)
add_block('simulink/Sinks/Out1', [modelName, '/', outputName], ...
    'Port', num2str(portNumber), 'Position', outputPosition);
add_block('simulink/Sinks/To Workspace', ...
    [modelName, '/Log ', outputName], ...
    'VariableName', variableName, ...
    'SaveFormat', 'Timeseries', ...
    'MaxDataPoints', 'inf', ...
    'Decimation', '1', ...
    'Position', loggerPosition);
end

function validate_output_directory(outputDirectory)
isScalarText = ischar(outputDirectory) || ...
    (isstring(outputDirectory) && isscalar(outputDirectory));
if ~isScalarText || strlength(string(outputDirectory)) == 0
    error('BatteryRCSimulink:OutputDirectory', ...
        'Output directory must be a nonempty character vector or string.');
end
end

function close_model_if_loaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
