%% Native Simulink Battery RC Check
% Builds and validates canonical and nonlinear-OCV generated models.

clearvars; clc;

modelDirectory = fileparts(mfilename('fullpath'));
referenceDirectory = fullfile(modelDirectory, '..', 'battery-rc-model');
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory, referenceDirectory);

assert(~isempty(ver('simulink')) && license('test', 'Simulink'), ...
    'The native battery RC check requires Simulink.');

temporaryDirectory = tempname;
mkdir(temporaryDirectory);
modelName = 'battery_rc_simulink_model';

defaultDirectory = fullfile(temporaryDirectory, 'default');
[defaultModelPath, defaultReference] = ...
    build_battery_rc_simulink_model(defaultDirectory);
cleanup = onCleanup(@() clean_generated_model(modelName, temporaryDirectory));
assert(isfile(defaultModelPath), ...
    'The builder must create a real battery RC SLX model file.');
load_system(defaultModelPath);

expectedBlocks = {
    'Applied current profile', 'FromWorkspace'; ...
    'SOC rate', 'Gain'; ...
    'SOC', 'Integrator'; ...
    'OCV lookup', 'Lookup_n-D'; ...
    'Polarization input', 'Gain'; ...
    'Polarization balance', 'Sum'; ...
    'RC polarization voltage', 'Integrator'; ...
    'Polarization decay', 'Gain'; ...
    'Ohmic voltage drop', 'Gain'; ...
    'Terminal voltage balance', 'Sum'; ...
    'Current', 'Outport'; ...
    'State of charge', 'Outport'; ...
    'Open circuit voltage', 'Outport'; ...
    'Polarization voltage', 'Outport'; ...
    'Terminal voltage', 'Outport'; ...
    'Log Current', 'ToWorkspace'; ...
    'Log State of charge', 'ToWorkspace'; ...
    'Log Open circuit voltage', 'ToWorkspace'; ...
    'Log Polarization voltage', 'ToWorkspace'; ...
    'Log Terminal voltage', 'ToWorkspace'
};
for blockIndex = 1:size(expectedBlocks, 1)
    blockPath = [modelName, '/', expectedBlocks{blockIndex, 1}];
    assert(strcmp(get_param(blockPath, 'BlockType'), ...
        expectedBlocks{blockIndex, 2}), ...
        'Generated battery model contains an unexpected block type.');
end

assert_connection(modelName, 'Applied current profile', 1, 'SOC rate', 1);
assert_connection(modelName, 'SOC rate', 1, 'SOC', 1);
assert_connection(modelName, 'SOC', 1, 'OCV lookup', 1);
assert_connection(modelName, 'Applied current profile', 1, ...
    'Polarization input', 1);
assert_connection(modelName, 'Polarization input', 1, ...
    'Polarization balance', 1);
assert_connection(modelName, 'Polarization decay', 1, ...
    'Polarization balance', 2);
assert_connection(modelName, 'Polarization balance', 1, ...
    'RC polarization voltage', 1);
assert_connection(modelName, 'OCV lookup', 1, ...
    'Terminal voltage balance', 1);
assert_connection(modelName, 'Ohmic voltage drop', 1, ...
    'Terminal voltage balance', 2);
assert_connection(modelName, 'RC polarization voltage', 1, ...
    'Terminal voltage balance', 3);

assert(strcmp(get_param([modelName, '/Applied current profile'], ...
    'Interpolate'), 'off'), ...
    'Current input must use zero-order hold interpolation.');
assert(strcmp(get_param([modelName, '/OCV lookup'], 'InterpMethod'), ...
    'Linear point-slope') && ...
    strcmp(get_param([modelName, '/OCV lookup'], 'ExtrapMethod'), 'Clip'), ...
    'OCV lookup must use linear interpolation and clipped extrapolation.');
assert(strcmp(get_param([modelName, '/SOC'], 'LimitOutput'), 'on') && ...
    strcmp(get_param([modelName, '/SOC'], 'UpperSaturationLimit'), '1') && ...
    strcmp(get_param([modelName, '/SOC'], 'LowerSaturationLimit'), '0'), ...
    'SOC integrator must enforce the physical state interval.');

set_param(modelName, 'SimulationCommand', 'update');
defaultMetrics = compare_model_to_reference(...
    modelName, defaultReference);
close_system(modelName, 0);

customProfile = table(...
    [0; 2; 4; 6], ...
    [20; -10; 5; 0], ...
    'VariableNames', {'time_s', 'current_A'});
customParameters = battery_rc_default_parameters();
customParameters.initial_soc = 0.65;
customParameters.ocv_lookup_V = [3.10; 3.42; 3.57; 3.68; 3.86; 4.15];
customDirectory = fullfile(temporaryDirectory, 'custom');
[customModelPath, customReference] = build_battery_rc_simulink_model(...
    customDirectory, customProfile, customParameters, 0.1);
load_system(customModelPath);
set_param(modelName, 'SimulationCommand', 'update');
customMetrics = compare_model_to_reference(modelName, customReference);
assert(max(customReference.ocv_V) - min(customReference.ocv_V) > 1e-5, ...
    'Custom case must exercise the nonlinear OCV lookup.');
close_system(modelName, 0);

invalidParameters = battery_rc_default_parameters();
invalidParameters.capacity_Ah = 0;
invalidParameterRejected = false;
try
    build_battery_rc_simulink_model(...
        temporaryDirectory, customProfile, invalidParameters, 0.1);
catch validationError
    invalidParameterRejected = strcmp(validationError.identifier, ...
        'BatteryRC:Parameters');
end
assert(invalidParameterRejected, ...
    'Builder must preserve the reference model parameter validation.');

verify_loaded_model_collision(modelName, @(directory) ...
    build_battery_rc_simulink_model(...
    directory, customProfile, customParameters, 0.1), ...
    'BatteryRCSimulink:ModelAlreadyLoaded', 'cleanSaved');
verify_loaded_model_collision(modelName, @(directory) ...
    build_battery_rc_simulink_model(...
    directory, customProfile, customParameters, 0.1), ...
    'BatteryRCSimulink:ModelAlreadyLoaded', 'unsaved');
verify_loaded_model_collision(modelName, @(directory) ...
    build_battery_rc_simulink_model(...
    directory, customProfile, customParameters, 0.1), ...
    'BatteryRCSimulink:ModelAlreadyLoaded', 'dirtySaved');

maximumCurrentError_A = max(defaultMetrics.current_error_A, ...
    customMetrics.current_error_A);
maximumSocError = max(defaultMetrics.soc_error, customMetrics.soc_error);
maximumPolarizationError_V = max(...
    defaultMetrics.polarization_error_V, ...
    customMetrics.polarization_error_V);
maximumOcvError_V = max(defaultMetrics.ocv_error_V, ...
    customMetrics.ocv_error_V);
maximumTerminalError_V = max(defaultMetrics.terminal_error_V, ...
    customMetrics.terminal_error_V);

fprintf('Native Simulink battery RC check passed.\n');
fprintf('Final SOC: %.3f\n', defaultReference.soc(end));
fprintf('Voltage range: %.3f V to %.3f V\n', ...
    min(defaultReference.terminal_voltage_V), ...
    max(defaultReference.terminal_voltage_V));
fprintf(['Maximum parity errors: %.3e A, %.3e SOC, %.3e Vrc, ', ...
    '%.3e OCV, %.3e Vterminal\n'], ...
    maximumCurrentError_A, maximumSocError, ...
    maximumPolarizationError_V, maximumOcvError_V, ...
    maximumTerminalError_V);

function metrics = compare_model_to_reference(modelName, referenceResult)
simulationOutput = sim(modelName);
current = simulationOutput.get('current_A');
soc = simulationOutput.get('soc');
ocv = simulationOutput.get('ocv_V');
polarization = simulationOutput.get('v_rc_V');
terminalVoltage = simulationOutput.get('terminal_voltage_V');

signals = {current; soc; ocv; polarization; terminalVoltage};
for signalIndex = 1:numel(signals)
    signal = signals{signalIndex};
    assert(isa(signal, 'timeseries'), ...
        'Every generated battery output must be a timeseries.');
    assert(numel(signal.Time) == numel(referenceResult.time_s) && ...
        max(abs(signal.Time(:) - referenceResult.time_s)) < 1e-12, ...
        'Generated battery outputs must use the reference time grid.');
    assert(all(isfinite(signal.Data(:))), ...
        'Generated battery outputs must remain finite.');
end

metrics.current_error_A = max(abs(...
    current.Data(:) - referenceResult.current_A));
metrics.soc_error = max(abs(soc.Data(:) - referenceResult.soc));
metrics.ocv_error_V = max(abs(ocv.Data(:) - referenceResult.ocv_V));
metrics.polarization_error_V = max(abs(...
    polarization.Data(:) - referenceResult.v_rc_V));
metrics.terminal_error_V = max(abs(...
    terminalVoltage.Data(:) - referenceResult.terminal_voltage_V));

assert(metrics.current_error_A < 1e-12, ...
    'Generated model current differs from the applied reference profile.');
assert(metrics.soc_error < 1e-8, ...
    'Generated model SOC differs from the exact reference state.');
assert(metrics.polarization_error_V < 1e-8, ...
    'Generated model polarization differs from the exact RC state.');
assert(metrics.ocv_error_V < 1e-8, ...
    'Generated model OCV differs from the reference lookup.');
assert(metrics.terminal_error_V < 1e-7, ...
    'Generated model terminal voltage differs from the reference balance.');
end

function assert_connection(modelName, sourceBlock, sourcePort, ...
        destinationBlock, destinationPort)
sourceHandles = get_param([modelName, '/', sourceBlock], 'PortHandles');
destinationHandles = get_param(...
    [modelName, '/', destinationBlock], 'PortHandles');
lineHandle = get_param(destinationHandles.Inport(destinationPort), 'Line');
assert(lineHandle ~= -1 && ...
    get_param(lineHandle, 'SrcPortHandle') == ...
    sourceHandles.Outport(sourcePort), ...
    'Generated battery model contains an incorrect or missing connection.');
end

function clean_generated_model(modelName, temporaryDirectory)
close_model_if_owned(modelName, temporaryDirectory);
if isfolder(temporaryDirectory)
    rmdir(temporaryDirectory, 's');
end
end

function verify_loaded_model_collision(modelName, buildFunction, errorId, ...
        fixtureState)
assert(~bdIsLoaded(modelName), ...
    'Collision fixture must not replace a pre-existing caller model.');
sourceDirectory = tempname;
targetDirectory = tempname;
mkdir(sourceDirectory);
mkdir(targetDirectory);
sourcePath = fullfile(sourceDirectory, [modelName, '.slx']);
targetPath = fullfile(targetDirectory, [modelName, '.slx']);
targetBytes = uint8([17, 34, 51, 68]);
write_binary_file(targetPath, targetBytes);
new_system(modelName);
modelHandle = get_param(modelName, 'Handle');
cleanup = onCleanup(@() clean_collision_fixture( ...
    modelName, modelHandle, sourceDirectory, targetDirectory));
isSaved = strcmp(fixtureState, 'cleanSaved') || ...
    strcmp(fixtureState, 'dirtySaved');
hasSentinel = strcmp(fixtureState, 'unsaved') || ...
    strcmp(fixtureState, 'dirtySaved');
sourceBytes = uint8.empty(0, 1);
if isSaved
    save_system(modelName, sourcePath);
    sourceBytes = read_binary_file(sourcePath);
end
if hasSentinel
    add_block('simulink/Sources/Constant', [modelName, '/Caller sentinel'], ...
        'Value', '123', 'Position', [30, 30, 100, 60]);
    modelWorkspace = get_param(modelName, 'ModelWorkspace');
    assignin(modelWorkspace, 'callerSentinel', 42);
end
expectedDirty = get_param(modelName, 'Dirty');
if strcmp(fixtureState, 'cleanSaved')
    assert(strcmp(expectedDirty, 'off'), ...
        'Clean saved collision fixture must start clean.');
else
    assert(strcmp(expectedDirty, 'on'), ...
        'Dirty or unsaved collision fixture must start dirty.');
end

collisionRejected = false;
try
    buildFunction(targetDirectory);
catch buildError
    collisionRejected = strcmp(buildError.identifier, errorId);
end
assert(collisionRejected, ...
    'Builder must reject a same-name model that is already loaded.');
assert(bdIsLoaded(modelName), 'Loaded caller model must remain loaded.');
assert(get_param(modelName, 'Handle') == modelHandle, ...
    'Loaded caller model handle must remain unchanged.');
assert(strcmp(get_param(modelName, 'Dirty'), expectedDirty), ...
    'Loaded caller model dirty state must remain unchanged.');
if isSaved
    assert(strcmpi(get_param(modelName, 'FileName'), sourcePath), ...
        'Loaded caller model path must remain unchanged.');
    assert(isequal(read_binary_file(sourcePath), sourceBytes), ...
        'Loaded caller model file bytes must remain unchanged.');
else
    assert(strcmp(get_param(modelName, 'FileName'), ''), ...
        'Unsaved caller model must remain unsaved.');
    assert(~isfile(sourcePath), ...
        'Unsaved caller model must not gain a source file.');
end
if hasSentinel
    assert(strcmp(get_param([modelName, '/Caller sentinel'], 'Value'), '123'), ...
        'Loaded caller model content must remain unchanged.');
    assert(evalin(modelWorkspace, 'callerSentinel') == 42, ...
        'Loaded caller model workspace must remain unchanged.');
end
assert(isequal(read_binary_file(targetPath), targetBytes(:)), ...
    'Target model file must remain unchanged after rejection.');
clear cleanup;
end

function clean_collision_fixture(modelName, modelHandle, ...
        sourceDirectory, targetDirectory)
if bdIsLoaded(modelName) && ...
        get_param(modelName, 'Handle') == modelHandle
    close_system(modelName, 0);
end
if isfolder(sourceDirectory)
    rmdir(sourceDirectory, 's');
end
if isfolder(targetDirectory)
    rmdir(targetDirectory, 's');
end
end

function close_model_if_owned(modelName, directory)
if ~bdIsLoaded(modelName)
    return;
end
fileName = string(get_param(modelName, 'FileName'));
if strlength(fileName) == 0
    return;
end
rootDirectory = string(fullfile(directory, filesep));
if startsWith(fileName, rootDirectory, 'IgnoreCase', true)
    close_system(modelName, 0);
end
end

function write_binary_file(filePath, bytes)
fileIdentifier = fopen(filePath, 'w');
assert(fileIdentifier > 0, 'Could not create binary fixture file.');
fwrite(fileIdentifier, bytes, 'uint8');
fclose(fileIdentifier);
end

function bytes = read_binary_file(filePath)
fileIdentifier = fopen(filePath, 'r');
assert(fileIdentifier > 0, 'Could not open binary fixture file.');
bytes = fread(fileIdentifier, inf, '*uint8');
fclose(fileIdentifier);
end
