function [modelPath, referenceResult] = build_battery_2rc_simulink_model(...
        outputDirectory, profile, parameters, sampleTime_s)
%BUILD_BATTERY_2RC_SIMULINK_MODEL Generate the native battery 2RC reference.

modelDirectory = fileparts(mfilename('fullpath'));
referenceDirectory = fullfile(modelDirectory, '..', 'battery-2rc-model');
baseReferenceDirectory = fullfile(modelDirectory, '..', 'battery-rc-model');
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(referenceDirectory, baseReferenceDirectory);

if nargin < 1 || isempty(outputDirectory)
    outputDirectory = fullfile(tempdir, 'matlab-simulink-energy-lab');
end
if nargin < 2 || isempty(profile)
    profilePath = fullfile(baseReferenceDirectory, 'data', ...
        'pulse_current_profile.csv');
    profile = readtable(profilePath);
end
if nargin < 3 || isempty(parameters)
    parameters = battery_2rc_default_parameters();
end
if nargin < 4 || isempty(sampleTime_s)
    sampleTime_s = 1;
end

validate_output_directory(outputDirectory);
referenceResult = simulate_battery_2rc_model(...
    profile, parameters, sampleTime_s);
if isempty(ver('simulink')) || ~license('test', 'Simulink')
    error('Battery2RCSimulink:SimulinkUnavailable', ...
        'Building this model requires an available Simulink license.');
end

outputDirectory = char(outputDirectory);
if ~isfolder(outputDirectory)
    [created, message] = mkdir(outputDirectory);
    if ~created
        error('Battery2RCSimulink:OutputDirectory', ...
            'Could not create output directory: %s', message);
    end
end

modelName = 'battery_2rc_simulink_model';
modelPath = fullfile(outputDirectory, [modelName, '.slx']);
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if isfile(modelPath)
    delete(modelPath);
end

new_system(modelName);
modelCleanup = onCleanup(@() close_model_if_loaded(modelName));
numberText = @(value) sprintf('%.17g', value);
vectorText = @(value) mat2str(value(:)', 17);
profileText = mat2str([referenceResult.time_s, ...
    referenceResult.current_A], 17);
outputTimesText = vectorText(referenceResult.time_s);
maximumStep_s = sampleTime_s / 20;

set_param(modelName, ...
    'SolverType', 'Variable-step', ...
    'Solver', 'ode45', ...
    'StartTime', '0', ...
    'StopTime', numberText(referenceResult.time_s(end)), ...
    'MaxStep', numberText(maximumStep_s), ...
    'RelTol', '1e-10', ...
    'AbsTol', '1e-12', ...
    'OutputOption', 'SpecifiedOutputTimes', ...
    'OutputTimes', outputTimesText, ...
    'ReturnWorkspaceOutputs', 'on', ...
    'SaveTime', 'on', ...
    'TimeSaveName', 'tout', ...
    'SaveOutput', 'on', ...
    'OutputSaveName', 'yout', ...
    'SaveFormat', 'Dataset');

add_block('simulink/Sources/From Workspace', ...
    [modelName, '/Applied current profile'], ...
    'VariableName', profileText, ...
    'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value', ...
    'ZeroCross', 'on', ...
    'Position', [30, 215, 145, 255]);

add_block('simulink/Math Operations/Gain', [modelName, '/SOC rate'], ...
    'Gain', numberText(-1 / (parameters.capacity_Ah * 3600)), ...
    'Position', [205, 35, 295, 65]);
add_block('simulink/Continuous/Integrator', [modelName, '/SOC'], ...
    'InitialCondition', numberText(parameters.initial_soc), ...
    'LimitOutput', 'on', ...
    'UpperSaturationLimit', '1', ...
    'LowerSaturationLimit', '0', ...
    'Position', [340, 30, 375, 70]);
add_block('simulink/Lookup Tables/1-D Lookup Table', ...
    [modelName, '/OCV lookup'], ...
    'Table', vectorText(parameters.ocv_lookup_V), ...
    'BreakpointsForDimension1', ...
    vectorText(parameters.ocv_soc_breakpoints), ...
    'InterpMethod', 'Linear point-slope', ...
    'ExtrapMethod', 'Clip', ...
    'Position', [425, 25, 535, 75]);

add_polarization_branch(modelName, 'Fast', parameters.r1_Ohm, ...
    parameters.c1_F, [205, 180, 295, 210], [340, 170, 370, 230], ...
    [425, 180, 460, 220], [205, 270, 295, 300], numberText);
add_polarization_branch(modelName, 'Slow', parameters.r2_Ohm, ...
    parameters.c2_F, [205, 350, 295, 380], [340, 340, 370, 400], ...
    [425, 350, 460, 390], [205, 440, 295, 470], numberText);

add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Ohmic voltage drop'], ...
    'Gain', numberText(parameters.r0_Ohm), ...
    'Position', [205, 105, 295, 135]);
add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Total polarization'], ...
    'Inputs', '++', ...
    'Position', [535, 265, 565, 345]);
add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Terminal voltage balance'], ...
    'Inputs', '+---', ...
    'Position', [625, 95, 655, 185]);

add_output_and_logger(modelName, 'Current', 'current_A', 1, ...
    [735, 25, 765, 45], [790, 20, 900, 50]);
add_output_and_logger(modelName, 'State of charge', 'soc', 2, ...
    [735, 75, 765, 95], [790, 70, 900, 100]);
add_output_and_logger(modelName, 'Open circuit voltage', 'ocv_V', 3, ...
    [735, 125, 765, 145], [790, 120, 900, 150]);
add_output_and_logger(modelName, 'Fast polarization', ...
    'v_rc1_V', 4, [735, 225, 765, 245], [790, 220, 900, 250]);
add_output_and_logger(modelName, 'Slow polarization', ...
    'v_rc2_V', 5, [735, 275, 765, 295], [790, 270, 900, 300]);
add_output_and_logger(modelName, 'Total polarization voltage', ...
    'v_polarization_V', 6, ...
    [735, 325, 765, 345], [790, 320, 900, 350]);
add_output_and_logger(modelName, 'Terminal voltage', ...
    'terminal_voltage_V', 7, ...
    [735, 175, 765, 195], [790, 170, 900, 200]);

add_line(modelName, 'Applied current profile/1', 'SOC rate/1', ...
    'autorouting', 'on');
add_line(modelName, 'SOC rate/1', 'SOC/1', 'autorouting', 'on');
add_line(modelName, 'SOC/1', 'OCV lookup/1', 'autorouting', 'on');
connect_polarization_branch(modelName, 'Fast');
connect_polarization_branch(modelName, 'Slow');
add_line(modelName, 'Applied current profile/1', ...
    'Ohmic voltage drop/1', 'autorouting', 'on');
add_line(modelName, 'Fast polarization voltage/1', ...
    'Total polarization/1', 'autorouting', 'on');
add_line(modelName, 'Slow polarization voltage/1', ...
    'Total polarization/2', 'autorouting', 'on');
add_line(modelName, 'OCV lookup/1', 'Terminal voltage balance/1', ...
    'autorouting', 'on');
add_line(modelName, 'Ohmic voltage drop/1', ...
    'Terminal voltage balance/2', 'autorouting', 'on');
add_line(modelName, 'Fast polarization voltage/1', ...
    'Terminal voltage balance/3', 'autorouting', 'on');
add_line(modelName, 'Slow polarization voltage/1', ...
    'Terminal voltage balance/4', 'autorouting', 'on');

connect_output_and_logger(modelName, 'Applied current profile', 'Current');
connect_output_and_logger(modelName, 'SOC', 'State of charge');
connect_output_and_logger(modelName, 'OCV lookup', 'Open circuit voltage');
connect_output_and_logger(modelName, 'Fast polarization voltage', ...
    'Fast polarization');
connect_output_and_logger(modelName, 'Slow polarization voltage', ...
    'Slow polarization');
connect_output_and_logger(modelName, 'Total polarization', ...
    'Total polarization voltage');
connect_output_and_logger(modelName, 'Terminal voltage balance', ...
    'Terminal voltage');

set_param(modelName, 'SimulationCommand', 'update');
save_system(modelName, modelPath);
clear modelCleanup pathCleanup;
end

function add_polarization_branch(modelName, branchName, resistance_Ohm, ...
        capacitance_F, inputPosition, balancePosition, statePosition, ...
        decayPosition, numberText)
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/', branchName, ' polarization input'], ...
    'Gain', numberText(1 / capacitance_F), ...
    'Position', inputPosition);
add_block('simulink/Math Operations/Sum', ...
    [modelName, '/', branchName, ' polarization balance'], ...
    'Inputs', '+-', ...
    'Position', balancePosition);
add_block('simulink/Continuous/Integrator', ...
    [modelName, '/', branchName, ' polarization voltage'], ...
    'InitialCondition', '0', ...
    'Position', statePosition);
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/', branchName, ' polarization decay'], ...
    'Gain', numberText(1 / (resistance_Ohm * capacitance_F)), ...
    'Position', decayPosition);
end

function connect_polarization_branch(modelName, branchName)
add_line(modelName, 'Applied current profile/1', ...
    [branchName, ' polarization input/1'], 'autorouting', 'on');
add_line(modelName, [branchName, ' polarization input/1'], ...
    [branchName, ' polarization balance/1'], 'autorouting', 'on');
add_line(modelName, [branchName, ' polarization balance/1'], ...
    [branchName, ' polarization voltage/1'], 'autorouting', 'on');
add_line(modelName, [branchName, ' polarization voltage/1'], ...
    [branchName, ' polarization decay/1'], 'autorouting', 'on');
add_line(modelName, [branchName, ' polarization decay/1'], ...
    [branchName, ' polarization balance/2'], 'autorouting', 'on');
end

function add_output_and_logger(modelName, outputName, variableName, ...
        portNumber, outputPosition, loggerPosition)
add_block('simulink/Sinks/Out1', [modelName, '/', outputName], ...
    'Port', num2str(portNumber), 'Position', outputPosition);
add_block('simulink/Sinks/To Workspace', ...
    [modelName, '/Log ', outputName], ...
    'VariableName', variableName, ...
    'SaveFormat', 'Timeseries', ...
    'MaxDataPoints', 'inf', ...
    'Decimation', '1', ...
    'Position', loggerPosition);
end

function connect_output_and_logger(modelName, sourceName, outputName)
add_line(modelName, [sourceName, '/1'], [outputName, '/1'], ...
    'autorouting', 'on');
add_line(modelName, [sourceName, '/1'], ['Log ', outputName, '/1'], ...
    'autorouting', 'on');
end

function validate_output_directory(outputDirectory)
isScalarText = ischar(outputDirectory) || ...
    (isstring(outputDirectory) && isscalar(outputDirectory));
if ~isScalarText || strlength(string(outputDirectory)) == 0
    error('Battery2RCSimulink:OutputDirectory', ...
        'Output directory must be a nonempty character vector or string.');
end
end

function close_model_if_loaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
