%% Native Simulink Battery 2RC Check
% Builds and validates canonical and custom generated two-RC models.

clear; clc;

modelDirectory = fileparts(mfilename('fullpath'));
referenceDirectory = fullfile(modelDirectory, '..', 'battery-2rc-model');
baseReferenceDirectory = fullfile(modelDirectory, '..', 'battery-rc-model');
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory, referenceDirectory, baseReferenceDirectory);

assert(~isempty(ver('simulink')) && license('test', 'Simulink'), ...
    'The native battery 2RC check requires Simulink.');

temporaryDirectory = tempname;
mkdir(temporaryDirectory);
modelName = 'battery_2rc_simulink_model';
cleanup = onCleanup(@() clean_generated_model(modelName, temporaryDirectory));

defaultDirectory = fullfile(temporaryDirectory, 'default');
[defaultModelPath, defaultReference] = ...
    build_battery_2rc_simulink_model(defaultDirectory);
assert(isfile(defaultModelPath), ...
    'The builder must create a real battery 2RC SLX model file.');
load_system(defaultModelPath);

expectedBlocks = {
    'Applied current profile', 'FromWorkspace'; ...
    'SOC rate', 'Gain'; ...
    'SOC', 'Integrator'; ...
    'OCV lookup', 'Lookup_n-D'; ...
    'Fast polarization input', 'Gain'; ...
    'Fast polarization balance', 'Sum'; ...
    'Fast polarization voltage', 'Integrator'; ...
    'Fast polarization decay', 'Gain'; ...
    'Slow polarization input', 'Gain'; ...
    'Slow polarization balance', 'Sum'; ...
    'Slow polarization voltage', 'Integrator'; ...
    'Slow polarization decay', 'Gain'; ...
    'Ohmic voltage drop', 'Gain'; ...
    'Total polarization', 'Sum'; ...
    'Terminal voltage balance', 'Sum'; ...
    'Current', 'Outport'; ...
    'State of charge', 'Outport'; ...
    'Open circuit voltage', 'Outport'; ...
    'Fast polarization', 'Outport'; ...
    'Slow polarization', 'Outport'; ...
    'Total polarization voltage', 'Outport'; ...
    'Terminal voltage', 'Outport'; ...
    'Log Current', 'ToWorkspace'; ...
    'Log State of charge', 'ToWorkspace'; ...
    'Log Open circuit voltage', 'ToWorkspace'; ...
    'Log Fast polarization', 'ToWorkspace'; ...
    'Log Slow polarization', 'ToWorkspace'; ...
    'Log Total polarization voltage', 'ToWorkspace'; ...
    'Log Terminal voltage', 'ToWorkspace'
};
for blockIndex = 1:size(expectedBlocks, 1)
    blockPath = [modelName, '/', expectedBlocks{blockIndex, 1}];
    assert(strcmp(get_param(blockPath, 'BlockType'), ...
        expectedBlocks{blockIndex, 2}), ...
        'Generated battery 2RC model contains an unexpected block type.');
end

assert_connection(modelName, 'Applied current profile', 1, 'SOC rate', 1);
assert_connection(modelName, 'SOC rate', 1, 'SOC', 1);
assert_connection(modelName, 'SOC', 1, 'OCV lookup', 1);
assert_branch_connections(modelName, 'Fast');
assert_branch_connections(modelName, 'Slow');
assert_connection(modelName, 'Fast polarization voltage', 1, ...
    'Total polarization', 1);
assert_connection(modelName, 'Slow polarization voltage', 1, ...
    'Total polarization', 2);
assert_connection(modelName, 'OCV lookup', 1, ...
    'Terminal voltage balance', 1);
assert_connection(modelName, 'Ohmic voltage drop', 1, ...
    'Terminal voltage balance', 2);
assert_connection(modelName, 'Fast polarization voltage', 1, ...
    'Terminal voltage balance', 3);
assert_connection(modelName, 'Slow polarization voltage', 1, ...
    'Terminal voltage balance', 4);

assert(strcmp(get_param([modelName, '/Applied current profile'], ...
    'Interpolate'), 'off'), ...
    'Current input must use zero-order hold interpolation.');
assert(strcmp(get_param([modelName, '/OCV lookup'], 'InterpMethod'), ...
    'Linear point-slope') && ...
    strcmp(get_param([modelName, '/OCV lookup'], 'ExtrapMethod'), 'Clip'), ...
    'OCV lookup must use linear interpolation and clipped extrapolation.');
assert(strcmp(get_param([modelName, '/SOC'], 'LimitOutput'), 'on') && ...
    strcmp(get_param([modelName, '/SOC'], 'UpperSaturationLimit'), '1') && ...
    strcmp(get_param([modelName, '/SOC'], 'LowerSaturationLimit'), '0'), ...
    'SOC integrator must enforce the physical state interval.');

defaultParameters = battery_2rc_default_parameters();
assert_gain(modelName, 'Fast polarization input', ...
    1 / defaultParameters.c1_F);
assert_gain(modelName, 'Fast polarization decay', ...
    1 / (defaultParameters.r1_Ohm * defaultParameters.c1_F));
assert_gain(modelName, 'Slow polarization input', ...
    1 / defaultParameters.c2_F);
assert_gain(modelName, 'Slow polarization decay', ...
    1 / (defaultParameters.r2_Ohm * defaultParameters.c2_F));

set_param(modelName, 'SimulationCommand', 'update');
defaultMetrics = compare_model_to_reference(modelName, defaultReference);
close_system(modelName, 0);

customProfile = table(...
    [0; 2; 4; 6], ...
    [20; -10; 5; 0], ...
    'VariableNames', {'time_s', 'current_A'});
customParameters = battery_2rc_default_parameters();
customParameters.initial_soc = 0.65;
customParameters.r1_Ohm = 0.0018;
customParameters.c1_F = 900;
customParameters.r2_Ohm = 0.0030;
customParameters.c2_F = 7000;
customParameters.ocv_lookup_V = [3.10; 3.42; 3.57; 3.68; 3.86; 4.15];
customDirectory = fullfile(temporaryDirectory, 'custom');
[customModelPath, customReference] = ...
    build_battery_2rc_simulink_model(...
        customDirectory, customProfile, customParameters, 0.1);
load_system(customModelPath);
set_param(modelName, 'SimulationCommand', 'update');
customMetrics = compare_model_to_reference(modelName, customReference);
assert(max(customReference.ocv_V) - min(customReference.ocv_V) > 1e-5, ...
    'Custom case must exercise the nonlinear OCV lookup.');
assert(max(abs(customReference.v_rc1_V)) > ...
    max(abs(customReference.v_rc2_V)), ...
    'Custom case must exercise distinct fast and slow branch responses.');
close_system(modelName, 0);

invalidParameters = battery_2rc_default_parameters();
invalidParameters.r2_Ohm = 0;
invalidParameterRejected = false;
try
    build_battery_2rc_simulink_model(...
        temporaryDirectory, customProfile, invalidParameters, 0.1);
catch validationError
    invalidParameterRejected = strcmp(validationError.identifier, ...
        'Battery2RC:Parameters');
end
assert(invalidParameterRejected, ...
    'Builder must preserve second-branch parameter validation.');

maximumCurrentError_A = max(defaultMetrics.current_error_A, ...
    customMetrics.current_error_A);
maximumSocError = max(defaultMetrics.soc_error, customMetrics.soc_error);
maximumFastError_V = max(defaultMetrics.fast_error_V, ...
    customMetrics.fast_error_V);
maximumSlowError_V = max(defaultMetrics.slow_error_V, ...
    customMetrics.slow_error_V);
maximumTotalError_V = max(defaultMetrics.total_error_V, ...
    customMetrics.total_error_V);
maximumOcvError_V = max(defaultMetrics.ocv_error_V, ...
    customMetrics.ocv_error_V);
maximumTerminalError_V = max(defaultMetrics.terminal_error_V, ...
    customMetrics.terminal_error_V);

fprintf('Native Simulink battery 2RC check passed.\n');
fprintf('Final SOC: %.3f\n', defaultReference.soc(end));
fprintf('Voltage range: %.3f V to %.3f V\n', ...
    min(defaultReference.terminal_voltage_V), ...
    max(defaultReference.terminal_voltage_V));
fprintf(['Maximum parity errors: %.3e A, %.3e SOC, %.3e Vrc1, ', ...
    '%.3e Vrc2, %.3e Vpolarization, %.3e OCV, %.3e Vterminal\n'], ...
    maximumCurrentError_A, maximumSocError, maximumFastError_V, ...
    maximumSlowError_V, maximumTotalError_V, maximumOcvError_V, ...
    maximumTerminalError_V);

function metrics = compare_model_to_reference(modelName, referenceResult)
simulationOutput = sim(modelName);
current = simulationOutput.get('current_A');
soc = simulationOutput.get('soc');
ocv = simulationOutput.get('ocv_V');
fastPolarization = simulationOutput.get('v_rc1_V');
slowPolarization = simulationOutput.get('v_rc2_V');
totalPolarization = simulationOutput.get('v_polarization_V');
terminalVoltage = simulationOutput.get('terminal_voltage_V');

signals = {current; soc; ocv; fastPolarization; slowPolarization; ...
    totalPolarization; terminalVoltage};
for signalIndex = 1:numel(signals)
    signal = signals{signalIndex};
    assert(isa(signal, 'timeseries'), ...
        'Every generated battery 2RC output must be a timeseries.');
    assert(numel(signal.Time) == numel(referenceResult.time_s) && ...
        max(abs(signal.Time(:) - referenceResult.time_s)) < 1e-12, ...
        'Generated battery 2RC outputs must use the reference time grid.');
    assert(all(isfinite(signal.Data(:))), ...
        'Generated battery 2RC outputs must remain finite.');
end

metrics.current_error_A = max(abs(...
    current.Data(:) - referenceResult.current_A));
metrics.soc_error = max(abs(soc.Data(:) - referenceResult.soc));
metrics.ocv_error_V = max(abs(ocv.Data(:) - referenceResult.ocv_V));
metrics.fast_error_V = max(abs(...
    fastPolarization.Data(:) - referenceResult.v_rc1_V));
metrics.slow_error_V = max(abs(...
    slowPolarization.Data(:) - referenceResult.v_rc2_V));
metrics.total_error_V = max(abs(...
    totalPolarization.Data(:) - referenceResult.v_polarization_V));
metrics.terminal_error_V = max(abs(...
    terminalVoltage.Data(:) - referenceResult.terminal_voltage_V));

assert(max(abs(totalPolarization.Data(:) - ...
    fastPolarization.Data(:) - slowPolarization.Data(:))) < 1e-12, ...
    'Total polarization must equal the two simulated branch states.');
assert(metrics.current_error_A < 1e-12, ...
    'Generated model current differs from the applied reference profile.');
assert(metrics.soc_error < 1e-8, ...
    'Generated model SOC differs from the exact reference state.');
assert(metrics.fast_error_V < 1e-8, ...
    'Generated model fast polarization differs from the exact state.');
assert(metrics.slow_error_V < 1e-8, ...
    'Generated model slow polarization differs from the exact state.');
assert(metrics.total_error_V < 2e-8, ...
    'Generated model total polarization differs from the exact state.');
assert(metrics.ocv_error_V < 1e-8, ...
    'Generated model OCV differs from the reference lookup.');
assert(metrics.terminal_error_V < 1e-7, ...
    'Generated model terminal voltage differs from the reference balance.');
end

function assert_branch_connections(modelName, branchName)
assert_connection(modelName, 'Applied current profile', 1, ...
    [branchName, ' polarization input'], 1);
assert_connection(modelName, [branchName, ' polarization input'], 1, ...
    [branchName, ' polarization balance'], 1);
assert_connection(modelName, [branchName, ' polarization decay'], 1, ...
    [branchName, ' polarization balance'], 2);
assert_connection(modelName, [branchName, ' polarization balance'], 1, ...
    [branchName, ' polarization voltage'], 1);
assert_connection(modelName, [branchName, ' polarization voltage'], 1, ...
    [branchName, ' polarization decay'], 1);
end

function assert_gain(modelName, blockName, expectedGain)
actualGain = str2double(get_param([modelName, '/', blockName], 'Gain'));
assert(isfinite(actualGain) && ...
    abs(actualGain - expectedGain) < 1e-14 * max(1, abs(expectedGain)), ...
    'Generated battery 2RC model contains an incorrect branch gain.');
end

function assert_connection(modelName, sourceBlock, sourcePort, ...
        destinationBlock, destinationPort)
sourceHandles = get_param([modelName, '/', sourceBlock], 'PortHandles');
destinationHandles = get_param(...
    [modelName, '/', destinationBlock], 'PortHandles');
lineHandle = get_param(destinationHandles.Inport(destinationPort), 'Line');
assert(lineHandle ~= -1 && ...
    get_param(lineHandle, 'SrcPortHandle') == ...
    sourceHandles.Outport(sourcePort), ...
    'Generated battery 2RC model has an incorrect or missing connection.');
end

function clean_generated_model(modelName, temporaryDirectory)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if isfolder(temporaryDirectory)
    rmdir(temporaryDirectory, 's');
end
end
