function parameters = bess_unified_control_parameters(overrides)
%BESS_UNIFIED_CONTROL_PARAMETERS Return validated educational parameters.
% Positive active power means BESS discharge/injection at the PCC.
% All controller and plant constants without a paper value are
% PROJECT_ASSUMPTION starter values documented in requirements/assumptions.md.

parameters.rated_power_VA = 10e6;
parameters.nominal_line_voltage_V = 690;
parameters.nominal_frequency_Hz = 50;
parameters.sample_time_s = 0.005;
parameters.current_limit_pu = 1.00;
parameters.active_power_limit_pu = 1.00;
parameters.reactive_power_limit_pu = 0.80;
parameters.minimum_dc_voltage_pu = 0.75;
parameters.maximum_dc_voltage_pu = 1.20;
parameters.filter_current_time_constant_s = 0.040;
parameters.plant_voltage_time_constant_s = 0.050;
parameters.plant_frequency_time_constant_s = 0.050;
parameters.grid_voltage_sensitivity_pu_per_pu = 0.010;
parameters.grid_frequency_droop_Hz_per_pu = 0.50;
parameters.grid_voltage_droop_pu_per_pu = 0.050;
parameters.frequency_restoration_gain_per_s = 3.0;
parameters.voltage_restoration_gain_per_s = 3.0;
parameters.grid_support_frequency_gain_pu_per_Hz = 0.20;
parameters.grid_support_voltage_gain_pu_per_pu = 1.00;
parameters.sync_phase_gain_Hz_per_rad = 0.80;
parameters.sync_voltage_gain = 2.0;
parameters.sync_voltage_threshold_pu = 0.05;
parameters.sync_frequency_threshold_Hz = 0.10;
parameters.sync_phase_threshold_deg = 5.0;
parameters.sync_hold_time_s = 0.10;
parameters.prepare_island_time_s = 0.020;
parameters.forming_prepare_time_s = 0.050;
parameters.prepare_reconnect_time_s = 0.020;
parameters.recovery_hold_time_s = 0.10;
parameters.power_command_slew_pu_per_s = 5.0;
parameters.voltage_command_slew_pu_per_s = 2.0;
parameters.frequency_command_slew_Hz_per_s = 5.0;
parameters.minimum_valid_voltage_pu = 0.0;
parameters.maximum_valid_voltage_pu = 1.30;
parameters.minimum_valid_frequency_Hz = 45.0;
parameters.maximum_valid_frequency_Hz = 55.0;
parameters.transition_voltage_min_pu = 0.85;
parameters.transition_voltage_max_pu = 1.15;
parameters.transition_frequency_fraction = 0.02;
parameters.steady_power_error_pu = 0.02;
parameters.steady_voltage_error_pu = 0.02;
parameters.steady_frequency_error_fraction = 0.001;
parameters.numeric_current_tolerance = 0.01;
parameters.metric_settling_window_s = 0.50;

if nargin >= 1 && ~isempty(overrides)
    if ~isstruct(overrides) || ~isscalar(overrides)
        error('BessUnifiedControl:Overrides', ...
            'Parameter overrides must be a scalar structure.');
    end
    overrideNames = fieldnames(overrides);
    for fieldIndex = 1:numel(overrideNames)
        fieldName = overrideNames{fieldIndex};
        if ~isfield(parameters, fieldName)
            error('BessUnifiedControl:Overrides', ...
                'Unknown parameter override: %s', fieldName);
        end
        parameters.(fieldName) = overrides.(fieldName);
    end
end

validate_parameters(parameters);
parameters.base_phase_voltage_V = ...
    parameters.nominal_line_voltage_V / sqrt(3);
parameters.base_current_A = parameters.rated_power_VA / ...
    (sqrt(3) * parameters.nominal_line_voltage_V);
parameters.base_impedance_Ohm = ...
    parameters.nominal_line_voltage_V ^ 2 / parameters.rated_power_VA;
end

function validate_parameters(parameters)
fieldNames = fieldnames(parameters);
for fieldIndex = 1:numel(fieldNames)
    value = parameters.(fieldNames{fieldIndex});
    if ~isnumeric(value) || ~isscalar(value) || ~isreal(value) || ...
            ~isfinite(value)
        error('BessUnifiedControl:Parameters', ...
            'Every parameter must be a finite real numeric scalar.');
    end
end

positiveFields = {
    'rated_power_VA', ...
    'nominal_line_voltage_V', ...
    'nominal_frequency_Hz', ...
    'sample_time_s', ...
    'current_limit_pu', ...
    'active_power_limit_pu', ...
    'reactive_power_limit_pu', ...
    'filter_current_time_constant_s', ...
    'plant_voltage_time_constant_s', ...
    'plant_frequency_time_constant_s', ...
    'transition_frequency_fraction', ...
    'steady_power_error_pu', ...
    'steady_voltage_error_pu', ...
    'steady_frequency_error_fraction', ...
    'sync_voltage_threshold_pu', ...
    'sync_frequency_threshold_Hz', ...
    'sync_phase_threshold_deg', ...
    'sync_hold_time_s', ...
    'prepare_island_time_s', ...
    'forming_prepare_time_s', ...
    'prepare_reconnect_time_s', ...
    'recovery_hold_time_s', ...
    'power_command_slew_pu_per_s', ...
    'voltage_command_slew_pu_per_s', ...
    'frequency_command_slew_Hz_per_s', ...
    'metric_settling_window_s'
};
for fieldIndex = 1:numel(positiveFields)
    if parameters.(positiveFields{fieldIndex}) <= 0
        error('BessUnifiedControl:Parameters', ...
            'Positive parameter is not greater than zero: %s', ...
            positiveFields{fieldIndex});
    end
end

nonnegativeFields = {
    'grid_voltage_sensitivity_pu_per_pu', ...
    'grid_frequency_droop_Hz_per_pu', ...
    'grid_voltage_droop_pu_per_pu', ...
    'frequency_restoration_gain_per_s', ...
    'voltage_restoration_gain_per_s', ...
    'grid_support_frequency_gain_pu_per_Hz', ...
    'grid_support_voltage_gain_pu_per_pu', ...
    'sync_phase_gain_Hz_per_rad', ...
    'sync_voltage_gain', ...
    'numeric_current_tolerance'
};
for fieldIndex = 1:numel(nonnegativeFields)
    if parameters.(nonnegativeFields{fieldIndex}) < 0
        error('BessUnifiedControl:Parameters', ...
            'Nonnegative parameter is less than zero: %s', ...
            nonnegativeFields{fieldIndex});
    end
end

if parameters.sample_time_s >= min([ ...
        parameters.filter_current_time_constant_s, ...
        parameters.plant_voltage_time_constant_s, ...
        parameters.plant_frequency_time_constant_s])
    error('BessUnifiedControl:Parameters', ...
        'Sample time must be smaller than every plant time constant.');
end
if parameters.current_limit_pu > 2 || ...
        parameters.active_power_limit_pu > 2 || ...
        parameters.reactive_power_limit_pu > 2
    error('BessUnifiedControl:Parameters', ...
        'Per-unit current and power limits must not exceed 2.');
end
if parameters.minimum_dc_voltage_pu <= 0 || ...
        parameters.minimum_dc_voltage_pu >= ...
        parameters.maximum_dc_voltage_pu
    error('BessUnifiedControl:Parameters', ...
        'DC-voltage bounds must be positive and ordered.');
end
if parameters.minimum_valid_voltage_pu < 0 || ...
        parameters.minimum_valid_voltage_pu >= ...
        parameters.maximum_valid_voltage_pu
    error('BessUnifiedControl:Parameters', ...
        'Voltage-validity bounds must be nonnegative and ordered.');
end
if parameters.minimum_valid_frequency_Hz >= ...
        parameters.maximum_valid_frequency_Hz
    error('BessUnifiedControl:Parameters', ...
        'Frequency-validity bounds must be ordered.');
end
if parameters.transition_voltage_min_pu >= 1 || ...
        parameters.transition_voltage_max_pu <= 1
    error('BessUnifiedControl:Parameters', ...
        'Transition-voltage bounds must contain 1 p.u.');
end
end
