function score = bess_score_scenario(result, parameters)
%BESS_SCORE_SCENARIO Apply numeric project gates to one scenario result.

if nargin < 2
    parameters = bess_unified_control_parameters();
end
exampleDirectory = fileparts(mfilename('fullpath'));
sourceDirectory = fullfile(exampleDirectory, 'src');
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(sourceDirectory);
states = bess_state_codes();

score.scenario_id = result.scenario_id;
score.passed = true;
score.failures = {};
score.metrics.maximum_current_pu = max(result.current_pu);
score.metrics.minimum_voltage_pu = min(result.voltage_pu);
score.metrics.maximum_voltage_pu = max(result.voltage_pu);
score.metrics.minimum_frequency_Hz = min(result.frequency_Hz);
score.metrics.maximum_frequency_Hz = max(result.frequency_Hz);
score.metrics.final_p_error_pu = abs( ...
    result.p_pu(end) - result.p_ref_pu(end));
score.metrics.final_q_error_pu = abs( ...
    result.q_pu(end) - result.q_ref_pu(end));
score.metrics.final_voltage_error_pu = abs(result.voltage_pu(end) - 1);
score.metrics.final_frequency_error_Hz = abs( ...
    result.frequency_Hz(end) - parameters.nominal_frequency_Hz);

numericSignals = [
    result.p_pu; result.q_pu; result.voltage_pu; ...
    result.frequency_Hz; result.phase_rad; result.current_pu; ...
    result.p_command_pu; result.q_command_pu; ...
    result.voltage_command_pu; result.frequency_command_Hz; ...
    result.phase_error_rad; result.voltage_mismatch_pu; ...
    result.frequency_mismatch_Hz
];
add_gate(all(isfinite(numericSignals)), ...
    'All logged numeric outputs must remain finite.');
add_gate(score.metrics.maximum_current_pu <= ...
    parameters.current_limit_pu * ...
    (1 + parameters.numeric_current_tolerance) + 1e-12, ...
    'The configured current limit was exceeded.');

closingEdges = find(diff([false; result.breaker_closed]) > 0);
for edgeIndex = 1:numel(closingEdges)
    sampleIndex = closingEdges(edgeIndex);
    if sampleIndex > 1
        add_gate(result.sync_ready(sampleIndex) || ...
            result.sync_ready(sampleIndex - 1), ...
            'Breaker closed without synchronization-ready evidence.');
        add_gate(result.voltage_mismatch_pu(sampleIndex) <= ...
            parameters.sync_voltage_threshold_pu + 1e-12, ...
            'Breaker closed outside the voltage synchronization window.');
        add_gate(result.frequency_mismatch_Hz(sampleIndex) <= ...
            parameters.sync_frequency_threshold_Hz + 1e-12, ...
            'Breaker closed outside the frequency synchronization window.');
        add_gate(abs(rad2deg(result.phase_error_rad(sampleIndex))) <= ...
            parameters.sync_phase_threshold_deg + 1e-9, ...
            'Breaker closed outside the phase synchronization window.');
    end
end

settlingStart = result.time_s(end) - ...
    parameters.metric_settling_window_s;
settled = result.time_s >= settlingStart;
switch upper(result.scenario_id)
    case 'A'
        add_gate(max(abs(result.p_pu(settled) - ...
            result.p_ref_pu(settled))) <= ...
            parameters.steady_power_error_pu, ...
            'Grid-following active-power tracking missed the 2% gate.');
        add_gate(max(abs(result.q_pu(settled) - ...
            result.q_ref_pu(settled))) <= ...
            parameters.steady_power_error_pu, ...
            'Grid-following reactive-power tracking missed the 2% gate.');
        add_gate(all(result.state_code == states.GRID_FOLLOWING), ...
            'Scenario A left GRID_FOLLOWING unexpectedly.');
    case 'B'
        recovery = result.time_s >= 2.25 & result.time_s <= 2.35;
        add_gate(any(recovery) && min(result.voltage_pu(recovery)) >= 0.5, ...
            'Voltage did not recover above 50% after the source case dip.');
        add_gate(max(abs(result.voltage_pu(settled) - 1)) <= ...
            parameters.steady_voltage_error_pu, ...
            'Voltage did not recover to the steady-state gate.');
        add_gate(max(abs(result.frequency_Hz(settled) - ...
            parameters.nominal_frequency_Hz)) <= ...
            parameters.nominal_frequency_Hz * ...
            parameters.steady_frequency_error_fraction, ...
            'Frequency did not recover to the steady-state gate.');
        add_gate(all(result.breaker_closed), ...
            'Supported grid disturbance caused an unintended breaker opening.');
    case 'C'
        add_gate(bess_state_sequence_contains(result.state_code, ...
            [states.GRID_FOLLOWING, states.PREPARE_ISLAND, ...
            states.GRID_FORMING, states.ISLANDED_SUPPORT]), ...
            'Grid-loss state sequence was not observed in order.');
        afterLoss = result.time_s >= 2;
        add_gate(~any(result.breaker_closed(afterLoss)), ...
            'Breaker reclosed while the grid remained absent.');
        add_forming_final_gates();
        add_transition_envelope(afterLoss);
    case 'D'
        add_gate(bess_state_sequence_contains(result.state_code, ...
            [states.GRID_FORMING, states.ISLANDED_SUPPORT]), ...
            'Islanded forming state sequence was not observed.');
        add_forming_final_gates();
        add_gate(max(abs(result.p_pu(settled) - ...
            result.load_p_pu(settled))) <= ...
            parameters.steady_power_error_pu, ...
            'Islanded active load was not supplied within 2%.');
    case 'E'
        add_gate(bess_state_sequence_contains(result.state_code, ...
            [states.GRID_FORMING, states.ISLANDED_SUPPORT, ...
            states.SYNCHRONIZING, states.PREPARE_RECONNECT, ...
            states.GRID_FOLLOWING]), ...
            'Reconnection state sequence was not observed in order.');
        add_gate(result.breaker_closed(end), ...
            'Breaker was not closed after valid synchronization.');
        connected = result.breaker_closed;
        add_gate(all(result.voltage_mismatch_pu(connected) <= ...
            parameters.sync_voltage_threshold_pu + 1e-12) && ...
            all(result.frequency_mismatch_Hz(connected) <= ...
            parameters.sync_frequency_threshold_Hz + 1e-12) && ...
            all(abs(rad2deg(result.phase_error_rad(connected))) <= ...
            parameters.sync_phase_threshold_deg + 1e-9), ...
            'Connected synchronization observables left their limits.');
        beforeGridReturn = result.time_s < 3;
        add_gate(~any(result.breaker_closed(beforeGridReturn)), ...
            'Breaker closed before the utility grid returned.');
        add_transition_envelope(result.time_s >= 0.1);
    case 'F'
        add_gate(any(result.saturated), ...
            'Infeasible P-Q command did not report saturation.');
        add_gate(score.metrics.final_p_error_pu <= ...
            parameters.steady_power_error_pu, ...
            'Controller did not recover after saturation cleared.');
        add_gate(score.metrics.final_q_error_pu <= ...
            parameters.steady_power_error_pu, ...
            'Reactive-power command did not recover after saturation.');
    case 'G'
        add_gate(bess_state_sequence_contains(result.state_code, ...
            [states.FAULT_SAFE, states.RECOVERY, ...
            states.SYNCHRONIZING, states.PREPARE_RECONNECT, ...
            states.GRID_FOLLOWING]), ...
            'Fault-safe recovery sequence was not observed in order.');
        faultInterval = result.time_s >= 2 & result.time_s < 2.30;
        add_gate(all(result.faulted(faultInterval)), ...
            'Invalid measurements did not assert fault status.');
        add_gate(~any(result.breaker_closed(faultInterval)), ...
            'Breaker remained closed during invalid measurement.');
        add_gate(result.breaker_closed(end) && ...
            result.state_code(end) == states.GRID_FOLLOWING, ...
            'Controller did not safely recover to grid following.');
    case 'H'
        add_gate(any(result.saturated), ...
            'Boundary scenario did not exercise available-power limiting.');
        add_gate(max(abs(result.p_command_pu)) <= 0.20 + 1e-12, ...
            'Active command exceeded the configured available power.');
        biasInterval = result.time_s >= 4 & result.time_s < 4.5;
        add_gate(all(result.measurement_valid(biasInterval)), ...
            'Bounded measurement bias should remain valid.');
    otherwise
        add_gate(false, 'Unknown scenario identifier.');
end

clear pathCleanup;

    function add_forming_final_gates()
        add_gate(max(abs(result.voltage_pu(settled) - 1)) <= ...
            parameters.steady_voltage_error_pu, ...
            'Grid-forming voltage missed the 2% steady-state gate.');
        add_gate(max(abs(result.frequency_Hz(settled) - ...
            parameters.nominal_frequency_Hz)) <= ...
            parameters.nominal_frequency_Hz * ...
            parameters.steady_frequency_error_fraction, ...
            'Grid-forming frequency missed the 0.1% gate.');
    end

    function add_transition_envelope(interval)
        add_gate(min(result.voltage_pu(interval)) >= ...
            parameters.transition_voltage_min_pu - 1e-12 && ...
            max(result.voltage_pu(interval)) <= ...
            parameters.transition_voltage_max_pu + 1e-12, ...
            'Normal transition voltage left the 0.85-1.15 p.u. envelope.');
        allowedFrequencyDeviation = ...
            parameters.transition_frequency_fraction * ...
            parameters.nominal_frequency_Hz;
        add_gate(max(abs(result.frequency_Hz(interval) - ...
            parameters.nominal_frequency_Hz)) <= ...
            allowedFrequencyDeviation + 1e-12, ...
            'Normal transition frequency left the +/-2% envelope.');
    end

    function add_gate(condition, failureMessage)
        if ~condition
            score.passed = false;
            score.failures{end + 1} = failureMessage;
        end
    end
end
