function modelPath = build_bess_unified_control_model( ...
        outputDirectory, scenario, parameters)
%BUILD_BESS_UNIFIED_CONTROL_MODEL Generate the executable Simulink model.
% The MATLAB builder is the source of truth; the generated SLX is disposable.

exampleDirectory = fileparts(mfilename('fullpath'));
sourceDirectory = fullfile(exampleDirectory, 'src');
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(exampleDirectory, sourceDirectory);
if nargin < 1 || isempty(outputDirectory)
    outputDirectory = fullfile(tempdir, ...
        'matlab-simulink-energy-lab-bess');
end
if nargin < 2 || isempty(scenario)
    scenarios = bess_validation_scenarios();
    scenario = scenarios(1);
end
if nargin < 3 || isempty(parameters)
    parameters = bess_unified_control_parameters();
end
validate_output_directory(outputDirectory);
if isempty(ver('simulink')) || ~license('test', 'Simulink')
    error('BessUnifiedControl:SimulinkUnavailable', ...
        'Building the model requires an available Simulink license.');
end
if abs(median(diff(scenario.time_s)) - parameters.sample_time_s) > 1e-12
    error('BessUnifiedControl:ScenarioSampleTime', ...
        'Scenario time grid must match the configured sample time.');
end

outputDirectory = char(outputDirectory);
if ~isfolder(outputDirectory)
    [created, message] = mkdir(outputDirectory);
    if ~created
        error('BessUnifiedControl:OutputDirectory', ...
            'Could not create output directory: %s', message);
    end
end
fileGenerationConfig = Simulink.fileGenControl('getConfig');
fileGenerationCleanup = onCleanup(@() ...
    Simulink.fileGenControl('setConfig', ...
    'config', fileGenerationConfig));
Simulink.fileGenControl('set', ...
    'CacheFolder', fullfile(outputDirectory, 'cache'), ...
    'CodeGenFolder', fullfile(outputDirectory, 'codegen'), ...
    'createDir', true);
modelName = 'bess_unified_control';
modelPath = fullfile(outputDirectory, [modelName, '.slx']);
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if isfile(modelPath)
    delete(modelPath);
end

new_system(modelName);
modelCleanup = onCleanup(@() close_model_if_loaded(modelName));
numberText = @(value) sprintf('%.17g', value);
set_param(modelName, ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', numberText(parameters.sample_time_s), ...
    'StartTime', '0', ...
    'StopTime', numberText(scenario.time_s(end)), ...
    'ReturnWorkspaceOutputs', 'on', ...
    'SaveTime', 'on', ...
    'TimeSaveName', 'tout', ...
    'SaveOutput', 'on', ...
    'OutputSaveName', 'yout', ...
    'SaveFormat', 'Dataset');

profile = bess_scenario_profile(scenario);
profileTimeseries = timeseries(profile, profile(:, 1));
modelWorkspace = get_param(modelName, 'ModelWorkspace');
assignin(modelWorkspace, 'bess_profile', profileTimeseries);

add_block('simulink/Sources/From Workspace', ...
    [modelName, '/Scenario profile'], ...
    'VariableName', 'bess_profile', ...
    'Interpolate', 'on', ...
    'OutputAfterFinalValue', 'Holding final value', ...
    'Position', [35, 160, 165, 200]);
load_system('simulink');
matlabFunctionPaths = find_system('simulink', ...
    'LookUnderMasks', 'all', 'FollowLinks', 'on', ...
    'MatchFilter', @Simulink.match.allVariants, ...
    'Name', 'MATLAB Function');
if isempty(matlabFunctionPaths)
    error('BessUnifiedControl:MATLABFunctionBlock', ...
        'Could not locate the built-in MATLAB Function block.');
end
controllerPlantPath = ...
    [modelName, '/Unified controller and averaged plant'];
add_block(matlabFunctionPaths{1}, controllerPlantPath, ...
    'Position', [235, 145, 430, 215]);
chart = find(sfroot, '-isa', 'Stateflow.EMChart', ...
    'Path', controllerPlantPath);
chart.Script = sprintf([ ...
    'function y = fcn(u)\n', ...
    '%%#codegen\n', ...
    'coder.extrinsic(''bess_simulink_runtime'');\n', ...
    'y = zeros(20, 1);\n', ...
    'y = bess_simulink_runtime(u);\n', ...
    'end\n']);
add_block('simulink/Signal Routing/Demux', ...
    [modelName, '/Observable interfaces'], ...
    'Outputs', '20', ...
    'Position', [500, 40, 505, 520]);
add_block('simulink/Sinks/To Workspace', ...
    [modelName, '/Validation output vector'], ...
    'VariableName', 'bess_output_vector', ...
    'SaveFormat', 'Timeseries', ...
    'MaxDataPoints', 'inf', ...
    'Decimation', '1', ...
    'Position', [485, 555, 625, 590]);

outputNames = {
    'P_pu', 'Q_pu', 'V_pu', 'f_Hz', 'phase_rad', ...
    'current_pu', 'breaker_closed', 'state_code', ...
    'controller_ready', 'sync_ready', 'saturated', 'faulted', ...
    'measurement_valid', 'P_command_pu', 'Q_command_pu', ...
    'V_command_pu', 'f_command_Hz', 'phase_error_rad', ...
    'voltage_mismatch_pu', 'frequency_mismatch_Hz'
};
for outputIndex = 1:numel(outputNames)
    yPosition = 30 + (outputIndex - 1) * 28;
    add_block('simulink/Sinks/Out1', ...
        [modelName, '/', outputNames{outputIndex}], ...
        'Port', num2str(outputIndex), ...
        'Position', [660, yPosition, 690, yPosition + 14]);
    add_line(modelName, ...
        sprintf('Observable interfaces/%d', outputIndex), ...
        sprintf('%s/1', outputNames{outputIndex}), ...
        'autorouting', 'on');
end

add_line(modelName, 'Scenario profile/1', ...
    'Unified controller and averaged plant/1', 'autorouting', 'on');
add_line(modelName, 'Unified controller and averaged plant/1', ...
    'Observable interfaces/1', 'autorouting', 'on');
add_line(modelName, 'Unified controller and averaged plant/1', ...
    'Validation output vector/1', 'autorouting', 'on');

annotation = Simulink.Annotation(modelName, ...
    ['SOURCE BOUNDARY: implements GFL/GS/stiff-GFM concepts; ', ...
    'VSG excluded; PROJECT_ASSUMPTION plant/transitions/limits/faults.']);
annotation.Position = [35, 20, 620, 35];
set_param(modelName, 'SimulationCommand', 'update');
save_system(modelName, modelPath);
clear modelCleanup fileGenerationCleanup pathCleanup;
end

function validate_output_directory(outputDirectory)
isScalarText = ischar(outputDirectory) || ...
    (isstring(outputDirectory) && isscalar(outputDirectory));
if ~isScalarText || strlength(string(outputDirectory)) == 0
    error('BessUnifiedControl:OutputDirectory', ...
        'Output directory must be nonempty text.');
end
end

function close_model_if_loaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
