function [results, scores] = run_bess_validation_scenarios()
%RUN_BESS_VALIDATION_SCENARIOS Run and assert mandatory scenarios A-H.

exampleDirectory = fileparts(mfilename('fullpath'));
sourceDirectory = fullfile(exampleDirectory, 'src');
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(exampleDirectory, sourceDirectory);
parameters = bess_unified_control_parameters();
scenarios = bess_validation_scenarios(parameters);
results = cell(size(scenarios));
scores = cell(size(scenarios));
for scenarioIndex = 1:numel(scenarios)
    results{scenarioIndex} = simulate_bess_unified_control( ...
        scenarios(scenarioIndex), parameters);
    scores{scenarioIndex} = bess_score_scenario( ...
        results{scenarioIndex}, parameters);
    assert(scores{scenarioIndex}.passed, ...
        'BessUnifiedControl:ScenarioFailure', ...
        'Scenario %s failed: %s', scenarios(scenarioIndex).id, ...
        strjoin(scores{scenarioIndex}.failures, newline));
    fprintf('Scenario %s passed: Imax %.4f p.u., V %.4f-%.4f p.u., ', ...
        scenarios(scenarioIndex).id, ...
        scores{scenarioIndex}.metrics.maximum_current_pu, ...
        scores{scenarioIndex}.metrics.minimum_voltage_pu, ...
        scores{scenarioIndex}.metrics.maximum_voltage_pu);
    fprintf('f %.4f-%.4f Hz.\n', ...
        scores{scenarioIndex}.metrics.minimum_frequency_Hz, ...
        scores{scenarioIndex}.metrics.maximum_frequency_Hz);
end
clear pathCleanup;
end
