%% Averaged Buck Controller Comparison Check
% Validates load-step metrics for open-loop, PI, and filtered PID cases.

clearvars; clc;

addpath(fileparts(mfilename('fullpath')));
comparison = simulate_converter_controller_comparison();
controllers = {comparison.open_loop, comparison.pi, ...
    comparison.filtered_pid};
summary = build_controller_comparison_table(comparison);

assert(comparison.load_resistance_Ohm(1) == ...
    comparison.parameters.initial_load_resistance_Ohm, ...
    'The initial load resistance is incorrect.');
assert(comparison.load_resistance_Ohm(end) == ...
    comparison.parameters.final_load_resistance_Ohm, ...
    'The final load resistance is incorrect.');

requiredVariableNames = {
    'controller_name';
    'steady_state_error_V';
    'overshoot_percent';
    'undershoot_percent';
    'settling_time_s';
    'minimum_duty_cycle';
    'maximum_duty_cycle';
    'minimum_current_reference_A';
    'maximum_current_reference_A';
    'duty_limits_respected';
    'current_limits_respected'
}';
requiredVariableUnits = {
    '';
    'V';
    '%';
    '%';
    's';
    '';
    '';
    'A';
    'A';
    '';
    ''
}';
assert(height(summary) == 3 && ...
    isequal(summary.controller_name, ...
    ["Open loop"; "PI"; "Filtered PID"]), ...
    'The summary must preserve the required three-row controller order.');
assert(isequal(summary.Properties.VariableNames, requiredVariableNames), ...
    'The summary table is missing required metric columns.');
assert(isequal(summary.Properties.VariableUnits, requiredVariableUnits), ...
    'The summary table must expose the required engineering units.');
assert(islogical(summary.duty_limits_respected) && ...
    islogical(summary.current_limits_respected) && ...
    all(summary.duty_limits_respected) && ...
    all(summary.current_limits_respected), ...
    'Compliance columns must be true logical values for the default cases.');

numericVariableNames = requiredVariableNames(2:9);
expectedMetrics = [
    1.9844663639164, 3.83855106669938, 6.47607620431627, ...
        0.02055, 0.5025, 0.5025, 20, 20;
    -6.7190102299719e-06, 1.24510573523131, 9.9540369371235, ...
        0.01034, 0.463788285230767, 0.510149548923914, ...
        20, 44.5946699122674;
    -0.0146704272094667, 1.67239217373742, 7.37924106444464, ...
        0.01396, 0.470628658218035, 0.525875014831113, ...
        20, 42.4499561470601
];
metricTolerances = [
    1e-9, 1e-9, 1e-9, 1e-12, 1e-12, 1e-12, 1e-9, 1e-9
];
assert(all(abs(summary{:, numericVariableNames} - expectedMetrics) <= ...
    metricTolerances, 'all'), ...
    'The summary table did not reproduce the default controller metrics.');

for index = 1:numel(controllers)
    controller = controllers{index};
    assert(all(isfinite(controller.output_voltage_V)), ...
        '%s output voltage must remain finite.', controller.display_name);
    assert(all(isfinite(controller.inductor_current_A)), ...
        '%s inductor current must remain finite.', controller.display_name);
    assert(all(controller.inductor_current_A >= 0), ...
        '%s current became negative.', controller.display_name);
    assert(controller.metrics.duty_limits_respected, ...
        '%s duty-cycle limits were violated.', controller.display_name);
    assert(controller.metrics.current_limits_respected, ...
        '%s current-reference limits were violated.', ...
        controller.display_name);
end

assert(abs(comparison.open_loop.metrics.steady_state_error_V) >= 1, ...
    'The open-loop case should retain a visible load-regulation error.');
assert(abs(comparison.pi.metrics.steady_state_error_V) <= 0.5, ...
    'The PI case must recover to within 0.5 V of the reference.');
assert(abs(comparison.filtered_pid.metrics.steady_state_error_V) <= 0.5, ...
    'The filtered-PID case must recover to within 0.5 V of the reference.');
assert(comparison.pi.metrics.overshoot_percent <= 5, ...
    'The PI response exceeded five percent overshoot.');
assert(comparison.filtered_pid.metrics.overshoot_percent <= 5, ...
    'The filtered-PID response exceeded five percent overshoot.');
assert(comparison.pi.metrics.settling_time_s <= 0.08, ...
    'The PI response did not settle within 80 ms.');
assert(comparison.filtered_pid.metrics.settling_time_s <= 0.08, ...
    'The filtered-PID response did not settle within 80 ms.');

fprintf('Controller comparison check passed.\n');
fprintf(['Controller      Steady error (V)  Overshoot (%%)  ' ...
    'Settling (ms)  Duty range\n']);
for index = 1:numel(controllers)
    fprintf('%-15s %16.3f %14.2f %14.1f  %.3f to %.3f\n', ...
        summary.controller_name(index), ...
        summary.steady_state_error_V(index), ...
        summary.overshoot_percent(index), ...
        1000 * summary.settling_time_s(index), ...
        summary.minimum_duty_cycle(index), ...
        summary.maximum_duty_cycle(index));
end
