%% Averaged Buck Controller Comparison Check
% Validates load-step metrics for open-loop, PI, and filtered PID cases.

clearvars; clc;

addpath(fileparts(mfilename('fullpath')));
comparison = simulate_converter_controller_comparison();
controllers = {comparison.open_loop, comparison.pi, ...
    comparison.filtered_pid};

assert(comparison.load_resistance_Ohm(1) == ...
    comparison.parameters.initial_load_resistance_Ohm, ...
    'The initial load resistance is incorrect.');
assert(comparison.load_resistance_Ohm(end) == ...
    comparison.parameters.final_load_resistance_Ohm, ...
    'The final load resistance is incorrect.');

for index = 1:numel(controllers)
    controller = controllers{index};
    assert(all(isfinite(controller.output_voltage_V)), ...
        '%s output voltage must remain finite.', controller.display_name);
    assert(all(isfinite(controller.inductor_current_A)), ...
        '%s inductor current must remain finite.', controller.display_name);
    assert(all(controller.inductor_current_A >= 0), ...
        '%s current became negative.', controller.display_name);
    assert(controller.metrics.duty_limits_respected, ...
        '%s duty-cycle limits were violated.', controller.display_name);
    assert(controller.metrics.current_limits_respected, ...
        '%s current-reference limits were violated.', ...
        controller.display_name);
end

assert(abs(comparison.open_loop.metrics.steady_state_error_V) >= 1, ...
    'The open-loop case should retain a visible load-regulation error.');
assert(abs(comparison.pi.metrics.steady_state_error_V) <= 0.5, ...
    'The PI case must recover to within 0.5 V of the reference.');
assert(abs(comparison.filtered_pid.metrics.steady_state_error_V) <= 0.5, ...
    'The filtered-PID case must recover to within 0.5 V of the reference.');
assert(comparison.pi.metrics.overshoot_percent <= 5, ...
    'The PI response exceeded five percent overshoot.');
assert(comparison.filtered_pid.metrics.overshoot_percent <= 5, ...
    'The filtered-PID response exceeded five percent overshoot.');
assert(comparison.pi.metrics.settling_time_s <= 0.08, ...
    'The PI response did not settle within 80 ms.');
assert(comparison.filtered_pid.metrics.settling_time_s <= 0.08, ...
    'The filtered-PID response did not settle within 80 ms.');

fprintf('Controller comparison check passed.\n');
fprintf(['Controller      Steady error (V)  Overshoot (%%)  ' ...
    'Settling (ms)  Duty range\n']);
for index = 1:numel(controllers)
    metrics = controllers{index}.metrics;
    fprintf('%-15s %16.3f %14.2f %14.1f  %.3f to %.3f\n', ...
        controllers{index}.display_name, metrics.steady_state_error_V, ...
        metrics.overshoot_percent, 1000 * metrics.settling_time_s, ...
        metrics.minimum_duty_cycle, metrics.maximum_duty_cycle);
end
