function modelPath = build_switching_closed_loop_buck_simulink_model( ...
    outputDirectory, parameters)
%BUILD_SWITCHING_CLOSED_LOOP_BUCK_SIMULINK_MODEL Generate native diagram.

if nargin < 1 || isempty(outputDirectory)
    outputDirectory = fullfile(tempdir, 'matlab-simulink-energy-lab');
end
if nargin < 2
    parameters = switching_closed_loop_buck_default_parameters();
end
validate_output_directory(outputDirectory);
parameters = validate_switching_closed_loop_buck_parameters(parameters);
if ~parameters.control_enabled || ~parameters.enforce_continuous_conduction
    error('SwitchingClosedLoopBuckSimulink:Parameters', ...
        ['The native companion requires the period-sampled controller ', ...
        'and continuous-conduction enforcement.']);
end
if isempty(ver('simulink')) || ~license('test', 'Simulink')
    error('SwitchingClosedLoopBuckSimulink:SimulinkUnavailable', ...
        'Building this model requires an available Simulink license.');
end

stepsPerPeriod = parameters.steps_per_switching_period;
switchingPeriod_s = 1/parameters.switching_frequency_Hz;
timeStep_s = switchingPeriod_s/stepsPerPeriod;
referenceStepTime_s = round(parameters.reference_step_time_s/ ...
    switchingPeriod_s)*switchingPeriod_s;
loadStepTime_s = round(parameters.load_step_time_s/ ...
    switchingPeriod_s)*switchingPeriod_s;
endTime_s = round(parameters.end_time_s/ ...
    switchingPeriod_s)*switchingPeriod_s;
maps = switching_closed_loop_buck_interval_maps(parameters, timeStep_s);
numberText = @(value) sprintf('%.17g', value);
matrixText = @(value) mat2str(value, 17);

outputDirectory = char(outputDirectory);
if ~isfolder(outputDirectory)
    [created, message] = mkdir(outputDirectory);
    if ~created
        error('SwitchingClosedLoopBuckSimulink:OutputDirectory', ...
            'Could not create output directory: %s', message);
    end
end

modelName = 'switching_closed_loop_buck_simulink_model';
modelPath = fullfile(outputDirectory, [modelName, '.slx']);
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if isfile(modelPath)
    delete(modelPath);
end
new_system(modelName);
modelCleanup = onCleanup(@() close_model_if_loaded(modelName));

set_param(modelName, ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', numberText(timeStep_s), ...
    'StartTime', '0', ...
    'StopTime', numberText(endTime_s), ...
    'ReturnWorkspaceOutputs', 'on', ...
    'SaveTime', 'on', ...
    'TimeSaveName', 'tout', ...
    'SaveOutput', 'on', ...
    'OutputSaveName', 'yout', ...
    'SaveFormat', 'Dataset');

add_block('simulink/Sources/Step', [modelName, '/Voltage reference'], ...
    'Time', numberText(referenceStepTime_s), ...
    'Before', numberText(parameters.initial_reference_voltage_V), ...
    'After', numberText(parameters.final_reference_voltage_V), ...
    'SampleTime', numberText(switchingPeriod_s), ...
    'Position', [25, 25, 85, 55]);
add_block('simulink/Sources/Step', [modelName, '/Load resistance'], ...
    'Time', numberText(loadStepTime_s), ...
    'Before', numberText(parameters.initial_load_resistance_Ohm), ...
    'After', numberText(parameters.final_load_resistance_Ohm), ...
    'SampleTime', numberText(switchingPeriod_s), ...
    'Position', [25, 85, 85, 115]);
add_block('simulink/Sources/Step', [modelName, '/Load selector'], ...
    'Time', numberText(loadStepTime_s), ...
    'Before', '0', 'After', '1', ...
    'SampleTime', numberText(switchingPeriod_s), ...
    'Position', [25, 555, 85, 585]);

add_block('simulink/Discrete/Unit Delay', [modelName, '/Plant state'], ...
    'InitialCondition', matrixText([ ...
    parameters.initial_inductor_current_A; ...
    parameters.initial_output_voltage_V]), ...
    'SampleTime', numberText(timeStep_s), ...
    'Position', [930, 370, 980, 420]);
add_block('simulink/Signal Routing/Demux', [modelName, '/State signals'], ...
    'Outputs', '2', 'Position', [1015, 365, 1020, 425]);
add_line(modelName, 'Plant state/1', 'State signals/1');
add_block('simulink/Sources/Constant', [modelName, '/CCM lower bound'], ...
    'Value', '-1e-9', 'Position', [1035, 470, 1095, 500]);
add_block('simulink/Logic and Bit Operations/Relational Operator', ...
    [modelName, '/Continuous conduction'], 'Operator', '>=', ...
    'Position', [1130, 455, 1175, 505]);
add_block('simulink/Model Verification/Assertion', ...
    [modelName, '/Enforce continuous conduction'], ...
    'Position', [1210, 465, 1260, 495]);
add_line(modelName, 'State signals/1', 'Continuous conduction/1', ...
    'autorouting', 'on');
add_line(modelName, 'CCM lower bound/1', 'Continuous conduction/2');
add_line(modelName, 'Continuous conduction/1', ...
    'Enforce continuous conduction/1');

add_block('simulink/Discrete/Zero-Order Hold', ...
    [modelName, '/Sample current'], ...
    'SampleTime', numberText(switchingPeriod_s), ...
    'Position', [1080, 345, 1140, 375]);
add_block('simulink/Discrete/Zero-Order Hold', ...
    [modelName, '/Sample voltage'], ...
    'SampleTime', numberText(switchingPeriod_s), ...
    'Position', [1080, 405, 1140, 435]);
add_line(modelName, 'State signals/1', 'Sample current/1');
add_line(modelName, 'State signals/2', 'Sample voltage/1');

add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Voltage error'], 'Inputs', '+-', ...
    'Position', [225, 15, 255, 65]);
add_line(modelName, 'Voltage reference/1', 'Voltage error/1');
add_line(modelName, 'Sample voltage/1', 'Voltage error/2', ...
    'autorouting', 'on');
add_block('simulink/Math Operations/Product', ...
    [modelName, '/Load current demand'], 'Inputs', '*/', ...
    'Position', [225, 85, 260, 120]);
add_line(modelName, 'Voltage reference/1', 'Load current demand/1', ...
    'autorouting', 'on');
add_line(modelName, 'Load resistance/1', 'Load current demand/2');
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Voltage proportional action'], ...
    'Gain', numberText(parameters.voltage_proportional_gain_A_per_V), ...
    'Position', [300, 20, 380, 50]);
add_line(modelName, 'Voltage error/1', 'Voltage proportional action/1');
add_block('simulink/Discrete/Unit Delay', ...
    [modelName, '/Voltage integral action'], ...
    'InitialCondition', '0', ...
    'SampleTime', numberText(switchingPeriod_s), ...
    'Position', [300, 150, 370, 180]);
add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Unconstrained current reference'], ...
    'Inputs', '+++', 'Position', [420, 65, 450, 125]);
add_line(modelName, 'Load current demand/1', ...
    'Unconstrained current reference/1');
add_line(modelName, 'Voltage proportional action/1', ...
    'Unconstrained current reference/2');
add_line(modelName, 'Voltage integral action/1', ...
    'Unconstrained current reference/3');
add_block('simulink/Discontinuities/Saturation', ...
    [modelName, '/Current reference limit'], ...
    'UpperLimit', numberText(parameters.maximum_current_reference_A), ...
    'LowerLimit', numberText(parameters.minimum_current_reference_A), ...
    'Position', [490, 80, 550, 110]);
add_line(modelName, 'Unconstrained current reference/1', ...
    'Current reference limit/1');

add_anti_windup(modelName, parameters, switchingPeriod_s, numberText);

add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Current error'], 'Inputs', '+-', ...
    'Position', [590, 200, 620, 245]);
add_line(modelName, 'Current reference limit/1', 'Current error/1', ...
    'autorouting', 'on');
add_line(modelName, 'Sample current/1', 'Current error/2', ...
    'autorouting', 'on');
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Current proportional action'], ...
    'Gain', numberText(parameters.current_proportional_gain_Ohm), ...
    'Position', [655, 205, 725, 235]);
add_line(modelName, 'Current error/1', 'Current proportional action/1');
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Inductor drop'], ...
    'Gain', numberText(parameters.inductor_resistance_Ohm), ...
    'Position', [655, 255, 725, 285]);
add_line(modelName, 'Sample current/1', 'Inductor drop/1', ...
    'autorouting', 'on');
add_block('simulink/Sources/Constant', [modelName, '/Diode drop'], ...
    'Value', numberText(parameters.diode_forward_voltage_V), ...
    'Position', [655, 305, 725, 335]);
add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Duty numerator'], 'Inputs', '++++', ...
    'Position', [765, 210, 795, 300]);
add_line(modelName, 'Sample voltage/1', 'Duty numerator/1', ...
    'autorouting', 'on');
add_line(modelName, 'Inductor drop/1', 'Duty numerator/2');
add_line(modelName, 'Diode drop/1', 'Duty numerator/3');
add_line(modelName, 'Current proportional action/1', 'Duty numerator/4');
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Duty denominator'], ...
    'Gain', numberText(1/(parameters.input_voltage_V + ...
    parameters.diode_forward_voltage_V)), ...
    'Position', [830, 240, 890, 270]);
add_line(modelName, 'Duty numerator/1', 'Duty denominator/1');
add_block('simulink/Discontinuities/Saturation', ...
    [modelName, '/Duty limit'], ...
    'UpperLimit', numberText(parameters.maximum_duty_cycle), ...
    'LowerLimit', numberText(parameters.minimum_duty_cycle), ...
    'Position', [920, 240, 980, 270]);
add_line(modelName, 'Duty denominator/1', 'Duty limit/1');
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Duty to ON steps'], 'Gain', numberText(stepsPerPeriod), ...
    'Position', [1015, 240, 1085, 270]);
add_block('simulink/Math Operations/Rounding Function', ...
    [modelName, '/Quantize ON steps'], 'Operator', 'round', ...
    'SampleTime', '-1', 'Position', [1120, 240, 1180, 270]);
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Quantized duty'], 'Gain', numberText(1/stepsPerPeriod), ...
    'Position', [1220, 240, 1290, 270]);
add_line(modelName, 'Duty limit/1', 'Duty to ON steps/1');
add_line(modelName, 'Duty to ON steps/1', 'Quantize ON steps/1');
add_line(modelName, 'Quantize ON steps/1', 'Quantized duty/1');

add_block('simulink/Sources/Repeating Sequence Stair', ...
    [modelName, '/PWM counter'], ...
    'OutValues', matrixText(0:(stepsPerPeriod - 1)), ...
    'tsamp', numberText(timeStep_s), ...
    'Position', [1015, 300, 1095, 330]);
add_block('simulink/Logic and Bit Operations/Relational Operator', ...
    [modelName, '/PWM compare'], 'Operator', '<', ...
    'Position', [1130, 300, 1170, 340]);
add_line(modelName, 'PWM counter/1', 'PWM compare/1');
add_line(modelName, 'Quantize ON steps/1', 'PWM compare/2', ...
    'autorouting', 'on');

add_plant_branches(modelName, maps, matrixText);
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Weighted load selector'], 'Gain', '2', ...
    'Position', [120, 555, 180, 585]);
add_block('simulink/Sources/Constant', [modelName, '/Mode offset'], ...
    'Value', '1', 'Position', [120, 615, 180, 645]);
add_block('simulink/Math Operations/Sum', [modelName, '/Plant mode'], ...
    'Inputs', '+++', 'Position', [225, 555, 255, 635]);
add_line(modelName, 'Load selector/1', 'Weighted load selector/1');
add_line(modelName, 'Mode offset/1', 'Plant mode/1');
add_line(modelName, 'PWM compare/1', 'Plant mode/2', 'autorouting', 'on');
add_line(modelName, 'Weighted load selector/1', 'Plant mode/3');
add_line(modelName, 'Plant mode/1', 'Next state selector/1');
add_line(modelName, 'Next state selector/1', 'Plant state/1', ...
    'autorouting', 'on');

add_logging(modelName);
set_param(modelName, 'SimulationCommand', 'update');
save_system(modelName, modelPath);
clear modelCleanup;
end

function add_anti_windup(modelName, parameters, switchingPeriod_s, numberText)
limits = {'Minimum current', parameters.minimum_current_reference_A; ...
    'Maximum current', parameters.maximum_current_reference_A; ...
    'Zero error', 0};
for limitIndex = 1:size(limits, 1)
    add_block('simulink/Sources/Constant', ...
        [modelName, '/', limits{limitIndex, 1}], ...
        'Value', numberText(limits{limitIndex, 2}), ...
        'Position', [470, 330 + 45*limitIndex, 535, 355 + 45*limitIndex]);
end
comparisons = {
    'Above minimum', '>', 'Unconstrained current reference', 'Minimum current'; ...
    'Below maximum', '<', 'Unconstrained current reference', 'Maximum current'; ...
    'At maximum', '>=', 'Unconstrained current reference', 'Maximum current'; ...
    'At minimum', '<=', 'Unconstrained current reference', 'Minimum current'; ...
    'Negative error', '<', 'Voltage error', 'Zero error'; ...
    'Positive error', '>', 'Voltage error', 'Zero error'
};
for comparisonIndex = 1:size(comparisons, 1)
    name = comparisons{comparisonIndex, 1};
    add_block('simulink/Logic and Bit Operations/Relational Operator', ...
        [modelName, '/', name], 'Operator', comparisons{comparisonIndex, 2}, ...
        'Position', [575, 330 + 45*comparisonIndex, ...
        620, 355 + 45*comparisonIndex]);
    add_line(modelName, [comparisons{comparisonIndex, 3}, '/1'], ...
        [name, '/1'], 'autorouting', 'on');
    add_line(modelName, [comparisons{comparisonIndex, 4}, '/1'], ...
        [name, '/2'], 'autorouting', 'on');
end
logicalBlocks = {
    'Current reference free', 'AND', '2'; ...
    'Upper recovery', 'AND', '2'; ...
    'Lower recovery', 'AND', '2'; ...
    'Enable integral update', 'OR', '3'
};
for logicalIndex = 1:size(logicalBlocks, 1)
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        [modelName, '/', logicalBlocks{logicalIndex, 1}], ...
        'Operator', logicalBlocks{logicalIndex, 2}, ...
        'Inputs', logicalBlocks{logicalIndex, 3}, ...
        'Position', [665, 350 + 55*logicalIndex, ...
        720, 380 + 55*logicalIndex]);
end
add_line(modelName, 'Above minimum/1', 'Current reference free/1');
add_line(modelName, 'Below maximum/1', 'Current reference free/2');
add_line(modelName, 'At maximum/1', 'Upper recovery/1');
add_line(modelName, 'Negative error/1', 'Upper recovery/2');
add_line(modelName, 'At minimum/1', 'Lower recovery/1');
add_line(modelName, 'Positive error/1', 'Lower recovery/2');
add_line(modelName, 'Current reference free/1', 'Enable integral update/1');
add_line(modelName, 'Upper recovery/1', 'Enable integral update/2');
add_line(modelName, 'Lower recovery/1', 'Enable integral update/3');
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Integral increment gain'], ...
    'Gain', numberText(parameters.voltage_integral_gain_A_per_Vs* ...
    switchingPeriod_s), 'Position', [770, 430, 850, 460]);
add_block('simulink/Math Operations/Product', ...
    [modelName, '/Conditional integral increment'], ...
    'Inputs', '**', 'Position', [885, 440, 925, 480]);
add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Next voltage integral action'], ...
    'Inputs', '++', 'Position', [955, 440, 985, 490]);
add_line(modelName, 'Voltage error/1', 'Integral increment gain/1', ...
    'autorouting', 'on');
add_line(modelName, 'Integral increment gain/1', ...
    'Conditional integral increment/1');
add_line(modelName, 'Enable integral update/1', ...
    'Conditional integral increment/2');
add_line(modelName, 'Voltage integral action/1', ...
    'Next voltage integral action/1', 'autorouting', 'on');
add_line(modelName, 'Conditional integral increment/1', ...
    'Next voltage integral action/2');
add_line(modelName, 'Next voltage integral action/1', ...
    'Voltage integral action/1', 'autorouting', 'on');
end

function add_plant_branches(modelName, maps, matrixText)
branchNames = {'Initial OFF', 'Initial ON', 'Final OFF', 'Final ON'};
branchIndex = 0;
for loadIndex = 1:2
    for switchIndex = 1:2
        branchIndex = branchIndex + 1;
        yPosition = 660 + 75*(branchIndex - 1);
        add_block('simulink/Math Operations/Gain', ...
            [modelName, '/', branchNames{branchIndex}, ' transition'], ...
            'Gain', matrixText(maps(loadIndex, switchIndex).transition), ...
            'Multiplication', 'Matrix(K*u)', ...
            'Position', [400, yPosition, 500, yPosition + 35]);
        add_block('simulink/Sources/Constant', ...
            [modelName, '/', branchNames{branchIndex}, ' increment'], ...
            'Value', matrixText(maps(loadIndex, switchIndex).increment), ...
            'Position', [535, yPosition + 40, 635, yPosition + 70]);
        add_block('simulink/Math Operations/Sum', ...
            [modelName, '/', branchNames{branchIndex}, ' next state'], ...
            'Inputs', '++', ...
            'Position', [680, yPosition, 710, yPosition + 65]);
        add_line(modelName, 'Plant state/1', ...
            [branchNames{branchIndex}, ' transition/1'], 'autorouting', 'on');
        add_line(modelName, [branchNames{branchIndex}, ' transition/1'], ...
            [branchNames{branchIndex}, ' next state/1']);
        add_line(modelName, [branchNames{branchIndex}, ' increment/1'], ...
            [branchNames{branchIndex}, ' next state/2']);
    end
end
add_block('simulink/Signal Routing/Multiport Switch', ...
    [modelName, '/Next state selector'], ...
    'DataPortOrder', 'One-based contiguous', 'Inputs', '4', ...
    'Position', [780, 680, 835, 920]);
for branchIndex = 1:4
    add_line(modelName, [branchNames{branchIndex}, ' next state/1'], ...
        sprintf('Next state selector/%d', branchIndex + 1), ...
        'autorouting', 'on');
end
end

function add_logging(modelName)
signals = {
    'State signals/1', 'inductor_current', [1080, 690, 1180, 720]; ...
    'State signals/2', 'output_voltage', [1080, 735, 1180, 765]; ...
    'PWM compare/1', 'switch_state', [1210, 300, 1310, 330]; ...
    'Quantized duty/1', 'duty_cycle', [1330, 240, 1430, 270]; ...
    'Current reference limit/1', 'current_reference', [590, 80, 690, 110]; ...
    'Voltage reference/1', 'reference_voltage', [225, 135, 325, 165]; ...
    'Load resistance/1', 'load_resistance', [225, 180, 325, 210]
};
for signalIndex = 1:size(signals, 1)
    blockName = ['Log ', strrep(signals{signalIndex, 2}, '_', ' ')];
    add_block('simulink/Sinks/To Workspace', ...
        [modelName, '/', blockName], ...
        'VariableName', signals{signalIndex, 2}, ...
        'SaveFormat', 'Timeseries', 'MaxDataPoints', 'inf', ...
        'Decimation', '1', 'Position', signals{signalIndex, 3});
    add_line(modelName, signals{signalIndex, 1}, [blockName, '/1'], ...
        'autorouting', 'on');
end
end

function validate_output_directory(outputDirectory)
isScalarText = ischar(outputDirectory) || ...
    (isstring(outputDirectory) && isscalar(outputDirectory));
if ~isScalarText || strlength(string(outputDirectory)) == 0
    error('SwitchingClosedLoopBuckSimulink:OutputDirectory', ...
        'Output directory must be a nonempty character vector or string.');
end
end

function close_model_if_loaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
