%% Native Simulink Switching Closed-Loop Buck Check
% Generates, inspects, simulates, and compares the native block diagram.

clearvars;
clc;

modelDirectory = fileparts(mfilename('fullpath'));
examplesDirectory = fileparts(modelDirectory);
referenceDirectory = fullfile(examplesDirectory, ...
    'converter-switching-closed-loop-model');
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory, referenceDirectory);

assert(~isempty(ver('simulink')) && license('test', 'Simulink'), ...
    'The native switching closed-loop buck check requires Simulink.');
parameters = switching_closed_loop_buck_default_parameters();
reference = simulate_switching_closed_loop_buck(parameters);
firstDirectory = tempname;
secondDirectory = tempname;
mkdir(firstDirectory);
mkdir(secondDirectory);
modelName = 'switching_closed_loop_buck_simulink_model';
cleanup = onCleanup(@() clean_generated_models( ...
    modelName, firstDirectory, secondDirectory));

firstPath = build_switching_closed_loop_buck_simulink_model( ...
    firstDirectory, parameters);
load_system(firstPath);
firstSignature = model_signature(modelName);
expectedBlocks = {
    'Plant state', 'UnitDelay'; ...
    'Voltage integral action', 'UnitDelay'; ...
    'Enforce continuous conduction', 'Assertion'; ...
    'PWM counter', 'SubSystem'; ...
    'PWM compare', 'RelationalOperator'; ...
    'Current reference limit', 'Saturate'; ...
    'Duty limit', 'Saturate'; ...
    'Quantize ON steps', 'Rounding'; ...
    'Next state selector', 'MultiPortSwitch'; ...
    'Initial OFF transition', 'Gain'; ...
    'Initial ON transition', 'Gain'; ...
    'Final OFF transition', 'Gain'; ...
    'Final ON transition', 'Gain'
};
for blockIndex = 1:size(expectedBlocks, 1)
    blockPath = [modelName, '/', expectedBlocks{blockIndex, 1}];
    assert(strcmp(get_param(blockPath, 'BlockType'), ...
        expectedBlocks{blockIndex, 2}), ...
        'Generated model contains an unexpected block type.');
end
assert_connection(modelName, 'Plant state', 1, 'State signals', 1);
assert_connection(modelName, 'PWM counter', 1, 'PWM compare', 1);
assert_connection(modelName, 'Quantize ON steps', 1, 'PWM compare', 2);
assert_connection(modelName, 'Plant mode', 1, 'Next state selector', 1);
assert_connection(modelName, 'Next state selector', 1, 'Plant state', 1);
assert_connection(modelName, 'Next voltage integral action', 1, ...
    'Voltage integral action', 1);
assert_connection(modelName, 'Continuous conduction', 1, ...
    'Enforce continuous conduction', 1);
assert(strcmp(get_param(modelName, 'SolverType'), 'Fixed-step') && ...
    strcmp(get_param(modelName, 'Solver'), 'FixedStepDiscrete') && ...
    abs(str2double(get_param(modelName, 'FixedStep')) - ...
    reference.time_step_s) < eps(reference.time_step_s), ...
    'Generated model must use the exact fixed-step discrete grid.');
assert(abs(str2double(get_param([modelName, '/Plant state'], ...
    'SampleTime')) - reference.time_step_s) < eps(reference.time_step_s) && ...
    abs(str2double(get_param([modelName, '/Voltage integral action'], ...
    'SampleTime')) - reference.switching_period_s) < ...
    eps(reference.switching_period_s), ...
    'Plant and controller delays must use their declared sample rates.');
assert(abs(str2double(get_param([modelName, '/Current reference limit'], ...
    'UpperLimit')) - parameters.maximum_current_reference_A) < eps && ...
    abs(str2double(get_param([modelName, '/Duty limit'], ...
    'UpperLimit')) - parameters.maximum_duty_cycle) < eps, ...
    'Generated controller limits must match the parameter structure.');

simulationOutput = sim(modelName);
inductorCurrent = simulationOutput.get('inductor_current');
outputVoltage = simulationOutput.get('output_voltage');
switchState = simulationOutput.get('switch_state');
dutyCycle = simulationOutput.get('duty_cycle');
currentReference = simulationOutput.get('current_reference');
referenceVoltage = simulationOutput.get('reference_voltage');
loadResistance = simulationOutput.get('load_resistance');

assert(isa(inductorCurrent, 'timeseries') && ...
    isa(outputVoltage, 'timeseries') && ...
    isa(switchState, 'timeseries'), ...
    'Generated model must return timeseries state and PWM signals.');
assert(isequal(inductorCurrent.Time(:), reference.time_s) && ...
    isequal(outputVoltage.Time(:), reference.time_s) && ...
    isequal(switchState.Time(:), reference.time_s), ...
    'Native state and PWM grids must match exactly.');
maximumCurrentError_A = max(abs( ...
    inductorCurrent.Data(:) - reference.inductor_current_A));
maximumVoltageError_V = max(abs( ...
    outputVoltage.Data(:) - reference.output_voltage_V));
assert(maximumCurrentError_A < 1e-12 && maximumVoltageError_V < 1e-12, ...
    'Native exact-affine plant states must match the MATLAB reference.');
assert(isequal(logical(switchState.Data(1:end-1)), ...
    reference.switch_state), ...
    'Native PWM state must match every MATLAB interval.');
assert(max(abs(dutyCycle.Data(1:end-1) - ...
    reference.duty_cycle)) < 1e-12 && ...
    max(abs(currentReference.Data(1:end-1) - ...
    reference.current_reference_A)) < 1e-12, ...
    'Native period-rate controller outputs must match the MATLAB reference.');

periodStateIndices = 1:parameters.steps_per_switching_period: ...
    numel(reference.time_s);
periodTime_s = reference.time_s(periodStateIndices);
timeTolerance_s = 4*eps(parameters.end_time_s);
assert(max(abs(dutyCycle.Time(:) - periodTime_s)) < timeTolerance_s && ...
    max(abs(currentReference.Time(:) - periodTime_s)) < timeTolerance_s && ...
    max(abs(referenceVoltage.Time(:) - periodTime_s)) < timeTolerance_s && ...
    max(abs(loadResistance.Time(:) - periodTime_s)) < timeTolerance_s, ...
    'Every period-rate log must use the exact controller sample grid.');
assert(isequal(referenceVoltage.Data(:), ...
    reference.reference_voltage_V(periodStateIndices)) && ...
    isequal(loadResistance.Data(:), ...
    reference.load_resistance_Ohm(periodStateIndices)), ...
    'Native reference and load events must match the aligned MATLAB samples.');
assert(all(isfinite(inductorCurrent.Data(:))) && ...
    all(isfinite(outputVoltage.Data(:))) && ...
    all(inductorCurrent.Data(:) >= -1e-12), ...
    'Native states must remain finite and in continuous conduction.');

close_system(modelName, 0);
nearBoundaryParameters = parameters;
nearBoundaryParameters.steps_per_switching_period = 80;
nearBoundaryParameters.reference_step_time_s = ...
    parameters.reference_step_time_s + ...
    5e-11/parameters.switching_frequency_Hz;
nearBoundaryParameters.load_step_time_s = ...
    parameters.load_step_time_s - ...
    5e-11/parameters.switching_frequency_Hz;
nearBoundaryParameters.end_time_s = parameters.end_time_s + ...
    5e-11/parameters.switching_frequency_Hz;
nearBoundaryReference = simulate_switching_closed_loop_buck( ...
    nearBoundaryParameters);
secondPath = build_switching_closed_loop_buck_simulink_model( ...
    secondDirectory, nearBoundaryParameters);
load_system(secondPath);
secondSignature = model_signature(modelName);
assert(isequal(firstSignature, secondSignature), ...
    'Repeated generation must preserve the native model structure.');
nearBoundaryOutput = sim(modelName);
nearBoundaryCurrent = nearBoundaryOutput.get('inductor_current');
nearBoundaryVoltage = nearBoundaryOutput.get('output_voltage');
nearBoundarySwitch = nearBoundaryOutput.get('switch_state');
nearBoundaryDuty = nearBoundaryOutput.get('duty_cycle');
nearBoundaryCurrentReference = ...
    nearBoundaryOutput.get('current_reference');
assert(isequal(nearBoundaryCurrent.Time(:), ...
    nearBoundaryReference.time_s) && ...
    max(abs(nearBoundaryCurrent.Data(:) - ...
    nearBoundaryReference.inductor_current_A)) < 1e-12 && ...
    max(abs(nearBoundaryVoltage.Data(:) - ...
    nearBoundaryReference.output_voltage_V)) < 1e-12 && ...
    isequal(logical(nearBoundarySwitch.Data(1:end-1)), ...
    nearBoundaryReference.switch_state) && ...
    max(abs(nearBoundaryDuty.Data(1:end-1) - ...
    nearBoundaryReference.duty_cycle)) < 1e-12 && ...
    max(abs(nearBoundaryCurrentReference.Data(1:end-1) - ...
    nearBoundaryReference.current_reference_A)) < 1e-12, ...
    'Perturbed-grid and near-boundary events must retain exact parity.');

invalidParameters = parameters;
invalidParameters.control_enabled = false;
assert_error(@() build_switching_closed_loop_buck_simulink_model( ...
    firstDirectory, invalidParameters), ...
    'SwitchingClosedLoopBuckSimulink:Parameters');
invalidParameters = parameters;
invalidParameters.control_enabled = 1;
assert_error(@() build_switching_closed_loop_buck_simulink_model( ...
    firstDirectory, invalidParameters), ...
    'SwitchingClosedLoopBuck:Parameters');
invalidParameters = parameters;
invalidParameters.reference_step_time_s = ...
    parameters.reference_step_time_s + ...
    2e-10/parameters.switching_frequency_Hz;
assert_error(@() build_switching_closed_loop_buck_simulink_model( ...
    firstDirectory, invalidParameters), ...
    'SwitchingClosedLoopBuck:TimeGrid');
assert_error(@() build_switching_closed_loop_buck_simulink_model( ...
    strings(2, 1), parameters), ...
    'SwitchingClosedLoopBuckSimulink:OutputDirectory');

ccmParameters = parameters;
ccmParameters.initial_inductor_current_A = 0;
ccmParameters.initial_output_voltage_V = 810;
ccmParameters.initial_reference_voltage_V = 810;
ccmParameters.final_reference_voltage_V = 810;
ccmParameters.minimum_duty_cycle = 0.95;
ccmParameters.maximum_duty_cycle = 0.96;
ccmParameters.reference_step_time_s = 0;
ccmParameters.load_step_time_s = 0.005;
ccmParameters.end_time_s = 0.01;
assert_error(@() simulate_switching_closed_loop_buck(ccmParameters), ...
    'SwitchingClosedLoopBuck:ConductionMode');
close_system(modelName, 0);
ccmPath = build_switching_closed_loop_buck_simulink_model( ...
    firstDirectory, ccmParameters);
load_system(ccmPath);
assert_error(@() sim(modelName), 'Simulink:blocks:AssertionAssert');

fprintf('Native Simulink switching closed-loop buck check passed.\n');
fprintf('Maximum MATLAB parity error: %.3e A, %.3e V\n', ...
    maximumCurrentError_A, maximumVoltageError_V);
fprintf('Matched PWM intervals / controller periods: %d / %d\n', ...
    numel(reference.switch_state), reference.period_count);

function signature = model_signature(modelName)
blocks = find_system(modelName, 'Type', 'Block');
relativePaths = erase(string(blocks), modelName + "/");
blockTypes = string(get_param(blocks, 'BlockType'));
signature = sortrows(table(relativePaths(:), blockTypes(:)));
end

function assert_connection(modelName, sourceBlock, sourcePort, ...
        destinationBlock, destinationPort)
sourceHandles = get_param([modelName, '/', sourceBlock], 'PortHandles');
destinationHandles = get_param( ...
    [modelName, '/', destinationBlock], 'PortHandles');
lineHandle = get_param(destinationHandles.Inport(destinationPort), 'Line');
assert(lineHandle ~= -1 && get_param(lineHandle, 'SrcPortHandle') == ...
    sourceHandles.Outport(sourcePort), ...
    'Generated model contains an incorrect or missing connection.');
end

function assert_error(functionHandle, expectedIdentifier)
try
    functionHandle();
catch errorDetails
    assert(strcmp(errorDetails.identifier, expectedIdentifier), ...
        'Expected error %s but received %s.', ...
        expectedIdentifier, errorDetails.identifier);
    return;
end
error('SwitchingClosedLoopBuckSimulink:MissingError', ...
    'Expected error %s was not raised.', expectedIdentifier);
end

function clean_generated_models(modelName, firstDirectory, secondDirectory)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
directories = {firstDirectory, secondDirectory};
for directoryIndex = 1:numel(directories)
    if isfolder(directories{directoryIndex})
        rmdir(directories{directoryIndex}, 's');
    end
end
end
