%% Native Simulink Switching Closed-Loop Buck Check
% Generates, inspects, simulates, and compares the native block diagram.

clearvars;
clc;

modelDirectory = fileparts(mfilename('fullpath'));
examplesDirectory = fileparts(modelDirectory);
referenceDirectory = fullfile(examplesDirectory, ...
    'converter-switching-closed-loop-model');
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory, referenceDirectory);

assert(~isempty(ver('simulink')) && license('test', 'Simulink'), ...
    'The native switching closed-loop buck check requires Simulink.');
parameters = switching_closed_loop_buck_default_parameters();
reference = simulate_switching_closed_loop_buck(parameters);
firstDirectory = tempname;
secondDirectory = tempname;
mkdir(firstDirectory);
mkdir(secondDirectory);
modelName = 'switching_closed_loop_buck_simulink_model';

firstPath = build_switching_closed_loop_buck_simulink_model( ...
    firstDirectory, parameters);
cleanup = onCleanup(@() clean_generated_models( ...
    modelName, firstDirectory, secondDirectory));
load_system(firstPath);
firstSignature = model_signature(modelName);
expectedBlocks = {
    'Plant state', 'UnitDelay'; ...
    'Voltage integral action', 'UnitDelay'; ...
    'Enforce continuous conduction', 'Assertion'; ...
    'PWM counter', 'SubSystem'; ...
    'PWM compare', 'RelationalOperator'; ...
    'Current reference limit', 'Saturate'; ...
    'Duty limit', 'Saturate'; ...
    'Quantize ON steps', 'Rounding'; ...
    'Next state selector', 'MultiPortSwitch'; ...
    'Initial OFF transition', 'Gain'; ...
    'Initial ON transition', 'Gain'; ...
    'Final OFF transition', 'Gain'; ...
    'Final ON transition', 'Gain'
};
for blockIndex = 1:size(expectedBlocks, 1)
    blockPath = [modelName, '/', expectedBlocks{blockIndex, 1}];
    assert(strcmp(get_param(blockPath, 'BlockType'), ...
        expectedBlocks{blockIndex, 2}), ...
        'Generated model contains an unexpected block type.');
end
assert_connection(modelName, 'Plant state', 1, 'State signals', 1);
assert_connection(modelName, 'PWM counter', 1, 'PWM compare', 1);
assert_connection(modelName, 'Quantize ON steps', 1, 'PWM compare', 2);
assert_connection(modelName, 'Plant mode', 1, 'Next state selector', 1);
assert_connection(modelName, 'Next state selector', 1, 'Plant state', 1);
assert_connection(modelName, 'Next voltage integral action', 1, ...
    'Voltage integral action', 1);
assert_connection(modelName, 'Continuous conduction', 1, ...
    'Enforce continuous conduction', 1);
assert(strcmp(get_param(modelName, 'SolverType'), 'Fixed-step') && ...
    strcmp(get_param(modelName, 'Solver'), 'FixedStepDiscrete') && ...
    abs(str2double(get_param(modelName, 'FixedStep')) - ...
    reference.time_step_s) < eps(reference.time_step_s), ...
    'Generated model must use the exact fixed-step discrete grid.');
assert(abs(str2double(get_param([modelName, '/Plant state'], ...
    'SampleTime')) - reference.time_step_s) < eps(reference.time_step_s) && ...
    abs(str2double(get_param([modelName, '/Voltage integral action'], ...
    'SampleTime')) - reference.switching_period_s) < ...
    eps(reference.switching_period_s), ...
    'Plant and controller delays must use their declared sample rates.');
assert(abs(str2double(get_param([modelName, '/Current reference limit'], ...
    'UpperLimit')) - parameters.maximum_current_reference_A) < eps && ...
    abs(str2double(get_param([modelName, '/Duty limit'], ...
    'UpperLimit')) - parameters.maximum_duty_cycle) < eps, ...
    'Generated controller limits must match the parameter structure.');

simulationOutput = sim(modelName);
inductorCurrent = simulationOutput.get('inductor_current');
outputVoltage = simulationOutput.get('output_voltage');
switchState = simulationOutput.get('switch_state');
dutyCycle = simulationOutput.get('duty_cycle');
currentReference = simulationOutput.get('current_reference');
referenceVoltage = simulationOutput.get('reference_voltage');
loadResistance = simulationOutput.get('load_resistance');

assert(isa(inductorCurrent, 'timeseries') && ...
    isa(outputVoltage, 'timeseries') && ...
    isa(switchState, 'timeseries'), ...
    'Generated model must return timeseries state and PWM signals.');
assert(isequal(inductorCurrent.Time(:), reference.time_s) && ...
    isequal(outputVoltage.Time(:), reference.time_s) && ...
    isequal(switchState.Time(:), reference.time_s), ...
    'Native state and PWM grids must match exactly.');
maximumCurrentError_A = max(abs( ...
    inductorCurrent.Data(:) - reference.inductor_current_A));
maximumVoltageError_V = max(abs( ...
    outputVoltage.Data(:) - reference.output_voltage_V));
assert(maximumCurrentError_A < 1e-12 && maximumVoltageError_V < 1e-12, ...
    'Native exact-affine plant states must match the MATLAB reference.');
assert(isequal(logical(switchState.Data(1:end-1)), ...
    reference.switch_state), ...
    'Native PWM state must match every MATLAB interval.');
assert(max(abs(dutyCycle.Data(1:end-1) - ...
    reference.duty_cycle)) < 1e-12 && ...
    max(abs(currentReference.Data(1:end-1) - ...
    reference.current_reference_A)) < 1e-12, ...
    'Native period-rate controller outputs must match the MATLAB reference.');

periodStateIndices = 1:parameters.steps_per_switching_period: ...
    numel(reference.time_s);
periodTime_s = reference.time_s(periodStateIndices);
timeTolerance_s = 4*eps(parameters.end_time_s);
assert(max(abs(dutyCycle.Time(:) - periodTime_s)) < timeTolerance_s && ...
    max(abs(currentReference.Time(:) - periodTime_s)) < timeTolerance_s && ...
    max(abs(referenceVoltage.Time(:) - periodTime_s)) < timeTolerance_s && ...
    max(abs(loadResistance.Time(:) - periodTime_s)) < timeTolerance_s, ...
    'Every period-rate log must use the exact controller sample grid.');
assert(isequal(referenceVoltage.Data(:), ...
    reference.reference_voltage_V(periodStateIndices)) && ...
    isequal(loadResistance.Data(:), ...
    reference.load_resistance_Ohm(periodStateIndices)), ...
    'Native reference and load events must match the aligned MATLAB samples.');
assert(all(isfinite(inductorCurrent.Data(:))) && ...
    all(isfinite(outputVoltage.Data(:))) && ...
    all(inductorCurrent.Data(:) >= -1e-12), ...
    'Native states must remain finite and in continuous conduction.');

close_system(modelName, 0);
nearBoundaryParameters = parameters;
nearBoundaryParameters.steps_per_switching_period = 80;
nearBoundaryParameters.reference_step_time_s = ...
    parameters.reference_step_time_s + ...
    5e-11/parameters.switching_frequency_Hz;
nearBoundaryParameters.load_step_time_s = ...
    parameters.load_step_time_s - ...
    5e-11/parameters.switching_frequency_Hz;
nearBoundaryParameters.end_time_s = parameters.end_time_s + ...
    5e-11/parameters.switching_frequency_Hz;
nearBoundaryReference = simulate_switching_closed_loop_buck( ...
    nearBoundaryParameters);
secondPath = build_switching_closed_loop_buck_simulink_model( ...
    secondDirectory, nearBoundaryParameters);
load_system(secondPath);
secondSignature = model_signature(modelName);
assert(isequal(firstSignature, secondSignature), ...
    'Repeated generation must preserve the native model structure.');
nearBoundaryOutput = sim(modelName);
nearBoundaryCurrent = nearBoundaryOutput.get('inductor_current');
nearBoundaryVoltage = nearBoundaryOutput.get('output_voltage');
nearBoundarySwitch = nearBoundaryOutput.get('switch_state');
nearBoundaryDuty = nearBoundaryOutput.get('duty_cycle');
nearBoundaryCurrentReference = ...
    nearBoundaryOutput.get('current_reference');
assert(isequal(nearBoundaryCurrent.Time(:), ...
    nearBoundaryReference.time_s) && ...
    max(abs(nearBoundaryCurrent.Data(:) - ...
    nearBoundaryReference.inductor_current_A)) < 1e-12 && ...
    max(abs(nearBoundaryVoltage.Data(:) - ...
    nearBoundaryReference.output_voltage_V)) < 1e-12 && ...
    isequal(logical(nearBoundarySwitch.Data(1:end-1)), ...
    nearBoundaryReference.switch_state) && ...
    max(abs(nearBoundaryDuty.Data(1:end-1) - ...
    nearBoundaryReference.duty_cycle)) < 1e-12 && ...
    max(abs(nearBoundaryCurrentReference.Data(1:end-1) - ...
    nearBoundaryReference.current_reference_A)) < 1e-12, ...
    'Perturbed-grid and near-boundary events must retain exact parity.');

invalidParameters = parameters;
invalidParameters.control_enabled = false;
assert_error(@() build_switching_closed_loop_buck_simulink_model( ...
    firstDirectory, invalidParameters), ...
    'SwitchingClosedLoopBuckSimulink:Parameters');
invalidParameters = parameters;
invalidParameters.control_enabled = 1;
assert_error(@() build_switching_closed_loop_buck_simulink_model( ...
    firstDirectory, invalidParameters), ...
    'SwitchingClosedLoopBuck:Parameters');
invalidParameters = parameters;
invalidParameters.reference_step_time_s = ...
    parameters.reference_step_time_s + ...
    2e-10/parameters.switching_frequency_Hz;
assert_error(@() build_switching_closed_loop_buck_simulink_model( ...
    firstDirectory, invalidParameters), ...
    'SwitchingClosedLoopBuck:TimeGrid');
assert_error(@() build_switching_closed_loop_buck_simulink_model( ...
    strings(2, 1), parameters), ...
    'SwitchingClosedLoopBuckSimulink:OutputDirectory');

ccmParameters = parameters;
ccmParameters.initial_inductor_current_A = 0;
ccmParameters.initial_output_voltage_V = 810;
ccmParameters.initial_reference_voltage_V = 810;
ccmParameters.final_reference_voltage_V = 810;
ccmParameters.minimum_duty_cycle = 0.95;
ccmParameters.maximum_duty_cycle = 0.96;
ccmParameters.reference_step_time_s = 0;
ccmParameters.load_step_time_s = 0.005;
ccmParameters.end_time_s = 0.01;
assert_error(@() simulate_switching_closed_loop_buck(ccmParameters), ...
    'SwitchingClosedLoopBuck:ConductionMode');
close_system(modelName, 0);

verify_loaded_model_collision(modelName, @(directory) ...
    build_switching_closed_loop_buck_simulink_model(directory, parameters), ...
    'SwitchingClosedLoopBuckSimulink:ModelAlreadyLoaded', 'cleanSaved');
verify_loaded_model_collision(modelName, @(directory) ...
    build_switching_closed_loop_buck_simulink_model(directory, parameters), ...
    'SwitchingClosedLoopBuckSimulink:ModelAlreadyLoaded', 'dirtySaved');
verify_loaded_model_collision(modelName, @(directory) ...
    build_switching_closed_loop_buck_simulink_model(directory, parameters), ...
    'SwitchingClosedLoopBuckSimulink:ModelAlreadyLoaded', 'unsaved');

ccmPath = build_switching_closed_loop_buck_simulink_model( ...
    firstDirectory, ccmParameters);
load_system(ccmPath);
assert_error(@() sim(modelName), 'Simulink:blocks:AssertionAssert');

fprintf('Native Simulink switching closed-loop buck check passed.\n');
fprintf('Maximum MATLAB parity error: %.3e A, %.3e V\n', ...
    maximumCurrentError_A, maximumVoltageError_V);
fprintf('Matched PWM intervals / controller periods: %d / %d\n', ...
    numel(reference.switch_state), reference.period_count);

function signature = model_signature(modelName)
blocks = find_system(modelName, 'Type', 'Block');
relativePaths = erase(string(blocks), modelName + "/");
blockTypes = string(get_param(blocks, 'BlockType'));
signature = sortrows(table(relativePaths(:), blockTypes(:)));
end

function assert_connection(modelName, sourceBlock, sourcePort, ...
        destinationBlock, destinationPort)
sourceHandles = get_param([modelName, '/', sourceBlock], 'PortHandles');
destinationHandles = get_param( ...
    [modelName, '/', destinationBlock], 'PortHandles');
lineHandle = get_param(destinationHandles.Inport(destinationPort), 'Line');
assert(lineHandle ~= -1 && get_param(lineHandle, 'SrcPortHandle') == ...
    sourceHandles.Outport(sourcePort), ...
    'Generated model contains an incorrect or missing connection.');
end

function assert_error(functionHandle, expectedIdentifier)
try
    functionHandle();
catch errorDetails
    assert(strcmp(errorDetails.identifier, expectedIdentifier), ...
        'Expected error %s but received %s.', ...
        expectedIdentifier, errorDetails.identifier);
    return;
end
error('SwitchingClosedLoopBuckSimulink:MissingError', ...
    'Expected error %s was not raised.', expectedIdentifier);
end

function clean_generated_models(modelName, firstDirectory, secondDirectory)
close_model_if_owned(modelName, {firstDirectory, secondDirectory});
directories = {firstDirectory, secondDirectory};
for directoryIndex = 1:numel(directories)
    remove_owned_temp_directory(directories{directoryIndex});
end
end

function verify_loaded_model_collision(modelName, buildFunction, errorId, ...
        fixtureState)
assert(~bdIsLoaded(modelName), ...
    'Collision fixture must not replace a pre-existing caller model.');
sourceDirectory = tempname;
targetDirectory = tempname;
mkdir(sourceDirectory);
mkdir(targetDirectory);
sourcePath = fullfile(sourceDirectory, [modelName, '.slx']);
targetPath = fullfile(targetDirectory, [modelName, '.slx']);
targetBytes = uint8([17, 34, 51, 68]);
write_binary_file(targetPath, targetBytes);
new_system(modelName);
modelHandle = get_param(modelName, 'Handle');
cleanup = onCleanup(@() clean_collision_fixture(...
    modelName, modelHandle, sourceDirectory, targetDirectory));

isSaved = strcmp(fixtureState, 'cleanSaved') || ...
    strcmp(fixtureState, 'dirtySaved');
hasSentinel = strcmp(fixtureState, 'dirtySaved') || ...
    strcmp(fixtureState, 'unsaved');
sourceBytes = uint8.empty(0, 1);
if isSaved
    save_system(modelName, sourcePath);
    sourceBytes = read_binary_file(sourcePath);
end
if hasSentinel
    add_block('simulink/Sources/Constant', [modelName, '/Caller sentinel'], ...
        'Value', '123', 'Position', [30, 30, 100, 60]);
    modelWorkspace = get_param(modelName, 'ModelWorkspace');
    assignin(modelWorkspace, 'callerSentinel', 42);
end
expectedDirty = get_param(modelName, 'Dirty');
if strcmp(fixtureState, 'cleanSaved')
    assert(strcmp(expectedDirty, 'off'), ...
        'Clean saved collision fixture must start clean.');
else
    assert(strcmp(expectedDirty, 'on'), ...
        'Dirty or unsaved collision fixture must start dirty.');
end

collisionRejected = false;
try
    buildFunction(targetDirectory);
catch buildError
    collisionRejected = strcmp(buildError.identifier, errorId);
end
assert(collisionRejected, ...
    'Builder must reject a same-name model that is already loaded.');
assert(bdIsLoaded(modelName), 'Loaded caller model must remain loaded.');
assert(get_param(modelName, 'Handle') == modelHandle, ...
    'Loaded caller model handle must remain unchanged.');
assert(strcmp(get_param(modelName, 'Dirty'), expectedDirty), ...
    'Loaded caller model dirty state must remain unchanged.');
if isSaved
    assert(strcmpi(get_param(modelName, 'FileName'), sourcePath), ...
        'Loaded caller model path must remain unchanged.');
    assert(isequal(read_binary_file(sourcePath), sourceBytes), ...
        'Loaded caller model file bytes must remain unchanged.');
else
    assert(strcmp(get_param(modelName, 'FileName'), ''), ...
        'Unsaved caller model must remain unsaved.');
    assert(~isfile(sourcePath), ...
        'Unsaved caller model must not gain a source file.');
end
if hasSentinel
    assert(strcmp(get_param([modelName, '/Caller sentinel'], 'Value'), '123'), ...
        'Loaded caller model content must remain unchanged.');
    assert(evalin(modelWorkspace, 'callerSentinel') == 42, ...
        'Loaded caller model workspace must remain unchanged.');
end
assert(isequal(read_binary_file(targetPath), targetBytes(:)), ...
    'Target model file must remain unchanged after rejection.');
clear cleanup;
end

function clean_collision_fixture(modelName, modelHandle, sourceDirectory, ...
        targetDirectory)
close_model_by_handle(modelName, modelHandle);
remove_owned_temp_directory(sourceDirectory);
remove_owned_temp_directory(targetDirectory);
end

function close_model_by_handle(modelName, modelHandle)
if bdIsLoaded(modelName) && get_param(modelName, 'Handle') == modelHandle
    close_system(modelName, 0);
end
end

function close_model_if_owned(modelName, directories)
if ~bdIsLoaded(modelName)
    return;
end
fileName = string(get_param(modelName, 'FileName'));
for directoryIndex = 1:numel(directories)
    rootDirectory = string(fullfile(directories{directoryIndex}, filesep));
    if strlength(fileName) > 0 && ...
            startsWith(fileName, rootDirectory, 'IgnoreCase', true)
        close_system(modelName, 0);
        return;
    end
end
end

function remove_owned_temp_directory(directory)
if ~isfolder(directory)
    return;
end
rootDirectory = string(fullfile(tempdir, filesep));
candidate = string(directory);
if strlength(candidate) <= strlength(rootDirectory) || ...
        ~startsWith(candidate, rootDirectory, 'IgnoreCase', true)
    return;
end
rmdir(char(candidate), 's');
end

function write_binary_file(filePath, bytes)
fileIdentifier = fopen(filePath, 'w');
assert(fileIdentifier > 0, 'Could not create binary fixture file.');
fwrite(fileIdentifier, bytes, 'uint8');
fclose(fileIdentifier);
end

function bytes = read_binary_file(filePath)
fileIdentifier = fopen(filePath, 'r');
assert(fileIdentifier > 0, 'Could not open binary fixture file.');
bytes = fread(fileIdentifier, inf, '*uint8');
fclose(fileIdentifier);
end
