function inputVector = bess_scenario_input_vector(scenario, sampleIndex)
%BESS_SCENARIO_INPUT_VECTOR Pack one scenario sample for the kernels.

inputVector = [
    scenario.time_s(sampleIndex); ...
    scenario.inputs.p_ref_pu(sampleIndex); ...
    scenario.inputs.q_ref_pu(sampleIndex); ...
    scenario.inputs.voltage_ref_pu(sampleIndex); ...
    scenario.inputs.frequency_ref_Hz(sampleIndex); ...
    scenario.inputs.load_p_pu(sampleIndex); ...
    scenario.inputs.load_q_pu(sampleIndex); ...
    scenario.inputs.grid_present(sampleIndex); ...
    scenario.inputs.grid_voltage_pu(sampleIndex); ...
    scenario.inputs.grid_frequency_Hz(sampleIndex); ...
    scenario.inputs.grid_phase_rad(sampleIndex); ...
    scenario.inputs.request_grid_following(sampleIndex); ...
    scenario.inputs.grid_support_enable(sampleIndex); ...
    scenario.inputs.fault_code(sampleIndex); ...
    scenario.inputs.available_power_pu(sampleIndex); ...
    scenario.inputs.dc_voltage_pu(sampleIndex)
];
end
