function outputVector = bess_simulink_runtime(inputVector)
%BESS_SIMULINK_RUNTIME Stateful interpreted kernel used by generated SLX.
% The explicit time-zero reset makes repeated simulations deterministic.

persistent parameters plantState controllerState measurement
if isempty(parameters) || inputVector(1) <= 1e-12
    parameters = bess_unified_control_parameters();
    plantState = bess_initialize_plant_state(inputVector, parameters);
    measurement = bess_measure_plant(plantState);
    controllerState = bess_initialize_controller_state( ...
        inputVector, measurement);
end
[command, controllerState] = bess_controller_step( ...
    inputVector, measurement, controllerState, parameters);
plantState = bess_plant_step( ...
    inputVector, command, plantState, parameters);
measurement = bess_measure_plant(plantState);
outputVector = [
    measurement.p_pu; ...
    measurement.q_pu; ...
    measurement.voltage_pu; ...
    measurement.frequency_Hz; ...
    measurement.phase_rad; ...
    measurement.current_pu; ...
    double(measurement.breaker_closed); ...
    command.state_code; ...
    double(command.controller_ready); ...
    double(command.sync_ready); ...
    double(command.saturated); ...
    double(command.faulted); ...
    double(command.measurement_valid); ...
    command.p_command_pu; ...
    command.q_command_pu; ...
    command.voltage_command_pu; ...
    command.frequency_command_Hz; ...
    command.phase_error_rad; ...
    command.voltage_mismatch_pu; ...
    command.frequency_mismatch_Hz
];
end
