function metrics = bess_sync_metrics(pccVoltage_pu, pccFrequency_Hz, ...
        pccPhase_rad, gridVoltage_pu, gridFrequency_Hz, gridPhase_rad, ...
        parameters)
%BESS_SYNC_METRICS Calculate breaker synchronization mismatches and gate.

inputs = [pccVoltage_pu, pccFrequency_Hz, pccPhase_rad, ...
    gridVoltage_pu, gridFrequency_Hz, gridPhase_rad];
validateattributes(inputs, {'numeric'}, ...
    {'real', 'finite', 'vector', 'numel', 6});
metrics.voltage_mismatch_pu = abs(pccVoltage_pu - gridVoltage_pu);
metrics.frequency_mismatch_Hz = abs( ...
    pccFrequency_Hz - gridFrequency_Hz);
metrics.phase_error_rad = atan2(sin(gridPhase_rad - pccPhase_rad), ...
    cos(gridPhase_rad - pccPhase_rad));
metrics.phase_mismatch_deg = abs(rad2deg(metrics.phase_error_rad));
metrics.within_limits = ...
    metrics.voltage_mismatch_pu <= ...
        parameters.sync_voltage_threshold_pu && ...
    metrics.frequency_mismatch_Hz <= ...
        parameters.sync_frequency_threshold_Hz && ...
    metrics.phase_mismatch_deg <= parameters.sync_phase_threshold_deg;
end
