function [conditioned, valid] = bess_condition_measurement( ...
        measurement, input, parameters)
%BESS_CONDITION_MEASUREMENT Apply deterministic selected fault models.
% fault_code 0 normal; 1 invalid/dropout; 2 stale; 3 bounded bias; 4 noise.

conditioned = measurement;
if input.fault_code == 1
    conditioned.voltage_abc_pu(:) = NaN;
    conditioned.voltage_pu = NaN;
elseif input.fault_code == 3
    conditioned.voltage_abc_pu = ...
        1.08 .* conditioned.voltage_abc_pu;
    conditioned.voltage_pu = 1.08 .* conditioned.voltage_pu;
elseif input.fault_code == 4
    deterministicNoise = 0.01 * sin(2 * pi * 7 * input.time_s);
    conditioned.voltage_abc_pu = conditioned.voltage_abc_pu + ...
        deterministicNoise .* [1, -0.5, -0.5];
    conditioned.frequency_Hz = conditioned.frequency_Hz + ...
        0.02 * sin(2 * pi * 3 * input.time_s);
end

finiteValues = [
    conditioned.voltage_abc_pu(:); ...
    conditioned.current_abc_pu(:); ...
    conditioned.p_pu; ...
    conditioned.q_pu; ...
    conditioned.voltage_pu; ...
    conditioned.frequency_Hz; ...
    conditioned.phase_rad; ...
    conditioned.current_pu; ...
    conditioned.current_d_pu; ...
    conditioned.current_q_pu
];
valid = all(isfinite(finiteValues)) && input.fault_code ~= 2 && ...
    conditioned.voltage_pu >= parameters.minimum_valid_voltage_pu && ...
    conditioned.voltage_pu <= parameters.maximum_valid_voltage_pu && ...
    conditioned.frequency_Hz >= ...
        parameters.minimum_valid_frequency_Hz && ...
    conditioned.frequency_Hz <= ...
        parameters.maximum_valid_frequency_Hz && ...
    input.dc_voltage_pu >= parameters.minimum_dc_voltage_pu && ...
    input.dc_voltage_pu <= parameters.maximum_dc_voltage_pu && ...
    input.available_power_pu >= 0;

if valid
    [conditioned.p_from_abc_pu, conditioned.q_from_abc_pu] = ...
        bess_power_from_abc(conditioned.voltage_abc_pu, ...
        conditioned.current_abc_pu);
    [voltageAlpha, voltageBeta] = bess_clarke_transform( ...
        conditioned.voltage_abc_pu(1), ...
        conditioned.voltage_abc_pu(2), ...
        conditioned.voltage_abc_pu(3));
    [conditioned.voltage_d_pu, conditioned.voltage_q_pu] = ...
        bess_park_transform(voltageAlpha, voltageBeta, ...
        conditioned.phase_rad - pi / 2);
else
    conditioned.p_from_abc_pu = 0;
    conditioned.q_from_abc_pu = 0;
    conditioned.voltage_d_pu = 0;
    conditioned.voltage_q_pu = 0;
end
end
