function name = bess_state_name(stateCode)
%BESS_STATE_NAME Convert a stable supervisor code to its review name.

names = {
    'GRID_FOLLOWING'; ...
    'PREPARE_ISLAND'; ...
    'GRID_FORMING'; ...
    'ISLANDED_SUPPORT'; ...
    'SYNCHRONIZING'; ...
    'PREPARE_RECONNECT'; ...
    'RECOVERY'; ...
    'FAULT_SAFE'
};
if ~isnumeric(stateCode) || ~isscalar(stateCode) || ...
        stateCode < 1 || stateCode > numel(names) || ...
        stateCode ~= floor(stateCode)
    error('BessUnifiedControl:StateCode', ...
        'State code must be an integer from 1 through 8.');
end
name = names{stateCode};
end
