function [limitedP_pu, limitedQ_pu, scale, saturated] = ...
        bess_limit_pq(requestedP_pu, requestedQ_pu, voltage_pu, ...
        availablePower_pu, parameters)
%BESS_LIMIT_PQ Enforce P, Q, apparent-current, and DC availability limits.

validateattributes(requestedP_pu, {'numeric'}, ...
    {'real', 'finite', 'scalar'});
validateattributes(requestedQ_pu, {'numeric'}, ...
    {'real', 'finite', 'scalar'});
validateattributes(voltage_pu, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'nonnegative'});
validateattributes(availablePower_pu, {'numeric'}, ...
    {'real', 'finite', 'scalar', 'nonnegative'});

limitedP_pu = min(max(requestedP_pu, ...
    -parameters.active_power_limit_pu), ...
    parameters.active_power_limit_pu);
limitedP_pu = min(max(limitedP_pu, -availablePower_pu), ...
    availablePower_pu);
limitedQ_pu = min(max(requestedQ_pu, ...
    -parameters.reactive_power_limit_pu), ...
    parameters.reactive_power_limit_pu);

apparentLimit_pu = parameters.current_limit_pu * ...
    max(voltage_pu, 0.05);
requestedMagnitude = hypot(limitedP_pu, limitedQ_pu);
if requestedMagnitude > apparentLimit_pu && requestedMagnitude > 0
    scale = apparentLimit_pu / requestedMagnitude;
    limitedP_pu = limitedP_pu * scale;
    limitedQ_pu = limitedQ_pu * scale;
else
    scale = 1;
end
saturated = scale < 1 - 10 * eps || ...
    abs(limitedP_pu - requestedP_pu) > 10 * eps || ...
    abs(limitedQ_pu - requestedQ_pu) > 10 * eps;
end
