function [activePower_pu, reactivePower_pu] = ...
        bess_power_from_abc(voltage_abc_pu, current_abc_pu)
%BESS_POWER_FROM_ABC Calculate balanced three-phase P and Q in per unit.
% Input amplitudes are normalized to phase RMS bases. The 0.5 factor converts
% alpha-beta peak products to the three-phase apparent-power base.

validateattributes(voltage_abc_pu, {'numeric'}, ...
    {'real', 'finite', '2d', 'ncols', 3});
validateattributes(current_abc_pu, {'numeric'}, ...
    {'real', 'finite', 'size', size(voltage_abc_pu)});
[voltageAlpha, voltageBeta] = bess_clarke_transform( ...
    voltage_abc_pu(:, 1), voltage_abc_pu(:, 2), ...
    voltage_abc_pu(:, 3));
[currentAlpha, currentBeta] = bess_clarke_transform( ...
    current_abc_pu(:, 1), current_abc_pu(:, 2), ...
    current_abc_pu(:, 3));
activePower_pu = 0.5 .* ( ...
    voltageAlpha .* currentAlpha + voltageBeta .* currentBeta);
reactivePower_pu = 0.5 .* ( ...
    voltageBeta .* currentAlpha - voltageAlpha .* currentBeta);
end
