function outputVector = bess_simulink_runtime(inputVector, runParameters)
%BESS_SIMULINK_RUNTIME Stateful interpreted kernel used by generated SLX.
% The explicit time-zero reset makes repeated simulations deterministic.

% The runtime receives one row per invocation, so it retains the command
% computed at t_k until the next invocation advances the plant to t_(k+1).
persistent parameters plantState controllerState measurement
persistent previousInputVector previousCommand previousTime
persistent previousOutput
input = bess_unpack_input(inputVector);
if nargin < 2
    runParameters = bess_unified_control_parameters();
end
isTimeZero = abs(input.time_s) <= 1e-12;
if ~isempty(parameters) && ~isTimeZero && ...
        ~isequal(parameters, runParameters)
    error('BessUnifiedControl:RuntimeParametersChanged', ...
        'Parameters must remain constant until the next time-zero reset.');
end
if ~isempty(previousTime) && input.time_s == previousTime && ...
        isequal(inputVector, previousInputVector) && ...
        isequal(parameters, runParameters)
    outputVector = previousOutput;
    return;
end
if isempty(parameters) && ~isTimeZero
    error('BessUnifiedControl:TimeGrid', ...
        'Start the runtime with a time-zero sample.');
end
if isempty(parameters) || isTimeZero
    parameters = runParameters;
    plantState = bess_initialize_plant_state(inputVector, parameters);
    measurement = bess_measure_plant(plantState);
    controllerState = bess_initialize_controller_state( ...
        inputVector, measurement);
    [command, controllerState] = bess_controller_step( ...
        inputVector, measurement, controllerState, parameters, 0);
    plantState = bess_plant_step( ...
        inputVector, command, plantState, parameters, 0);
    measurement = bess_measure_plant(plantState);
    previousInputVector = inputVector;
    previousCommand = command;
    previousTime = input.time_s;
else
    elapsedTime_s = input.time_s - previousTime;
    if elapsedTime_s < 0
        error('BessUnifiedControl:NonmonotonicTime', ...
            'Runtime timestamps must not move backwards.');
    end
    if elapsedTime_s > 0
        if abs(elapsedTime_s - parameters.sample_time_s) > 1e-12
            error('BessUnifiedControl:TimeGrid', ...
                'Runtime samples must follow the configured sample period.');
        end
        % Use the fixed solver period, not subtraction roundoff from the
        % interpolated time signal, as the integration duration.
        elapsedTime_s = parameters.sample_time_s;
    end

    % Advance exactly once for the interval since the previous invocation,
    % using the command and input held from that previous boundary.
    if elapsedTime_s > 0
        plantState = bess_plant_step(previousInputVector, previousCommand, ...
            plantState, parameters, elapsedTime_s);
    end

    % Apply current-boundary events (and same-time phase alignment) without
    % an additional dynamic advance before evaluating the new command.
    plantState = bess_plant_step(inputVector, previousCommand, ...
        plantState, parameters, 0);
    measurement = bess_measure_plant(plantState);
    [command, controllerState] = bess_controller_step( ...
        inputVector, measurement, controllerState, parameters, ...
        elapsedTime_s);
    plantState = bess_plant_step( ...
        inputVector, command, plantState, parameters, 0);
    measurement = bess_measure_plant(plantState);
    previousInputVector = inputVector;
    previousCommand = command;
    previousTime = input.time_s;
end
outputVector = pack_output(measurement, command);
previousOutput = outputVector;
end

function outputVector = pack_output(measurement, command)
outputVector = [
    measurement.p_pu; ...
    measurement.q_pu; ...
    measurement.voltage_pu; ...
    measurement.frequency_Hz; ...
    measurement.phase_rad; ...
    measurement.current_pu; ...
    double(measurement.breaker_closed); ...
    command.state_code; ...
    double(command.controller_ready); ...
    double(command.sync_ready); ...
    double(command.saturated); ...
    double(command.faulted); ...
    double(command.measurement_valid); ...
    command.p_command_pu; ...
    command.q_command_pu; ...
    command.voltage_command_pu; ...
    command.frequency_command_Hz; ...
    command.phase_error_rad; ...
    command.voltage_mismatch_pu; ...
    command.frequency_mismatch_Hz
];
end
