function scenario = build_battery_2rc_fit_scenario()
%BUILD_BATTERY_2RC_FIT_SCENARIO Build deterministic fit and validation data.
% The returned voltage records are synthetic and are intended to verify the
% identification workflow. They are not measurements from a physical cell.

trueParameters = battery_2rc_default_parameters();
trueParameters.r0_Ohm = 0.0042;
trueParameters.r1_Ohm = 0.0022;
trueParameters.c1_F = 900;
trueParameters.r2_Ohm = 0.0038;
trueParameters.c2_F = 9000;

calibrationProfile = table( ...
    [0; 20; 70; 120; 180; 230; 300; 360; 430; 500; 600], ...
    [0; 35; 0; -20; 0; 50; 10; 0; -35; 0; 0], ...
    'VariableNames', {'time_s', 'current_A'});
validationProfile = table( ...
    [0; 15; 55; 95; 160; 210; 275; 330; 410; 480; 560], ...
    [0; 25; -10; 0; 45; 0; -30; 15; 0; 35; 0], ...
    'VariableNames', {'time_s', 'current_A'});

calibrationData = buildSyntheticRecord( ...
    calibrationProfile, trueParameters, 0.0);
validationData = buildSyntheticRecord( ...
    validationProfile, trueParameters, 1.2);
scenario = struct( ...
    'true_parameters', trueParameters, ...
    'initial_parameters', battery_2rc_default_parameters(), ...
    'calibration_data', calibrationData, ...
    'validation_data', validationData, ...
    'noise_description', ...
        ['Deterministic 0.45 mV sine plus 0.25 mV cosine ', ...
        'sensor-like perturbation.']);
end

function data = buildSyntheticRecord(profile, parameters, phase_rad)
result = simulate_battery_2rc_model(profile, parameters, 1);
noise_V = 0.00045*sin(2*pi*result.time_s/19 + phase_rad) + ...
    0.00025*cos(2*pi*result.time_s/47 - 0.5*phase_rad);
measuredVoltage_V = result.terminal_voltage_V + noise_V;
data = table( ...
    result.time_s, ...
    result.current_A, ...
    result.ocv_V, ...
    measuredVoltage_V, ...
    result.terminal_voltage_V, ...
    noise_V, ...
    'VariableNames', {
        'time_s', ...
        'current_A', ...
        'ocv_V', ...
        'terminal_voltage_V', ...
        'reference_terminal_voltage_V', ...
        'measurement_noise_V'
    });
end
