%% Battery 2RC Parameter Identification Check
% Verifies positive parameter recovery and independent profile validation.

clearvars; clc;

modelDirectory = fileparts(mfilename('fullpath'));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory);

scenario = build_battery_2rc_fit_scenario();
fitResult = fit_battery_2rc_parameters( ...
    scenario.calibration_data, scenario.initial_parameters);
calibrationEvaluation = evaluate_battery_2rc_fit( ...
    scenario.calibration_data, fitResult.parameters);
validationEvaluation = evaluate_battery_2rc_fit( ...
    scenario.validation_data, fitResult.parameters);
initialValidation = evaluate_battery_2rc_fit( ...
    scenario.validation_data, scenario.initial_parameters);

estimatedParameters = fitResult.parameters;
trueParameters = scenario.true_parameters;
estimatedTau_s = [
    estimatedParameters.r1_Ohm*estimatedParameters.c1_F, ...
    estimatedParameters.r2_Ohm*estimatedParameters.c2_F
];
trueTau_s = [
    trueParameters.r1_Ohm*trueParameters.c1_F, ...
    trueParameters.r2_Ohm*trueParameters.c2_F
];
resistanceRelativeError = abs([
    estimatedParameters.r0_Ohm/trueParameters.r0_Ohm - 1, ...
    estimatedParameters.r1_Ohm/trueParameters.r1_Ohm - 1, ...
    estimatedParameters.r2_Ohm/trueParameters.r2_Ohm - 1
]);
timeConstantRelativeError = abs(estimatedTau_s./trueTau_s - 1);

assert(all([
    estimatedParameters.r0_Ohm, ...
    estimatedParameters.r1_Ohm, ...
    estimatedParameters.c1_F, ...
    estimatedParameters.r2_Ohm, ...
    estimatedParameters.c2_F
] > 0), ...
    'All fitted electrical parameters must be positive.');
assert(estimatedTau_s(1) < estimatedTau_s(2), ...
    'The fitted fast time constant must remain below the slow one.');
assert(max(resistanceRelativeError) < 0.15, ...
    'The deterministic benchmark must recover all resistances within 15%%.');
assert(max(timeConstantRelativeError) < 0.20, ...
    'The deterministic benchmark must recover both time constants within 20%%.');
assert(calibrationEvaluation.metrics.rmse_V < 0.001, ...
    'Calibration RMSE must remain below 1 mV.');
assert(validationEvaluation.metrics.rmse_V < 0.0015, ...
    'Held-out validation RMSE must remain below 1.5 mV.');
assert(validationEvaluation.metrics.rmse_V < ...
    0.5*initialValidation.metrics.rmse_V, ...
    'Fitting must halve held-out error relative to initial parameters.');
assert(fitResult.metrics.design_condition_number < 1e4, ...
    'The selected linear resistance fit must remain well conditioned.');
assert(fitResult.search.candidate_count > 500, ...
    'The deterministic search must evaluate a substantive candidate set.');

shiftedValidationData = scenario.validation_data;
shiftedValidationData.time_s = shiftedValidationData.time_s + 1000;
shiftedEvaluation = evaluate_battery_2rc_fit( ...
    shiftedValidationData, fitResult.parameters);
assert(isequal(shiftedEvaluation.predicted_terminal_voltage_V, ...
    validationEvaluation.predicted_terminal_voltage_V) && ...
    isequal(shiftedEvaluation.time_s, shiftedValidationData.time_s), ...
    'Evaluation must preserve results when timestamps have a fixed offset.');

repeatFit = fit_battery_2rc_parameters( ...
    scenario.calibration_data, scenario.initial_parameters);
assert(isequal(fitResult.parameters, repeatFit.parameters) && ...
    isequal(fitResult.predicted_terminal_voltage_V, ...
        repeatFit.predicted_terminal_voltage_V), ...
    'Repeated identification must be deterministic.');

invalidData = removevars(scenario.calibration_data, 'ocv_V');
missingColumnRejected = false;
try
    fit_battery_2rc_parameters(invalidData, scenario.initial_parameters);
catch validationError
    missingColumnRejected = strcmp(validationError.identifier, ...
        'Battery2RCFit:Data');
end
assert(missingColumnRejected, ...
    'The fitter must reject data without independently supplied OCV.');

invalidData = scenario.calibration_data;
invalidData.time_s(10) = invalidData.time_s(9);
invalidTimeRejected = false;
try
    fit_battery_2rc_parameters(invalidData, scenario.initial_parameters);
catch validationError
    invalidTimeRejected = strcmp(validationError.identifier, ...
        'Battery2RCFit:Time');
end
assert(invalidTimeRejected, ...
    'The fitter must reject non-increasing timestamps.');

unexcitedData = scenario.calibration_data;
unexcitedData.current_A(:) = 0;
unexcitedDataRejected = false;
try
    fit_battery_2rc_parameters(unexcitedData, scenario.initial_parameters);
catch validationError
    unexcitedDataRejected = strcmp(validationError.identifier, ...
        'Battery2RCFit:Excitation');
end
assert(unexcitedDataRejected, ...
    'The fitter must reject a record without current excitation.');

fprintf('Battery 2RC identification check passed.\n');
fprintf('Calibration RMSE: %.3f mV\n', ...
    1000*calibrationEvaluation.metrics.rmse_V);
fprintf('Held-out RMSE: %.3f mV\n', ...
    1000*validationEvaluation.metrics.rmse_V);
fprintf('Estimated time constants: %.2f s and %.2f s\n', ...
    estimatedTau_s(1), estimatedTau_s(2));
