%% Battery 2RC Model Check
% Validates fast and slow exact polarization branches and inherited states.

clearvars; clc;

modelDirectory = fileparts(mfilename('fullpath'));
baseModelDirectory = fullfile(fileparts(modelDirectory), 'battery-rc-model');
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory, baseModelDirectory);

profilePath = fullfile(baseModelDirectory, 'data', ...
    'pulse_current_profile.csv');
profile = readtable(profilePath);
parameters = battery_2rc_default_parameters();
result = simulate_battery_2rc_model(profile, parameters, 1);

assert(numel(result.time_s) == 601, ...
    'Expected a 600-second, 1 Hz result.');
assert(all(isfinite(result.terminal_voltage_V)) && ...
    all(isfinite(result.v_rc1_V)) && all(isfinite(result.v_rc2_V)), ...
    'Voltage and polarization states must remain finite.');
assert(all(result.soc >= 0 & result.soc <= 1), ...
    'SOC must remain within [0, 1].');
assert(isequal(result.requested_current_A, result.current_A) && ...
    ~any(result.current_limited), ...
    'Canonical profile must remain inside inherited SOC current limits.');
assert(max(abs(result.soc_charge_balance_error)) < 1e-12, ...
    'SOC must close against cumulative applied-current charge balance.');
assert(max(abs(result.v_polarization_V - ...
    (result.v_rc1_V + result.v_rc2_V))) < 1e-14, ...
    'Total polarization voltage must equal both branch states.');
reconstructedVoltage_V = result.ocv_V - ...
    result.current_A * parameters.r0_Ohm - ...
    result.v_rc1_V - result.v_rc2_V;
assert(max(abs(result.terminal_voltage_V - reconstructedVoltage_V)) < ...
    1e-12, ...
    'Terminal voltage must satisfy the two-RC voltage balance.');
assert(result.branch_time_constants_s(1) < ...
    result.branch_time_constants_s(2), ...
    'Default R1-C1 branch must be faster than R2-C2.');

oneBranchResult = simulate_battery_rc_model(profile, parameters, 1);
assert(isequal(result.time_s, oneBranchResult.time_s) && ...
    isequal(result.current_A, oneBranchResult.current_A) && ...
    isequal(result.soc, oneBranchResult.soc) && ...
    isequal(result.ocv_V, oneBranchResult.ocv_V), ...
    'Two-RC wrapper must preserve validated profile, current, SOC, and OCV.');
assert(max(abs(result.v_rc1_V - oneBranchResult.v_rc_V)) < 1e-14, ...
    'First polarization branch must match the shared one-RC simulator.');
assert(max(abs(result.terminal_voltage_V - ...
    (oneBranchResult.terminal_voltage_V - result.v_rc2_V))) < 1e-12, ...
    'Two-RC voltage must add exactly the second polarization drop.');

constantProfile = table(...
    [0; 10], ...
    [40; 40], ...
    'VariableNames', {'time_s', 'current_A'});
constantResult = simulate_battery_2rc_model(...
    constantProfile, parameters);
expectedVrc1_V = parameters.r1_Ohm * ...
    (1 - exp(-10 / (parameters.r1_Ohm * parameters.c1_F))) * 40;
expectedVrc2_V = parameters.r2_Ohm * ...
    (1 - exp(-10 / (parameters.r2_Ohm * parameters.c2_F))) * 40;
assert(abs(constantResult.v_rc1_V(end) - expectedVrc1_V) < 1e-14 && ...
    abs(constantResult.v_rc2_V(end) - expectedVrc2_V) < 1e-14, ...
    'Each branch must match its analytic constant-current response.');

relaxationProfile = table(...
    [0; 20; 40; 100], ...
    [50; 0; 0; 0], ...
    'VariableNames', {'time_s', 'current_A'});
relaxationResult = simulate_battery_2rc_model(...
    relaxationProfile, parameters);
fastDecayRatio = relaxationResult.v_rc1_V(3) / ...
    relaxationResult.v_rc1_V(2);
slowDecayRatio = relaxationResult.v_rc2_V(3) / ...
    relaxationResult.v_rc2_V(2);
assert(abs(fastDecayRatio - exp(-20 / ...
    result.branch_time_constants_s(1))) < 1e-14 && ...
    abs(slowDecayRatio - exp(-20 / ...
    result.branch_time_constants_s(2))) < 1e-14 && ...
    fastDecayRatio < slowDecayRatio, ...
    'Rest response must preserve distinct fast and slow time constants.');

irregularProfile = table(...
    [0; 1.5; 8; 23], ...
    [10; -5; 15; 0], ...
    'VariableNames', {'time_s', 'current_A'});
irregularResult = simulate_battery_2rc_model(...
    irregularProfile, parameters);
expectedVrc1_V = zeros(height(irregularProfile), 1);
expectedVrc2_V = zeros(height(irregularProfile), 1);
for intervalIndex = 1:(height(irregularProfile) - 1)
    intervalDuration_s = irregularProfile.time_s(intervalIndex + 1) - ...
        irregularProfile.time_s(intervalIndex);
    decay1 = exp(-intervalDuration_s / ...
        (parameters.r1_Ohm * parameters.c1_F));
    decay2 = exp(-intervalDuration_s / ...
        (parameters.r2_Ohm * parameters.c2_F));
    expectedVrc1_V(intervalIndex + 1) = ...
        decay1 * expectedVrc1_V(intervalIndex) + ...
        parameters.r1_Ohm * (1 - decay1) * ...
        irregularProfile.current_A(intervalIndex);
    expectedVrc2_V(intervalIndex + 1) = ...
        decay2 * expectedVrc2_V(intervalIndex) + ...
        parameters.r2_Ohm * (1 - decay2) * ...
        irregularProfile.current_A(intervalIndex);
end
assert(isempty(irregularResult.dt_s) && ...
    isequal(irregularResult.interval_s, diff(irregularProfile.time_s)) && ...
    max(abs(irregularResult.v_rc1_V - expectedVrc1_V)) < 1e-14 && ...
    max(abs(irregularResult.v_rc2_V - expectedVrc2_V)) < 1e-14, ...
    'Irregular intervals must use exact updates for both branches.');

boundaryParameters = parameters;
boundaryParameters.capacity_Ah = 1;
boundaryParameters.initial_soc = 0.10;
boundaryProfile = table(...
    [0; 3600; 7200], ...
    [1; 1; 0], ...
    'VariableNames', {'time_s', 'current_A'});
boundaryResult = simulate_battery_2rc_model(...
    boundaryProfile, boundaryParameters);
assert(max(abs(boundaryResult.current_A - [0.1; 0; 0])) < 1e-12 && ...
    isequal(boundaryResult.current_limited, [true; true; false]) && ...
    max(abs(boundaryResult.soc - [0.1; 0; 0])) < 1e-12, ...
    'Both branches must use SOC-limited applied current at a boundary.');
boundaryVoltage_V = boundaryResult.ocv_V - ...
    boundaryResult.current_A * boundaryParameters.r0_Ohm - ...
    boundaryResult.v_rc1_V - boundaryResult.v_rc2_V;
assert(max(abs(boundaryResult.terminal_voltage_V - boundaryVoltage_V)) < ...
    1e-12, ...
    'Boundary response must retain the full two-RC voltage balance.');

invalidParameters = parameters;
invalidParameters.r2_Ohm = 0;
invalidResistanceRejected = false;
try
    simulate_battery_2rc_model(profile, invalidParameters, 1);
catch validationError
    invalidResistanceRejected = strcmp(validationError.identifier, ...
        'Battery2RC:Parameters');
end
assert(invalidResistanceRejected, ...
    'Simulator must reject a nonpositive second-branch resistance.');

invalidParameters = parameters;
invalidParameters.c2_F = NaN;
invalidCapacitanceRejected = false;
try
    simulate_battery_2rc_model(profile, invalidParameters, 1);
catch validationError
    invalidCapacitanceRejected = strcmp(validationError.identifier, ...
        'Battery2RC:Parameters');
end
assert(invalidCapacitanceRejected, ...
    'Simulator must reject a nonfinite second-branch capacitance.');

missingParameters = rmfield(parameters, 'c2_F');
missingFieldRejected = false;
try
    simulate_battery_2rc_model(profile, missingParameters, 1);
catch validationError
    missingFieldRejected = strcmp(validationError.identifier, ...
        'Battery2RC:Parameters');
end
assert(missingFieldRejected, ...
    'Simulator must reject a missing second-branch parameter.');

repeatResult = simulate_battery_2rc_model(profile, parameters, 1);
assert(isequal(result.soc, repeatResult.soc) && ...
    isequal(result.v_rc1_V, repeatResult.v_rc1_V) && ...
    isequal(result.v_rc2_V, repeatResult.v_rc2_V) && ...
    isequal(result.terminal_voltage_V, repeatResult.terminal_voltage_V), ...
    'Repeated two-RC simulation must be deterministic.');

fprintf('Battery 2RC check passed. Final SOC: %.3f\n', result.soc(end));
fprintf('Voltage range: %.3f V to %.3f V\n', ...
    min(result.terminal_voltage_V), max(result.terminal_voltage_V));
fprintf('Peak polarization: fast %.3f V, slow %.3f V\n', ...
    max(abs(result.v_rc1_V)), max(abs(result.v_rc2_V)));
