function evaluation = evaluate_battery_2rc_fit(data, parameters)
%EVALUATE_BATTERY_2RC_FIT Evaluate parameters against a voltage record.
% data must contain time_s, current_A, and terminal_voltage_V. The simulator
% assumes rested RC states at the first sample.

requiredVariables = {'time_s', 'current_A', 'terminal_voltage_V'};
if ~istable(data) || ...
        ~all(ismember(requiredVariables, data.Properties.VariableNames))
    error('Battery2RCEvaluation:Data', ...
        ['Data must be a table containing time_s, current_A, and ', ...
        'terminal_voltage_V.']);
end

time_s = data.time_s(:);
current_A = data.current_A(:);
measuredVoltage_V = data.terminal_voltage_V(:);
if ~isnumeric(time_s) || ~isnumeric(current_A) || ...
        ~isnumeric(measuredVoltage_V) || ...
        any(~isfinite(time_s)) || any(~isfinite(current_A)) || ...
        any(~isfinite(measuredVoltage_V)) || ...
        numel(current_A) ~= numel(time_s) || ...
        numel(measuredVoltage_V) ~= numel(time_s) || ...
        numel(time_s) < 2
    error('Battery2RCEvaluation:Data', ...
        ['Evaluation columns must be equal-length finite numeric vectors ', ...
        'with at least two samples.']);
end
if any(diff(time_s) <= 0)
    error('Battery2RCEvaluation:Time', ...
        'Evaluation time_s must be strictly increasing.');
end

profile = table( ...
    time_s - time_s(1), current_A, ...
    'VariableNames', {'time_s', 'current_A'});
simulation = simulate_battery_2rc_model(profile, parameters);
predictedVoltage_V = simulation.terminal_voltage_V;
residual_V = measuredVoltage_V - predictedVoltage_V;
residualSumSquares = sum(residual_V.^2);
totalSumSquares = sum((measuredVoltage_V - mean(measuredVoltage_V)).^2);
if totalSumSquares > eps
    rSquared = 1 - residualSumSquares/totalSumSquares;
else
    rSquared = NaN;
end
metrics = struct( ...
    'rmse_V', sqrt(mean(residual_V.^2)), ...
    'mae_V', mean(abs(residual_V)), ...
    'maximum_absolute_error_V', max(abs(residual_V)), ...
    'r_squared', rSquared);
evaluation = struct( ...
    'time_s', time_s, ...
    'simulation', simulation, ...
    'measured_terminal_voltage_V', measuredVoltage_V, ...
    'predicted_terminal_voltage_V', predictedVoltage_V, ...
    'residual_V', residual_V, ...
    'metrics', metrics);
end
