%% Battery RC Model Check
% Validates the shared simulator against the canonical pulse profile.

clear; clc;

modelDirectory = fileparts(mfilename('fullpath'));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory);

profilePath = fullfile(modelDirectory, 'data', 'pulse_current_profile.csv');
profile = readtable(profilePath);
parameters = battery_rc_default_parameters();
result = simulate_battery_rc_model(profile, parameters, 1);

assert(height(profile) >= 10, 'Expected at least 10 sample profile rows.');
assert(numel(result.time_s) == 601, 'Expected a 600-second, 1 Hz result.');
assert(all(isfinite(result.terminal_voltage_V)), ...
    'Terminal voltage must remain finite.');
assert(all(result.soc >= 0 & result.soc <= 1), ...
    'SOC must remain within [0, 1].');
assert(all(result.ocv_V >= parameters.ocv_lookup_V(1) & ...
    result.ocv_V <= parameters.ocv_lookup_V(end)), ...
    'Interpolated OCV must remain inside the lookup-table range.');
assert(max(result.terminal_voltage_V) > min(result.terminal_voltage_V), ...
    'Voltage response should vary over the pulse profile.');
assert(abs(result.soc(end) - 0.7667) < 0.01, ...
    'Final SOC moved outside the expected starter-model tolerance.');
assert(abs(result.ocv_V(1) - 3.73) < 1e-12 && ...
    abs(result.terminal_voltage_V(1) - result.ocv_V(1)) < 1e-12, ...
    'Initial voltage must use the OCV lookup and initial current sample.');
reconstructedVoltage_V = result.ocv_V - ...
    result.current_A * parameters.r0_Ohm - result.v_rc_V;
assert(max(abs(result.terminal_voltage_V - reconstructedVoltage_V)) < 1e-12, ...
    'Terminal voltage must satisfy the equivalent-circuit voltage balance.');

index60 = find(result.time_s == 60, 1);
index61 = find(result.time_s == 61, 1);
assert(result.current_A(index60) == 0 && result.current_A(index61) == 50, ...
    'Canonical discharge pulse must begin after the 60-second sample.');

repeatResult = simulate_battery_rc_model(profile, parameters, 1);
assert(isequal(result.soc, repeatResult.soc) && ...
    isequal(result.ocv_V, repeatResult.ocv_V) && ...
    isequal(result.terminal_voltage_V, repeatResult.terminal_voltage_V), ...
    'Repeated simulation must be deterministic.');

curvedParameters = parameters;
curvedParameters.initial_soc = 0.70;
curvedParameters.ocv_lookup_V = [3.10; 3.48; 3.58; 3.66; 3.78; 4.15];
curvedResult = simulate_battery_rc_model(profile, curvedParameters, 1);
expectedInitialOcv_V = interp1(curvedParameters.ocv_soc_breakpoints, ...
    curvedParameters.ocv_lookup_V, curvedParameters.initial_soc, 'linear');
assert(abs(curvedResult.ocv_V(1) - expectedInitialOcv_V) < 1e-12, ...
    'A custom nonlinear OCV lookup must be interpolated at the initial SOC.');

invalidProfile = profile;
invalidProfile.time_s(2) = invalidProfile.time_s(1);
caughtTimeOrder = false;
try
    simulate_battery_rc_model(invalidProfile, parameters, 1);
catch validationError
    caughtTimeOrder = strcmp(validationError.identifier, 'BatteryRC:TimeOrder');
end
assert(caughtTimeOrder, ...
    'Simulator must reject non-increasing profile timestamps.');

coarseProfile = table(...
    [0; 100], ...
    [50; 50], ...
    'VariableNames', {'time_s', 'current_A'});
coarseResult = simulate_battery_rc_model(coarseProfile, parameters, 100);
expectedCoarseVrc_V = parameters.r1_Ohm * ...
    (1 - exp(-100 / (parameters.r1_Ohm * parameters.c1_F))) * 50;
assert(all(isfinite(coarseResult.v_rc_V)) && ...
    abs(coarseResult.v_rc_V(end) - expectedCoarseVrc_V) < 1e-14, ...
    'A coarse interval must match the bounded analytic RC solution.');

invalidGridRejected = false;
try
    simulate_battery_rc_model(profile, parameters, 7);
catch validationError
    invalidGridRejected = strcmp(...
        validationError.identifier, 'BatteryRC:TimeGrid');
end
assert(invalidGridRejected, ...
    'A requested uniform grid must end exactly at the profile end time.');

irregularProfile = table(...
    [0; 2.5; 9; 13.25], ...
    [12; -8; 5; 0], ...
    'VariableNames', {'time_s', 'current_A'});
irregularResult = simulate_battery_rc_model(irregularProfile, parameters);
assert(isequal(irregularResult.time_s, irregularProfile.time_s) && ...
    isequal(irregularResult.interval_s, diff(irregularProfile.time_s)) && ...
    isempty(irregularResult.dt_s), ...
    'Omitted dt_s must preserve native irregular profile timestamps.');
expectedIrregularSoc = zeros(height(irregularProfile), 1);
expectedIrregularVrc_V = zeros(height(irregularProfile), 1);
expectedIrregularSoc(1) = parameters.initial_soc;
for intervalIndex = 1:(height(irregularProfile) - 1)
    intervalDuration_s = irregularProfile.time_s(intervalIndex + 1) - ...
        irregularProfile.time_s(intervalIndex);
    expectedIrregularSoc(intervalIndex + 1) = min(max(...
        expectedIrregularSoc(intervalIndex) - ...
        irregularProfile.current_A(intervalIndex) * intervalDuration_s / ...
        (parameters.capacity_Ah * 3600), 0), 1);
    decayFactor = exp(-intervalDuration_s / ...
        (parameters.r1_Ohm * parameters.c1_F));
    expectedIrregularVrc_V(intervalIndex + 1) = ...
        decayFactor * expectedIrregularVrc_V(intervalIndex) + ...
        parameters.r1_Ohm * (1 - decayFactor) * ...
        irregularProfile.current_A(intervalIndex);
end
assert(max(abs(irregularResult.soc - expectedIrregularSoc)) < 1e-14 && ...
    max(abs(irregularResult.v_rc_V - expectedIrregularVrc_V)) < 1e-14, ...
    'Every irregular interval must match the analytic SOC and RC updates.');

invalidCurveParameters = parameters;
invalidCurveParameters.ocv_soc_breakpoints(4) = ...
    invalidCurveParameters.ocv_soc_breakpoints(3);
invalidCurveRejected = false;
try
    simulate_battery_rc_model(profile, invalidCurveParameters, 1);
catch validationError
    invalidCurveRejected = strcmp(validationError.identifier, ...
        'BatteryRC:OCVCurve');
end
assert(invalidCurveRejected, ...
    'Simulator must reject non-increasing OCV SOC breakpoints.');

decreasingOcvParameters = parameters;
decreasingOcvParameters.ocv_lookup_V(4) = ...
    decreasingOcvParameters.ocv_lookup_V(3) - 0.01;
decreasingOcvRejected = false;
try
    simulate_battery_rc_model(profile, decreasingOcvParameters, 1);
catch validationError
    decreasingOcvRejected = strcmp(validationError.identifier, ...
        'BatteryRC:OCVCurve');
end
assert(decreasingOcvRejected, ...
    'Simulator must reject OCV values that decrease with SOC.');

fprintf('Battery RC check passed. Final SOC: %.3f\n', result.soc(end));
fprintf('Voltage range: %.3f V to %.3f V\n', ...
    min(result.terminal_voltage_V), max(result.terminal_voltage_V));
