%% Battery RC Model Check
% Validates the shared simulator against the canonical pulse profile.

clear; clc;

modelDirectory = fileparts(mfilename('fullpath'));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory);

profilePath = fullfile(modelDirectory, 'data', 'pulse_current_profile.csv');
profile = readtable(profilePath);
parameters = battery_rc_default_parameters();
result = simulate_battery_rc_model(profile, parameters, 1);

assert(height(profile) >= 10, 'Expected at least 10 sample profile rows.');
assert(numel(result.time_s) == 601, 'Expected a 600-second, 1 Hz result.');
assert(all(isfinite(result.terminal_voltage_V)), ...
    'Terminal voltage must remain finite.');
assert(all(result.soc >= 0 & result.soc <= 1), ...
    'SOC must remain within [0, 1].');
assert(all(result.ocv_V >= parameters.ocv_lookup_V(1) & ...
    result.ocv_V <= parameters.ocv_lookup_V(end)), ...
    'Interpolated OCV must remain inside the lookup-table range.');
assert(max(result.terminal_voltage_V) > min(result.terminal_voltage_V), ...
    'Voltage response should vary over the pulse profile.');
assert(abs(result.soc(end) - 0.7667) < 0.01, ...
    'Final SOC moved outside the expected starter-model tolerance.');
assert(abs(result.ocv_V(1) - 3.73) < 1e-12 && ...
    abs(result.terminal_voltage_V(1) - result.ocv_V(1)) < 1e-12, ...
    'Initial voltage must use the OCV lookup and initial current sample.');
reconstructedVoltage_V = result.ocv_V - ...
    result.current_A * parameters.r0_Ohm - result.v_rc_V;
assert(max(abs(result.terminal_voltage_V - reconstructedVoltage_V)) < 1e-12, ...
    'Terminal voltage must satisfy the equivalent-circuit voltage balance.');

index60 = find(result.time_s == 60, 1);
index61 = find(result.time_s == 61, 1);
assert(result.current_A(index60) == 0 && result.current_A(index61) == 50, ...
    'Canonical discharge pulse must begin after the 60-second sample.');
assert(isequal(result.requested_current_A, result.current_A) && ...
    ~any(result.current_limited), ...
    'Canonical profile must remain inside SOC current limits.');
expectedSocFromCharge = parameters.initial_soc - ...
    result.cumulative_net_discharge_Ah / parameters.capacity_Ah;
assert(max(abs(result.soc - expectedSocFromCharge)) < 1e-12 && ...
    max(abs(result.soc_charge_balance_error)) < 1e-12, ...
    'SOC must close against cumulative applied-current charge balance.');

duty = summarize_battery_duty_cycle(result);
expectedDischarged_Ah = sum(max(result.current_A(1:end-1), 0) .* ...
    result.interval_s) / 3600;
expectedCharged_Ah = sum(max(-result.current_A(1:end-1), 0) .* ...
    result.interval_s) / 3600;
signedTerminalEnergy_Wh = result.current_A(1:end-1) .* ...
    result.terminal_voltage_V(1:end-1) .* result.interval_s / 3600;
assert(abs(duty.discharged_Ah - expectedDischarged_Ah) < 1e-14 && ...
    abs(duty.charged_Ah - expectedCharged_Ah) < 1e-14 && ...
    abs(duty.net_discharged_Ah - ...
    (expectedDischarged_Ah - expectedCharged_Ah)) < 1e-14, ...
    'Duty summary must preserve directional and net charge.');
assert(abs(duty.charge_throughput_Ah - ...
    (duty.discharged_Ah + duty.charged_Ah)) < 1e-14 && ...
    abs(duty.equivalent_full_cycles - ...
    duty.charge_throughput_Ah / (2 * parameters.capacity_Ah)) < 1e-14, ...
    'Charge throughput and equivalent full cycles are inconsistent.');
assert(abs(duty.discharged_energy_Wh - ...
    sum(max(signedTerminalEnergy_Wh, 0))) < 1e-14 && ...
    abs(duty.charged_energy_Wh - ...
    sum(max(-signedTerminalEnergy_Wh, 0))) < 1e-14 && ...
    abs(duty.net_delivered_energy_Wh - ...
    (duty.discharged_energy_Wh - duty.charged_energy_Wh)) < 1e-14 && ...
    abs(duty.energy_throughput_Wh - ...
    (duty.discharged_energy_Wh + duty.charged_energy_Wh)) < 1e-14, ...
    'Duty summary must preserve directional and net terminal energy.');
assert(abs(duty.soc_charge_balance_error) < 1e-12 && ...
    duty.minimum_soc == min(result.soc) && ...
    duty.maximum_soc == max(result.soc) && ...
    duty.minimum_terminal_voltage_V == min(result.terminal_voltage_V) && ...
    duty.maximum_terminal_voltage_V == max(result.terminal_voltage_V), ...
    'Duty summary extrema and SOC charge balance are inconsistent.');

repeatResult = simulate_battery_rc_model(profile, parameters, 1);
assert(isequal(result.soc, repeatResult.soc) && ...
    isequal(result.ocv_V, repeatResult.ocv_V) && ...
    isequal(result.terminal_voltage_V, repeatResult.terminal_voltage_V), ...
    'Repeated simulation must be deterministic.');

curvedParameters = parameters;
curvedParameters.initial_soc = 0.70;
curvedParameters.ocv_lookup_V = [3.10; 3.48; 3.58; 3.66; 3.78; 4.15];
curvedResult = simulate_battery_rc_model(profile, curvedParameters, 1);
expectedInitialOcv_V = interp1(curvedParameters.ocv_soc_breakpoints, ...
    curvedParameters.ocv_lookup_V, curvedParameters.initial_soc, 'linear');
assert(abs(curvedResult.ocv_V(1) - expectedInitialOcv_V) < 1e-12, ...
    'A custom nonlinear OCV lookup must be interpolated at the initial SOC.');

invalidProfile = profile;
invalidProfile.time_s(2) = invalidProfile.time_s(1);
caughtTimeOrder = false;
try
    simulate_battery_rc_model(invalidProfile, parameters, 1);
catch validationError
    caughtTimeOrder = strcmp(validationError.identifier, 'BatteryRC:TimeOrder');
end
assert(caughtTimeOrder, ...
    'Simulator must reject non-increasing profile timestamps.');

coarseProfile = table(...
    [0; 100], ...
    [50; 50], ...
    'VariableNames', {'time_s', 'current_A'});
coarseResult = simulate_battery_rc_model(coarseProfile, parameters, 100);
expectedCoarseVrc_V = parameters.r1_Ohm * ...
    (1 - exp(-100 / (parameters.r1_Ohm * parameters.c1_F))) * 50;
assert(all(isfinite(coarseResult.v_rc_V)) && ...
    abs(coarseResult.v_rc_V(end) - expectedCoarseVrc_V) < 1e-14, ...
    'A coarse interval must match the bounded analytic RC solution.');

invalidGridRejected = false;
try
    simulate_battery_rc_model(profile, parameters, 7);
catch validationError
    invalidGridRejected = strcmp(...
        validationError.identifier, 'BatteryRC:TimeGrid');
end
assert(invalidGridRejected, ...
    'A requested uniform grid must end exactly at the profile end time.');

irregularProfile = table(...
    [0; 2.5; 9; 13.25], ...
    [12; -8; 5; 0], ...
    'VariableNames', {'time_s', 'current_A'});
irregularResult = simulate_battery_rc_model(irregularProfile, parameters);
assert(isequal(irregularResult.time_s, irregularProfile.time_s) && ...
    isequal(irregularResult.interval_s, diff(irregularProfile.time_s)) && ...
    isempty(irregularResult.dt_s), ...
    'Omitted dt_s must preserve native irregular profile timestamps.');
expectedIrregularSoc = zeros(height(irregularProfile), 1);
expectedIrregularVrc_V = zeros(height(irregularProfile), 1);
expectedIrregularSoc(1) = parameters.initial_soc;
for intervalIndex = 1:(height(irregularProfile) - 1)
    intervalDuration_s = irregularProfile.time_s(intervalIndex + 1) - ...
        irregularProfile.time_s(intervalIndex);
    expectedIrregularSoc(intervalIndex + 1) = min(max(...
        expectedIrregularSoc(intervalIndex) - ...
        irregularProfile.current_A(intervalIndex) * intervalDuration_s / ...
        (parameters.capacity_Ah * 3600), 0), 1);
    decayFactor = exp(-intervalDuration_s / ...
        (parameters.r1_Ohm * parameters.c1_F));
    expectedIrregularVrc_V(intervalIndex + 1) = ...
        decayFactor * expectedIrregularVrc_V(intervalIndex) + ...
        parameters.r1_Ohm * (1 - decayFactor) * ...
        irregularProfile.current_A(intervalIndex);
end
assert(max(abs(irregularResult.soc - expectedIrregularSoc)) < 1e-14 && ...
    max(abs(irregularResult.v_rc_V - expectedIrregularVrc_V)) < 1e-14, ...
    'Every irregular interval must match the analytic SOC and RC updates.');
assert(isequal(irregularResult.requested_current_A, ...
    irregularResult.current_A) && ~any(irregularResult.current_limited), ...
    'Feasible irregular currents must pass through without limiting.');
irregularDuty = summarize_battery_duty_cycle(irregularResult);
expectedIrregularDischarge_Ah = (12 * 2.5 + 5 * 4.25) / 3600;
expectedIrregularCharge_Ah = 8 * 6.5 / 3600;
assert(abs(irregularDuty.discharged_Ah - ...
    expectedIrregularDischarge_Ah) < 1e-14 && ...
    abs(irregularDuty.charged_Ah - expectedIrregularCharge_Ah) < 1e-14 && ...
    irregularDuty.duration_s == 13.25, ...
    'Duty integration must respect each native irregular interval.');

boundaryParameters = parameters;
boundaryParameters.capacity_Ah = 1;
boundaryParameters.initial_soc = 0.10;
emptyBoundaryProfile = table(...
    [0; 3600; 7200], ...
    [1; 1; 0], ...
    'VariableNames', {'time_s', 'current_A'});
emptyBoundaryResult = simulate_battery_rc_model(...
    emptyBoundaryProfile, boundaryParameters);
assert(max(abs(emptyBoundaryResult.current_A - [0.1; 0; 0])) < 1e-12 && ...
    isequal(emptyBoundaryResult.current_limited, [true; true; false]), ...
    'Discharge current must be limited by energy available above zero SOC.');
assert(max(abs(emptyBoundaryResult.soc - [0.1; 0; 0])) < 1e-12 && ...
    max(abs(emptyBoundaryResult.interval_net_discharge_Ah - [0.1; 0])) < ...
    1e-12 && ...
    max(abs(emptyBoundaryResult.cumulative_net_discharge_Ah - ...
    [0; 0.1; 0.1])) < 1e-12, ...
    'Discharge boundary case must preserve interval and cumulative charge.');
emptyDecayFactor = exp(-3600 / ...
    (boundaryParameters.r1_Ohm * boundaryParameters.c1_F));
expectedBoundaryVrc_V = [
    0;
    boundaryParameters.r1_Ohm * (1 - emptyDecayFactor) * 0.1;
    emptyDecayFactor * boundaryParameters.r1_Ohm * ...
    (1 - emptyDecayFactor) * 0.1
];
assert(max(abs(emptyBoundaryResult.v_rc_V - expectedBoundaryVrc_V)) < ...
    1e-12, ...
    'RC polarization must use SOC-limited applied current.');
emptyBoundaryVoltage_V = emptyBoundaryResult.ocv_V - ...
    emptyBoundaryResult.current_A * boundaryParameters.r0_Ohm - ...
    emptyBoundaryResult.v_rc_V;
assert(max(abs(emptyBoundaryResult.terminal_voltage_V - ...
    emptyBoundaryVoltage_V)) < 1e-12 && ...
    abs(emptyBoundaryResult.terminal_voltage_V(1) - ...
    (emptyBoundaryResult.ocv_V(1) - 0.1 * boundaryParameters.r0_Ohm)) < ...
    1e-12, ...
    'Terminal voltage must use SOC-limited applied current.');

boundaryParameters.initial_soc = 0.90;
fullBoundaryProfile = table(...
    [0; 3600], ...
    [-1; -1], ...
    'VariableNames', {'time_s', 'current_A'});
fullBoundaryResult = simulate_battery_rc_model(...
    fullBoundaryProfile, boundaryParameters);
assert(max(abs(fullBoundaryResult.current_A - [-0.1; 0])) < 1e-12 && ...
    all(fullBoundaryResult.current_limited) && ...
    max(abs(fullBoundaryResult.soc - [0.9; 1])) < 1e-12, ...
    'Charge current must be limited by headroom below full SOC.');
assert(max(abs(fullBoundaryResult.soc_charge_balance_error)) < 1e-12, ...
    'Charge boundary case must close its SOC charge balance.');

invalidCurveParameters = parameters;
invalidCurveParameters.ocv_soc_breakpoints(4) = ...
    invalidCurveParameters.ocv_soc_breakpoints(3);
invalidCurveRejected = false;
try
    simulate_battery_rc_model(profile, invalidCurveParameters, 1);
catch validationError
    invalidCurveRejected = strcmp(validationError.identifier, ...
        'BatteryRC:OCVCurve');
end
assert(invalidCurveRejected, ...
    'Simulator must reject non-increasing OCV SOC breakpoints.');

decreasingOcvParameters = parameters;
decreasingOcvParameters.ocv_lookup_V(4) = ...
    decreasingOcvParameters.ocv_lookup_V(3) - 0.01;
decreasingOcvRejected = false;
try
    simulate_battery_rc_model(profile, decreasingOcvParameters, 1);
catch validationError
    decreasingOcvRejected = strcmp(validationError.identifier, ...
        'BatteryRC:OCVCurve');
end
assert(decreasingOcvRejected, ...
    'Simulator must reject OCV values that decrease with SOC.');

terminalSampleResult = result;
terminalSampleResult.current_A(end) = 1e9;
terminalSampleDuty = summarize_battery_duty_cycle(terminalSampleResult);
assert(terminalSampleDuty.charge_throughput_Ah == ...
    duty.charge_throughput_Ah && ...
    terminalSampleDuty.energy_throughput_Wh == ...
    duty.energy_throughput_Wh, ...
    'The final timestamp must not create a nonexistent energy interval.');

invalidDutyCases = {
    rmfield(result, 'soc'), 'BatteryDuty:ResultFields';
    setfield(result, 'current_A', result.current_A(1:end-1)), ... %#ok<SFLD>
        'BatteryDuty:SignalShape';
    setfield(result, 'time_s', [0; result.time_s(1:end-1)]), ... %#ok<SFLD>
        'BatteryDuty:TimeOrder';
    setfield(result, 'terminal_voltage_V', ... %#ok<SFLD>
        [0; result.terminal_voltage_V(2:end)]), ...
        'BatteryDuty:TerminalVoltage';
    setfield(result, 'soc', [-0.1; result.soc(2:end)]), ... %#ok<SFLD>
        'BatteryDuty:SOCBounds'
};
for caseIndex = 1:size(invalidDutyCases, 1)
    rejected = false;
    try
        summarize_battery_duty_cycle(invalidDutyCases{caseIndex, 1});
    catch validationError
        rejected = strcmp(validationError.identifier, ...
            invalidDutyCases{caseIndex, 2});
    end
    assert(rejected, ...
        'Duty summary must reject malformed result signals deterministically.');
end
invalidCapacityResult = result;
invalidCapacityResult.parameters.capacity_Ah = 0;
invalidCapacityRejected = false;
try
    summarize_battery_duty_cycle(invalidCapacityResult);
catch validationError
    invalidCapacityRejected = strcmp(validationError.identifier, ...
        'BatteryDuty:Capacity');
end
assert(invalidCapacityRejected, ...
    'Duty summary must reject nonpositive battery capacity.');

fprintf('Battery RC check passed. Final SOC: %.3f\n', result.soc(end));
fprintf('Voltage range: %.3f V to %.3f V\n', ...
    min(result.terminal_voltage_V), max(result.terminal_voltage_V));
fprintf('Charge throughput: %.3f Ah (%.5f equivalent full cycles)\n', ...
    duty.charge_throughput_Ah, duty.equivalent_full_cycles);
fprintf('Terminal energy throughput: %.3f Wh\n', ...
    duty.energy_throughput_Wh);
