classdef TestBessUnifiedControl < matlab.unittest.TestCase
    %TESTBESSUNIFIEDCONTROL Deterministic unit and integration tests.

    properties (TestParameter)
        ScenarioIndex = num2cell(1:8)
    end

    properties
        ExampleDirectory
        Parameters
        Scenarios
    end

    methods (TestMethodSetup)
        function addExamplePaths(testCase)
            testCase.ExampleDirectory = fileparts(fileparts( ...
                mfilename('fullpath')));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                {testCase.ExampleDirectory, ...
                fullfile(testCase.ExampleDirectory, 'src')}));
            testCase.Parameters = bess_unified_control_parameters();
            testCase.Scenarios = bess_validation_scenarios( ...
                testCase.Parameters);
        end
    end

    methods (Test)
        function parameterBasesAreSelfConsistent(testCase)
            expectedCurrent = testCase.Parameters.rated_power_VA / ...
                (sqrt(3) * ...
                testCase.Parameters.nominal_line_voltage_V);
            testCase.verifyEqual(testCase.Parameters.base_current_A, ...
                expectedCurrent, 'AbsTol', 1e-12);
            testCase.verifyEqual( ...
                testCase.Parameters.base_phase_voltage_V, ...
                testCase.Parameters.nominal_line_voltage_V / sqrt(3), ...
                'AbsTol', 1e-12);
        end

        function parameterValidationRejectsUnknownOverride(testCase)
            testCase.verifyError(@() ...
                bess_unified_control_parameters( ...
                struct('not_a_parameter', 1)), ...
                'BessUnifiedControl:Overrides');
            testCase.verifyError(@() ...
                bess_unified_control_parameters( ...
                struct('sample_time_s', -0.01)), ...
                'BessUnifiedControl:Parameters');
        end

        function nonfiniteRawInputIsRejected(testCase)
            testCase.verifyError(@() bess_unpack_input(nan(16, 1)), ...
                'MATLAB:expectedFinite');
        end

        function negativeFeedbackAndGateValuesAreRejected(testCase)
            fields = {
                'grid_voltage_sensitivity_pu_per_pu', ...
                'grid_frequency_droop_Hz_per_pu', ...
                'grid_voltage_droop_pu_per_pu', ...
                'frequency_restoration_gain_per_s', ...
                'voltage_restoration_gain_per_s', ...
                'grid_support_frequency_gain_pu_per_Hz', ...
                'grid_support_voltage_gain_pu_per_pu', ...
                'sync_phase_gain_Hz_per_rad', ...
                'sync_voltage_gain', ...
                'transition_frequency_fraction', ...
                'steady_power_error_pu', ...
                'steady_voltage_error_pu', ...
                'steady_frequency_error_fraction', ...
                'numeric_current_tolerance'
            };
            for fieldIndex = 1:numel(fields)
                override = struct();
                override.(fields{fieldIndex}) = -0.01;
                testCase.verifyError(@() ...
                    bess_unified_control_parameters(override), ...
                    'BessUnifiedControl:Parameters', fields{fieldIndex});
            end
        end

        function stateNamesCoverExplicitSupervisor(testCase)
            expectedNames = {
                'GRID_FOLLOWING', 'PREPARE_ISLAND', 'GRID_FORMING', ...
                'ISLANDED_SUPPORT', 'SYNCHRONIZING', ...
                'PREPARE_RECONNECT', 'RECOVERY', 'FAULT_SAFE'
            };
            for stateCode = 1:numel(expectedNames)
                testCase.verifyEqual(bess_state_name(stateCode), ...
                    expectedNames{stateCode});
            end
            testCase.verifyError(@() bess_state_name(0), ...
                'BessUnifiedControl:StateCode');
        end

        function balancedTransformsAndPowerAreCorrect(testCase)
            theta = 0.37;
            voltageMagnitude = 1.04;
            currentMagnitude = 0.61;
            powerAngle = -0.22;
            voltageAbc = voltageMagnitude * cos( ...
                theta + [0, -2 * pi / 3, 2 * pi / 3]);
            currentAbc = currentMagnitude * cos( ...
                theta - powerAngle + [0, -2 * pi / 3, 2 * pi / 3]);
            [alpha, beta] = bess_clarke_transform( ...
                voltageAbc(1), voltageAbc(2), voltageAbc(3));
            [dAxis, qAxis] = bess_park_transform(alpha, beta, theta);
            [activePower, reactivePower] = bess_power_from_abc( ...
                voltageAbc, currentAbc);

            testCase.verifyEqual(dAxis, voltageMagnitude, ...
                'AbsTol', 1e-12);
            testCase.verifyEqual(qAxis, 0, 'AbsTol', 1e-12);
            testCase.verifyEqual(activePower, ...
                0.5 * voltageMagnitude * currentMagnitude * ...
                cos(powerAngle), ...
                'AbsTol', 1e-12);
            testCase.verifyEqual(reactivePower, ...
                0.5 * voltageMagnitude * currentMagnitude * ...
                sin(powerAngle), ...
                'AbsTol', 1e-12);
        end

        function dqPlantStatesDeterminePowerAndCurrent(testCase)
            scenario = testCase.Scenarios(1);
            inputVector = bess_scenario_input_vector(scenario, 1);
            state = bess_initialize_plant_state( ...
                inputVector, testCase.Parameters);
            states = bess_state_codes();
            command.breaker_command = true;
            command.controller_ready = true;
            command.measurement_valid = true;
            command.p_command_pu = 0.5;
            command.q_command_pu = 0.2;
            command.voltage_command_pu = 1;
            command.frequency_command_Hz = ...
                testCase.Parameters.nominal_frequency_Hz;
            command.state_code = states.GRID_FOLLOWING;
            state = bess_plant_step(inputVector, command, ...
                state, testCase.Parameters);
            measurement = bess_measure_plant(state);

            testCase.verifyEqual(state.p_pu, ...
                state.voltage_pu * state.current_d_pu, ...
                'AbsTol', 1e-12);
            testCase.verifyEqual(state.q_pu, ...
                -state.voltage_pu * state.current_q_pu, ...
                'AbsTol', 1e-12);
            testCase.verifyEqual(measurement.current_pu, hypot( ...
                state.current_d_pu, state.current_q_pu), ...
                'AbsTol', 1e-12);
            testCase.verifyLessThanOrEqual(measurement.current_pu, ...
                testCase.Parameters.current_limit_pu + 1e-12);
        end

        function pqLimiterRespectsCurrentAndPowerLimits(testCase)
            [activePower, reactivePower, ~, saturated] = bess_limit_pq( ...
                1.3, 0.8, 1.0, 1.0, testCase.Parameters);
            testCase.verifyTrue(saturated);
            testCase.verifyLessThanOrEqual( ...
                hypot(activePower, reactivePower), ...
                testCase.Parameters.current_limit_pu + 1e-12);
            testCase.verifyLessThanOrEqual(abs(activePower), ...
                testCase.Parameters.active_power_limit_pu + 1e-12);
            testCase.verifyLessThanOrEqual(abs(reactivePower), ...
                testCase.Parameters.reactive_power_limit_pu + 1e-12);
        end

        function synchronizationWindowIsEnforced(testCase)
            metrics = bess_sync_metrics( ...
                1.00, 50.00, deg2rad(1), ...
                1.03, 50.05, deg2rad(4), testCase.Parameters);
            testCase.verifyTrue(metrics.within_limits);
            testCase.verifyLessThanOrEqual( ...
                metrics.phase_mismatch_deg, ...
                testCase.Parameters.sync_phase_threshold_deg);

            notReadyMetrics = bess_sync_metrics( ...
                1.00, 50.00, 0, ...
                1.06, 50.00, 0, testCase.Parameters);
            testCase.verifyFalse(notReadyMetrics.within_limits);
        end

        function formingDroopMatchesIndependentCalculation(testCase)
            scenario = testCase.Scenarios(4);
            inputVector = bess_scenario_input_vector(scenario, 1);
            plantState = bess_initialize_plant_state( ...
                inputVector, testCase.Parameters);
            measurement = bess_measure_plant(plantState);
            controllerState = bess_initialize_controller_state( ...
                inputVector, measurement);
            [command, ~] = bess_controller_step(inputVector, ...
                measurement, controllerState, testCase.Parameters);

            rawFrequency = ...
                testCase.Parameters.nominal_frequency_Hz - ...
                testCase.Parameters.grid_frequency_droop_Hz_per_pu * ...
                (measurement.p_pu - scenario.inputs.p_ref_pu(1));
            maximumStep = ...
                testCase.Parameters.frequency_command_slew_Hz_per_s * ...
                testCase.Parameters.sample_time_s;
            expectedFrequency = measurement.frequency_Hz + min(max( ...
                rawFrequency - measurement.frequency_Hz, ...
                -maximumStep), maximumStep);
            testCase.verifyEqual(command.frequency_command_Hz, ...
                expectedFrequency, 'AbsTol', 1e-12);
            testCase.verifyEqual(command.voltage_command_pu, 1, ...
                'AbsTol', 1e-12);
        end

        function gridSupportReactiveSignRaisesVoltage(testCase)
            supportedScenario = testCase.Scenarios(2);
            unsupportedScenario = supportedScenario;
            unsupportedScenario.inputs.grid_support_enable(:) = 0;
            supported = simulate_bess_unified_control( ...
                supportedScenario, testCase.Parameters);
            unsupported = simulate_bess_unified_control( ...
                unsupportedScenario, testCase.Parameters);
            disturbance = supported.time_s >= 2 & ...
                supported.time_s < 2.15;
            improvement = supported.voltage_pu(disturbance) - ...
                unsupported.voltage_pu(disturbance);
            testCase.verifyGreaterThan(max(improvement), 1e-4);
            testCase.verifyGreaterThanOrEqual(min(improvement), -1e-12);
        end

        function formingRestorationAntiWindupIsBoundedAndReversible( ...
                testCase)
            scenario = testCase.Scenarios(4);
            inputVector = bess_scenario_input_vector(scenario, 1);
            inputVector(6) = 1.5;
            inputVector(7) = 1.0;
            plantState = bess_initialize_plant_state( ...
                inputVector, testCase.Parameters);
            measurement = bess_measure_plant(plantState);
            controllerState = bess_initialize_controller_state( ...
                inputVector, measurement);
            measurement.frequency_Hz = 49;
            measurement.voltage_pu = 0.8;
            saturated = false;
            for stepIndex = 1:500
                [command, controllerState] = bess_controller_step( ...
                    inputVector, measurement, controllerState, ...
                    testCase.Parameters);
                saturated = saturated || command.saturated;
            end
            testCase.verifyTrue(saturated);
            testCase.verifyEqual( ...
                controllerState.frequency_restoration_Hz, 1, ...
                'AbsTol', 1e-12);
            testCase.verifyEqual( ...
                controllerState.voltage_restoration_pu, 0.2, ...
                'AbsTol', 1e-12);

            measurement.frequency_Hz = 51;
            measurement.voltage_pu = 1.2;
            for stepIndex = 1:200
                [~, controllerState] = bess_controller_step( ...
                    inputVector, measurement, controllerState, ...
                    testCase.Parameters);
            end
            testCase.verifyLessThan( ...
                controllerState.frequency_restoration_Hz, 1);
            testCase.verifyLessThan( ...
                controllerState.voltage_restoration_pu, 0.2);
            testCase.verifyGreaterThanOrEqual( ...
                controllerState.frequency_restoration_Hz, -1);
            testCase.verifyGreaterThanOrEqual( ...
                controllerState.voltage_restoration_pu, -0.2);
        end

        function traceabilityCoversEveryRequirement(testCase)
            traceabilityPath = fullfile(testCase.ExampleDirectory, ...
                'requirements', 'traceability.csv');
            matrix = readtable(traceabilityPath, ...
                'TextType', 'string', ...
                'VariableNamingRule', 'preserve');
            testCase.verifyGreaterThan(height(matrix), 0);
            testCase.verifyTrue(all(strlength( ...
                matrix.requirement_id) > 0));
            testCase.verifyTrue(all(strlength(matrix.implementation) > 0));
            testCase.verifyTrue(all(strlength(matrix.test) > 0));
            allowedStatus = matrix.status == "PASS" | ...
                matrix.status == "PENDING_PUBLICATION";
            testCase.verifyTrue(all(allowedStatus));
            pendingIds = matrix.requirement_id( ...
                matrix.status == "PENDING_PUBLICATION");
            if ~isempty(pendingIds)
                testCase.verifyEqual(pendingIds, "BESS-EVID-006");
            end
            testCase.verifyEqual(numel(unique(matrix.requirement_id)), ...
                height(matrix));
        end

        function mandatoryScenarioPasses(testCase, ScenarioIndex)
            result = simulate_bess_unified_control( ...
                testCase.Scenarios(ScenarioIndex), testCase.Parameters);
            score = bess_score_scenario(result, testCase.Parameters);
            testCase.verifyTrue(score.passed, ...
                strjoin(score.failures, newline));
        end

        function mandatoryScenarioIsDeterministic( ...
                testCase, ScenarioIndex)
            first = simulate_bess_unified_control( ...
                testCase.Scenarios(ScenarioIndex), testCase.Parameters);
            second = simulate_bess_unified_control( ...
                testCase.Scenarios(ScenarioIndex), testCase.Parameters);
            testCase.verifyEqual(second.p_pu, first.p_pu);
            testCase.verifyEqual(second.q_pu, first.q_pu);
            testCase.verifyEqual(second.voltage_pu, first.voltage_pu);
            testCase.verifyEqual(second.frequency_Hz, ...
                first.frequency_Hz);
            testCase.verifyEqual(second.state_code, first.state_code);
        end

        function generatedModelIsIdempotentAndExecutable(testCase)
            firstDirectory = tempname;
            secondDirectory = tempname;
            cleanup = onCleanup(@() clean_directories( ...
                firstDirectory, secondDirectory));
            scenario = testCase.Scenarios(1);
            firstModel = build_bess_unified_control_model( ...
                firstDirectory, scenario, testCase.Parameters);
            secondModel = build_bess_unified_control_model( ...
                secondDirectory, scenario, testCase.Parameters);

            firstSignature = model_signature(firstModel);
            secondSignature = model_signature(secondModel);
            testCase.verifyEqual(secondSignature, firstSignature);

            result = simulate_bess_unified_control_model( ...
                scenario, testCase.Parameters, firstModel);
            score = bess_score_scenario(result, testCase.Parameters);
            testCase.verifyTrue(score.passed, ...
                strjoin(score.failures, newline));
            clear cleanup;
        end

        function generatedModelMatchesReferenceForAllScenarios(testCase)
            outputDirectory = tempname;
            cleanup = onCleanup(@() clean_directories(outputDirectory));
            modelPath = build_bess_unified_control_model( ...
                outputDirectory, testCase.Scenarios(1), ...
                testCase.Parameters);

            numericFields = {
                'p_pu', 'q_pu', 'voltage_pu', 'frequency_Hz', ...
                'phase_rad', 'current_pu', 'state_code', ...
                'p_command_pu', 'q_command_pu', ...
                'voltage_command_pu', 'frequency_command_Hz', ...
                'phase_error_rad', 'voltage_mismatch_pu', ...
                'frequency_mismatch_Hz'
            };
            logicalFields = {
                'breaker_closed', 'controller_ready', 'sync_ready', ...
                'saturated', 'faulted', 'measurement_valid'
            };
            for scenarioIndex = 1:numel(testCase.Scenarios)
                scenario = testCase.Scenarios(scenarioIndex);
                reference = simulate_bess_unified_control( ...
                    scenario, testCase.Parameters);
                actual = simulate_bess_unified_control_model( ...
                    scenario, testCase.Parameters, modelPath);
                score = bess_score_scenario(actual, testCase.Parameters);
                testCase.verifyTrue(score.passed, ...
                    sprintf('Scenario %s: %s', scenario.id, ...
                    strjoin(score.failures, newline)));
                for fieldIndex = 1:numel(numericFields)
                    fieldName = numericFields{fieldIndex};
                    testCase.verifyEqual(actual.(fieldName), ...
                        reference.(fieldName), 'AbsTol', 1e-12, ...
                        sprintf('Scenario %s field %s', ...
                        scenario.id, fieldName));
                end
                for fieldIndex = 1:numel(logicalFields)
                    fieldName = logicalFields{fieldIndex};
                    testCase.verifyEqual(actual.(fieldName), ...
                        reference.(fieldName), ...
                        sprintf('Scenario %s field %s', ...
                        scenario.id, fieldName));
                end
            end
            clear cleanup;
        end
    end
end

function signature = model_signature(modelPath)
[modelDirectory, modelName] = fileparts(modelPath);
fileGenerationConfig = Simulink.fileGenControl('getConfig');
fileGenerationCleanup = onCleanup(@() ...
    Simulink.fileGenControl('setConfig', ...
    'config', fileGenerationConfig));
Simulink.fileGenControl('set', ...
    'CacheFolder', fullfile(modelDirectory, 'cache'), ...
    'CodeGenFolder', fullfile(modelDirectory, 'codegen'), ...
    'createDir', true);
load_system(modelPath);
cleanup = onCleanup(@() close_system(modelName, 0));
blocks = find_system(modelName, ...
    'LookUnderMasks', 'all', 'FollowLinks', 'on', ...
    'MatchFilter', @Simulink.match.allVariants, 'Type', 'Block');
blocks = erase(blocks, [modelName, '/']);
signature.blocks = sort(blocks);
signature.solver_type = get_param(modelName, 'SolverType');
signature.solver = get_param(modelName, 'Solver');
signature.fixed_step = get_param(modelName, 'FixedStep');
signature.outport_count = numel(find_system(modelName, ...
    'SearchDepth', 1, 'BlockType', 'Outport'));
clear cleanup fileGenerationCleanup;
end

function clean_directories(varargin)
for directoryIndex = 1:nargin
    directory = varargin{directoryIndex};
    if isfolder(directory)
        rmdir(directory, 's');
    end
end
end
