%% Battery OCV Hysteresis Check
% Validates exact hysteresis propagation, memory, and charge balance.

clearvars; clc;

modelDirectory = fileparts(mfilename('fullpath'));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory);

profile = battery_hysteresis_default_profile();
parameters = battery_hysteresis_default_parameters();
result = simulate_battery_ocv_hysteresis(profile, parameters);

assert(isequal(result.time_s, profile.time_s) && isempty(result.dt_s), ...
    'The native reversal profile must preserve its irregular timestamps.');
assert(all(isfinite(result.terminal_voltage_V)) && ...
    all(isfinite(result.hysteresis_state)), ...
    'Voltage and hysteresis states must remain finite.');
assert(all(result.soc >= 0 & result.soc <= 1), ...
    'SOC must remain within [0, 1].');
assert(all(abs(result.hysteresis_state) <= 1 + 1e-14), ...
    'The normalized hysteresis state must remain within [-1, 1].');
assert(~any(result.current_limited), ...
    'The canonical reversal profile must remain inside SOC limits.');

expectedSoc = parameters.initial_soc - ...
    result.cumulative_net_discharge_Ah/parameters.capacity_Ah;
assert(max(abs(result.soc - expectedSoc)) < 1e-12 && ...
    max(abs(result.soc_charge_balance_error)) < 1e-12, ...
    'SOC must close against cumulative applied-current charge balance.');
reconstructedVoltage_V = result.ocv_mean_V + ...
    result.hysteresis_voltage_V - ...
    result.current_A*parameters.r0_Ohm - result.v_rc_V;
assert(max(abs(result.terminal_voltage_V - reconstructedVoltage_V)) < ...
    1e-12, ...
    'Terminal voltage must satisfy the complete hysteresis ECM balance.');

index900 = find(result.time_s == 900, 1);
index1200 = find(result.time_s == 1200, 1);
index1500 = find(result.time_s == 1500, 1);
index1800 = find(result.time_s == 1800, 1);
index2100 = find(result.time_s == 2100, 1);
index2400 = find(result.time_s == 2400, 1);

gamma = parameters.hysteresis_rate_per_fractional_throughput;
expectedAfterDischarge = -1 + exp(-gamma*0.10);
expectedAfterChargeReversal = 1 + ...
    (expectedAfterDischarge - 1)*exp(-gamma*0.05);
expectedAfterSecondDischarge = -1 + ...
    (expectedAfterChargeReversal + 1)*exp(-gamma*0.05);
assert(abs(result.hysteresis_state(index900) - ...
    expectedAfterDischarge) < 1e-12, ...
    'The first discharge must match the exact one-state update.');
assert(result.hysteresis_state(index1200) == ...
    result.hysteresis_state(index900) && ...
    result.hysteresis_state(index1800) == ...
    result.hysteresis_state(index1500) && ...
    result.hysteresis_state(index2400) == ...
    result.hysteresis_state(index2100), ...
    'Zero-current intervals must preserve hysteresis memory exactly.');
assert(abs(result.hysteresis_state(index1500) - ...
    expectedAfterChargeReversal) < 1e-12 && ...
    abs(result.hysteresis_state(index2100) - ...
    expectedAfterSecondDischarge) < 1e-12, ...
    'Charge and discharge reversals must follow the exact minor-loop state.');

assert(abs(result.soc(index1200) - result.soc(index2400)) < 1e-12, ...
    'The two minor-loop comparison points must have equal SOC.');
minorLoopGap_V = result.equilibrium_voltage_V(index2400) - ...
    result.equilibrium_voltage_V(index1200);
expectedMinorLoopGap_V = parameters.hysteresis_max_V* ...
    (expectedAfterSecondDischarge - expectedAfterDischarge);
assert(abs(minorLoopGap_V - expectedMinorLoopGap_V) < 1e-12 && ...
    minorLoopGap_V > 0.005, ...
    'Reversal history must create a visible same-SOC minor-loop gap.');

uniformResult = simulate_battery_ocv_hysteresis(profile, parameters, 10);
originalIndices = round(profile.time_s/10) + 1;
assert(max(abs(uniformResult.soc(originalIndices) - result.soc)) < 1e-12 && ...
    max(abs(uniformResult.hysteresis_state(originalIndices) - ...
    result.hysteresis_state)) < 1e-12 && ...
    max(abs(uniformResult.v_rc_V(originalIndices) - result.v_rc_V)) < ...
    1e-12, ...
    'Exact state propagation must be invariant at shared profile timestamps.');

noHysteresisParameters = parameters;
noHysteresisParameters.hysteresis_max_V = 0;
noHysteresisResult = simulate_battery_ocv_hysteresis(...
    profile, noHysteresisParameters);
assert(~any(noHysteresisResult.hysteresis_voltage_V) && ...
    max(abs(noHysteresisResult.equilibrium_voltage_V - ...
    noHysteresisResult.ocv_mean_V)) < 1e-14, ...
    'Zero hysteresis magnitude must reduce the equilibrium voltage to OCV.');

frozenParameters = parameters;
frozenParameters.hysteresis_rate_per_fractional_throughput = 0;
frozenParameters.initial_hysteresis_state = 0.35;
frozenResult = simulate_battery_ocv_hysteresis(profile, frozenParameters);
assert(all(frozenResult.hysteresis_state == 0.35), ...
    'Zero hysteresis rate must freeze the initial memory state.');

boundaryParameters = parameters;
boundaryParameters.capacity_Ah = 1;
boundaryParameters.initial_soc = 0.10;
boundaryProfile = table(...
    [0; 3600; 7200], ...
    [1; 1; 0], ...
    'VariableNames', {'time_s', 'current_A'});
boundaryResult = simulate_battery_ocv_hysteresis(...
    boundaryProfile, boundaryParameters);
assert(max(abs(boundaryResult.current_A - [0.1; 0; 0])) < 1e-12 && ...
    isequal(boundaryResult.current_limited, [true; true; false]) && ...
    max(abs(boundaryResult.soc - [0.1; 0; 0])) < 1e-12, ...
    'Applied current must be limited by charge available above zero SOC.');
expectedBoundaryState = -1 + ...
    (boundaryParameters.initial_hysteresis_state + 1)* ...
    exp(-boundaryParameters.hysteresis_rate_per_fractional_throughput*0.10);
assert(abs(boundaryResult.hysteresis_state(2) - ...
    expectedBoundaryState) < 1e-12 && ...
    boundaryResult.hysteresis_state(3) == ...
    boundaryResult.hysteresis_state(2), ...
    'Hysteresis must use limited applied current and then hold at zero current.');

invalidTimeProfile = profile;
invalidTimeProfile.time_s(3) = invalidTimeProfile.time_s(2);
caughtTimeOrder = false;
try
    simulate_battery_ocv_hysteresis(invalidTimeProfile, parameters);
catch validationError
    caughtTimeOrder = strcmp(validationError.identifier, ...
        'BatteryHysteresis:TimeOrder');
end
assert(caughtTimeOrder, ...
    'The simulator must reject non-increasing profile timestamps.');

invalidStateParameters = parameters;
invalidStateParameters.initial_hysteresis_state = 1.01;
caughtInvalidState = false;
try
    simulate_battery_ocv_hysteresis(profile, invalidStateParameters);
catch validationError
    caughtInvalidState = strcmp(validationError.identifier, ...
        'BatteryHysteresis:Parameters');
end
assert(caughtInvalidState, ...
    'The simulator must reject an initial hysteresis state outside [-1, 1].');

invalidCurveParameters = parameters;
invalidCurveParameters.ocv_lookup_V(6) = ...
    invalidCurveParameters.ocv_lookup_V(5) - 0.01;
caughtInvalidCurve = false;
try
    simulate_battery_ocv_hysteresis(profile, invalidCurveParameters);
catch validationError
    caughtInvalidCurve = strcmp(validationError.identifier, ...
        'BatteryHysteresis:OCVCurve');
end
assert(caughtInvalidCurve, ...
    'The simulator must reject a decreasing mean OCV curve.');

repeatResult = simulate_battery_ocv_hysteresis(profile, parameters);
assert(isequal(result.soc, repeatResult.soc) && ...
    isequal(result.hysteresis_state, repeatResult.hysteresis_state) && ...
    isequal(result.terminal_voltage_V, ...
    repeatResult.terminal_voltage_V), ...
    'Repeated simulation must be deterministic.');

fprintf('Battery OCV hysteresis check passed.\n');
fprintf('Final SOC: %.3f\n', result.soc(end));
fprintf('Hysteresis state range: %.3f to %.3f\n', ...
    min(result.hysteresis_state), max(result.hysteresis_state));
fprintf('Same-SOC minor-loop voltage gap: %.2f mV\n', ...
    1000*minorLoopGap_V);
