clear;
close all;
clc;

modelDirectory = fileparts(mfilename('fullpath'));
examplesDirectory = fileparts(modelDirectory);
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory, fullfile(examplesDirectory, ...
    'converter-switching-model'));

parameters = switching_closed_loop_buck_default_parameters();
result = simulate_switching_closed_loop_buck(parameters);
metrics = summarize_switching_closed_loop_buck(result, 100);

assert(all(isfinite(result.inductor_current_A)) && ...
    all(isfinite(result.output_voltage_V)), ...
    'Converter states must remain finite.');
assert(all(result.inductor_current_A >= -1e-12), ...
    'Default case must remain in continuous conduction.');
assert(all(result.duty_cycle >= parameters.minimum_duty_cycle - eps) && ...
    all(result.duty_cycle <= parameters.maximum_duty_cycle + eps), ...
    'Duty commands must respect configured limits.');
assert(all(result.current_reference_A >= ...
    parameters.minimum_current_reference_A - eps) && ...
    all(result.current_reference_A <= ...
    parameters.maximum_current_reference_A + eps), ...
    'Current references must respect configured limits.');

periodSwitchState = reshape(result.switch_state, ...
    parameters.steps_per_switching_period, []);
assert(all(sum(periodSwitchState, 1)' == result.on_steps_per_period), ...
    'Every period must contain exactly the commanded number of ON steps.');
assert(abs(metrics.final_voltage_error_V) < 1.0, ...
    'Final average voltage must be within 1 V of its reference.');
assert(metrics.reference_step_overshoot_percent < 8 && ...
    metrics.reference_step_settling_time_s < 0.05, ...
    'Reference-step response exceeds overshoot or settling limits.');
assert(metrics.load_step_undershoot_percent < 12 && ...
    metrics.load_step_settling_time_s < 0.05, ...
    'Load-step response exceeds undershoot or settling limits.');
assert(abs(metrics.average_output_voltage_V - ...
    metrics.expected_average_voltage_V) < 0.5, ...
    'Settled switched average must match the lossy diode averaged balance.');
assert(metrics.diode_loss_energy_J > 0 && ...
    metrics.inductor_loss_energy_J > 0 && ...
    metrics.switch_conduction_loss_energy_J > 0 && ...
    metrics.turn_on_loss_energy_J > 0 && ...
    metrics.turn_off_loss_energy_J > 0, ...
    'Configured conduction losses must remain positive.');
assert(result.turn_on_event_count == result.period_count && ...
    result.turn_off_event_count == result.period_count, ...
    'Canonical PWM must contain one turn-on and one turn-off per period.');
assert(metrics.energy_efficiency_percent > 0 && ...
    metrics.energy_efficiency_percent < 100, ...
    'Estimated electrical energy efficiency must be bounded.');
assert(metrics.relative_energy_balance_residual < 2e-4, ...
    'Integrated converter energy balance does not close.');

fixedParameters = parameters;
fixedParameters.control_enabled = false;
fixedParameters.enforce_continuous_conduction = false;
fixedParameters.diode_forward_voltage_V = 0;
fixedParameters.switch_on_resistance_Ohm = 0;
fixedParameters.turn_on_energy_reference_J = 0;
fixedParameters.turn_off_energy_reference_J = 0;
fixedParameters.initial_load_resistance_Ohm = 20;
fixedParameters.final_load_resistance_Ohm = 20;
fixedParameters.reference_step_time_s = 0.1;
fixedParameters.load_step_time_s = 0.2;
fixedParameters.end_time_s = 0.3;
fixedParameters.initial_inductor_current_A = 0;
fixedParameters.initial_output_voltage_V = 0;
fixedParameters.fixed_duty_cycle = 0.45;
fixedResult = simulate_switching_closed_loop_buck(fixedParameters);
baseParameters = switching_buck_default_parameters();
baseResult = simulate_switching_buck_converter(baseParameters);
assert(max(abs(fixedResult.inductor_current_A - ...
    baseResult.inductor_current_A)) < 1e-11 && ...
    max(abs(fixedResult.output_voltage_V - ...
    baseResult.output_voltage_V)) < 1e-11 && ...
    isequal(fixedResult.switch_state, baseResult.switch_state), ...
    ['Zero-semiconductor-loss fixed-duty mode must reproduce the existing ', ...
    'switched model.']);

zeroTransitionParameters = parameters;
zeroTransitionParameters.turn_on_energy_reference_J = 0;
zeroTransitionParameters.turn_off_energy_reference_J = 0;
zeroTransitionResult = simulate_switching_closed_loop_buck( ...
    zeroTransitionParameters);
assert(isequal(result.inductor_current_A, ...
    zeroTransitionResult.inductor_current_A) && ...
    isequal(result.output_voltage_V, ...
    zeroTransitionResult.output_voltage_V) && ...
    zeroTransitionResult.switching_loss_energy_J == 0, ...
    ['Transition-energy estimation must not alter the resolved electrical ', ...
    'trajectory.']);

fineParameters = parameters;
fineParameters.steps_per_switching_period = 200;
fineResult = simulate_switching_closed_loop_buck(fineParameters);
fineMetrics = summarize_switching_closed_loop_buck(fineResult, 100);
assert(abs(fineMetrics.average_output_voltage_V - ...
    metrics.average_output_voltage_V) < 0.5 && ...
    abs(fineMetrics.load_step_settling_time_s - ...
    metrics.load_step_settling_time_s) < 0.005, ...
    'Control metrics must converge when the PWM grid is doubled.');
assert(abs(fineMetrics.switch_conduction_loss_energy_J - ...
    metrics.switch_conduction_loss_energy_J) < 0.1 && ...
    abs(fineMetrics.switching_loss_energy_J - ...
    metrics.switching_loss_energy_J) < 0.02, ...
    'Semiconductor loss estimates must converge on the doubled PWM grid.');

frequencyParameters = parameters;
frequencyParameters.control_enabled = false;
frequencyParameters.enforce_continuous_conduction = false;
frequencyParameters.initial_load_resistance_Ohm = 20;
frequencyParameters.final_load_resistance_Ohm = 20;
frequencyParameters.reference_step_time_s = 0.02;
frequencyParameters.load_step_time_s = 0.03;
frequencyParameters.end_time_s = 0.04;
frequencyParameters.fixed_duty_cycle = 0.45;
lowFrequencyResult = simulate_switching_closed_loop_buck( ...
    frequencyParameters);
frequencyParameters.switching_frequency_Hz = 20000;
highFrequencyResult = simulate_switching_closed_loop_buck( ...
    frequencyParameters);
frequencyLossRatio = highFrequencyResult.switching_loss_energy_J/ ...
    lowFrequencyResult.switching_loss_energy_J;
assert(highFrequencyResult.turn_on_event_count == ...
    2*lowFrequencyResult.turn_on_event_count && ...
    frequencyLossRatio > 1.8 && frequencyLossRatio < 2.2, ...
    ['Switching-event loss must scale approximately with switching ', ...
    'frequency for the controlled comparison.']);

invalidParameters = parameters;
invalidParameters.diode_forward_voltage_V = -1;
assert_error(@() simulate_switching_closed_loop_buck(invalidParameters), ...
    'SwitchingClosedLoopBuck:Parameters');
invalidParameters = parameters;
invalidParameters.switch_on_resistance_Ohm = -0.01;
assert_error(@() simulate_switching_closed_loop_buck(invalidParameters), ...
    'SwitchingClosedLoopBuck:Parameters');
invalidParameters = parameters;
invalidParameters.turn_on_energy_reference_J = -1e-6;
assert_error(@() simulate_switching_closed_loop_buck(invalidParameters), ...
    'SwitchingClosedLoopBuck:Parameters');
invalidParameters = parameters;
invalidParameters.switching_loss_reference_current_A = 0;
assert_error(@() simulate_switching_closed_loop_buck(invalidParameters), ...
    'SwitchingClosedLoopBuck:LossReference');
invalidParameters = parameters;
invalidParameters.control_enabled = 1;
assert_error(@() simulate_switching_closed_loop_buck(invalidParameters), ...
    'SwitchingClosedLoopBuck:Parameters');
invalidParameters = parameters;
invalidParameters.reference_step_time_s = 0.04005;
assert_error(@() simulate_switching_closed_loop_buck(invalidParameters), ...
    'SwitchingClosedLoopBuck:TimeGrid');
invalidParameters = parameters;
invalidParameters.minimum_duty_cycle = 0.055;
assert_error(@() simulate_switching_closed_loop_buck(invalidParameters), ...
    'SwitchingClosedLoopBuck:TimeGrid');

fprintf('Switching closed-loop buck check passed.\n');
fprintf('Final average voltage: %.2f V\n', ...
    metrics.average_output_voltage_V);
fprintf('Reference-step overshoot: %.2f%%, settling %.1f ms\n', ...
    metrics.reference_step_overshoot_percent, ...
    1000*metrics.reference_step_settling_time_s);
fprintf('Load-step undershoot: %.2f%%, settling %.1f ms\n', ...
    metrics.load_step_undershoot_percent, ...
    1000*metrics.load_step_settling_time_s);
fprintf('Average duty cycle: %.3f\n', metrics.average_duty_cycle);
fprintf('Diode/inductor loss energy: %.3f J / %.3f J\n', ...
    metrics.diode_loss_energy_J, metrics.inductor_loss_energy_J);
fprintf('Switch conduction/transition loss energy: %.3f J / %.3f J\n', ...
    metrics.switch_conduction_loss_energy_J, ...
    metrics.switching_loss_energy_J);
fprintf('Turn-on/turn-off transition energy: %.3f J / %.3f J\n', ...
    metrics.turn_on_loss_energy_J, metrics.turn_off_loss_energy_J);
fprintf('Estimated energy efficiency: %.3f%%\n', ...
    metrics.energy_efficiency_percent);

function assert_error(functionHandle, expectedIdentifier)
try
    functionHandle();
catch errorDetails
    assert(strcmp(errorDetails.identifier, expectedIdentifier), ...
        'Expected error %s but received %s.', ...
        expectedIdentifier, errorDetails.identifier);
    return;
end
error('SwitchingClosedLoopBuck:MissingError', ...
    'Expected error %s was not raised.', expectedIdentifier);
end
