clear;
close all;
clc;

modelDirectory = fileparts(mfilename('fullpath'));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory);

temperature_C = [25; 75; 125; 150; 175];
sensitivity = ...
    evaluate_switching_closed_loop_buck_temperature_sensitivity( ...
    temperature_C);

assert(isequal(sensitivity.junction_temperature_C, temperature_C) && ...
    all(isfinite(sensitivity.total_switch_loss_energy_J)), ...
    'Temperature cases and loss metrics must be finite and ordered.');
assert(isequal(sensitivity.switch_on_resistance_Ohm([1, 4, 5]), ...
    [0.040; 0.081; 0.094]) && ...
    isequal(sensitivity.turn_on_energy_reference_J([1, 5]), ...
    [109e-6; 200e-6]) && ...
    isequal(sensitivity.turn_off_energy_reference_J([1, 5]), ...
    [45e-6; 67e-6]), ...
    'Interpolation must reproduce every tabulated datasheet anchor.');

baselineParameters = switching_closed_loop_buck_default_parameters();
baselineResult = simulate_switching_closed_loop_buck(baselineParameters);
coldResult = sensitivity.case_results{1};
assert(isequal(coldResult.inductor_current_A, ...
    baselineResult.inductor_current_A) && ...
    isequal(coldResult.output_voltage_V, baselineResult.output_voltage_V) && ...
    isequal(coldResult.duty_cycle, baselineResult.duty_cycle) && ...
    coldResult.switch_conduction_loss_energy_J == ...
    baselineResult.switch_conduction_loss_energy_J && ...
    coldResult.switching_loss_energy_J == ...
    baselineResult.switching_loss_energy_J, ...
    'The 25 degC sensitivity case must reproduce the canonical model exactly.');

assert(all(diff(sensitivity.switch_on_resistance_Ohm) > 0) && ...
    all(diff(sensitivity.turn_on_energy_reference_J) > 0) && ...
    all(diff(sensitivity.turn_off_energy_reference_J) > 0), ...
    'Interpolated source parameters must increase over the sourced range.');
assert(all(diff(sensitivity.switch_conduction_loss_energy_J) > 0) && ...
    all(diff(sensitivity.switching_loss_energy_J) > 0) && ...
    all(diff(sensitivity.total_switch_loss_energy_J) > 0) && ...
    all(diff(sensitivity.energy_efficiency_percent) < 0), ...
    ['The canonical fixed-temperature cases must show increasing switch ', ...
    'loss and decreasing estimated efficiency.']);

for caseIndex = 1:numel(sensitivity.case_results)
    result = sensitivity.case_results{caseIndex};
    relativeResidual = abs(result.energy_balance_residual_J)/ ...
        max(result.input_energy_J, eps);
    assert(relativeResidual < 2e-4 && ...
        result.turn_on_event_count == result.period_count && ...
        result.turn_off_event_count == result.period_count, ...
        'Every temperature case must preserve energy and PWM event checks.');
end

repeatSensitivity = ...
    evaluate_switching_closed_loop_buck_temperature_sensitivity( ...
    temperature_C);
assert(isequal(sensitivity.total_switch_loss_energy_J, ...
    repeatSensitivity.total_switch_loss_energy_J) && ...
    isequal(sensitivity.average_output_voltage_V, ...
    repeatSensitivity.average_output_voltage_V), ...
    'The temperature sensitivity must be deterministic.');

fineParameters = baselineParameters;
fineParameters.steps_per_switching_period = 200;
fineSensitivity = ...
    evaluate_switching_closed_loop_buck_temperature_sensitivity( ...
    [25; 175], fineParameters);
coarseHotLoss_J = sensitivity.total_switch_loss_energy_J(end);
fineHotLoss_J = fineSensitivity.total_switch_loss_energy_J(end);
assert(abs(fineHotLoss_J - coarseHotLoss_J) < 0.15 && ...
    abs(fineSensitivity.average_output_voltage_V(end) - ...
    sensitivity.average_output_voltage_V(end)) < 0.5, ...
    'Hot-junction loss and output metrics must converge on a doubled grid.');

assert_error(@() ...
    evaluate_switching_closed_loop_buck_temperature_sensitivity([24; 25]), ...
    'SwitchingClosedLoopBuck:TemperatureRange');
assert_error(@() ...
    evaluate_switching_closed_loop_buck_temperature_sensitivity([25; 176]), ...
    'SwitchingClosedLoopBuck:TemperatureRange');
assert_error(@() ...
    evaluate_switching_closed_loop_buck_temperature_sensitivity([25; 25]), ...
    'SwitchingClosedLoopBuck:TemperatureRange');
assert_error(@() ...
    evaluate_switching_closed_loop_buck_temperature_sensitivity([25; NaN]), ...
    'MATLAB:expectedFinite');
invalidReferenceParameters = baselineParameters;
invalidReferenceParameters.switching_loss_reference_current_A = 20;
assert_error(@() ...
    evaluate_switching_closed_loop_buck_temperature_sensitivity( ...
    [25; 175], invalidReferenceParameters), ...
    'SwitchingClosedLoopBuck:TemperatureReference');
invalidReferenceParameters = baselineParameters;
invalidReferenceParameters.input_voltage_V = 700;
assert_error(@() ...
    evaluate_switching_closed_loop_buck_temperature_sensitivity( ...
    [25; 175], invalidReferenceParameters), ...
    'SwitchingClosedLoopBuck:TemperatureReference');

fprintf('Switch fixed-temperature sensitivity check passed.\n');
fprintf('25/175 degC total switch loss: %.3f J / %.3f J\n', ...
    sensitivity.total_switch_loss_energy_J(1), ...
    sensitivity.total_switch_loss_energy_J(end));
fprintf('25/175 degC estimated efficiency: %.3f%% / %.3f%%\n', ...
    sensitivity.energy_efficiency_percent(1), ...
    sensitivity.energy_efficiency_percent(end));

function assert_error(functionHandle, expectedIdentifier)
try
    functionHandle();
catch errorDetails
    assert(strcmp(errorDetails.identifier, expectedIdentifier), ...
        'Expected error %s but received %s.', ...
        expectedIdentifier, errorDetails.identifier);
    return;
end
error('SwitchingClosedLoopBuck:MissingError', ...
    'Expected error %s was not raised.', expectedIdentifier);
end
