function sensitivity = evaluate_switching_closed_loop_buck_temperature_sensitivity( ...
        temperatures_C, baseParameters)
%EVALUATE_SWITCHING_CLOSED_LOOP_BUCK_TEMPERATURE_SENSITIVITY
% Evaluate fixed-junction-temperature switch-loss sensitivity using
% piecewise-linear interpolation between published datasheet anchors.

if nargin < 1
    temperatures_C = [25; 75; 125; 150; 175];
end
if nargin < 2
    baseParameters = switching_closed_loop_buck_default_parameters();
end
baseParameters = validate_switching_closed_loop_buck_parameters( ...
    baseParameters);
if baseParameters.input_voltage_V ~= 800 || ...
        baseParameters.switching_loss_reference_voltage_V ~= 800 || ...
        baseParameters.switching_loss_reference_current_A ~= 18
    error('SwitchingClosedLoopBuck:TemperatureReference', ...
        ['Temperature interpolation requires the sourced 800 V input ', ...
        'and 800 V, 18 A switching-energy reference point.']);
end
validateattributes(temperatures_C, {'numeric'}, ...
    {'vector', 'real', 'finite', 'nonempty'});
temperatures_C = temperatures_C(:);
if any(temperatures_C < 25 | temperatures_C > 175) || ...
        any(diff(temperatures_C) <= 0)
    error('SwitchingClosedLoopBuck:TemperatureRange', ...
        ['Junction temperatures must be strictly increasing and within ', ...
        'the sourced 25 to 175 degC interpolation range.']);
end

resistanceTemperature_C = [25; 150; 175];
resistance_Ohm = [0.040; 0.081; 0.094];
energyTemperature_C = [25; 175];
turnOnEnergy_J = [109e-6; 200e-6];
turnOffEnergy_J = [45e-6; 67e-6];

caseCount = numel(temperatures_C);
caseResults = cell(caseCount, 1);
interpolatedResistance_Ohm = interp1(resistanceTemperature_C, ...
    resistance_Ohm, temperatures_C, 'linear');
interpolatedTurnOnEnergy_J = interp1(energyTemperature_C, ...
    turnOnEnergy_J, temperatures_C, 'linear');
interpolatedTurnOffEnergy_J = interp1(energyTemperature_C, ...
    turnOffEnergy_J, temperatures_C, 'linear');

for caseIndex = 1:caseCount
    parameters = baseParameters;
    parameters.switch_on_resistance_Ohm = ...
        interpolatedResistance_Ohm(caseIndex);
    parameters.turn_on_energy_reference_J = ...
        interpolatedTurnOnEnergy_J(caseIndex);
    parameters.turn_off_energy_reference_J = ...
        interpolatedTurnOffEnergy_J(caseIndex);
    caseResults{caseIndex} = simulate_switching_closed_loop_buck(parameters);
    caseMetrics = summarize_switching_closed_loop_buck( ...
        caseResults{caseIndex}, 100);
    if caseIndex == 1
        metrics = repmat(caseMetrics, caseCount, 1);
    end
    metrics(caseIndex) = caseMetrics;
end

sensitivity.junction_temperature_C = temperatures_C;
sensitivity.switch_on_resistance_Ohm = interpolatedResistance_Ohm;
sensitivity.turn_on_energy_reference_J = interpolatedTurnOnEnergy_J;
sensitivity.turn_off_energy_reference_J = interpolatedTurnOffEnergy_J;
sensitivity.case_results = caseResults;
sensitivity.metrics = metrics;
sensitivity.switch_conduction_loss_energy_J = ...
    reshape([metrics.switch_conduction_loss_energy_J], [], 1);
sensitivity.switching_loss_energy_J = ...
    reshape([metrics.switching_loss_energy_J], [], 1);
sensitivity.total_switch_loss_energy_J = ...
    sensitivity.switch_conduction_loss_energy_J + ...
    sensitivity.switching_loss_energy_J;
sensitivity.energy_efficiency_percent = ...
    reshape([metrics.energy_efficiency_percent], [], 1);
sensitivity.average_output_voltage_V = ...
    reshape([metrics.average_output_voltage_V], [], 1);
sensitivity.source_conditions = struct( ...
    'device', 'Infineon IMZC120R040M2H', ...
    'datasheet_revision', '1.20', ...
    'datasheet_url', ['https://www.infineon.com/assets/row/public/', ...
    'documents/60/49/infineon-imzc120r040m2h-datasheet-en.pdf'], ...
    'on_resistance_table_page', 4, ...
    'switching_energy_table_page', 5, ...
    'turn_on_gate_voltage_V', 18, ...
    'turn_off_gate_voltage_V', 0, ...
    'switching_reference_voltage_V', 800, ...
    'switching_reference_current_A', 18, ...
    'external_gate_resistance_Ohm', 2.3, ...
    'stray_inductance_H', 12e-9);
end
