function result = simulate_switching_closed_loop_buck(parameters)
%SIMULATE_SWITCHING_CLOSED_LOOP_BUCK Simulate period-controlled PWM buck.
% The continuous-conduction plant uses a resistive high-side switch and a
% freewheel diode. Datasheet-reference transition energies are scaled by
% event voltage and current. The controller samples once per PWM period.

if nargin < 1
    parameters = switching_closed_loop_buck_default_parameters();
end
parameters = validate_parameters(parameters);

stepsPerPeriod = parameters.steps_per_switching_period;
switchingPeriod_s = 1/parameters.switching_frequency_Hz;
timeStep_s = switchingPeriod_s/stepsPerPeriod;
periodCount = round(parameters.end_time_s/ switchingPeriod_s);
intervalCount = periodCount*stepsPerPeriod;
time_s = (0:intervalCount)'*timeStep_s;
intervalStartTime_s = time_s(1:end-1);

referenceVoltage_V = parameters.initial_reference_voltage_V* ...
    ones(intervalCount + 1, 1);
referenceVoltage_V(time_s >= parameters.reference_step_time_s) = ...
    parameters.final_reference_voltage_V;
loadResistance_Ohm = parameters.initial_load_resistance_Ohm* ...
    ones(intervalCount + 1, 1);
loadResistance_Ohm(time_s >= parameters.load_step_time_s) = ...
    parameters.final_load_resistance_Ohm;

state = zeros(2, intervalCount + 1);
state(:, 1) = [parameters.initial_inductor_current_A; ...
    parameters.initial_output_voltage_V];
switchState = false(intervalCount, 1);
dutyCycle = zeros(periodCount, 1);
unquantizedDutyCycle = zeros(periodCount, 1);
onStepsPerPeriod = zeros(periodCount, 1);
currentReference_A = zeros(periodCount, 1);
voltageError_V = zeros(periodCount, 1);
voltageIntegralAction_A = zeros(periodCount + 1, 1);

[initialOnTransition, initialOnIncrement, initialOffTransition, ...
    initialOffIncrement] = ...
    interval_transitions(parameters, ...
    parameters.initial_load_resistance_Ohm, timeStep_s);
[finalOnTransition, finalOnIncrement, finalOffTransition, ...
    finalOffIncrement] = ...
    interval_transitions(parameters, ...
    parameters.final_load_resistance_Ohm, timeStep_s);

for periodIndex = 1:periodCount
    firstInterval = (periodIndex - 1)*stepsPerPeriod + 1;
    firstState = firstInterval;
    reference_V = referenceVoltage_V(firstState);
    load_Ohm = loadResistance_Ohm(firstState);
    sampledCurrent_A = state(1, firstState);
    sampledVoltage_V = state(2, firstState);

    if parameters.control_enabled
        voltageError_V(periodIndex) = reference_V - sampledVoltage_V;
        unconstrainedCurrentReference_A = reference_V/load_Ohm + ...
            parameters.voltage_proportional_gain_A_per_V* ...
            voltageError_V(periodIndex) + ...
            voltageIntegralAction_A(periodIndex);
        currentReference_A(periodIndex) = min(max( ...
            unconstrainedCurrentReference_A, ...
            parameters.minimum_current_reference_A), ...
            parameters.maximum_current_reference_A);
        currentReferenceFree = unconstrainedCurrentReference_A > ...
            parameters.minimum_current_reference_A && ...
            unconstrainedCurrentReference_A < ...
            parameters.maximum_current_reference_A;
        upperRecovery = unconstrainedCurrentReference_A >= ...
            parameters.maximum_current_reference_A && ...
            voltageError_V(periodIndex) < 0;
        lowerRecovery = unconstrainedCurrentReference_A <= ...
            parameters.minimum_current_reference_A && ...
            voltageError_V(periodIndex) > 0;
        voltageIntegralAction_A(periodIndex + 1) = ...
            voltageIntegralAction_A(periodIndex);
        if currentReferenceFree || upperRecovery || lowerRecovery
            voltageIntegralAction_A(periodIndex + 1) = ...
                voltageIntegralAction_A(periodIndex) + ...
                parameters.voltage_integral_gain_A_per_Vs* ...
                voltageError_V(periodIndex)*switchingPeriod_s;
        end

        currentError_A = currentReference_A(periodIndex) - sampledCurrent_A;
        unquantizedDutyCycle(periodIndex) = (sampledVoltage_V + ...
            parameters.inductor_resistance_Ohm*sampledCurrent_A + ...
            parameters.diode_forward_voltage_V + ...
            parameters.current_proportional_gain_Ohm*currentError_A)/ ...
            (parameters.input_voltage_V + ...
            parameters.diode_forward_voltage_V);
    else
        currentReference_A(periodIndex) = sampledCurrent_A;
        unquantizedDutyCycle(periodIndex) = parameters.fixed_duty_cycle;
        voltageIntegralAction_A(periodIndex + 1) = ...
            voltageIntegralAction_A(periodIndex);
    end

    boundedDuty = min(max(unquantizedDutyCycle(periodIndex), ...
        parameters.minimum_duty_cycle), parameters.maximum_duty_cycle);
    onStepsPerPeriod(periodIndex) = round(boundedDuty*stepsPerPeriod);
    dutyCycle(periodIndex) = onStepsPerPeriod(periodIndex)/stepsPerPeriod;

    if load_Ohm == parameters.initial_load_resistance_Ohm
        onTransition = initialOnTransition;
        offTransition = initialOffTransition;
        onIncrement = initialOnIncrement;
        offIncrement = initialOffIncrement;
    else
        onTransition = finalOnTransition;
        offTransition = finalOffTransition;
        onIncrement = finalOnIncrement;
        offIncrement = finalOffIncrement;
    end

    for stepIndex = 1:stepsPerPeriod
        intervalIndex = firstInterval + stepIndex - 1;
        isOn = stepIndex <= onStepsPerPeriod(periodIndex);
        switchState(intervalIndex) = isOn;
        if isOn
            transition = onTransition;
            increment = onIncrement;
        else
            transition = offTransition;
            increment = offIncrement;
        end
        state(:, intervalIndex + 1) = ...
            transition*state(:, intervalIndex) + increment;
        if parameters.enforce_continuous_conduction && ...
                state(1, intervalIndex + 1) < -1e-9
            error('SwitchingClosedLoopBuck:ConductionMode', ...
                ['Inductor current became negative at %.9g s. ', ...
                'The configured case leaves continuous conduction.'], ...
                time_s(intervalIndex + 1));
        end
    end
end

periodIndexForInterval = repelem((1:periodCount)', stepsPerPeriod);
intervalDutyCycle = dutyCycle(periodIndexForInterval);
intervalCurrentReference_A = currentReference_A(periodIndexForInterval);
inductorCurrent_A = state(1, :)';
outputVoltage_V = state(2, :)';
intervalAverageCurrent_A = 0.5*(inductorCurrent_A(1:end-1) + ...
    inductorCurrent_A(2:end));
intervalAverageVoltageSquared_V2 = 0.5*( ...
    outputVoltage_V(1:end-1).^2 + outputVoltage_V(2:end).^2);
intervalAverageCurrentSquared_A2 = 0.5*( ...
    inductorCurrent_A(1:end-1).^2 + inductorCurrent_A(2:end).^2);
intervalLoadResistance_Ohm = loadResistance_Ohm(1:end-1);
intervalSourceVoltage_V = double(switchState)* ...
    parameters.input_voltage_V - double(~switchState)* ...
    parameters.diode_forward_voltage_V;
sourceInput = [intervalSourceVoltage_V'/parameters.inductance_H; ...
    zeros(1, intervalCount)];
stateChange = state(:, 2:end) - state(:, 1:end-1);
integratedState = zeros(2, intervalCount);
initialLoadMask = intervalLoadResistance_Ohm == ...
    parameters.initial_load_resistance_Ohm;
for loadIsInitial = [true, false]
    if loadIsInitial
        loadMask = initialLoadMask;
        selectedLoad_Ohm = parameters.initial_load_resistance_Ohm;
    else
        loadMask = ~initialLoadMask;
        selectedLoad_Ohm = parameters.final_load_resistance_Ohm;
    end
    for isOn = [false, true]
        selectedMask = loadMask & switchState == isOn;
        selectedMatrix = system_matrix(parameters, selectedLoad_Ohm, isOn);
        integratedState(:, selectedMask) = selectedMatrix\( ...
            stateChange(:, selectedMask) - ...
            sourceInput(:, selectedMask)*timeStep_s);
    end
end
integratedCurrent_A_s = integratedState(1, :)';
circuitInputPower_W = double(switchState)*parameters.input_voltage_V.* ...
    intervalAverageCurrent_A;
diodePower_W = double(~switchState)*parameters.diode_forward_voltage_V.* ...
    intervalAverageCurrent_A;
inductorLossPower_W = parameters.inductor_resistance_Ohm* ...
    intervalAverageCurrentSquared_A2;
switchConductionLossPower_W = double(switchState)* ...
    parameters.switch_on_resistance_Ohm.* ...
    intervalAverageCurrentSquared_A2;
loadPower_W = intervalAverageVoltageSquared_V2./ ...
    intervalLoadResistance_Ohm;
previousSwitchState = [false; switchState(1:end-1)];
turnOnEvent = switchState & ~previousSwitchState;
turnOffEvent = ~switchState & previousSwitchState;
transitionCurrent_A = abs(inductorCurrent_A(1:end-1));
eventScale = parameters.input_voltage_V/ ...
    parameters.switching_loss_reference_voltage_V.* ...
    transitionCurrent_A/parameters.switching_loss_reference_current_A;
turnOnLossByInterval_J = double(turnOnEvent).* ...
    parameters.turn_on_energy_reference_J.*eventScale;
turnOffLossByInterval_J = double(turnOffEvent).* ...
    parameters.turn_off_energy_reference_J.*eventScale;
switchingLossByInterval_J = turnOnLossByInterval_J + ...
    turnOffLossByInterval_J;
switchingLossPower_W = switchingLossByInterval_J/timeStep_s;
inputPower_W = circuitInputPower_W + switchingLossPower_W;
circuitInputEnergy_J = parameters.input_voltage_V*sum( ...
    integratedCurrent_A_s(switchState));
turnOnLossEnergy_J = sum(turnOnLossByInterval_J);
turnOffLossEnergy_J = sum(turnOffLossByInterval_J);
switchingLossEnergy_J = turnOnLossEnergy_J + turnOffLossEnergy_J;
inputEnergy_J = circuitInputEnergy_J + switchingLossEnergy_J;
diodeLossEnergy_J = parameters.diode_forward_voltage_V*sum( ...
    integratedCurrent_A_s(~switchState));
inductorLossEnergy_J = sum(inductorLossPower_W)*timeStep_s;
switchConductionLossEnergy_J = ...
    sum(switchConductionLossPower_W)*timeStep_s;
loadEnergy_J = sum(loadPower_W)*timeStep_s;
initialStoredEnergy_J = 0.5*parameters.inductance_H* ...
    inductorCurrent_A(1)^2 + 0.5*parameters.capacitance_F* ...
    outputVoltage_V(1)^2;
finalStoredEnergy_J = 0.5*parameters.inductance_H* ...
    inductorCurrent_A(end)^2 + 0.5*parameters.capacitance_F* ...
    outputVoltage_V(end)^2;
energyBalanceResidual_J = inputEnergy_J - diodeLossEnergy_J - ...
    inductorLossEnergy_J - switchConductionLossEnergy_J - ...
    switchingLossEnergy_J - loadEnergy_J - ...
    (finalStoredEnergy_J - initialStoredEnergy_J);

result.time_s = time_s;
result.interval_start_time_s = intervalStartTime_s;
result.reference_voltage_V = referenceVoltage_V;
result.load_resistance_Ohm = loadResistance_Ohm;
result.switch_state = switchState;
result.duty_cycle = dutyCycle;
result.unquantized_duty_cycle = unquantizedDutyCycle;
result.interval_duty_cycle = intervalDutyCycle;
result.on_steps_per_period = onStepsPerPeriod;
result.current_reference_A = currentReference_A;
result.interval_current_reference_A = intervalCurrentReference_A;
result.voltage_error_V = voltageError_V;
result.voltage_integral_action_A = voltageIntegralAction_A;
result.inductor_current_A = inductorCurrent_A;
result.output_voltage_V = outputVoltage_V;
result.input_power_W = inputPower_W;
result.circuit_input_power_W = circuitInputPower_W;
result.diode_loss_power_W = diodePower_W;
result.inductor_loss_power_W = inductorLossPower_W;
result.switch_conduction_loss_power_W = switchConductionLossPower_W;
result.switching_loss_power_W = switchingLossPower_W;
result.load_power_W = loadPower_W;
result.input_energy_J = inputEnergy_J;
result.circuit_input_energy_J = circuitInputEnergy_J;
result.diode_loss_energy_J = diodeLossEnergy_J;
result.inductor_loss_energy_J = inductorLossEnergy_J;
result.switch_conduction_loss_energy_J = ...
    switchConductionLossEnergy_J;
result.turn_on_loss_energy_J = turnOnLossEnergy_J;
result.turn_off_loss_energy_J = turnOffLossEnergy_J;
result.switching_loss_energy_J = switchingLossEnergy_J;
result.turn_on_event_count = sum(turnOnEvent);
result.turn_off_event_count = sum(turnOffEvent);
result.load_energy_J = loadEnergy_J;
result.initial_stored_energy_J = initialStoredEnergy_J;
result.final_stored_energy_J = finalStoredEnergy_J;
result.energy_balance_residual_J = energyBalanceResidual_J;
result.time_step_s = timeStep_s;
result.switching_period_s = switchingPeriod_s;
result.period_count = periodCount;
result.parameters = parameters;
end

function [onTransition, onIncrement, offTransition, offIncrement] = ...
        interval_transitions(parameters, loadResistance_Ohm, timeStep_s)
onSystemMatrix = system_matrix(parameters, loadResistance_Ohm, true);
offSystemMatrix = system_matrix(parameters, loadResistance_Ohm, false);
onTransition = expm(onSystemMatrix*timeStep_s);
offTransition = expm(offSystemMatrix*timeStep_s);
onInput = [parameters.input_voltage_V/parameters.inductance_H; 0];
offInput = [-parameters.diode_forward_voltage_V/ ...
    parameters.inductance_H; 0];
onIncrement = onSystemMatrix\((onTransition - eye(2))*onInput);
offIncrement = offSystemMatrix\((offTransition - eye(2))*offInput);
end

function systemMatrix = system_matrix(parameters, loadResistance_Ohm, isOn)
seriesResistance_Ohm = parameters.inductor_resistance_Ohm + ...
    double(isOn)*parameters.switch_on_resistance_Ohm;
systemMatrix = [
    -seriesResistance_Ohm/parameters.inductance_H, ...
    -1/parameters.inductance_H; ...
    1/parameters.capacitance_F, ...
    -1/(loadResistance_Ohm*parameters.capacitance_F)
];
end

function parameters = validate_parameters(parameters)
requiredNumeric = {
    'input_voltage_V'; 'switching_frequency_Hz'; 'inductance_H'; ...
    'inductor_resistance_Ohm'; 'capacitance_F'; ...
    'diode_forward_voltage_V'; 'switch_on_resistance_Ohm'; ...
    'switching_loss_reference_voltage_V'; ...
    'switching_loss_reference_current_A'; ...
    'turn_on_energy_reference_J'; 'turn_off_energy_reference_J'; ...
    'initial_load_resistance_Ohm'; ...
    'final_load_resistance_Ohm'; 'load_step_time_s'; ...
    'initial_reference_voltage_V'; 'final_reference_voltage_V'; ...
    'reference_step_time_s'; 'end_time_s'; ...
    'steps_per_switching_period'; 'initial_inductor_current_A'; ...
    'initial_output_voltage_V'; ...
    'voltage_proportional_gain_A_per_V'; ...
    'voltage_integral_gain_A_per_Vs'; ...
    'current_proportional_gain_Ohm'; ...
    'minimum_current_reference_A'; 'maximum_current_reference_A'; ...
    'minimum_duty_cycle'; 'maximum_duty_cycle'; 'fixed_duty_cycle'
};
requiredLogical = {'control_enabled'; 'enforce_continuous_conduction'};
if ~isstruct(parameters) || ~all(isfield(parameters, ...
        [requiredNumeric; requiredLogical]))
    error('SwitchingClosedLoopBuck:Parameters', ...
        'Parameter structure is missing one or more required fields.');
end
for fieldIndex = 1:numel(requiredNumeric)
    value = parameters.(requiredNumeric{fieldIndex});
    if ~isnumeric(value) || ~isscalar(value) || ~isreal(value) || ...
            ~isfinite(value)
        error('SwitchingClosedLoopBuck:Parameters', ...
            'Every numeric parameter must be a finite real scalar.');
    end
end
if any(~cellfun(@(fieldName) ...
        islogical(parameters.(fieldName)) && ...
        isscalar(parameters.(fieldName)), requiredLogical))
    error('SwitchingClosedLoopBuck:Parameters', ...
        'Control and conduction flags must be logical scalars.');
end
positiveFields = {'input_voltage_V'; 'switching_frequency_Hz'; ...
    'inductance_H'; 'capacitance_F'; 'initial_load_resistance_Ohm'; ...
    'final_load_resistance_Ohm'; 'end_time_s'};
for fieldIndex = 1:numel(positiveFields)
    if parameters.(positiveFields{fieldIndex}) <= 0
        error('SwitchingClosedLoopBuck:Parameters', ...
            'Voltage, frequency, L, C, loads, and duration must be positive.');
    end
end
if parameters.inductor_resistance_Ohm < 0 || ...
        parameters.diode_forward_voltage_V < 0 || ...
        parameters.switch_on_resistance_Ohm < 0 || ...
        parameters.turn_on_energy_reference_J < 0 || ...
        parameters.turn_off_energy_reference_J < 0 || ...
        parameters.initial_inductor_current_A < 0 || ...
        parameters.initial_output_voltage_V < 0 || ...
        parameters.voltage_proportional_gain_A_per_V < 0 || ...
        parameters.voltage_integral_gain_A_per_Vs < 0 || ...
        parameters.current_proportional_gain_Ohm < 0
    error('SwitchingClosedLoopBuck:Parameters', ...
        'Loss, initial-state, and controller parameters must be nonnegative.');
end
if parameters.switching_loss_reference_voltage_V <= 0 || ...
        parameters.switching_loss_reference_current_A <= 0
    error('SwitchingClosedLoopBuck:LossReference', ...
        'Switching-loss reference voltage and current must be positive.');
end
if parameters.minimum_current_reference_A < 0 || ...
        parameters.maximum_current_reference_A <= ...
        parameters.minimum_current_reference_A || ...
        parameters.minimum_duty_cycle <= 0 || ...
        parameters.maximum_duty_cycle >= 1 || ...
        parameters.maximum_duty_cycle <= parameters.minimum_duty_cycle || ...
        parameters.fixed_duty_cycle <= 0 || ...
        parameters.fixed_duty_cycle >= 1
    error('SwitchingClosedLoopBuck:Limits', ...
        'Current and duty limits are inconsistent.');
end
stepsPerPeriod = parameters.steps_per_switching_period;
if stepsPerPeriod ~= round(stepsPerPeriod) || stepsPerPeriod < 20
    error('SwitchingClosedLoopBuck:TimeGrid', ...
        'steps_per_switching_period must be an integer of at least 20.');
end
alignedValues = [parameters.minimum_duty_cycle; ...
    parameters.maximum_duty_cycle; parameters.fixed_duty_cycle]* ...
    stepsPerPeriod;
if any(abs(alignedValues - round(alignedValues)) > 1e-10)
    error('SwitchingClosedLoopBuck:TimeGrid', ...
        'Configured duty values must align with integer PWM step counts.');
end
switchingPeriod_s = 1/parameters.switching_frequency_Hz;
eventTimes_s = [parameters.reference_step_time_s; ...
    parameters.load_step_time_s; parameters.end_time_s];
if any(eventTimes_s < 0) || ...
        parameters.reference_step_time_s >= parameters.end_time_s || ...
        parameters.load_step_time_s >= parameters.end_time_s || ...
        any(abs(eventTimes_s/switchingPeriod_s - ...
        round(eventTimes_s/switchingPeriod_s)) > 1e-10)
    error('SwitchingClosedLoopBuck:TimeGrid', ...
        'Reference, load, and end times must align with PWM periods.');
end
end
