function metrics = summarize_switching_closed_loop_buck(result, windowPeriods)
%SUMMARIZE_SWITCHING_CLOSED_LOOP_BUCK Return deterministic control metrics.

if nargin < 2
    windowPeriods = 100;
end
if ~isnumeric(windowPeriods) || ~isscalar(windowPeriods) || ...
        ~isreal(windowPeriods) || ~isfinite(windowPeriods) || ...
        windowPeriods ~= round(windowPeriods) || windowPeriods <= 0 || ...
        windowPeriods > result.period_count
    error('SwitchingClosedLoopBuck:Window', ...
        'Window periods must be a positive integer within the simulation.');
end
parameters = result.parameters;
stepsPerPeriod = parameters.steps_per_switching_period;
windowIntervals = windowPeriods*stepsPerPeriod;
firstInterval = numel(result.switch_state) - windowIntervals + 1;
stateIndices = firstInterval:(firstInterval + windowIntervals - 1);
periodIndices = (result.period_count - windowPeriods + 1):result.period_count;

windowVoltage_V = result.output_voltage_V(stateIndices);
windowCurrent_A = result.inductor_current_A(stateIndices);
metrics.window_periods = windowPeriods;
metrics.average_output_voltage_V = mean(windowVoltage_V);
metrics.average_inductor_current_A = mean(windowCurrent_A);
metrics.output_voltage_ripple_V = max(windowVoltage_V) - ...
    min(windowVoltage_V);
metrics.inductor_current_ripple_A = max(windowCurrent_A) - ...
    min(windowCurrent_A);
metrics.average_duty_cycle = mean(result.duty_cycle(periodIndices));
metrics.final_reference_voltage_V = result.reference_voltage_V(end);
metrics.final_voltage_error_V = metrics.final_reference_voltage_V - ...
    metrics.average_output_voltage_V;
metrics.expected_average_voltage_V = ...
    (metrics.average_duty_cycle*parameters.input_voltage_V - ...
    (1 - metrics.average_duty_cycle)* ...
    parameters.diode_forward_voltage_V)/ ...
    (1 + (parameters.inductor_resistance_Ohm + ...
    metrics.average_duty_cycle*parameters.switch_on_resistance_Ohm)/ ...
    parameters.final_load_resistance_Ohm);

referenceMask = result.time_s >= parameters.reference_step_time_s & ...
    result.time_s < parameters.load_step_time_s;
referenceResponse_V = result.output_voltage_V(referenceMask);
metrics.reference_step_peak_voltage_V = max(referenceResponse_V);
metrics.reference_step_overshoot_percent = 100*max(0, ...
    metrics.reference_step_peak_voltage_V - ...
    parameters.final_reference_voltage_V)/ ...
    parameters.final_reference_voltage_V;
metrics.reference_step_settling_time_s = settling_time( ...
    result.time_s(referenceMask), referenceResponse_V, ...
    parameters.reference_step_time_s, ...
    parameters.final_reference_voltage_V, 0.02);

loadMask = result.time_s >= parameters.load_step_time_s;
loadResponse_V = result.output_voltage_V(loadMask);
metrics.load_step_minimum_voltage_V = min(loadResponse_V);
metrics.load_step_undershoot_percent = 100*max(0, ...
    parameters.final_reference_voltage_V - ...
    metrics.load_step_minimum_voltage_V)/ ...
    parameters.final_reference_voltage_V;
metrics.load_step_settling_time_s = settling_time( ...
    result.time_s(loadMask), loadResponse_V, ...
    parameters.load_step_time_s, ...
    parameters.final_reference_voltage_V, 0.02);

metrics.diode_loss_energy_J = result.diode_loss_energy_J;
metrics.inductor_loss_energy_J = result.inductor_loss_energy_J;
metrics.switch_conduction_loss_energy_J = ...
    result.switch_conduction_loss_energy_J;
metrics.turn_on_loss_energy_J = result.turn_on_loss_energy_J;
metrics.turn_off_loss_energy_J = result.turn_off_loss_energy_J;
metrics.switching_loss_energy_J = result.switching_loss_energy_J;
metrics.total_semiconductor_loss_energy_J = ...
    result.switch_conduction_loss_energy_J + ...
    result.switching_loss_energy_J + result.diode_loss_energy_J;
metrics.average_switching_loss_power_W = ...
    result.switching_loss_energy_J/parameters.end_time_s;
metrics.energy_efficiency_percent = 100*result.load_energy_J/ ...
    result.input_energy_J;
metrics.energy_balance_residual_J = result.energy_balance_residual_J;
metrics.relative_energy_balance_residual = ...
    abs(result.energy_balance_residual_J)/max(result.input_energy_J, eps);
end

function settlingTime_s = settling_time( ...
        time_s, signal, eventTime_s, target, fraction)
outside = abs(signal - target) > fraction*abs(target);
lastOutside = find(outside, 1, 'last');
if isempty(lastOutside)
    settlingTime_s = 0;
elseif lastOutside < numel(time_s)
    settlingTime_s = time_s(lastOutside + 1) - eventTime_s;
else
    settlingTime_s = inf;
end
end
