function parameters = validate_switching_closed_loop_buck_parameters(parameters)
%VALIDATE_SWITCHING_CLOSED_LOOP_BUCK_PARAMETERS Validate benchmark inputs.

requiredNumeric = {
    'input_voltage_V'; 'switching_frequency_Hz'; 'inductance_H'; ...
    'inductor_resistance_Ohm'; 'capacitance_F'; ...
    'diode_forward_voltage_V'; 'switch_on_resistance_Ohm'; ...
    'switching_loss_reference_voltage_V'; ...
    'switching_loss_reference_current_A'; ...
    'turn_on_energy_reference_J'; 'turn_off_energy_reference_J'; ...
    'initial_load_resistance_Ohm'; ...
    'final_load_resistance_Ohm'; 'load_step_time_s'; ...
    'initial_reference_voltage_V'; 'final_reference_voltage_V'; ...
    'reference_step_time_s'; 'end_time_s'; ...
    'steps_per_switching_period'; 'initial_inductor_current_A'; ...
    'initial_output_voltage_V'; ...
    'voltage_proportional_gain_A_per_V'; ...
    'voltage_integral_gain_A_per_Vs'; ...
    'current_proportional_gain_Ohm'; ...
    'minimum_current_reference_A'; 'maximum_current_reference_A'; ...
    'minimum_duty_cycle'; 'maximum_duty_cycle'; 'fixed_duty_cycle'
};
requiredLogical = {'control_enabled'; 'enforce_continuous_conduction'};
if ~isstruct(parameters) || ~all(isfield(parameters, ...
        [requiredNumeric; requiredLogical]))
    error('SwitchingClosedLoopBuck:Parameters', ...
        'Parameter structure is missing one or more required fields.');
end
for fieldIndex = 1:numel(requiredNumeric)
    value = parameters.(requiredNumeric{fieldIndex});
    if ~isnumeric(value) || ~isscalar(value) || ~isreal(value) || ...
            ~isfinite(value)
        error('SwitchingClosedLoopBuck:Parameters', ...
            'Every numeric parameter must be a finite real scalar.');
    end
end
if any(~cellfun(@(fieldName) ...
        islogical(parameters.(fieldName)) && ...
        isscalar(parameters.(fieldName)), requiredLogical))
    error('SwitchingClosedLoopBuck:Parameters', ...
        'Control and conduction flags must be logical scalars.');
end
positiveFields = {'input_voltage_V'; 'switching_frequency_Hz'; ...
    'inductance_H'; 'capacitance_F'; 'initial_load_resistance_Ohm'; ...
    'final_load_resistance_Ohm'; 'end_time_s'};
for fieldIndex = 1:numel(positiveFields)
    if parameters.(positiveFields{fieldIndex}) <= 0
        error('SwitchingClosedLoopBuck:Parameters', ...
            'Voltage, frequency, L, C, loads, and duration must be positive.');
    end
end
if parameters.inductor_resistance_Ohm < 0 || ...
        parameters.diode_forward_voltage_V < 0 || ...
        parameters.switch_on_resistance_Ohm < 0 || ...
        parameters.turn_on_energy_reference_J < 0 || ...
        parameters.turn_off_energy_reference_J < 0 || ...
        parameters.initial_inductor_current_A < 0 || ...
        parameters.initial_output_voltage_V < 0 || ...
        parameters.voltage_proportional_gain_A_per_V < 0 || ...
        parameters.voltage_integral_gain_A_per_Vs < 0 || ...
        parameters.current_proportional_gain_Ohm < 0
    error('SwitchingClosedLoopBuck:Parameters', ...
        'Loss, initial-state, and controller parameters must be nonnegative.');
end
if parameters.switching_loss_reference_voltage_V <= 0 || ...
        parameters.switching_loss_reference_current_A <= 0
    error('SwitchingClosedLoopBuck:LossReference', ...
        'Switching-loss reference voltage and current must be positive.');
end
if parameters.minimum_current_reference_A < 0 || ...
        parameters.maximum_current_reference_A <= ...
        parameters.minimum_current_reference_A || ...
        parameters.minimum_duty_cycle <= 0 || ...
        parameters.maximum_duty_cycle >= 1 || ...
        parameters.maximum_duty_cycle <= parameters.minimum_duty_cycle || ...
        parameters.fixed_duty_cycle <= 0 || ...
        parameters.fixed_duty_cycle >= 1
    error('SwitchingClosedLoopBuck:Limits', ...
        'Current and duty limits are inconsistent.');
end
stepsPerPeriod = parameters.steps_per_switching_period;
if stepsPerPeriod ~= round(stepsPerPeriod) || stepsPerPeriod < 20
    error('SwitchingClosedLoopBuck:TimeGrid', ...
        'steps_per_switching_period must be an integer of at least 20.');
end
alignedValues = [parameters.minimum_duty_cycle; ...
    parameters.maximum_duty_cycle; parameters.fixed_duty_cycle]* ...
    stepsPerPeriod;
if any(abs(alignedValues - round(alignedValues)) > 1e-10)
    error('SwitchingClosedLoopBuck:TimeGrid', ...
        'Configured duty values must align with integer PWM step counts.');
end
switchingPeriod_s = 1/parameters.switching_frequency_Hz;
eventTimes_s = [parameters.reference_step_time_s; ...
    parameters.load_step_time_s; parameters.end_time_s];
if any(eventTimes_s < 0) || ...
        parameters.reference_step_time_s >= parameters.end_time_s || ...
        parameters.load_step_time_s >= parameters.end_time_s || ...
        any(abs(eventTimes_s/switchingPeriod_s - ...
        round(eventTimes_s/switchingPeriod_s)) > 1e-10)
    error('SwitchingClosedLoopBuck:TimeGrid', ...
        'Reference, load, and end times must align with PWM periods.');
end
end
