%% Pouch-Cell Through-Thickness Thermal Model Check
% Validates conservation, symmetry, spatial resolution, and input handling.

clearvars; clc;

modelDirectory = fileparts(mfilename("fullpath"));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory);

profile = pouch_cell_thermal_default_profile();
parameters = pouch_cell_thermal_default_parameters();
result = simulate_pouch_cell_thermal_model(profile, parameters, 0.5);

expectedSize = [6001, parameters.node_count];
assert(isequal(size(result.node_temperature_C), expectedSize) && ...
    result.dt_s == 0.5, ...
    "Canonical simulation must preserve the requested time and spatial grids.");
assert(all(isfinite(result.node_temperature_C), "all") && ...
    all(isfinite(result.interface_heat_W), "all") && ...
    all(isfinite(result.node_net_heat_W), "all"), ...
    "Every temperature and heat-flow sample must remain finite.");
assert(max(abs(sum(result.node_heat_generation_W, 2) - ...
    result.cell_heat_generation_W)) < 1e-12, ...
    "Finite-volume heat allocation must equal the cell heat profile.");

conductionClosure_W = ...
    sum(result.node_conduction_net_heat_W, 2) + ...
    result.boundary_heat_removal_W;
assert(max(abs(conductionClosure_W)) < 1e-12, ...
    "Internal interface heat must cancel in the cell energy balance.");
assert(max(abs(result.node_energy_balance_error_J)) < 1e-7 && ...
    abs(result.energy_balance_error_J) < 1e-7, ...
    "Node and whole-cell discrete energy balances must close.");

leftConvection_W = ...
    parameters.left_heat_transfer_coefficient_W_per_m2K * ...
    result.face_area_m2 * ...
    (result.left_surface_temperature_C - ...
    result.left_fluid_temperature_C);
rightConvection_W = ...
    parameters.right_heat_transfer_coefficient_W_per_m2K * ...
    result.face_area_m2 * ...
    (result.right_surface_temperature_C - ...
    result.right_fluid_temperature_C);
assert(max(abs(leftConvection_W - ...
    result.left_boundary_heat_removal_W)) < 1e-12 && ...
    max(abs(rightConvection_W - ...
    result.right_boundary_heat_removal_W)) < 1e-12, ...
    "Each inferred surface temperature must close its convection relation.");

assert(result.peak_temperature_C > 35 && ...
    result.peak_temperature_C < 55 && ...
    result.peak_temperature_spread_C > 0.5, ...
    "Canonical heating must produce a bounded, visible spatial gradient.");
assert(result.peak_position_m > parameters.thickness_m / 2, ...
    "The weaker right-side cooling should shift the hot spot rightward.");
assert(all(result.node_position_m > 0) && ...
    all(result.node_position_m < parameters.thickness_m) && ...
    all(diff(result.node_position_m) > 0), ...
    "Finite-volume node positions must be ordered inside the slab.");

zeroHeatProfile = table( ...
    [0; 60], [0; 0], [25; 25], [25; 25], ...
    VariableNames=["time_s", "cell_heat_generation_W", ...
    "left_fluid_temperature_C", "right_fluid_temperature_C"]);
zeroHeatResult = simulate_pouch_cell_thermal_model( ...
    zeroHeatProfile, parameters, 0.5);
assert(all(zeroHeatResult.node_temperature_C == 25, "all") && ...
    all(zeroHeatResult.boundary_heat_removal_W == 0) && ...
    all(zeroHeatResult.node_net_heat_W == 0, "all"), ...
    "An isothermal zero-heat case must remain exactly at equilibrium.");

symmetricParameters = parameters;
symmetricParameters.left_heat_transfer_coefficient_W_per_m2K = 20;
symmetricParameters.right_heat_transfer_coefficient_W_per_m2K = 20;
symmetricProfile = table( ...
    [0; 3600], [8; 8], [25; 25], [25; 25], ...
    VariableNames=["time_s", "cell_heat_generation_W", ...
    "left_fluid_temperature_C", "right_fluid_temperature_C"]);
symmetricResult = simulate_pouch_cell_thermal_model( ...
    symmetricProfile, symmetricParameters, 0.5);
symmetryError_C = max(abs( ...
    symmetricResult.node_temperature_C - ...
    fliplr(symmetricResult.node_temperature_C)), [], "all");
assert(symmetryError_C < 1e-12, ...
    "Equal boundary conditions must preserve through-thickness symmetry.");

cellVolume_m3 = parameters.thickness_m * ...
    parameters.width_m * parameters.height_m;
volumetricHeat_W_per_m3 = 8 / cellVolume_m3;
analyticCenterTemperature_C = 25 + ...
    volumetricHeat_W_per_m3 * parameters.thickness_m / (2 * 20) + ...
    volumetricHeat_W_per_m3 * parameters.thickness_m^2 / ( ...
    8 * parameters.through_plane_conductivity_W_per_mK);
assert(abs(symmetricResult.center_temperature_C(end) - ...
    analyticCenterTemperature_C) < 0.12, ...
    "The long symmetric simulation must approach the continuous " + ...
    "steady-state slab solution.");

gridNodeCounts = [7, 15, 31];
gridTimeSteps_s = [0.5, 0.25, 0.05];
gridCenterTemperature_C = zeros(size(gridNodeCounts));
gridProfile = table( ...
    [0; 600], [8; 8], [25; 25], [25; 25], ...
    VariableNames=["time_s", "cell_heat_generation_W", ...
    "left_fluid_temperature_C", "right_fluid_temperature_C"]);
for gridIndex = 1:numel(gridNodeCounts)
    gridParameters = symmetricParameters;
    gridParameters.node_count = gridNodeCounts(gridIndex);
    gridResult = simulate_pouch_cell_thermal_model( ...
        gridProfile, gridParameters, gridTimeSteps_s(gridIndex));
    gridCenterTemperature_C(gridIndex) = ...
        gridResult.center_temperature_C(end);
end
coarseGridError_C = abs( ...
    gridCenterTemperature_C(1) - gridCenterTemperature_C(3));
mediumGridError_C = abs( ...
    gridCenterTemperature_C(2) - gridCenterTemperature_C(3));
assert(mediumGridError_C < coarseGridError_C && ...
    mediumGridError_C < 0.05, ...
    "Center temperature must converge as the spatial grid is refined.");

irregularProfile = table( ...
    [0; 0.1; 0.3; 0.5], [0; 3; 6; 0], ...
    [25; 25; 24; 24], [25; 25; 26; 26], ...
    VariableNames=["time_s", "cell_heat_generation_W", ...
    "left_fluid_temperature_C", "right_fluid_temperature_C"]);
irregularResult = simulate_pouch_cell_thermal_model( ...
    irregularProfile, parameters);
assert(isempty(irregularResult.dt_s) && ...
    isequal(irregularResult.interval_s, diff(irregularProfile.time_s)), ...
    "Native irregular timestamps must remain unchanged.");

missingParameters = rmfield(parameters, "thickness_m");
invalidNodeParameters = parameters;
invalidNodeParameters.node_count = 2;
invalidInitialParameters = parameters;
invalidInitialParameters.initial_temperature_C = [25, 25];
missingHeatProfile = removevars(profile, "cell_heat_generation_W");
negativeHeatProfile = profile;
negativeHeatProfile.cell_heat_generation_W(:) = -1;
invalidCases = {
    missingParameters, profile, 0.5, ...
        "PouchCellThermal:Parameters";
    invalidNodeParameters, profile, 0.5, ...
        "PouchCellThermal:Parameters";
    invalidInitialParameters, profile, 0.5, ...
        "PouchCellThermal:InitialTemperature";
    parameters, missingHeatProfile, 0.5, ...
        "PouchCellThermal:ProfileColumns";
    parameters, negativeHeatProfile, 0.5, ...
        "PouchCellThermal:ProfileHeat";
    parameters, profile, 1, ...
        "PouchCellThermal:TimeStepStability"
};
for caseIndex = 1:size(invalidCases, 1)
    rejected = false;
    try
        simulate_pouch_cell_thermal_model( ...
            invalidCases{caseIndex, 2}, ...
            invalidCases{caseIndex, 1}, ...
            invalidCases{caseIndex, 3});
    catch validationError
        rejected = strcmp(validationError.identifier, ...
            invalidCases{caseIndex, 4});
    end
    assert(rejected, ...
        "Malformed pouch-cell input must be rejected deterministically.");
end

repeatResult = simulate_pouch_cell_thermal_model( ...
    profile, parameters, 0.5);
assert(isequal(result.node_temperature_C, ...
    repeatResult.node_temperature_C) && ...
    isequal(result.node_net_heat_W, ...
    repeatResult.node_net_heat_W), ...
    "Repeated pouch-cell simulations must be deterministic.");

fprintf("Pouch-cell thermal-gradient check passed.\n");
fprintf("Peak node temperature: %.2f degC at %.2f mm and %.0f s\n", ...
    result.peak_temperature_C, 1000 * result.peak_position_m, ...
    result.peak_time_s);
fprintf("Peak through-thickness node spread: %.2f degC\n", ...
    result.peak_temperature_spread_C);
fprintf("Symmetric steady center error: %.3f degC\n", ...
    abs(symmetricResult.center_temperature_C(end) - ...
    analyticCenterTemperature_C));
fprintf("Medium-to-fine grid center difference: %.4f degC\n", ...
    mediumGridError_C);
