function result = simulate_pouch_cell_thermal_model( ...
        profile, parameters, dt_s)
%SIMULATE_POUCH_CELL_THERMAL_MODEL Resolve a pouch-cell slab temperature.
% A cell-centered finite-volume network resolves one-dimensional
% through-thickness conduction, uniform volumetric heat generation, and
% independent convection conditions at the two broad faces.

if nargin < 3
    dt_s = [];
end

[profileTime_s, profileHeat_W, profileLeftFluid_C, ...
    profileRightFluid_C] = validate_profile(profile);
validate_parameters(parameters);
if isempty(dt_s)
    time_s = profileTime_s;
    cellHeat_W = profileHeat_W;
    leftFluid_C = profileLeftFluid_C;
    rightFluid_C = profileRightFluid_C;
else
    validate_time_step(dt_s, profileTime_s(end));
    time_s = (0:dt_s:profileTime_s(end))';
    cellHeat_W = interp1( ...
        profileTime_s, profileHeat_W, time_s, "previous", "extrap");
    leftFluid_C = interp1( ...
        profileTime_s, profileLeftFluid_C, ...
        time_s, "previous", "extrap");
    rightFluid_C = interp1( ...
        profileTime_s, profileRightFluid_C, ...
        time_s, "previous", "extrap");
end

nodeCount = parameters.node_count;
faceArea_m2 = parameters.width_m * parameters.height_m;
nodeThickness_m = parameters.thickness_m / nodeCount;
nodePosition_m = ((1:nodeCount) - 0.5) * nodeThickness_m;
nodeVolume_m3 = faceArea_m2 * nodeThickness_m;
nodeCapacity_J_per_K = parameters.density_kg_per_m3 * ...
    parameters.specific_heat_J_per_kgK * nodeVolume_m3;
interfaceConductance_W_per_K = ...
    parameters.through_plane_conductivity_W_per_mK * ...
    faceArea_m2 / nodeThickness_m;
leftBoundaryConductance_W_per_K = faceArea_m2 / ( ...
    nodeThickness_m / (2 * ...
    parameters.through_plane_conductivity_W_per_mK) + ...
    1 / parameters.left_heat_transfer_coefficient_W_per_m2K);
rightBoundaryConductance_W_per_K = faceArea_m2 / ( ...
    nodeThickness_m / (2 * ...
    parameters.through_plane_conductivity_W_per_mK) + ...
    1 / parameters.right_heat_transfer_coefficient_W_per_m2K);

interval_s = diff(time_s);
validate_explicit_euler_stability( ...
    interval_s, nodeCapacity_J_per_K, nodeCount, ...
    interfaceConductance_W_per_K, ...
    leftBoundaryConductance_W_per_K, ...
    rightBoundaryConductance_W_per_K);

sampleCount = numel(time_s);
nodeTemperature_C = zeros(sampleCount, nodeCount);
nodeHeatGeneration_W = zeros(sampleCount, nodeCount);
interfaceHeat_W = zeros(sampleCount, nodeCount - 1);
nodeConductionNetHeat_W = zeros(sampleCount, nodeCount);
nodeNetHeat_W = zeros(sampleCount, nodeCount);
leftBoundaryHeat_W = zeros(sampleCount, 1);
rightBoundaryHeat_W = zeros(sampleCount, 1);

initialTemperature_C = parameters.initial_temperature_C;
if isscalar(initialTemperature_C)
    nodeTemperature_C(1, :) = initialTemperature_C;
else
    nodeTemperature_C(1, :) = initialTemperature_C(:)';
end

for intervalIndex = 1:numel(interval_s)
    [nodeHeatGeneration_W(intervalIndex, :), ...
        interfaceHeat_W(intervalIndex, :), ...
        nodeConductionNetHeat_W(intervalIndex, :), ...
        leftBoundaryHeat_W(intervalIndex), ...
        rightBoundaryHeat_W(intervalIndex)] = calculate_heat_flows( ...
            nodeTemperature_C(intervalIndex, :), ...
            cellHeat_W(intervalIndex), ...
            leftFluid_C(intervalIndex), ...
            rightFluid_C(intervalIndex), ...
            nodeCount, interfaceConductance_W_per_K, ...
            leftBoundaryConductance_W_per_K, ...
            rightBoundaryConductance_W_per_K);
    nodeNetHeat_W(intervalIndex, :) = ...
        nodeHeatGeneration_W(intervalIndex, :) + ...
        nodeConductionNetHeat_W(intervalIndex, :);
    nodeTemperature_C(intervalIndex + 1, :) = ...
        nodeTemperature_C(intervalIndex, :) + ...
        interval_s(intervalIndex) * ...
        nodeNetHeat_W(intervalIndex, :) / nodeCapacity_J_per_K;
end

[nodeHeatGeneration_W(end, :), interfaceHeat_W(end, :), ...
    nodeConductionNetHeat_W(end, :), leftBoundaryHeat_W(end), ...
    rightBoundaryHeat_W(end)] = calculate_heat_flows( ...
        nodeTemperature_C(end, :), cellHeat_W(end), ...
        leftFluid_C(end), rightFluid_C(end), nodeCount, ...
        interfaceConductance_W_per_K, ...
        leftBoundaryConductance_W_per_K, ...
        rightBoundaryConductance_W_per_K);
nodeNetHeat_W(end, :) = nodeHeatGeneration_W(end, :) + ...
    nodeConductionNetHeat_W(end, :);

allSignals = [nodeTemperature_C, nodeHeatGeneration_W, ...
    interfaceHeat_W, nodeConductionNetHeat_W, nodeNetHeat_W, ...
    leftBoundaryHeat_W, rightBoundaryHeat_W];
if any(~isfinite(allSignals), "all")
    error("PouchCellThermal:Numerics", ...
        "Every simulated temperature and heat-flow sample must be finite.");
end
if any(nodeTemperature_C <= -273.15, "all")
    error("PouchCellThermal:AbsoluteTemperature", ...
        "Every simulated node temperature must exceed absolute zero.");
end

leftSurfaceTemperature_C = leftFluid_C + ...
    leftBoundaryHeat_W / ( ...
    parameters.left_heat_transfer_coefficient_W_per_m2K * faceArea_m2);
rightSurfaceTemperature_C = rightFluid_C + ...
    rightBoundaryHeat_W / ( ...
    parameters.right_heat_transfer_coefficient_W_per_m2K * faceArea_m2);
volumeAverageTemperature_C = mean(nodeTemperature_C, 2);
centerTemperature_C = calculate_center_temperature(nodeTemperature_C);
temperatureSpread_C = ...
    max(nodeTemperature_C, [], 2) - min(nodeTemperature_C, [], 2);
boundaryHeatRemoval_W = leftBoundaryHeat_W + rightBoundaryHeat_W;
cellNetHeat_W = cellHeat_W - boundaryHeatRemoval_W;

nodeEnergyChange_J = nodeCapacity_J_per_K * ...
    (nodeTemperature_C(end, :) - nodeTemperature_C(1, :));
integratedNodeNetHeat_J = sum( ...
    nodeNetHeat_W(1:end-1, :) .* interval_s, 1);
thermalEnergyChange_J = sum(nodeEnergyChange_J);
integratedCellNetHeat_J = sum( ...
    cellNetHeat_W(1:end-1) .* interval_s);

[peakTemperature_C, linearPeakIndex] = ...
    max(nodeTemperature_C, [], "all");
[peakTimeIndex, peakNodeIndex] = ...
    ind2sub(size(nodeTemperature_C), linearPeakIndex);

result.time_s = time_s;
result.cell_heat_generation_W = cellHeat_W;
result.left_fluid_temperature_C = leftFluid_C;
result.right_fluid_temperature_C = rightFluid_C;
result.node_position_m = nodePosition_m;
result.node_temperature_C = nodeTemperature_C;
result.left_surface_temperature_C = leftSurfaceTemperature_C;
result.right_surface_temperature_C = rightSurfaceTemperature_C;
result.center_temperature_C = centerTemperature_C;
result.volume_average_temperature_C = volumeAverageTemperature_C;
result.temperature_spread_C = temperatureSpread_C;
result.node_heat_generation_W = nodeHeatGeneration_W;
result.interface_heat_W = interfaceHeat_W;
result.node_conduction_net_heat_W = nodeConductionNetHeat_W;
result.node_net_heat_W = nodeNetHeat_W;
result.left_boundary_heat_removal_W = leftBoundaryHeat_W;
result.right_boundary_heat_removal_W = rightBoundaryHeat_W;
result.boundary_heat_removal_W = boundaryHeatRemoval_W;
result.cell_net_heat_W = cellNetHeat_W;
result.interval_s = interval_s;
result.face_area_m2 = faceArea_m2;
result.node_thickness_m = nodeThickness_m;
result.node_volume_m3 = nodeVolume_m3;
result.node_thermal_capacity_J_per_K = nodeCapacity_J_per_K;
result.interface_conductance_W_per_K = ...
    interfaceConductance_W_per_K;
result.left_boundary_conductance_W_per_K = ...
    leftBoundaryConductance_W_per_K;
result.right_boundary_conductance_W_per_K = ...
    rightBoundaryConductance_W_per_K;
result.node_energy_change_J = nodeEnergyChange_J;
result.integrated_node_net_heat_J = integratedNodeNetHeat_J;
result.node_energy_balance_error_J = ...
    nodeEnergyChange_J - integratedNodeNetHeat_J;
result.thermal_energy_change_J = thermalEnergyChange_J;
result.integrated_cell_net_heat_J = integratedCellNetHeat_J;
result.energy_balance_error_J = ...
    thermalEnergyChange_J - integratedCellNetHeat_J;
result.peak_temperature_C = peakTemperature_C;
result.peak_temperature_spread_C = max(temperatureSpread_C);
result.peak_time_s = time_s(peakTimeIndex);
result.peak_node_index = peakNodeIndex;
result.peak_position_m = nodePosition_m(peakNodeIndex);
result.parameters = parameters;

uniformTolerance_s = 1e-12 * max(1, max(abs(interval_s)));
if max(abs(interval_s - interval_s(1))) <= uniformTolerance_s
    result.dt_s = interval_s(1);
else
    result.dt_s = [];
end
end

function [nodeHeat_W, interfaceHeat_W, conductionNetHeat_W, ...
        leftBoundaryHeat_W, rightBoundaryHeat_W] = ...
        calculate_heat_flows(nodeTemperature_C, cellHeat_W, ...
            leftFluid_C, rightFluid_C, nodeCount, ...
            interfaceConductance_W_per_K, ...
            leftBoundaryConductance_W_per_K, ...
            rightBoundaryConductance_W_per_K)
nodeHeat_W = (cellHeat_W / nodeCount) * ones(1, nodeCount);
interfaceHeat_W = interfaceConductance_W_per_K * ...
    (nodeTemperature_C(1:end-1) - nodeTemperature_C(2:end));
leftBoundaryHeat_W = leftBoundaryConductance_W_per_K * ...
    (nodeTemperature_C(1) - leftFluid_C);
rightBoundaryHeat_W = rightBoundaryConductance_W_per_K * ...
    (nodeTemperature_C(end) - rightFluid_C);

conductionNetHeat_W = zeros(1, nodeCount);
conductionNetHeat_W(1:end-1) = ...
    conductionNetHeat_W(1:end-1) - interfaceHeat_W;
conductionNetHeat_W(2:end) = ...
    conductionNetHeat_W(2:end) + interfaceHeat_W;
conductionNetHeat_W(1) = ...
    conductionNetHeat_W(1) - leftBoundaryHeat_W;
conductionNetHeat_W(end) = ...
    conductionNetHeat_W(end) - rightBoundaryHeat_W;
end

function centerTemperature_C = ...
        calculate_center_temperature(nodeTemperature_C)
nodeCount = size(nodeTemperature_C, 2);
if rem(nodeCount, 2) == 1
    centerTemperature_C = ...
        nodeTemperature_C(:, (nodeCount + 1) / 2);
else
    centerIndices = [nodeCount / 2, nodeCount / 2 + 1];
    centerTemperature_C = mean( ...
        nodeTemperature_C(:, centerIndices), 2);
end
end

function [profileTime_s, profileHeat_W, profileLeftFluid_C, ...
        profileRightFluid_C] = validate_profile(profile)
requiredVariables = {
    "time_s";
    "cell_heat_generation_W";
    "left_fluid_temperature_C";
    "right_fluid_temperature_C"
};
if ~istable(profile) || ...
        ~all(ismember( ...
        string(requiredVariables), ...
        string(profile.Properties.VariableNames)))
    error("PouchCellThermal:ProfileColumns", ...
        "Profile must contain time_s, cell_heat_generation_W, " + ...
        "left_fluid_temperature_C, and right_fluid_temperature_C.");
end

profileVariables = {
    profile.time_s;
    profile.cell_heat_generation_W;
    profile.left_fluid_temperature_C;
    profile.right_fluid_temperature_C
};
for variableIndex = 1:numel(profileVariables)
    variableValue = profileVariables{variableIndex};
    if ~isnumeric(variableValue) || ~isvector(variableValue) || ...
            ~isreal(variableValue) || numel(variableValue) < 2
        error("PouchCellThermal:ProfileShape", ...
            "Profile columns must be real numeric vectors with " + ...
            "at least two rows.");
    end
end

profileTime_s = profileVariables{1}(:);
profileHeat_W = profileVariables{2}(:);
profileLeftFluid_C = profileVariables{3}(:);
profileRightFluid_C = profileVariables{4}(:);
profileSignals = [profileTime_s, profileHeat_W, ...
    profileLeftFluid_C, profileRightFluid_C];
if any(~isfinite(profileSignals), "all")
    error("PouchCellThermal:ProfileFinite", ...
        "Profile timestamps, heat, and fluid temperatures must be finite.");
end
if abs(profileTime_s(1)) > 1e-12
    error("PouchCellThermal:ProfileStart", ...
        "Profile time_s must start at zero.");
end
if any(diff(profileTime_s) <= 0)
    error("PouchCellThermal:TimeOrder", ...
        "Profile timestamps must be strictly increasing.");
end
if any(profileHeat_W < 0)
    error("PouchCellThermal:ProfileHeat", ...
        "Cell heat generation must be nonnegative.");
end
if any(profileLeftFluid_C <= -273.15) || ...
        any(profileRightFluid_C <= -273.15)
    error("PouchCellThermal:ProfileTemperature", ...
        "Boundary-fluid temperatures must exceed absolute zero.");
end
end

function validate_parameters(parameters)
requiredFields = {
    "node_count";
    "thickness_m";
    "width_m";
    "height_m";
    "density_kg_per_m3";
    "specific_heat_J_per_kgK";
    "through_plane_conductivity_W_per_mK";
    "left_heat_transfer_coefficient_W_per_m2K";
    "right_heat_transfer_coefficient_W_per_m2K";
    "initial_temperature_C"
};
if ~isstruct(parameters) || ...
        ~all(isfield(parameters, string(requiredFields)))
    error("PouchCellThermal:Parameters", ...
        "Parameter structure is missing one or more required fields.");
end
if ~isnumeric(parameters.node_count) || ...
        ~isscalar(parameters.node_count) || ...
        ~isreal(parameters.node_count) || ...
        ~isfinite(parameters.node_count) || ...
        parameters.node_count < 3 || ...
        parameters.node_count ~= round(parameters.node_count)
    error("PouchCellThermal:Parameters", ...
        "node_count must be an integer greater than or equal to three.");
end

positiveScalarFields = {
    "thickness_m";
    "width_m";
    "height_m";
    "density_kg_per_m3";
    "specific_heat_J_per_kgK";
    "through_plane_conductivity_W_per_mK";
    "left_heat_transfer_coefficient_W_per_m2K";
    "right_heat_transfer_coefficient_W_per_m2K"
};
for fieldIndex = 1:numel(positiveScalarFields)
    fieldValue = parameters.(positiveScalarFields{fieldIndex});
    if ~isnumeric(fieldValue) || ~isscalar(fieldValue) || ...
            ~isreal(fieldValue) || ~isfinite(fieldValue) || ...
            fieldValue <= 0
        error("PouchCellThermal:Parameters", ...
            "Geometry and thermal properties must be positive scalars.");
    end
end

initialTemperature_C = parameters.initial_temperature_C;
if ~isnumeric(initialTemperature_C) || ...
        ~isvector(initialTemperature_C) || ...
        ~isreal(initialTemperature_C) || ...
        any(~isfinite(initialTemperature_C)) || ...
        ~(isscalar(initialTemperature_C) || ...
        numel(initialTemperature_C) == parameters.node_count)
    error("PouchCellThermal:InitialTemperature", ...
        "initial_temperature_C must be a finite scalar or contain " + ...
        "one value per node.");
end
if any(initialTemperature_C <= -273.15)
    error("PouchCellThermal:InitialTemperature", ...
        "Initial temperatures must exceed absolute zero.");
end
end

function validate_time_step(dt_s, profileEndTime_s)
if ~isnumeric(dt_s) || ~isscalar(dt_s) || ...
        ~isreal(dt_s) || ~isfinite(dt_s) || dt_s <= 0
    error("PouchCellThermal:TimeStep", ...
        "dt_s must be empty or a finite positive real scalar.");
end
intervalCount = round(profileEndTime_s / dt_s);
if intervalCount < 1 || ...
        abs(intervalCount * dt_s - profileEndTime_s) > 1e-9
    error("PouchCellThermal:TimeGrid", ...
        "Profile end time must be an integer multiple of dt_s.");
end
end

function validate_explicit_euler_stability( ...
        interval_s, nodeCapacity_J_per_K, nodeCount, ...
        interfaceConductance_W_per_K, ...
        leftBoundaryConductance_W_per_K, ...
        rightBoundaryConductance_W_per_K)
outflowConductance_W_per_K = ...
    2 * interfaceConductance_W_per_K * ones(1, nodeCount);
outflowConductance_W_per_K(1) = ...
    interfaceConductance_W_per_K + ...
    leftBoundaryConductance_W_per_K;
outflowConductance_W_per_K(end) = ...
    interfaceConductance_W_per_K + ...
    rightBoundaryConductance_W_per_K;
stabilityLimit_s = min( ...
    nodeCapacity_J_per_K ./ outflowConductance_W_per_K);
if any(interval_s >= stabilityLimit_s)
    error("PouchCellThermal:TimeStepStability", ...
        "Every interval must satisfy the conservative explicit-Euler " + ...
        "finite-volume stability limit.");
end
end
