%% Battery Module Liquid-Cooling Network Check
% Validates heat exchange, spatial coupling, and discrete energy balances.

clearvars; clc;

modelDirectory = fileparts(mfilename('fullpath'));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory);

profile = battery_module_cooling_default_profile();
parameters = battery_module_cooling_default_parameters();
result = simulate_battery_module_cooling_network( ...
    profile, parameters, 1);

expectedSize = [height(profile), parameters.cell_count];
assert(isequal(size(result.cell_temp_C), expectedSize) && ...
    result.dt_s == 1 && numel(result.time_s) == 1801, ...
    'Canonical result must contain six cell traces over 1800 one-second steps.');
assert(all(isfinite(result.cell_temp_C), 'all') && ...
    all(isfinite(result.coolant_segment_outlet_temp_C), 'all') && ...
    all(isfinite(result.cell_to_coolant_heat_W), 'all'), ...
    'Every temperature and heat-flow sample must remain finite.');
assert(max(abs(sum(result.cell_heat_generation_W, 2) - ...
    result.module_heat_generation_W)) < 1e-12, ...
    'Allocated cell heat must equal the module heat profile.');

coolantHeatGain_W = result.coolant_capacity_rate_W_per_K * ...
    (result.coolant_segment_outlet_temp_C - ...
    result.coolant_segment_inlet_temp_C);
assert(max(abs(coolantHeatGain_W - ...
    result.cell_to_coolant_heat_W), [], 'all') < 1e-12, ...
    'Every coolant segment must close its local energy balance.');
assert(isequal(result.coolant_segment_inlet_temp_C(:, 1), ...
    result.coolant_supply_temp_C) && ...
    isequal(result.coolant_segment_inlet_temp_C(:, 2:end), ...
    result.coolant_segment_outlet_temp_C(:, 1:end-1)), ...
    'Each segment outlet must feed the next segment without discontinuity.');
assert(max(abs(sum(result.cell_conduction_net_heat_W, 2))) < 1e-12, ...
    'Cell-to-cell conduction must conserve module energy.');
assert(max(abs(result.cell_energy_balance_error_J)) < 1e-7 && ...
    abs(result.energy_balance_error_J) < 1e-7, ...
    'Cell and module thermal energy balances must close.');

assert(result.peak_cell_temp_C > 35 && ...
    result.peak_cell_temp_C < 50, ...
    'Canonical heating must be visible but remain bounded.');
assert(result.peak_temperature_spread_C > 1, ...
    'Canonical heat and coolant asymmetry must create a visible spread.');
assert(result.peak_coolant_outlet_temp_C > ...
    max(result.coolant_supply_temp_C) + 3, ...
    'The serial channel must show measurable coolant warming.');
assert(result.hottest_cell_index >= 3 && ...
    result.hottest_cell_index <= parameters.cell_count, ...
    'The hottest cell should reflect central heating and downstream warming.');

activeCooling = result.module_coolant_heat_removal_W > 0;
assert(any(activeCooling) && ...
    all(result.coolant_module_outlet_temp_C(activeCooling) > ...
    result.coolant_supply_temp_C(activeCooling)), ...
    'Positive module heat removal must warm the coolant.');
assert(all(result.segment_effectiveness > 0 & ...
    result.segment_effectiveness < 1) && ...
    all(result.effective_conductance_W_per_K > 0) && ...
    all(result.effective_conductance_W_per_K < ...
    parameters.cell_to_coolant_conductance_W_per_K), ...
    'Finite-flow heat-exchanger effectiveness must remain physical.');

highFlowParameters = parameters;
highFlowParameters.coolant_mass_flow_kg_per_s = ...
    3 * parameters.coolant_mass_flow_kg_per_s;
highFlowResult = simulate_battery_module_cooling_network( ...
    profile, highFlowParameters, 1);
assert(highFlowResult.peak_cell_temp_C < result.peak_cell_temp_C && ...
    highFlowResult.peak_temperature_spread_C < ...
    result.peak_temperature_spread_C && ...
    highFlowResult.peak_coolant_outlet_temp_C < ...
    result.peak_coolant_outlet_temp_C, ...
    ['Higher coolant flow must reduce peak cell temperature, ', ...
    'temperature spread, and outlet warming in the canonical case.']);

uniformProfile = table( ...
    [0; 10], [0; 0], [25; 25], ...
    'VariableNames', {'time_s', 'module_heat_generation_W', ...
    'coolant_inlet_temp_C'});
uniformParameters = parameters;
uniformParameters.initial_cell_temp_C(:) = 25;
uniformResult = simulate_battery_module_cooling_network( ...
    uniformProfile, uniformParameters, 1);
assert(all(uniformResult.cell_temp_C == 25, 'all') && ...
    all(uniformResult.coolant_segment_outlet_temp_C == 25, 'all') && ...
    all(uniformResult.cell_net_heat_W == 0, 'all'), ...
    'An isothermal zero-heat case must remain exactly at equilibrium.');

irregularProfile = table( ...
    [0; 2; 7; 10], [0; 60; 20; 0], [25; 25; 26; 26], ...
    'VariableNames', {'time_s', 'module_heat_generation_W', ...
    'coolant_inlet_temp_C'});
irregularResult = simulate_battery_module_cooling_network( ...
    irregularProfile, parameters);
assert(isempty(irregularResult.dt_s) && ...
    isequal(irregularResult.interval_s, diff(irregularProfile.time_s)), ...
    'Native irregular timestamps must remain unchanged.');
assert(irregularResult.coolant_supply_temp_C(3) == 26 && ...
    irregularResult.module_heat_generation_W(2) == 60, ...
    'Irregular input values must be preserved without resampling.');

columnParameters = parameters;
vectorFields = {
    'cell_mass_kg';
    'cell_specific_heat_J_per_kgK';
    'initial_cell_temp_C';
    'cell_heat_fraction';
    'cell_to_coolant_conductance_W_per_K';
    'cell_to_cell_conductance_W_per_K'
};
for fieldIndex = 1:numel(vectorFields)
    fieldName = vectorFields{fieldIndex};
    columnParameters.(fieldName) = columnParameters.(fieldName)(:);
end
columnResult = simulate_battery_module_cooling_network( ...
    profile, columnParameters, 1);
assert(isequal(result.cell_temp_C, columnResult.cell_temp_C) && ...
    isequal(result.coolant_segment_outlet_temp_C, ...
    columnResult.coolant_segment_outlet_temp_C), ...
    'Row and column parameter vectors must produce identical results.');

missingFractionParameters = rmfield(parameters, 'cell_heat_fraction');
invalidFractionParameters = parameters;
invalidFractionParameters.cell_heat_fraction = ...
    ones(1, parameters.cell_count);
zeroFlowParameters = parameters;
zeroFlowParameters.coolant_mass_flow_kg_per_s = 0;
missingTemperatureProfile = ...
    removevars(profile, 'coolant_inlet_temp_C');
negativeHeatProfile = profile;
negativeHeatProfile.module_heat_generation_W(:) = -1;
nonnumericTemperatureProfile = profile;
nonnumericTemperatureProfile.coolant_inlet_temp_C = ...
    string(nonnumericTemperatureProfile.coolant_inlet_temp_C);
invalidCases = {
    missingFractionParameters, profile, 1, ...
        'BatteryModuleCooling:Parameters';
    invalidFractionParameters, profile, 1, ...
        'BatteryModuleCooling:HeatFractions';
    zeroFlowParameters, profile, 1, ...
        'BatteryModuleCooling:Parameters';
    parameters, missingTemperatureProfile, 1, ...
        'BatteryModuleCooling:ProfileColumns';
    parameters, negativeHeatProfile, 1, ...
        'BatteryModuleCooling:ProfileHeat';
    parameters, nonnumericTemperatureProfile, 1, ...
        'BatteryModuleCooling:ProfileShape';
    parameters, profile, 600, ...
        'BatteryModuleCooling:TimeStepStability'
};
for caseIndex = 1:size(invalidCases, 1)
    rejected = false;
    try
        simulate_battery_module_cooling_network( ...
            invalidCases{caseIndex, 2}, ...
            invalidCases{caseIndex, 1}, ...
            invalidCases{caseIndex, 3});
    catch validationError
        rejected = strcmp(validationError.identifier, ...
            invalidCases{caseIndex, 4});
    end
    assert(rejected, ...
        'Malformed thermal-network input must be rejected deterministically.');
end

repeatResult = simulate_battery_module_cooling_network( ...
    profile, parameters, 1);
assert(isequal(result.cell_temp_C, repeatResult.cell_temp_C) && ...
    isequal(result.coolant_segment_outlet_temp_C, ...
    repeatResult.coolant_segment_outlet_temp_C) && ...
    isequal(result.cell_net_heat_W, repeatResult.cell_net_heat_W), ...
    'Repeated module simulations must be deterministic.');

fprintf('Battery module cooling-network check passed.\n');
fprintf('Peak cell temperature: %.2f degC (cell %d at %.0f s)\n', ...
    result.peak_cell_temp_C, result.hottest_cell_index, ...
    result.peak_time_s);
fprintf('Peak cell-temperature spread: %.2f degC\n', ...
    result.peak_temperature_spread_C);
fprintf('Peak coolant outlet temperature: %.2f degC\n', ...
    result.peak_coolant_outlet_temp_C);
fprintf('Peak cell temperature at 3x flow: %.2f degC\n', ...
    highFlowResult.peak_cell_temp_C);
