function result = simulate_battery_module_cooling_network( ...
        profile, parameters, dt_s)
%SIMULATE_BATTERY_MODULE_COOLING_NETWORK Simulate a cooled cell string.
% The coolant path is quasi-steady within each time sample. Cell thermal
% masses evolve with explicit Euler integration.

if nargin < 3
    dt_s = [];
end

[profileTime_s, profileHeat_W, profileCoolantInlet_C] = ...
    validate_profile(profile);
validate_parameters(parameters);
parameters.cell_mass_kg = parameters.cell_mass_kg(:)';
parameters.cell_specific_heat_J_per_kgK = ...
    parameters.cell_specific_heat_J_per_kgK(:)';
parameters.initial_cell_temp_C = parameters.initial_cell_temp_C(:)';
parameters.cell_heat_fraction = parameters.cell_heat_fraction(:)';
parameters.cell_to_coolant_conductance_W_per_K = ...
    parameters.cell_to_coolant_conductance_W_per_K(:)';
parameters.cell_to_cell_conductance_W_per_K = ...
    parameters.cell_to_cell_conductance_W_per_K(:)';
if isempty(dt_s)
    time_s = profileTime_s;
    moduleHeat_W = profileHeat_W;
    coolantSupply_C = profileCoolantInlet_C;
else
    validate_time_step(dt_s, profileTime_s(end));
    time_s = (0:dt_s:profileTime_s(end))';
    moduleHeat_W = interp1( ...
        profileTime_s, profileHeat_W, time_s, 'previous', 'extrap');
    coolantSupply_C = interp1( ...
        profileTime_s, profileCoolantInlet_C, ...
        time_s, 'previous', 'extrap');
end

interval_s = diff(time_s);
cellCapacity_J_per_K = parameters.cell_mass_kg .* ...
    parameters.cell_specific_heat_J_per_kgK;
validate_explicit_euler_stability( ...
    interval_s, parameters, cellCapacity_J_per_K);

sampleCount = numel(time_s);
cellCount = parameters.cell_count;
cellTemp_C = zeros(sampleCount, cellCount);
cellHeat_W = zeros(sampleCount, cellCount);
coolantSegmentInlet_C = zeros(sampleCount, cellCount);
coolantSegmentOutlet_C = zeros(sampleCount, cellCount);
cellToCoolantHeat_W = zeros(sampleCount, cellCount);
cellConductionNetHeat_W = zeros(sampleCount, cellCount);
cellNetHeat_W = zeros(sampleCount, cellCount);

coolantCapacityRate_W_per_K = ...
    parameters.coolant_mass_flow_kg_per_s * ...
    parameters.coolant_specific_heat_J_per_kgK;
segmentEffectiveness = 1 - exp( ...
    -parameters.cell_to_coolant_conductance_W_per_K ./ ...
    coolantCapacityRate_W_per_K);
effectiveConductance_W_per_K = ...
    segmentEffectiveness * coolantCapacityRate_W_per_K;

cellTemp_C(1, :) = parameters.initial_cell_temp_C;
for intervalIndex = 1:numel(interval_s)
    [cellHeat_W(intervalIndex, :), ...
        coolantSegmentInlet_C(intervalIndex, :), ...
        coolantSegmentOutlet_C(intervalIndex, :), ...
        cellToCoolantHeat_W(intervalIndex, :), ...
        cellConductionNetHeat_W(intervalIndex, :)] = ...
        calculate_heat_flows( ...
            cellTemp_C(intervalIndex, :), ...
            moduleHeat_W(intervalIndex), ...
            coolantSupply_C(intervalIndex), ...
            parameters, effectiveConductance_W_per_K, ...
            coolantCapacityRate_W_per_K);

    cellNetHeat_W(intervalIndex, :) = ...
        cellHeat_W(intervalIndex, :) - ...
        cellToCoolantHeat_W(intervalIndex, :) + ...
        cellConductionNetHeat_W(intervalIndex, :);
    cellTemp_C(intervalIndex + 1, :) = ...
        cellTemp_C(intervalIndex, :) + ...
        interval_s(intervalIndex) * ...
        cellNetHeat_W(intervalIndex, :) ./ cellCapacity_J_per_K;
end

[cellHeat_W(end, :), coolantSegmentInlet_C(end, :), ...
    coolantSegmentOutlet_C(end, :), cellToCoolantHeat_W(end, :), ...
    cellConductionNetHeat_W(end, :)] = calculate_heat_flows( ...
        cellTemp_C(end, :), moduleHeat_W(end), ...
        coolantSupply_C(end), parameters, ...
        effectiveConductance_W_per_K, ...
        coolantCapacityRate_W_per_K);
cellNetHeat_W(end, :) = cellHeat_W(end, :) - ...
    cellToCoolantHeat_W(end, :) + ...
    cellConductionNetHeat_W(end, :);

allSignals = [cellTemp_C, cellHeat_W, coolantSegmentInlet_C, ...
    coolantSegmentOutlet_C, cellToCoolantHeat_W, ...
    cellConductionNetHeat_W, cellNetHeat_W];
if any(~isfinite(allSignals), 'all')
    error('BatteryModuleCooling:Numerics', ...
        'Every simulated temperature and heat-flow sample must be finite.');
end
if any(cellTemp_C <= -273.15, 'all') || ...
        any(coolantSegmentInlet_C <= -273.15, 'all') || ...
        any(coolantSegmentOutlet_C <= -273.15, 'all')
    error('BatteryModuleCooling:AbsoluteTemperature', ...
        'Simulated cell and coolant temperatures must exceed absolute zero.');
end

moduleCoolantHeatRemoval_W = sum(cellToCoolantHeat_W, 2);
moduleNetHeat_W = moduleHeat_W - moduleCoolantHeatRemoval_W;
temperatureSpread_C = ...
    max(cellTemp_C, [], 2) - min(cellTemp_C, [], 2);
coolantModuleOutlet_C = coolantSegmentOutlet_C(:, end);

cellEnergyChange_J = cellCapacity_J_per_K .* ...
    (cellTemp_C(end, :) - cellTemp_C(1, :));
integratedCellNetHeat_J = sum( ...
    cellNetHeat_W(1:end-1, :) .* interval_s, 1);
thermalEnergyChange_J = sum(cellEnergyChange_J);
integratedModuleNetHeat_J = sum( ...
    moduleNetHeat_W(1:end-1) .* interval_s);

[peakCellTemp_C, linearPeakIndex] = max(cellTemp_C, [], 'all');
[peakTimeIndex, hottestCellIndex] = ...
    ind2sub(size(cellTemp_C), linearPeakIndex);

result.time_s = time_s;
result.module_heat_generation_W = moduleHeat_W;
result.coolant_supply_temp_C = coolantSupply_C;
result.cell_temp_C = cellTemp_C;
result.cell_heat_generation_W = cellHeat_W;
result.coolant_segment_inlet_temp_C = coolantSegmentInlet_C;
result.coolant_segment_outlet_temp_C = coolantSegmentOutlet_C;
result.coolant_module_outlet_temp_C = coolantModuleOutlet_C;
result.cell_to_coolant_heat_W = cellToCoolantHeat_W;
result.cell_conduction_net_heat_W = cellConductionNetHeat_W;
result.cell_net_heat_W = cellNetHeat_W;
result.module_coolant_heat_removal_W = moduleCoolantHeatRemoval_W;
result.module_net_heat_W = moduleNetHeat_W;
result.cell_temperature_spread_C = temperatureSpread_C;
result.interval_s = interval_s;
result.cell_thermal_capacity_J_per_K = cellCapacity_J_per_K;
result.coolant_capacity_rate_W_per_K = coolantCapacityRate_W_per_K;
result.segment_effectiveness = segmentEffectiveness;
result.effective_conductance_W_per_K = ...
    effectiveConductance_W_per_K;
result.cell_energy_change_J = cellEnergyChange_J;
result.integrated_cell_net_heat_J = integratedCellNetHeat_J;
result.cell_energy_balance_error_J = ...
    cellEnergyChange_J - integratedCellNetHeat_J;
result.thermal_energy_change_J = thermalEnergyChange_J;
result.integrated_module_net_heat_J = integratedModuleNetHeat_J;
result.energy_balance_error_J = ...
    thermalEnergyChange_J - integratedModuleNetHeat_J;
result.peak_cell_temp_C = peakCellTemp_C;
result.peak_temperature_spread_C = max(temperatureSpread_C);
result.peak_coolant_outlet_temp_C = max(coolantModuleOutlet_C);
result.hottest_cell_index = hottestCellIndex;
result.peak_time_s = time_s(peakTimeIndex);
result.parameters = parameters;

uniformTolerance_s = 1e-12 * max(1, max(abs(interval_s)));
if max(abs(interval_s - interval_s(1))) <= uniformTolerance_s
    result.dt_s = interval_s(1);
else
    result.dt_s = [];
end
end

function [cellHeat_W, segmentInlet_C, segmentOutlet_C, ...
        cellToCoolantHeat_W, conductionNetHeat_W] = ...
        calculate_heat_flows(cellTemp_C, moduleHeat_W, ...
            coolantSupply_C, parameters, ...
            effectiveConductance_W_per_K, ...
            coolantCapacityRate_W_per_K)
cellHeat_W = moduleHeat_W * parameters.cell_heat_fraction;
cellCount = parameters.cell_count;
segmentInlet_C = zeros(1, cellCount);
segmentOutlet_C = zeros(1, cellCount);
cellToCoolantHeat_W = zeros(1, cellCount);

nextInlet_C = coolantSupply_C;
for cellIndex = 1:cellCount
    segmentInlet_C(cellIndex) = nextInlet_C;
    cellToCoolantHeat_W(cellIndex) = ...
        effectiveConductance_W_per_K(cellIndex) * ...
        (cellTemp_C(cellIndex) - nextInlet_C);
    segmentOutlet_C(cellIndex) = nextInlet_C + ...
        cellToCoolantHeat_W(cellIndex) / ...
        coolantCapacityRate_W_per_K;
    nextInlet_C = segmentOutlet_C(cellIndex);
end

interfaceHeat_W = ...
    parameters.cell_to_cell_conductance_W_per_K .* ...
    (cellTemp_C(1:end-1) - cellTemp_C(2:end));
conductionNetHeat_W = zeros(1, cellCount);
conductionNetHeat_W(1:end-1) = ...
    conductionNetHeat_W(1:end-1) - interfaceHeat_W;
conductionNetHeat_W(2:end) = ...
    conductionNetHeat_W(2:end) + interfaceHeat_W;
end

function [profileTime_s, profileHeat_W, profileCoolantInlet_C] = ...
        validate_profile(profile)
requiredVariables = {
    'time_s';
    'module_heat_generation_W';
    'coolant_inlet_temp_C'
};
if ~istable(profile) || ...
        ~all(ismember(requiredVariables, profile.Properties.VariableNames))
    error('BatteryModuleCooling:ProfileColumns', ...
        ['Profile must be a table containing time_s, ', ...
        'module_heat_generation_W, and coolant_inlet_temp_C.']);
end

profileVariables = {
    profile.time_s;
    profile.module_heat_generation_W;
    profile.coolant_inlet_temp_C
};
for variableIndex = 1:numel(profileVariables)
    variableValue = profileVariables{variableIndex};
    if ~isnumeric(variableValue) || ~isvector(variableValue) || ...
            ~isreal(variableValue) || numel(variableValue) < 2
        error('BatteryModuleCooling:ProfileShape', ...
            ['Profile columns must be real numeric vectors with ', ...
            'at least two rows.']);
    end
end

profileTime_s = profileVariables{1}(:);
profileHeat_W = profileVariables{2}(:);
profileCoolantInlet_C = profileVariables{3}(:);
profileSignals = ...
    [profileTime_s, profileHeat_W, profileCoolantInlet_C];
if any(~isfinite(profileSignals), 'all')
    error('BatteryModuleCooling:ProfileFinite', ...
        'Profile timestamps, heat, and coolant temperature must be finite.');
end
if abs(profileTime_s(1)) > 1e-12
    error('BatteryModuleCooling:ProfileStart', ...
        'Profile time_s must start at zero.');
end
if any(diff(profileTime_s) <= 0)
    error('BatteryModuleCooling:TimeOrder', ...
        'Profile timestamps must be strictly increasing.');
end
if any(profileHeat_W < 0)
    error('BatteryModuleCooling:ProfileHeat', ...
        'Module heat generation must be nonnegative.');
end
if any(profileCoolantInlet_C <= -273.15)
    error('BatteryModuleCooling:ProfileTemperature', ...
        'Coolant inlet temperature must exceed absolute zero.');
end
end

function validate_time_step(dt_s, profileEndTime_s)
if ~isnumeric(dt_s) || ~isscalar(dt_s) || ...
        ~isreal(dt_s) || ~isfinite(dt_s) || dt_s <= 0
    error('BatteryModuleCooling:TimeStep', ...
        'dt_s must be empty or a finite positive real scalar.');
end
intervalCount = round(profileEndTime_s / dt_s);
if intervalCount < 1 || ...
        abs(intervalCount * dt_s - profileEndTime_s) > 1e-9
    error('BatteryModuleCooling:TimeGrid', ...
        'Profile end time must be an integer multiple of dt_s.');
end
end

function validate_parameters(parameters)
requiredFields = {
    'cell_count';
    'cell_mass_kg';
    'cell_specific_heat_J_per_kgK';
    'initial_cell_temp_C';
    'cell_heat_fraction';
    'cell_to_coolant_conductance_W_per_K';
    'cell_to_cell_conductance_W_per_K';
    'coolant_mass_flow_kg_per_s';
    'coolant_specific_heat_J_per_kgK'
};
if ~isstruct(parameters) || ~all(isfield(parameters, requiredFields))
    error('BatteryModuleCooling:Parameters', ...
        'Parameter structure is missing one or more required fields.');
end
if ~isnumeric(parameters.cell_count) || ...
        ~isscalar(parameters.cell_count) || ...
        ~isreal(parameters.cell_count) || ...
        ~isfinite(parameters.cell_count) || ...
        parameters.cell_count < 2 || ...
        parameters.cell_count ~= round(parameters.cell_count)
    error('BatteryModuleCooling:Parameters', ...
        'cell_count must be an integer greater than or equal to two.');
end

cellCount = parameters.cell_count;
cellVectors = {
    parameters.cell_mass_kg, cellCount;
    parameters.cell_specific_heat_J_per_kgK, cellCount;
    parameters.initial_cell_temp_C, cellCount;
    parameters.cell_heat_fraction, cellCount;
    parameters.cell_to_coolant_conductance_W_per_K, cellCount;
    parameters.cell_to_cell_conductance_W_per_K, cellCount - 1
};
for vectorIndex = 1:size(cellVectors, 1)
    vectorValue = cellVectors{vectorIndex, 1};
    requiredLength = cellVectors{vectorIndex, 2};
    if ~isnumeric(vectorValue) || ~isvector(vectorValue) || ...
            ~isreal(vectorValue) || any(~isfinite(vectorValue)) || ...
            numel(vectorValue) ~= requiredLength
        error('BatteryModuleCooling:Parameters', ...
            'Every cell parameter vector must be finite and correctly sized.');
    end
end

scalarFields = {
    'coolant_mass_flow_kg_per_s';
    'coolant_specific_heat_J_per_kgK'
};
for scalarIndex = 1:numel(scalarFields)
    scalarValue = parameters.(scalarFields{scalarIndex});
    if ~isnumeric(scalarValue) || ~isscalar(scalarValue) || ...
            ~isreal(scalarValue) || ~isfinite(scalarValue) || ...
            scalarValue <= 0
        error('BatteryModuleCooling:Parameters', ...
            ['Coolant mass flow and specific heat must be ', ...
            'positive finite real scalars.']);
    end
end
if any(parameters.cell_mass_kg <= 0) || ...
        any(parameters.cell_specific_heat_J_per_kgK <= 0) || ...
        any(parameters.cell_to_coolant_conductance_W_per_K < 0) || ...
        any(parameters.cell_to_cell_conductance_W_per_K < 0)
    error('BatteryModuleCooling:Parameters', ...
        'Thermal masses must be positive and conductances nonnegative.');
end
if ~any(parameters.cell_to_coolant_conductance_W_per_K > 0)
    error('BatteryModuleCooling:Parameters', ...
        'At least one cell-to-coolant conductance must be positive.');
end
if any(parameters.initial_cell_temp_C <= -273.15)
    error('BatteryModuleCooling:Parameters', ...
        'Initial cell temperatures must exceed absolute zero.');
end
if any(parameters.cell_heat_fraction < 0) || ...
        abs(sum(parameters.cell_heat_fraction) - 1) > 1e-12
    error('BatteryModuleCooling:HeatFractions', ...
        'Cell heat fractions must be nonnegative and sum to one.');
end
end

function validate_explicit_euler_stability( ...
        interval_s, parameters, cellCapacity_J_per_K)
adjacentConductance_W_per_K = zeros( ...
    1, parameters.cell_count);
adjacentConductance_W_per_K(1:end-1) = ...
    adjacentConductance_W_per_K(1:end-1) + ...
    parameters.cell_to_cell_conductance_W_per_K;
adjacentConductance_W_per_K(2:end) = ...
    adjacentConductance_W_per_K(2:end) + ...
    parameters.cell_to_cell_conductance_W_per_K;
outflowBound_W_per_K = ...
    parameters.cell_to_coolant_conductance_W_per_K + ...
    adjacentConductance_W_per_K;
stabilityLimit_s = min( ...
    cellCapacity_J_per_K ./ outflowBound_W_per_K);
if any(interval_s >= stabilityLimit_s)
    error('BatteryModuleCooling:TimeStepStability', ...
        ['Every interval must satisfy the conservative explicit-Euler ', ...
        'thermal stability limit.']);
end
end
