%% Switching Buck Converter Check
% Validates PWM timing, exact state propagation, averages, and ripple.

clearvars; clc;

modelDirectory = fileparts(mfilename('fullpath'));
addpath(modelDirectory);

parameters = switching_buck_default_parameters();
result = simulate_switching_buck_converter(parameters);
metrics = summarize_switching_buck_converter(result, 50);

expectedIntervalCount = parameters.end_time_s * ...
    parameters.switching_frequency_Hz * ...
    parameters.steps_per_switching_period;
assert(numel(result.switch_state) == expectedIntervalCount && ...
    numel(result.time_s) == expectedIntervalCount + 1, ...
    'State and PWM grids must cover every switching interval.');
assert(all(isfinite(result.inductor_current_A)) && ...
    all(isfinite(result.output_voltage_V)) && ...
    all(isfinite(result.inductor_voltage_V)), ...
    'All converter states and interval voltages must remain finite.');
assert(islogical(result.switch_state), ...
    'Switch state must remain a logical PWM trace.');

switchPeriods = reshape(result.switch_state, ...
    parameters.steps_per_switching_period, []);
assert(all(sum(switchPeriods, 1) == result.on_steps_per_period), ...
    'Every PWM period must contain the configured number of ON steps.');
assert(abs(metrics.measured_duty_cycle - parameters.duty_cycle) < 1e-14, ...
    'Measured steady-window duty cycle must match the command.');

assert(abs(metrics.average_output_voltage_V - ...
    metrics.expected_average_voltage_V) < 0.01, ...
    'Average switched output must match the lossy averaged buck solution.');
assert(abs(metrics.average_inductor_current_A - ...
    metrics.expected_average_current_A) < 0.001, ...
    'Average inductor current must match the resistive-load solution.');
assert(abs(metrics.inductor_current_ripple_A - ...
    metrics.expected_current_ripple_A) < 0.01, ...
    'Current ripple must match the continuous-conduction estimate.');
assert(abs(metrics.output_voltage_ripple_V - ...
    metrics.expected_voltage_ripple_V) < 0.002, ...
    'Voltage ripple must match the triangular-current estimate.');
assert(metrics.inductor_current_ripple_A > 0 && ...
    metrics.output_voltage_ripple_V > 0, ...
    'The switched model must preserve nonzero current and voltage ripple.');
assert(abs(metrics.mean_inductor_voltage_V) < 0.001 && ...
    abs(metrics.mean_capacitor_current_A) < 0.001, ...
    'Settled inductor volt-second and capacitor charge balances must close.');
assert(abs(metrics.inductor_current_change_A) < 0.001 && ...
    abs(metrics.output_voltage_change_V) < 0.001, ...
    'Settled state drift across the final whole-period window is too large.');

fineParameters = parameters;
fineParameters.steps_per_switching_period = 200;
fineResult = simulate_switching_buck_converter(fineParameters);
fineMetrics = summarize_switching_buck_converter(fineResult, 50);
assert(abs(fineMetrics.average_output_voltage_V - ...
    metrics.average_output_voltage_V) < 1e-5 && ...
    abs(fineMetrics.average_inductor_current_A - ...
    metrics.average_inductor_current_A) < 1e-5 && ...
    abs(fineMetrics.inductor_current_ripple_A - ...
    metrics.inductor_current_ripple_A) < 1e-6 && ...
    abs(fineMetrics.output_voltage_ripple_V - ...
    metrics.output_voltage_ripple_V) < 1e-3, ...
    'Steady metrics must converge when the PWM sampling grid is doubled.');

invalidParameters = parameters;
invalidParameters.inductance_H = 0;
invalidComponentRejected = false;
try
    simulate_switching_buck_converter(invalidParameters);
catch validationError
    invalidComponentRejected = strcmp(validationError.identifier, ...
        'SwitchingBuck:Parameters');
end
assert(invalidComponentRejected, ...
    'Simulator must reject nonpositive electrical components.');

invalidParameters = parameters;
invalidParameters.input_voltage_V = 800 + 1i;
complexParameterRejected = false;
try
    simulate_switching_buck_converter(invalidParameters);
catch validationError
    complexParameterRejected = strcmp(validationError.identifier, ...
        'SwitchingBuck:Parameters');
end
assert(complexParameterRejected, ...
    'Simulator must reject complex-valued scalar parameters.');

invalidParameters = parameters;
invalidParameters.duty_cycle = 0.455;
unalignedDutyRejected = false;
try
    simulate_switching_buck_converter(invalidParameters);
catch validationError
    unalignedDutyRejected = strcmp(validationError.identifier, ...
        'SwitchingBuck:TimeGrid');
end
assert(unalignedDutyRejected, ...
    'Simulator must reject a duty edge that is not aligned to the time grid.');

invalidParameters = parameters;
invalidParameters.end_time_s = 0.30005;
partialPeriodRejected = false;
try
    simulate_switching_buck_converter(invalidParameters);
catch validationError
    partialPeriodRejected = strcmp(validationError.identifier, ...
        'SwitchingBuck:TimeGrid');
end
assert(partialPeriodRejected, ...
    'Simulator must reject a duration containing a partial PWM period.');

invalidParameters = rmfield(parameters, 'capacitance_F');
missingFieldRejected = false;
try
    simulate_switching_buck_converter(invalidParameters);
catch validationError
    missingFieldRejected = strcmp(validationError.identifier, ...
        'SwitchingBuck:Parameters');
end
assert(missingFieldRejected, ...
    'Simulator must reject a missing required parameter.');

fprintf('Switching buck converter check passed.\n');
fprintf('Average output voltage: %.3f V\n', ...
    metrics.average_output_voltage_V);
fprintf('Average inductor current: %.3f A\n', ...
    metrics.average_inductor_current_A);
fprintf('Current ripple: %.3f A peak-to-peak\n', ...
    metrics.inductor_current_ripple_A);
fprintf('Voltage ripple: %.3f V peak-to-peak\n', ...
    metrics.output_voltage_ripple_V);
fprintf('Measured duty cycle: %.3f\n', metrics.measured_duty_cycle);
