function metrics = summarize_switching_buck_converter(result, windowPeriods)
%SUMMARIZE_SWITCHING_BUCK_CONVERTER Summarize a settled whole-period window.

if nargin < 2
    windowPeriods = 50;
end
if ~isnumeric(windowPeriods) || ~isscalar(windowPeriods) || ...
        ~isfinite(windowPeriods) || windowPeriods ~= round(windowPeriods) || ...
        windowPeriods <= 0 || windowPeriods > result.period_count
    error('SwitchingBuck:Window', ...
        'Window periods must be a positive integer within the simulation.');
end

parameters = result.parameters;
windowIntervalCount = windowPeriods * ...
    parameters.steps_per_switching_period;
firstInterval = numel(result.switch_state) - windowIntervalCount + 1;
intervalIndices = firstInterval:numel(result.switch_state);
stateIndices = firstInterval:(firstInterval + windowIntervalCount - 1);

windowInductorCurrent_A = result.inductor_current_A(stateIndices);
windowOutputVoltage_V = result.output_voltage_V(stateIndices);
windowCapacitorCurrent_A = result.capacitor_current_A(stateIndices);
windowSwitchState = result.switch_state(intervalIndices);

expectedAverageVoltage_V = parameters.duty_cycle * ...
    parameters.input_voltage_V / ...
    (1 + parameters.inductor_resistance_Ohm / ...
    parameters.load_resistance_Ohm);
expectedAverageCurrent_A = expectedAverageVoltage_V / ...
    parameters.load_resistance_Ohm;
expectedOnInductorVoltage_V = parameters.input_voltage_V - ...
    expectedAverageVoltage_V - parameters.inductor_resistance_Ohm * ...
    expectedAverageCurrent_A;
expectedCurrentRipple_A = expectedOnInductorVoltage_V * ...
    parameters.duty_cycle * result.switching_period_s / ...
    parameters.inductance_H;
expectedVoltageRipple_V = expectedCurrentRipple_A / ...
    (8 * parameters.switching_frequency_Hz * parameters.capacitance_F);

metrics.window_periods = windowPeriods;
metrics.window_start_time_s = result.interval_start_time_s(firstInterval);
metrics.average_output_voltage_V = mean(windowOutputVoltage_V);
metrics.average_inductor_current_A = mean(windowInductorCurrent_A);
metrics.inductor_current_ripple_A = max(windowInductorCurrent_A) - ...
    min(windowInductorCurrent_A);
metrics.output_voltage_ripple_V = max(windowOutputVoltage_V) - ...
    min(windowOutputVoltage_V);
metrics.measured_duty_cycle = mean(windowSwitchState);
metrics.mean_inductor_voltage_V = mean(...
    result.inductor_voltage_V(intervalIndices));
metrics.mean_capacitor_current_A = mean(windowCapacitorCurrent_A);
metrics.inductor_current_change_A = ...
    result.inductor_current_A(firstInterval + windowIntervalCount) - ...
    result.inductor_current_A(firstInterval);
metrics.output_voltage_change_V = ...
    result.output_voltage_V(firstInterval + windowIntervalCount) - ...
    result.output_voltage_V(firstInterval);
metrics.expected_average_voltage_V = expectedAverageVoltage_V;
metrics.expected_average_current_A = expectedAverageCurrent_A;
metrics.expected_current_ripple_A = expectedCurrentRipple_A;
metrics.expected_voltage_ripple_V = expectedVoltageRipple_V;
end
