function manifest = build_validation_manifest(report, sourceCommit)
%BUILD_VALIDATION_MANIFEST Build deterministic commit-bound validation data.

arguments
    report (1, 1) struct
    sourceCommit (1, 1) string
end

sourceCommit = lower(sourceCommit);
isCommit = ~isempty(regexp(sourceCommit, '^[0-9a-f]{40}$', 'once'));
if sourceCommit ~= "worktree" && ~isCommit
    error('ValidationManifest:SourceCommit', ...
        'Source commit must be a 40-character Git SHA or WORKTREE.');
end
requiredFields = ["suite", "check_count", "all_checks_passed", "checks"];
if ~all(isfield(report, cellstr(requiredFields))) || ...
        ~report.all_checks_passed || report.check_count ~= numel(report.checks)
    error('ValidationManifest:Report', ...
        'Report must describe a complete passing check run.');
end
statuses = string({report.checks.status});
if any(statuses ~= "passed")
    error('ValidationManifest:Status', ...
        'Every reported check must have passed.');
end

manifest.schema_version = "1.0.0";
manifest.source_commit = sourceCommit;
manifest.matlab_release = "R" + string(version('-release'));
manifest.matlab_version = string(version);
manifest.required_products = ["MATLAB", "Simulink"];
manifest.suite = string(report.suite);
manifest.status = "passed";
manifest.check_count = report.check_count;
manifest.checks = report.checks;
manifest.related_evidence.human_readable_results = ...
    "docs/validation-results.md";
manifest.related_evidence.unified_bess_schema_example = ...
    "examples/bess-unified-control/validation/results.json";
manifest.related_evidence.unified_bess_note = ...
    "Exact-commit BESS results are regenerated by the separate validate-bess CI job.";
manifest.claim_boundaries = [
    "Deterministic regression evidence for reduced-order educational models.";
    "Not physical-cell, hardware, safety, or grid-code qualification.";
    "The two-RC identification benchmark uses synthetic voltage records.";
    "A passing manifest describes only the exact source_commit and environment above."
];
end
