%% Generate Repository Social Preview
% Builds a 1280-by-640 social card from the validated two-RC fit benchmark.

generate_preview();

function generate_preview()
repoRoot = fileparts(fileparts(mfilename('fullpath')));
fitModelDir = fullfile(repoRoot, 'examples', 'battery-2rc-model');
addpath(fitModelDir);
pathCleanup = onCleanup(@() rmpath(fitModelDir));

scenario = build_battery_2rc_fit_scenario();
fitResult = fit_battery_2rc_parameters( ...
    scenario.calibration_data, scenario.initial_parameters);
calibrationEvaluation = evaluate_battery_2rc_fit( ...
    scenario.calibration_data, fitResult.parameters);
validationEvaluation = evaluate_battery_2rc_fit( ...
    scenario.validation_data, fitResult.parameters);

backgroundColor = [0.965, 0.976, 0.988];
navyColor = [0.090, 0.125, 0.200];
tealColor = [0.000, 0.440, 0.500];
orangeColor = [0.910, 0.360, 0.120];
purpleColor = [0.420, 0.230, 0.690];
mutedColor = [0.280, 0.340, 0.430];
gridColor = [0.810, 0.850, 0.900];

figureHandle = figure( ...
    'Visible', 'off', ...
    'Color', backgroundColor, ...
    'Units', 'inches', ...
    'Position', [1, 1, 12.8, 6.4], ...
    'PaperUnits', 'inches', ...
    'PaperPosition', [0, 0, 12.8, 6.4], ...
    'PaperSize', [12.8, 6.4]);
figureCleanup = onCleanup(@() close(figureHandle));

annotation(figureHandle, 'textbox', [0.055, 0.875, 0.285, 0.055], ...
    'String', 'OPEN-SOURCE BATTERY AND POWER MODELS', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'Color', [1, 1, 1], ...
    'BackgroundColor', tealColor, ...
    'EdgeColor', 'none', ...
    'FitBoxToText', 'off', ...
    'Interpreter', 'none');

annotation(figureHandle, 'textbox', [0.055, 0.700, 0.410, 0.155], ...
    'String', sprintf('MATLAB Simulink\nEnergy Lab'), ...
    'FontName', 'Arial', ...
    'FontSize', 34, ...
    'FontWeight', 'bold', ...
    'Color', navyColor, ...
    'EdgeColor', 'none', ...
    'FitBoxToText', 'off', ...
    'Interpreter', 'none');

annotation(figureHandle, 'textbox', [0.058, 0.550, 0.390, 0.130], ...
    'String', sprintf([ ...
        'Inspectable MATLAB and Simulink references\n' ...
        'from dynamic simulation to held-out validation.']), ...
    'FontName', 'Arial', ...
    'FontSize', 16, ...
    'Color', mutedColor, ...
    'EdgeColor', 'none', ...
    'FitBoxToText', 'off', ...
    'Interpreter', 'none');

annotation(figureHandle, 'line', [0.058, 0.440], [0.490, 0.490], ...
    'Color', gridColor, ...
    'LineWidth', 1.2);

annotation(figureHandle, 'textbox', [0.058, 0.365, 0.390, 0.100], ...
    'String', sprintf([ ...
        'BATTERY RC   |   SOC EKF   |   2RC FIT\n' ...
        'MATLAB R2026a   |   16 CHECKS   |   v0.7.0']), ...
    'FontName', 'Arial', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'Color', navyColor, ...
    'EdgeColor', 'none', ...
    'FitBoxToText', 'off', ...
    'Interpreter', 'none');

annotation(figureHandle, 'textbox', [0.058, 0.195, 0.370, 0.165], ...
    'String', sprintf([ ...
        'Validated, MIT-licensed references for:\n' ...
        '  - battery dynamics and state estimation\n' ...
        '  - toolbox-free parameter identification\n' ...
        '  - thermal and power-converter studies']), ...
    'FontName', 'Arial', ...
    'FontSize', 12, ...
    'Color', mutedColor, ...
    'EdgeColor', 'none', ...
    'FitBoxToText', 'off', ...
    'Interpreter', 'none');

annotation(figureHandle, 'textbox', [0.058, 0.070, 0.390, 0.055], ...
    'String', 'github.com/mohammadrezwankhan/matlab-simulink-energy-lab', ...
    'FontName', 'Arial', ...
    'FontSize', 9, ...
    'Color', tealColor, ...
    'EdgeColor', 'none', ...
    'FitBoxToText', 'off', ...
    'Interpreter', 'none');

annotation(figureHandle, 'line', [0.485, 0.485], [0.080, 0.920], ...
    'Color', gridColor, ...
    'LineWidth', 1.2);

calibrationAxes = axes(figureHandle, ...
    'Position', [0.545, 0.555, 0.405, 0.325]);
plot(calibrationAxes, scenario.calibration_data.time_s, ...
    scenario.calibration_data.terminal_voltage_V, ...
    'Color', tealColor, ...
    'LineWidth', 1.8);
hold(calibrationAxes, 'on');
plot(calibrationAxes, scenario.calibration_data.time_s, ...
    calibrationEvaluation.predicted_terminal_voltage_V, ...
    '--', ...
    'Color', orangeColor, ...
    'LineWidth', 1.8);
hold(calibrationAxes, 'off');
configure_axes(calibrationAxes, navyColor, gridColor);
xlim(calibrationAxes, [0, scenario.calibration_data.time_s(end)]);
ylabel(calibrationAxes, 'Voltage [V]');
title(calibrationAxes, sprintf('Calibration fit (%.3f mV RMSE)', ...
    1000*calibrationEvaluation.metrics.rmse_V), ...
    'Color', navyColor, ...
    'FontWeight', 'bold');
legend(calibrationAxes, {'Synthetic measurement', 'Fitted model'}, ...
    'Location', 'southwest', ...
    'Box', 'off');

validationAxes = axes(figureHandle, ...
    'Position', [0.545, 0.135, 0.405, 0.325]);
plot(validationAxes, scenario.validation_data.time_s, ...
    scenario.validation_data.terminal_voltage_V, ...
    'Color', tealColor, ...
    'LineWidth', 1.8);
hold(validationAxes, 'on');
plot(validationAxes, scenario.validation_data.time_s, ...
    validationEvaluation.predicted_terminal_voltage_V, ...
    '--', ...
    'Color', purpleColor, ...
    'LineWidth', 1.8);
hold(validationAxes, 'off');
configure_axes(validationAxes, navyColor, gridColor);
xlim(validationAxes, [0, scenario.validation_data.time_s(end)]);
xlabel(validationAxes, 'Time [s]');
ylabel(validationAxes, 'Voltage [V]');
title(validationAxes, sprintf('Held-out profile (%.3f mV RMSE)', ...
    1000*validationEvaluation.metrics.rmse_V), ...
    'Color', navyColor, ...
    'FontWeight', 'bold');
legend(validationAxes, {'Synthetic measurement', 'Fitted model'}, ...
    'Location', 'southwest', ...
    'Box', 'off');

outputPath = fullfile(repoRoot, 'assets', 'social-preview.png');
print(figureHandle, outputPath, '-dpng', '-r100');

imageInfo = imfinfo(outputPath);
assert(imageInfo.Width == 1280 && imageInfo.Height == 640, ...
    'SocialPreview:Dimensions', ...
    'Expected a 1280-by-640 social preview.');
assert(imageInfo.FileSize < 1e6, ...
    'SocialPreview:FileSize', ...
    'Social preview must remain smaller than 1 MB.');

fprintf('Generated %s (%d x %d, %.1f kB).\n', ...
    outputPath, imageInfo.Width, imageInfo.Height, ...
    imageInfo.FileSize / 1024);
end

function configure_axes(axesHandle, textColor, axesGridColor)
axesHandle.Color = [1, 1, 1];
axesHandle.XColor = textColor;
axesHandle.YColor = textColor;
axesHandle.GridColor = axesGridColor;
axesHandle.GridAlpha = 0.9;
axesHandle.FontName = 'Arial';
axesHandle.FontSize = 10;
axesHandle.LineWidth = 0.9;
axesHandle.Box = 'off';
axesHandle.XGrid = 'on';
axesHandle.YGrid = 'on';
end
