%% Generate Repository Social Preview
% Builds a 1280-by-640 social card from the validated pouch-cell model.

generate_preview();

function generate_preview()
repoRoot = fileparts(fileparts(mfilename('fullpath')));
pouchModelDir = fullfile( ...
    repoRoot, 'examples', 'pouch-cell-thermal-gradient');
addpath(pouchModelDir);
pathCleanup = onCleanup(@() rmpath(pouchModelDir));

parameters = pouch_cell_thermal_default_parameters();
profile = pouch_cell_thermal_default_profile();
result = simulate_pouch_cell_thermal_model(profile, parameters, 0.5);

backgroundColor = [0.965, 0.976, 0.988];
navyColor = [0.090, 0.125, 0.200];
tealColor = [0.000, 0.440, 0.500];
orangeColor = [0.910, 0.360, 0.120];
purpleColor = [0.420, 0.230, 0.690];
mutedColor = [0.280, 0.340, 0.430];
gridColor = [0.810, 0.850, 0.900];

figureHandle = figure( ...
    'Visible', 'off', ...
    'Color', backgroundColor, ...
    'Units', 'inches', ...
    'Position', [1, 1, 12.8, 6.4], ...
    'PaperUnits', 'inches', ...
    'PaperPosition', [0, 0, 12.8, 6.4], ...
    'PaperSize', [12.8, 6.4]);
figureCleanup = onCleanup(@() close(figureHandle));

annotation(figureHandle, 'textbox', [0.055, 0.875, 0.285, 0.055], ...
    'String', 'OPEN-SOURCE BATTERY AND POWER MODELS', ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'Color', [1, 1, 1], ...
    'BackgroundColor', tealColor, ...
    'EdgeColor', 'none', ...
    'FitBoxToText', 'off', ...
    'Interpreter', 'none');

annotation(figureHandle, 'textbox', [0.055, 0.700, 0.410, 0.155], ...
    'String', sprintf('MATLAB Simulink\nEnergy Lab'), ...
    'FontName', 'Arial', ...
    'FontSize', 34, ...
    'FontWeight', 'bold', ...
    'Color', navyColor, ...
    'EdgeColor', 'none', ...
    'FitBoxToText', 'off', ...
    'Interpreter', 'none');

annotation(figureHandle, 'textbox', [0.058, 0.550, 0.390, 0.130], ...
    'String', sprintf([ ...
        'Inspectable MATLAB and Simulink references\n' ...
        'from electrical dynamics to spatial thermal evidence.']), ...
    'FontName', 'Arial', ...
    'FontSize', 16, ...
    'Color', mutedColor, ...
    'EdgeColor', 'none', ...
    'FitBoxToText', 'off', ...
    'Interpreter', 'none');

annotation(figureHandle, 'line', [0.058, 0.440], [0.490, 0.490], ...
    'Color', gridColor, ...
    'LineWidth', 1.2);

annotation(figureHandle, 'textbox', [0.058, 0.365, 0.390, 0.100], ...
    'String', sprintf([ ...
        'BATTERY RC   |   SOC EKF   |   SPATIAL THERMAL\n' ...
        'MATLAB R2026a   |   15 CHECKS   |   v0.6.0']), ...
    'FontName', 'Arial', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'Color', navyColor, ...
    'EdgeColor', 'none', ...
    'FitBoxToText', 'off', ...
    'Interpreter', 'none');

annotation(figureHandle, 'textbox', [0.058, 0.195, 0.370, 0.165], ...
    'String', sprintf([ ...
        'Validated, MIT-licensed references for:\n' ...
        '  - battery dynamics and state estimation\n' ...
        '  - pouch-cell through-thickness gradients\n' ...
        '  - cooling and power-converter studies']), ...
    'FontName', 'Arial', ...
    'FontSize', 12, ...
    'Color', mutedColor, ...
    'EdgeColor', 'none', ...
    'FitBoxToText', 'off', ...
    'Interpreter', 'none');

annotation(figureHandle, 'textbox', [0.058, 0.070, 0.390, 0.055], ...
    'String', 'github.com/mohammadrezwankhan/matlab-simulink-energy-lab', ...
    'FontName', 'Arial', ...
    'FontSize', 9, ...
    'Color', tealColor, ...
    'EdgeColor', 'none', ...
    'FitBoxToText', 'off', ...
    'Interpreter', 'none');

annotation(figureHandle, 'line', [0.485, 0.485], [0.080, 0.920], ...
    'Color', gridColor, ...
    'LineWidth', 1.2);

time_min = result.time_s / 60;

temperatureAxes = axes(figureHandle, ...
    'Position', [0.545, 0.555, 0.405, 0.325]);
plot(temperatureAxes, time_min, result.center_temperature_C, ...
    'Color', orangeColor, ...
    'LineWidth', 2.3);
hold(temperatureAxes, 'on');
plot(temperatureAxes, time_min, result.left_surface_temperature_C, ...
    'Color', tealColor, ...
    'LineWidth', 1.8);
plot(temperatureAxes, time_min, result.right_surface_temperature_C, ...
    'Color', purpleColor, ...
    'LineWidth', 1.8);
plot(temperatureAxes, time_min, result.volume_average_temperature_C, ...
    '--', ...
    'Color', mutedColor, ...
    'LineWidth', 1.2);
hold(temperatureAxes, 'off');
configure_axes(temperatureAxes, navyColor, gridColor);
xlim(temperatureAxes, [0, 50]);
ylabel(temperatureAxes, 'Temperature [degC]');
title(temperatureAxes, 'Pouch-cell temperature response', ...
    'Color', navyColor, ...
    'FontWeight', 'bold');
legend(temperatureAxes, {'Center', 'Left surface', ...
    'Right surface', 'Volume average'}, ...
    'Location', 'northeast', ...
    'Box', 'off');

profileAxes = axes(figureHandle, ...
    'Position', [0.545, 0.135, 0.405, 0.325]);
peakTimeIndex = find(result.time_s == result.peak_time_s, 1);
position_mm = 1000 * result.node_position_m;
plot(profileAxes, position_mm, ...
    result.node_temperature_C(peakTimeIndex, :), ...
    'o-', ...
    'Color', orangeColor, ...
    'MarkerFaceColor', backgroundColor, ...
    'LineWidth', 2.2);
hold(profileAxes, 'on');
plot(profileAxes, position_mm, ...
    result.node_temperature_C(end, :), ...
    's--', ...
    'Color', tealColor, ...
    'MarkerFaceColor', backgroundColor, ...
    'LineWidth', 1.8);
hold(profileAxes, 'off');
configure_axes(profileAxes, navyColor, gridColor);
xlabel(profileAxes, 'Through-thickness position [mm]');
ylabel(profileAxes, 'Temperature [degC]');
title(profileAxes, 'Resolved through-thickness gradient', ...
    'Color', navyColor, ...
    'FontWeight', 'bold');
legend(profileAxes, {'Peak temperature', 'Final state'}, ...
    'Location', 'southwest', ...
    'Box', 'off');

outputPath = fullfile(repoRoot, 'assets', 'social-preview.png');
print(figureHandle, outputPath, '-dpng', '-r100');

imageInfo = imfinfo(outputPath);
assert(imageInfo.Width == 1280 && imageInfo.Height == 640, ...
    'SocialPreview:Dimensions', ...
    'Expected a 1280-by-640 social preview.');
assert(imageInfo.FileSize < 1e6, ...
    'SocialPreview:FileSize', ...
    'Social preview must remain smaller than 1 MB.');

fprintf('Generated %s (%d x %d, %.1f kB).\n', ...
    outputPath, imageInfo.Width, imageInfo.Height, ...
    imageInfo.FileSize / 1024);
end

function configure_axes(axesHandle, textColor, axesGridColor)
axesHandle.Color = [1, 1, 1];
axesHandle.XColor = textColor;
axesHandle.YColor = textColor;
axesHandle.GridColor = axesGridColor;
axesHandle.GridAlpha = 0.9;
axesHandle.FontName = 'Arial';
axesHandle.FontSize = 10;
axesHandle.LineWidth = 0.9;
axesHandle.Box = 'off';
axesHandle.XGrid = 'on';
axesHandle.YGrid = 'on';
end
