clear;
close all;
clc;

modelDirectory = fileparts(mfilename('fullpath'));
examplesDirectory = fileparts(modelDirectory);
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory, fullfile(examplesDirectory, 'battery-soc-ekf'));

result = simulate_battery_soc_hysteresis_ekf_example();
estimate = result.hysteresis_estimate;
truth = result.truth;
metrics = result.metrics;
sampleCount = numel(truth.time_s);

assert(numel(estimate.soc) == sampleCount && ...
    numel(estimate.hysteresis_state) == sampleCount, ...
    'Every estimate must align with the measurement grid.');
assert(all(isfinite(estimate.soc)) && ...
    all(isfinite(estimate.v_rc_V)) && ...
    all(isfinite(estimate.hysteresis_state)) && ...
    all(isfinite(estimate.terminal_voltage_V)), ...
    'All estimator outputs must remain finite.');
assert(all(estimate.soc >= 0 & estimate.soc <= 1), ...
    'Estimated SOC must remain within [0, 1].');
assert(all(abs(estimate.hysteresis_state) <= 1), ...
    'Estimated hysteresis state must remain within [-1, 1].');
for sampleIndex = 1:sampleCount
    covariance = estimate.covariance(:, :, sampleIndex);
    assert(max(abs(covariance - covariance'), [], 'all') < 1e-12, ...
        'Joseph-form covariance must remain symmetric.');
    assert(min(eig(covariance)) >= -1e-12, ...
        'Joseph-form covariance must remain positive semidefinite.');
end
assert(metrics.hysteresis_soc_rmse < metrics.baseline_soc_rmse, ...
    'Hysteresis-aware SOC RMSE must improve on the two-state baseline.');
assert(metrics.hysteresis_voltage_rmse_V < metrics.baseline_voltage_rmse_V, ...
    'Hysteresis-aware voltage RMSE must improve on the baseline.');
assert(metrics.hysteresis_soc_rmse < 0.04, ...
    'Hysteresis-aware SOC RMSE exceeds the educational limit.');
assert(metrics.hysteresis_state_rmse < 0.35, ...
    'Hysteresis-state RMSE exceeds the educational limit.');

repeatResult = simulate_battery_soc_hysteresis_ekf_example();
assert(isequal(result.measured_voltage_V, repeatResult.measured_voltage_V) && ...
    isequal(estimate.soc, repeatResult.hysteresis_estimate.soc), ...
    'The benchmark and estimator must be deterministic.');

irregularIndices = unique([1; (2:3:1200)'; (1202:5:2400)'; ...
    (2402:7:sampleCount)'; sampleCount]);
irregularEstimate = estimate_battery_soc_hysteresis_ekf( ...
    truth.time_s(irregularIndices), truth.current_A(irregularIndices), ...
    result.measured_voltage_V(irregularIndices), estimate.parameters, ...
    estimate.options);
assert(all(isfinite(irregularEstimate.soc)) && ...
    all(abs(irregularEstimate.hysteresis_state) <= 1), ...
    'The estimator must support a strictly increasing irregular time grid.');

zeroHysteresisParameters = estimate.parameters;
zeroHysteresisParameters.hysteresis_max_V = 0;
voltageWithoutHysteresis_V = result.measured_voltage_V - ...
    truth.hysteresis_voltage_V;
zeroHysteresisEstimate = estimate_battery_soc_hysteresis_ekf( ...
    truth.time_s, truth.current_A, voltageWithoutHysteresis_V, ...
    zeroHysteresisParameters, estimate.options);
baselineZeroHysteresis = estimate_battery_soc_ekf( ...
    truth.time_s, truth.current_A, voltageWithoutHysteresis_V, ...
    zeroHysteresisParameters, result.baseline_estimate.options);
assert(max(abs(zeroHysteresisEstimate.soc - ...
    baselineZeroHysteresis.soc)) < 1e-12, ...
    'Zero hysteresis magnitude must reduce to the two-state SOC result.');

badOptions = estimate.options;
badOptions.initial_state = [0.5; 0; 1.1];
assert_error(@() estimate_battery_soc_hysteresis_ekf( ...
    [0; 1], [0; 0], [3.7; 3.7], estimate.parameters, badOptions), ...
    'BatterySOCHysteresisEKF:Options');
badOptions = estimate.options;
badOptions.initial_covariance = eye(2);
assert_error(@() estimate_battery_soc_hysteresis_ekf( ...
    [0; 1], [0; 0], [3.7; 3.7], estimate.parameters, badOptions), ...
    'BatterySOCHysteresisEKF:Covariance');
badParameters = estimate.parameters;
badParameters.hysteresis_max_V = -0.01;
assert_error(@() estimate_battery_soc_hysteresis_ekf( ...
    [0; 1], [0; 0], [3.7; 3.7], badParameters, estimate.options), ...
    'BatterySOCHysteresisEKF:Parameters');

fprintf('Battery SOC hysteresis EKF check passed.\n');
fprintf('SOC RMSE: hysteresis %.4f, baseline %.4f\n', ...
    metrics.hysteresis_soc_rmse, metrics.baseline_soc_rmse);
fprintf('Final SOC error: hysteresis %+.4f, baseline %+.4f\n', ...
    metrics.hysteresis_final_soc_error, metrics.baseline_final_soc_error);
fprintf('Hysteresis-state RMSE: %.4f\n', metrics.hysteresis_state_rmse);
fprintf('Voltage RMSE: hysteresis %.3f mV, baseline %.3f mV\n', ...
    1000*metrics.hysteresis_voltage_rmse_V, ...
    1000*metrics.baseline_voltage_rmse_V);

function assert_error(functionHandle, expectedIdentifier)
try
    functionHandle();
catch errorDetails
    assert(strcmp(errorDetails.identifier, expectedIdentifier), ...
        'Expected error %s but received %s.', ...
        expectedIdentifier, errorDetails.identifier);
    return;
end
error('BatterySOCHysteresisEKF:MissingError', ...
    'Expected error %s was not raised.', expectedIdentifier);
end
