clear;
close all;
clc;

modelDirectory = fileparts(mfilename('fullpath'));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory);

result = simulate_battery_soc_ekf_example();
estimate = result.estimate;
truth = result.truth;
metrics = result.metrics;

signalCount = numel(truth.time_s);
assert(numel(estimate.soc) == signalCount && ...
    numel(estimate.v_rc_V) == signalCount && ...
    numel(estimate.innovation_V) == signalCount, ...
    'Every EKF output must align with the measurement grid.');
assert(all(isfinite(estimate.soc)) && ...
    all(isfinite(estimate.v_rc_V)) && ...
    all(isfinite(estimate.terminal_voltage_V)) && ...
    all(isfinite(estimate.innovation_V)), ...
    'EKF signals must remain finite.');
assert(all(estimate.soc >= 0 & estimate.soc <= 1), ...
    'Estimated SOC must remain within [0, 1].');
assert(abs(metrics.final_soc_error) < 0.02, ...
    'Final SOC error must be below two percentage points.');
assert(metrics.soc_rmse < 0.035, ...
    'SOC RMSE must remain below the educational benchmark limit.');
assert(metrics.soc_settling_time_s < 1500, ...
    'SOC error must enter and remain inside two percentage points.');
assert(abs(metrics.final_soc_error) < ...
    0.15 * abs(metrics.initial_prior_soc_error), ...
    'Voltage correction must materially reduce the initial SOC bias.');
assert(metrics.voltage_rmse_V < 0.006, ...
    'Posterior terminal-voltage RMSE must remain below 6 mV.');
assert(all(estimate.innovation_variance_V2 > 0), ...
    'Innovation variance must remain positive.');

for sampleIndex = 1:signalCount
    covariance = estimate.covariance(:, :, sampleIndex);
    assert(max(abs(covariance - covariance'), [], 'all') < 1e-12, ...
        'Joseph-form covariance must remain symmetric.');
    assert(min(eig(covariance)) >= -1e-12, ...
        'Joseph-form covariance must remain positive semidefinite.');
end

repeatResult = simulate_battery_soc_ekf_example();
assert(isequal(result.measured_voltage_V, ...
    repeatResult.measured_voltage_V) && ...
    isequal(estimate.soc, repeatResult.estimate.soc), ...
    'The synthetic benchmark and EKF result must be deterministic.');

irregularIndices = unique([1; (2:3:1200)'; (1202:5:2400)'; ...
    (2402:7:signalCount)'; signalCount]);
irregularEstimate = estimate_battery_soc_ekf( ...
    truth.time_s(irregularIndices), truth.current_A(irregularIndices), ...
    result.measured_voltage_V(irregularIndices), ...
    estimate.parameters, estimate.options);
assert(all(isfinite(irregularEstimate.soc)) && ...
    all(irregularEstimate.soc >= 0 & irregularEstimate.soc <= 1), ...
    'The EKF must support a strictly increasing irregular time grid.');

assert_error(@() estimate_battery_soc_ekf( ...
    [0; 1; 1], zeros(3, 1), 3.7 * ones(3, 1), ...
    estimate.parameters, estimate.options), ...
    'BatterySOCEKF:TimeOrder');
badOptions = estimate.options;
badOptions.measurement_variance_V2 = 0;
assert_error(@() estimate_battery_soc_ekf( ...
    [0; 1], [0; 0], [3.7; 3.7], estimate.parameters, badOptions), ...
    'BatterySOCEKF:MeasurementVariance');
badOptions = estimate.options;
badOptions.initial_covariance = [1, 2; 0, 1];
assert_error(@() estimate_battery_soc_ekf( ...
    [0; 1], [0; 0], [3.7; 3.7], estimate.parameters, badOptions), ...
    'BatterySOCEKF:Covariance');
badParameters = estimate.parameters;
badParameters.ocv_soc_breakpoints = [0; 0.5; 0.5; 1];
badParameters.ocv_lookup_V = [3.0; 3.5; 3.6; 4.2];
assert_error(@() estimate_battery_soc_ekf( ...
    [0; 1], [0; 0], [3.7; 3.7], badParameters, estimate.options), ...
    'BatterySOCEKF:OCVCurve');

fprintf('Battery SOC EKF check passed.\n');
fprintf('Initial prior SOC error: %+.3f\n', ...
    metrics.initial_prior_soc_error);
fprintf('First posterior SOC error: %+.3f\n', ...
    metrics.initial_posterior_soc_error);
fprintf('Final SOC error: %+.4f\n', metrics.final_soc_error);
fprintf('SOC RMSE: %.4f\n', metrics.soc_rmse);
fprintf('Two-percent settling time: %.0f s\n', ...
    metrics.soc_settling_time_s);
fprintf('Posterior voltage RMSE: %.3f mV\n', ...
    1000 * metrics.voltage_rmse_V);

function assert_error(functionHandle, expectedIdentifier)
try
    functionHandle();
catch errorDetails
    assert(strcmp(errorDetails.identifier, expectedIdentifier), ...
        'Expected error %s but received %s.', ...
        expectedIdentifier, errorDetails.identifier);
    return;
end
error('BatterySOCEKF:MissingError', ...
    'Expected error %s was not raised.', expectedIdentifier);
end
