clear;
close all;
clc;

modelDirectory = fileparts(mfilename('fullpath'));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory);

bias_A = [-0.50; -0.25; 0; 0.25; 0.50];
sensitivity = evaluate_battery_soc_ekf_current_bias(bias_A);
zeroIndex = find(bias_A == 0);
baseline = simulate_battery_soc_ekf_example();
zeroBias = sensitivity.case_results{zeroIndex};

assert(isequal(zeroBias.truth.soc, baseline.truth.soc) && ...
    isequal(zeroBias.measured_voltage_V, baseline.measured_voltage_V) && ...
    isequal(zeroBias.estimate.soc, baseline.estimate.soc) && ...
    isequal(zeroBias.estimate.covariance, baseline.estimate.covariance) && ...
    isequal(zeroBias.metrics, baseline.metrics), ...
    'The zero-bias case must reproduce the established benchmark exactly.');

for caseIndex = 1:numel(sensitivity.case_results)
    result = sensitivity.case_results{caseIndex};
    assert(isequal(result.truth, baseline.truth) && ...
        isequal(result.measured_voltage_V, baseline.measured_voltage_V), ...
        'Truth and voltage measurements must remain fixed across bias cases.');
    assert(max(abs(result.measured_current_A - result.truth.current_A - ...
        bias_A(caseIndex))) < 1e-14, ...
        'Only the estimator current input may receive the configured bias.');
    assert(all(isfinite(result.estimate.soc)) && ...
        all(result.estimate.soc >= 0 & result.estimate.soc <= 1) && ...
        all(isfinite(result.estimate.innovation_V)) && ...
        all(result.estimate.innovation_variance_V2 > 0), ...
        'Every biased estimate must remain finite and bounded.');
    for sampleIndex = 1:size(result.estimate.covariance, 3)
        covariance = result.estimate.covariance(:, :, sampleIndex);
        assert(max(abs(covariance - covariance'), [], 'all') < 1e-12 && ...
            min(eig(covariance)) >= -1e-12, ...
            'Joseph covariance must remain symmetric positive semidefinite.');
    end
end

assert(all(diff(sensitivity.final_soc_error) > 0), ...
    'Negative and positive current bias must produce ordered signed SOC error.');
assert(all(sensitivity.minimum_covariance_eigenvalue >= -1e-12), ...
    'Every bias case must preserve positive-semidefinite covariance.');

[~, parameters, options] = battery_soc_ekf_default_scenario();
irregularIndices = unique([1; (3:3:numel(baseline.truth.time_s))'; ...
    numel(baseline.truth.time_s)]);
irregularBias_A = 0.25;
irregularEstimate = estimate_battery_soc_ekf( ...
    baseline.truth.time_s(irregularIndices), ...
    baseline.truth.current_A(irregularIndices) + irregularBias_A, ...
    baseline.measured_voltage_V(irregularIndices), parameters, options);
assert(all(isfinite(irregularEstimate.soc)) && ...
    all(irregularEstimate.soc >= 0 & irregularEstimate.soc <= 1), ...
    'A nonzero bias case must remain bounded on irregular timestamps.');

repeatSensitivity = evaluate_battery_soc_ekf_current_bias(bias_A);
assert(isequal(sensitivity.final_soc_error, ...
    repeatSensitivity.final_soc_error) && ...
    isequal(sensitivity.mean_normalized_innovation_squared, ...
    repeatSensitivity.mean_normalized_innovation_squared), ...
    'The current-bias sensitivity must be deterministic.');

assert_error(@() evaluate_battery_soc_ekf_current_bias([0; 0.1; 0.1]), ...
    'BatterySOCEKF:BiasGrid');
assert_error(@() evaluate_battery_soc_ekf_current_bias([0.1; 0.2]), ...
    'BatterySOCEKF:BiasGrid');
assert_error(@() evaluate_battery_soc_ekf_current_bias([0; NaN]), ...
    'MATLAB:expectedFinite');
assert_error(@() simulate_battery_soc_ekf_example(Inf), ...
    'MATLAB:expectedFinite');

fprintf('Battery SOC EKF current-bias sensitivity check passed.\n');
fprintf('Bias range: %.2f A to %.2f A\n', bias_A(1), bias_A(end));
fprintf('Final SOC error range: %+.4f to %+.4f\n', ...
    min(sensitivity.final_soc_error), ...
    max(sensitivity.final_soc_error));
fprintf('Zero/bias-edge SOC RMSE: %.4f / %.4f / %.4f\n', ...
    sensitivity.soc_rmse(zeroIndex), sensitivity.soc_rmse(1), ...
    sensitivity.soc_rmse(end));

function assert_error(functionHandle, expectedIdentifier)
try
    functionHandle();
catch errorDetails
    assert(strcmp(errorDetails.identifier, expectedIdentifier), ...
        'Expected error %s but received %s.', ...
        expectedIdentifier, errorDetails.identifier);
    return;
end
error('BatterySOCEKF:MissingError', ...
    'Expected error %s was not raised.', expectedIdentifier);
end
