function [modelPath, referenceResult] = ...
        build_battery_thermal_simulink_model(...
            outputDirectory, profile, parameters, sampleTime_s)
%BUILD_BATTERY_THERMAL_SIMULINK_MODEL Generate the thermal battery diagram.

modelDirectory = fileparts(mfilename('fullpath'));
referenceDirectory = fullfile(modelDirectory, '..', 'battery-thermal-model');
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(referenceDirectory);

if nargin < 1 || isempty(outputDirectory)
    outputDirectory = fullfile(tempdir, 'matlab-simulink-energy-lab');
end
if nargin < 2 || isempty(profile)
    profile = battery_thermal_default_profile();
end
if nargin < 3 || isempty(parameters)
    parameters = battery_thermal_default_parameters();
end
if nargin < 4 || isempty(sampleTime_s)
    sampleTime_s = 1;
end

validate_output_directory(outputDirectory);
referenceResult = simulate_battery_thermal_model(...
    profile, parameters, sampleTime_s);
if isempty(ver('simulink')) || ~license('test', 'Simulink')
    error('BatteryThermalSimulink:SimulinkUnavailable', ...
        'Building this model requires an available Simulink license.');
end

outputDirectory = char(outputDirectory);
if ~isfolder(outputDirectory)
    [created, message] = mkdir(outputDirectory);
    if ~created
        error('BatteryThermalSimulink:OutputDirectory', ...
            'Could not create output directory: %s', message);
    end
end

modelName = 'battery_thermal_simulink_model';
modelPath = fullfile(outputDirectory, [modelName, '.slx']);
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if isfile(modelPath)
    delete(modelPath);
end

new_system(modelName);
modelCleanup = onCleanup(@() close_model_if_loaded(modelName));
numberText = @(value) sprintf('%.17g', value);
vectorText = @(value) mat2str(value(:)', 17);
profileText = mat2str([referenceResult.time_s, ...
    referenceResult.current_A], 17);
thermalCapacity_J_per_K = referenceResult.thermal_capacity_J_per_K;

set_param(modelName, ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', numberText(sampleTime_s), ...
    'StartTime', '0', ...
    'StopTime', numberText(referenceResult.time_s(end)), ...
    'ReturnWorkspaceOutputs', 'on', ...
    'SaveTime', 'on', ...
    'TimeSaveName', 'tout', ...
    'SaveOutput', 'on', ...
    'OutputSaveName', 'yout', ...
    'SaveFormat', 'Dataset');

add_block('simulink/Sources/From Workspace', ...
    [modelName, '/Applied current profile'], ...
    'VariableName', profileText, ...
    'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value', ...
    'ZeroCross', 'on', ...
    'Position', [30, 245, 145, 285]);

add_block('simulink/Math Operations/Gain', ...
    [modelName, '/SOC increment'], ...
    'Gain', numberText(-sampleTime_s / ...
        (parameters.capacity_Ah * 3600)), ...
    'Position', [195, 25, 300, 55]);
add_block('simulink/Math Operations/Sum', [modelName, '/SOC update'], ...
    'Inputs', '++', ...
    'Position', [350, 20, 380, 80]);
add_block('simulink/Discontinuities/Saturation', ...
    [modelName, '/SOC limits'], ...
    'UpperLimit', '1', ...
    'LowerLimit', '0', ...
    'Position', [425, 30, 470, 70]);
add_block('simulink/Discrete/Unit Delay', [modelName, '/SOC'], ...
    'InitialCondition', numberText(parameters.initial_soc), ...
    'SampleTime', numberText(sampleTime_s), ...
    'Position', [515, 30, 560, 70]);

add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Polarization input increment'], ...
    'Gain', numberText(sampleTime_s / parameters.c1_F), ...
    'Position', [195, 165, 300, 195]);
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Polarization decay increment'], ...
    'Gain', numberText(sampleTime_s / ...
        (parameters.r1_Ohm * parameters.c1_F)), ...
    'Position', [195, 115, 300, 145]);
add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Polarization update'], ...
    'Inputs', '++-', ...
    'Position', [350, 125, 380, 205]);
add_block('simulink/Discrete/Unit Delay', ...
    [modelName, '/Polarization voltage'], ...
    'InitialCondition', '0', ...
    'SampleTime', numberText(sampleTime_s), ...
    'Position', [425, 145, 470, 185]);

add_block('simulink/Math Operations/Gain', ...
    [modelName, '/OCV SOC slope'], ...
    'Gain', numberText(parameters.ocv_soc_slope_V), ...
    'Position', [615, 25, 705, 55]);
add_block('simulink/Sources/Constant', [modelName, '/OCV baseline'], ...
    'Value', numberText(parameters.ocv_nominal_V - ...
        0.5 * parameters.ocv_soc_slope_V), ...
    'Position', [615, 75, 705, 105]);
add_block('simulink/Math Operations/Sum', [modelName, '/OCV'], ...
    'Inputs', '++', ...
    'Position', [750, 35, 780, 95]);

add_block('simulink/Sources/Constant', ...
    [modelName, '/Reference temperature'], ...
    'Value', numberText(parameters.reference_temp_C), ...
    'Position', [195, 350, 300, 380]);
add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Reference temperature difference'], ...
    'Inputs', '+-', ...
    'Position', [350, 335, 380, 395]);
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Resistance temperature exponent'], ...
    'Gain', numberText(...
        parameters.resistance_temp_coefficient_per_C), ...
    'Position', [425, 345, 525, 375]);
add_block('simulink/Math Operations/Math Function', ...
    [modelName, '/Resistance exponential'], ...
    'Operator', 'exp', ...
    'Position', [570, 345, 615, 375]);
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Ohmic resistance'], ...
    'Gain', numberText(parameters.r0_reference_Ohm), ...
    'Position', [660, 345, 750, 375]);

add_block('simulink/Math Operations/Product', ...
    [modelName, '/Ohmic voltage drop'], ...
    'Inputs', '**', ...
    'Position', [800, 250, 830, 310]);
add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Terminal voltage balance'], ...
    'Inputs', '+--', ...
    'Position', [875, 125, 905, 205]);

add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Equivalent circuit voltage loss'], ...
    'Inputs', '++', ...
    'Position', [875, 260, 905, 320]);
add_block('simulink/Math Operations/Product', ...
    [modelName, '/Irreversible heat generation'], ...
    'Inputs', '**', ...
    'Position', [950, 260, 980, 320]);

add_block('simulink/Lookup Tables/1-D Lookup Table', ...
    [modelName, '/Entropic coefficient'], ...
    'Table', vectorText(parameters.entropic_coefficient_V_per_K), ...
    'BreakpointsForDimension1', ...
    vectorText(parameters.entropic_soc_breakpoints), ...
    'InterpMethod', 'Linear point-slope', ...
    'ExtrapMethod', 'Clip', ...
    'Position', [615, 560, 750, 600]);
add_block('simulink/Sources/Constant', ...
    [modelName, '/Celsius to kelvin offset'], ...
    'Value', '273.15', ...
    'Position', [615, 650, 750, 680]);
add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Absolute cell temperature'], ...
    'Inputs', '++', ...
    'Position', [800, 625, 830, 685]);
add_block('simulink/Math Operations/Product', ...
    [modelName, '/Reversible heat product'], ...
    'Inputs', '***', ...
    'Position', [875, 555, 905, 615]);
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Reversible heat sign'], ...
    'Gain', '-1', ...
    'Position', [950, 570, 1040, 600]);
add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Total heat generation'], ...
    'Inputs', '++', ...
    'Position', [1000, 350, 1030, 410]);

add_block('simulink/Sources/Constant', ...
    [modelName, '/Ambient temperature'], ...
    'Value', numberText(parameters.ambient_temp_C), ...
    'Position', [195, 500, 300, 530]);
add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Temperature rise above ambient'], ...
    'Inputs', '+-', ...
    'Position', [350, 475, 380, 535]);
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Ambient cooling'], ...
    'Gain', numberText(parameters.heat_transfer_W_per_K), ...
    'Position', [425, 485, 525, 515]);
add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Net heat'], ...
    'Inputs', '++-', ...
    'Position', [570, 440, 600, 500]);
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Thermal increment'], ...
    'Gain', numberText(sampleTime_s / thermalCapacity_J_per_K), ...
    'Position', [645, 450, 745, 480]);
add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Temperature update'], ...
    'Inputs', '++', ...
    'Position', [790, 425, 820, 485]);
add_block('simulink/Discrete/Unit Delay', ...
    [modelName, '/Cell temperature'], ...
    'InitialCondition', numberText(parameters.initial_cell_temp_C), ...
    'SampleTime', numberText(sampleTime_s), ...
    'Position', [865, 435, 910, 475]);

add_output_and_logger(modelName, 'Current', 'current_A', 1, ...
    [1150, 20, 1180, 40], [1210, 15, 1330, 45]);
add_output_and_logger(modelName, 'State of charge', 'soc', 2, ...
    [1150, 60, 1180, 80], [1210, 55, 1330, 85]);
add_output_and_logger(modelName, 'Polarization', 'v_rc_V', 3, ...
    [1150, 100, 1180, 120], [1210, 95, 1330, 125]);
add_output_and_logger(modelName, 'Open circuit voltage', 'ocv_V', 4, ...
    [1150, 140, 1180, 160], [1210, 135, 1330, 165]);
add_output_and_logger(modelName, 'Resistance', 'r0_Ohm', 5, ...
    [1150, 180, 1180, 200], [1210, 175, 1330, 205]);
add_output_and_logger(modelName, 'Terminal voltage', ...
    'terminal_voltage_V', 6, ...
    [1150, 220, 1180, 240], [1210, 215, 1330, 245]);
add_output_and_logger(modelName, 'Irreversible heat', ...
    'heat_generation_W', 7, ...
    [1150, 260, 1180, 280], [1210, 255, 1330, 285]);
add_output_and_logger(modelName, 'Entropic coefficient output', ...
    'entropic_coefficient_V_per_K', 8, ...
    [1150, 300, 1180, 320], [1210, 295, 1330, 325]);
add_output_and_logger(modelName, 'Reversible heat', ...
    'reversible_heat_W', 9, ...
    [1150, 340, 1180, 360], [1210, 335, 1330, 365]);
add_output_and_logger(modelName, 'Total heat output', ...
    'total_heat_generation_W', 10, ...
    [1150, 380, 1180, 400], [1210, 375, 1330, 405]);
add_output_and_logger(modelName, 'Cooling power', ...
    'cooling_power_W', 11, ...
    [1150, 420, 1180, 440], [1210, 415, 1330, 445]);
add_output_and_logger(modelName, 'Net heat output', 'net_heat_W', 12, ...
    [1150, 460, 1180, 480], [1210, 455, 1330, 485]);
add_output_and_logger(modelName, 'Temperature', 'cell_temp_C', 13, ...
    [1150, 500, 1180, 520], [1210, 495, 1330, 525]);

add_line(modelName, 'Applied current profile/1', 'SOC increment/1', ...
    'autorouting', 'on');
add_line(modelName, 'SOC increment/1', 'SOC update/1', ...
    'autorouting', 'on');
add_line(modelName, 'SOC/1', 'SOC update/2', 'autorouting', 'on');
add_line(modelName, 'SOC update/1', 'SOC limits/1', 'autorouting', 'on');
add_line(modelName, 'SOC limits/1', 'SOC/1', 'autorouting', 'on');

add_line(modelName, 'Applied current profile/1', ...
    'Polarization input increment/1', 'autorouting', 'on');
add_line(modelName, 'Polarization input increment/1', ...
    'Polarization update/2', 'autorouting', 'on');
add_line(modelName, 'Polarization voltage/1', ...
    'Polarization decay increment/1', 'autorouting', 'on');
add_line(modelName, 'Polarization decay increment/1', ...
    'Polarization update/3', 'autorouting', 'on');
add_line(modelName, 'Polarization voltage/1', ...
    'Polarization update/1', 'autorouting', 'on');
add_line(modelName, 'Polarization update/1', ...
    'Polarization voltage/1', 'autorouting', 'on');

add_line(modelName, 'SOC/1', 'OCV SOC slope/1', 'autorouting', 'on');
add_line(modelName, 'OCV SOC slope/1', 'OCV/1', 'autorouting', 'on');
add_line(modelName, 'OCV baseline/1', 'OCV/2', 'autorouting', 'on');

add_line(modelName, 'Reference temperature/1', ...
    'Reference temperature difference/1', 'autorouting', 'on');
add_line(modelName, 'Cell temperature/1', ...
    'Reference temperature difference/2', 'autorouting', 'on');
add_line(modelName, 'Reference temperature difference/1', ...
    'Resistance temperature exponent/1', 'autorouting', 'on');
add_line(modelName, 'Resistance temperature exponent/1', ...
    'Resistance exponential/1', 'autorouting', 'on');
add_line(modelName, 'Resistance exponential/1', ...
    'Ohmic resistance/1', 'autorouting', 'on');

add_line(modelName, 'Applied current profile/1', ...
    'Ohmic voltage drop/1', 'autorouting', 'on');
add_line(modelName, 'Ohmic resistance/1', ...
    'Ohmic voltage drop/2', 'autorouting', 'on');
add_line(modelName, 'OCV/1', 'Terminal voltage balance/1', ...
    'autorouting', 'on');
add_line(modelName, 'Ohmic voltage drop/1', ...
    'Terminal voltage balance/2', 'autorouting', 'on');
add_line(modelName, 'Polarization voltage/1', ...
    'Terminal voltage balance/3', 'autorouting', 'on');

add_line(modelName, 'Ohmic voltage drop/1', ...
    'Equivalent circuit voltage loss/1', 'autorouting', 'on');
add_line(modelName, 'Polarization voltage/1', ...
    'Equivalent circuit voltage loss/2', 'autorouting', 'on');
add_line(modelName, 'Applied current profile/1', ...
    'Irreversible heat generation/1', 'autorouting', 'on');
add_line(modelName, 'Equivalent circuit voltage loss/1', ...
    'Irreversible heat generation/2', 'autorouting', 'on');

add_line(modelName, 'SOC/1', 'Entropic coefficient/1', ...
    'autorouting', 'on');
add_line(modelName, 'Cell temperature/1', ...
    'Absolute cell temperature/1', 'autorouting', 'on');
add_line(modelName, 'Celsius to kelvin offset/1', ...
    'Absolute cell temperature/2', 'autorouting', 'on');
add_line(modelName, 'Applied current profile/1', ...
    'Reversible heat product/1', 'autorouting', 'on');
add_line(modelName, 'Absolute cell temperature/1', ...
    'Reversible heat product/2', 'autorouting', 'on');
add_line(modelName, 'Entropic coefficient/1', ...
    'Reversible heat product/3', 'autorouting', 'on');
add_line(modelName, 'Reversible heat product/1', ...
    'Reversible heat sign/1', 'autorouting', 'on');
add_line(modelName, 'Irreversible heat generation/1', ...
    'Total heat generation/1', 'autorouting', 'on');
add_line(modelName, 'Reversible heat sign/1', ...
    'Total heat generation/2', 'autorouting', 'on');

add_line(modelName, 'Cell temperature/1', ...
    'Temperature rise above ambient/1', 'autorouting', 'on');
add_line(modelName, 'Ambient temperature/1', ...
    'Temperature rise above ambient/2', 'autorouting', 'on');
add_line(modelName, 'Temperature rise above ambient/1', ...
    'Ambient cooling/1', 'autorouting', 'on');
add_line(modelName, 'Irreversible heat generation/1', ...
    'Net heat/1', 'autorouting', 'on');
add_line(modelName, 'Reversible heat sign/1', 'Net heat/2', ...
    'autorouting', 'on');
add_line(modelName, 'Ambient cooling/1', 'Net heat/3', ...
    'autorouting', 'on');
add_line(modelName, 'Net heat/1', 'Thermal increment/1', ...
    'autorouting', 'on');
add_line(modelName, 'Cell temperature/1', 'Temperature update/1', ...
    'autorouting', 'on');
add_line(modelName, 'Thermal increment/1', 'Temperature update/2', ...
    'autorouting', 'on');
add_line(modelName, 'Temperature update/1', 'Cell temperature/1', ...
    'autorouting', 'on');

connect_output_and_logger(modelName, 'Applied current profile', 'Current');
connect_output_and_logger(modelName, 'SOC', 'State of charge');
connect_output_and_logger(modelName, 'Polarization voltage', 'Polarization');
connect_output_and_logger(modelName, 'OCV', 'Open circuit voltage');
connect_output_and_logger(modelName, 'Ohmic resistance', 'Resistance');
connect_output_and_logger(modelName, 'Terminal voltage balance', ...
    'Terminal voltage');
connect_output_and_logger(modelName, 'Irreversible heat generation', ...
    'Irreversible heat');
connect_output_and_logger(modelName, 'Entropic coefficient', ...
    'Entropic coefficient output');
connect_output_and_logger(modelName, 'Reversible heat sign', ...
    'Reversible heat');
connect_output_and_logger(modelName, 'Total heat generation', ...
    'Total heat output');
connect_output_and_logger(modelName, 'Ambient cooling', 'Cooling power');
connect_output_and_logger(modelName, 'Net heat', 'Net heat output');
connect_output_and_logger(modelName, 'Cell temperature', 'Temperature');

set_param(modelName, 'SimulationCommand', 'update');
save_system(modelName, modelPath);
clear modelCleanup pathCleanup;
end

function add_output_and_logger(modelName, outputName, variableName, ...
        portNumber, outputPosition, loggerPosition)
add_block('simulink/Sinks/Out1', [modelName, '/', outputName], ...
    'Port', num2str(portNumber), 'Position', outputPosition);
add_block('simulink/Sinks/To Workspace', ...
    [modelName, '/Log ', outputName], ...
    'VariableName', variableName, ...
    'SaveFormat', 'Timeseries', ...
    'MaxDataPoints', 'inf', ...
    'Decimation', '1', ...
    'Position', loggerPosition);
end

function connect_output_and_logger(modelName, sourceName, outputName)
add_line(modelName, [sourceName, '/1'], [outputName, '/1'], ...
    'autorouting', 'on');
add_line(modelName, [sourceName, '/1'], ['Log ', outputName, '/1'], ...
    'autorouting', 'on');
end

function validate_output_directory(outputDirectory)
isScalarText = ischar(outputDirectory) || ...
    (isstring(outputDirectory) && isscalar(outputDirectory));
if ~isScalarText || strlength(string(outputDirectory)) == 0
    error('BatteryThermalSimulink:OutputDirectory', ...
        'Output directory must be a nonempty character vector or string.');
end
end

function close_model_if_loaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
