%% Native Simulink Battery Thermal Check
% Builds and validates canonical and custom electro-thermal diagrams.

clear; clc;

modelDirectory = fileparts(mfilename('fullpath'));
referenceDirectory = fullfile(modelDirectory, '..', 'battery-thermal-model');
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory, referenceDirectory);

assert(~isempty(ver('simulink')) && license('test', 'Simulink'), ...
    'The native battery thermal check requires Simulink.');

temporaryDirectory = tempname;
mkdir(temporaryDirectory);
modelName = 'battery_thermal_simulink_model';
cleanup = onCleanup(@() clean_generated_model(modelName, temporaryDirectory));

defaultDirectory = fullfile(temporaryDirectory, 'default');
[defaultModelPath, defaultReference] = ...
    build_battery_thermal_simulink_model(defaultDirectory);
assert(isfile(defaultModelPath), ...
    'The builder must create a real battery thermal SLX model file.');
load_system(defaultModelPath);

expectedBlocks = {
    'Applied current profile', 'FromWorkspace'; ...
    'SOC increment', 'Gain'; ...
    'SOC update', 'Sum'; ...
    'SOC limits', 'Saturate'; ...
    'SOC', 'UnitDelay'; ...
    'Polarization input increment', 'Gain'; ...
    'Polarization decay increment', 'Gain'; ...
    'Polarization update', 'Sum'; ...
    'Polarization voltage', 'UnitDelay'; ...
    'OCV SOC slope', 'Gain'; ...
    'OCV baseline', 'Constant'; ...
    'OCV', 'Sum'; ...
    'Reference temperature', 'Constant'; ...
    'Reference temperature difference', 'Sum'; ...
    'Resistance temperature exponent', 'Gain'; ...
    'Resistance exponential', 'Math'; ...
    'Ohmic resistance', 'Gain'; ...
    'Ohmic voltage drop', 'Product'; ...
    'Terminal voltage balance', 'Sum'; ...
    'Equivalent circuit voltage loss', 'Sum'; ...
    'Irreversible heat generation', 'Product'; ...
    'Entropic coefficient', 'Lookup_n-D'; ...
    'Celsius to kelvin offset', 'Constant'; ...
    'Absolute cell temperature', 'Sum'; ...
    'Reversible heat product', 'Product'; ...
    'Reversible heat sign', 'Gain'; ...
    'Total heat generation', 'Sum'; ...
    'Ambient temperature', 'Constant'; ...
    'Temperature rise above ambient', 'Sum'; ...
    'Ambient cooling', 'Gain'; ...
    'Net heat', 'Sum'; ...
    'Thermal increment', 'Gain'; ...
    'Temperature update', 'Sum'; ...
    'Cell temperature', 'UnitDelay'; ...
    'Current', 'Outport'; ...
    'State of charge', 'Outport'; ...
    'Polarization', 'Outport'; ...
    'Open circuit voltage', 'Outport'; ...
    'Resistance', 'Outport'; ...
    'Terminal voltage', 'Outport'; ...
    'Irreversible heat', 'Outport'; ...
    'Entropic coefficient output', 'Outport'; ...
    'Reversible heat', 'Outport'; ...
    'Total heat output', 'Outport'; ...
    'Cooling power', 'Outport'; ...
    'Net heat output', 'Outport'; ...
    'Temperature', 'Outport'; ...
    'Log Current', 'ToWorkspace'; ...
    'Log State of charge', 'ToWorkspace'; ...
    'Log Polarization', 'ToWorkspace'; ...
    'Log Open circuit voltage', 'ToWorkspace'; ...
    'Log Resistance', 'ToWorkspace'; ...
    'Log Terminal voltage', 'ToWorkspace'; ...
    'Log Irreversible heat', 'ToWorkspace'; ...
    'Log Entropic coefficient output', 'ToWorkspace'; ...
    'Log Reversible heat', 'ToWorkspace'; ...
    'Log Total heat output', 'ToWorkspace'; ...
    'Log Cooling power', 'ToWorkspace'; ...
    'Log Net heat output', 'ToWorkspace'; ...
    'Log Temperature', 'ToWorkspace'
};
for blockIndex = 1:size(expectedBlocks, 1)
    blockPath = [modelName, '/', expectedBlocks{blockIndex, 1}];
    assert(strcmp(get_param(blockPath, 'BlockType'), ...
        expectedBlocks{blockIndex, 2}), ...
        'Generated thermal model contains an unexpected block type.');
end

assert_connection(modelName, 'Applied current profile', 1, ...
    'SOC increment', 1);
assert_connection(modelName, 'SOC increment', 1, 'SOC update', 1);
assert_connection(modelName, 'SOC', 1, 'SOC update', 2);
assert_connection(modelName, 'SOC update', 1, 'SOC limits', 1);
assert_connection(modelName, 'SOC limits', 1, 'SOC', 1);

assert_connection(modelName, 'Applied current profile', 1, ...
    'Polarization input increment', 1);
assert_connection(modelName, 'Polarization voltage', 1, ...
    'Polarization decay increment', 1);
assert_connection(modelName, 'Polarization voltage', 1, ...
    'Polarization update', 1);
assert_connection(modelName, 'Polarization input increment', 1, ...
    'Polarization update', 2);
assert_connection(modelName, 'Polarization decay increment', 1, ...
    'Polarization update', 3);
assert_connection(modelName, 'Polarization update', 1, ...
    'Polarization voltage', 1);

assert_connection(modelName, 'Cell temperature', 1, ...
    'Reference temperature difference', 2);
assert_connection(modelName, 'Reference temperature difference', 1, ...
    'Resistance temperature exponent', 1);
assert_connection(modelName, 'Resistance temperature exponent', 1, ...
    'Resistance exponential', 1);
assert_connection(modelName, 'Resistance exponential', 1, ...
    'Ohmic resistance', 1);
assert_connection(modelName, 'Ohmic resistance', 1, ...
    'Ohmic voltage drop', 2);

assert_connection(modelName, 'Ohmic voltage drop', 1, ...
    'Equivalent circuit voltage loss', 1);
assert_connection(modelName, 'Polarization voltage', 1, ...
    'Equivalent circuit voltage loss', 2);
assert_connection(modelName, 'Equivalent circuit voltage loss', 1, ...
    'Irreversible heat generation', 2);
assert_connection(modelName, 'SOC', 1, 'Entropic coefficient', 1);
assert_connection(modelName, 'Cell temperature', 1, ...
    'Absolute cell temperature', 1);
assert_connection(modelName, 'Celsius to kelvin offset', 1, ...
    'Absolute cell temperature', 2);
assert_connection(modelName, 'Applied current profile', 1, ...
    'Reversible heat product', 1);
assert_connection(modelName, 'Absolute cell temperature', 1, ...
    'Reversible heat product', 2);
assert_connection(modelName, 'Entropic coefficient', 1, ...
    'Reversible heat product', 3);
assert_connection(modelName, 'Reversible heat product', 1, ...
    'Reversible heat sign', 1);
assert_connection(modelName, 'Irreversible heat generation', 1, ...
    'Total heat generation', 1);
assert_connection(modelName, 'Reversible heat sign', 1, ...
    'Total heat generation', 2);
assert_connection(modelName, 'Irreversible heat generation', 1, ...
    'Net heat', 1);
assert_connection(modelName, 'Reversible heat sign', 1, 'Net heat', 2);
assert_connection(modelName, 'Ambient cooling', 1, 'Net heat', 3);
assert_connection(modelName, 'Net heat', 1, 'Thermal increment', 1);
assert_connection(modelName, 'Cell temperature', 1, ...
    'Temperature update', 1);
assert_connection(modelName, 'Thermal increment', 1, ...
    'Temperature update', 2);
assert_connection(modelName, 'Temperature update', 1, ...
    'Cell temperature', 1);

assert(strcmp(get_param([modelName, '/Applied current profile'], ...
    'Interpolate'), 'off'), ...
    'Current input must use zero-order hold interpolation.');
assert(strcmp(get_param(modelName, 'SolverType'), 'Fixed-step') && ...
    strcmp(get_param(modelName, 'Solver'), 'FixedStepDiscrete'), ...
    'Thermal model must use a fixed-step discrete solver.');
assert(strcmp(get_param([modelName, '/Resistance exponential'], ...
    'Operator'), 'exp'), ...
    'Temperature feedback must use an exponential resistance relation.');
assert(strcmp(get_param([modelName, '/Entropic coefficient'], ...
    'InterpMethod'), 'Linear point-slope') && ...
    strcmp(get_param([modelName, '/Entropic coefficient'], ...
    'ExtrapMethod'), 'Clip'), ...
    'Entropic lookup must interpolate linearly and clip outside its table.');
assert(strcmp(get_param([modelName, '/Reversible heat sign'], ...
    'Gain'), '-1'), ...
    'Reversible heat must follow the declared discharge-current sign.');
assert(strcmp(get_param([modelName, '/SOC limits'], 'UpperLimit'), '1') && ...
    strcmp(get_param([modelName, '/SOC limits'], 'LowerLimit'), '0'), ...
    'SOC update must enforce the physical state interval.');
assert_delay_configuration(modelName, 'SOC', 0.8, 1);
assert_delay_configuration(modelName, 'Polarization voltage', 0, 1);
assert_delay_configuration(modelName, 'Cell temperature', 25, 1);

set_param(modelName, 'SimulationCommand', 'update');
defaultMetrics = compare_model_to_reference(modelName, defaultReference);
close_system(modelName, 0);

customProfile = table(...
    [0; 5; 15; 30], ...
    [0; 40; -10; 0], ...
    'VariableNames', {'time_s', 'current_A'});
customParameters = battery_thermal_default_parameters();
customParameters.ambient_temp_C = 20;
customParameters.initial_cell_temp_C = 22;
customParameters.heat_transfer_W_per_K = 2.0;
customParameters.resistance_temp_coefficient_per_C = 0.035;
customParameters.entropic_soc_breakpoints = [0, 0.5, 1];
customParameters.entropic_coefficient_V_per_K = ...
    [0.12e-3, -0.08e-3, 0.04e-3];
customDirectory = fullfile(temporaryDirectory, 'custom');
[customModelPath, customReference] = ...
    build_battery_thermal_simulink_model(...
        customDirectory, customProfile, customParameters, 0.5);
load_system(customModelPath);
assert_delay_configuration(modelName, 'SOC', ...
    customParameters.initial_soc, 0.5);
assert_delay_configuration(modelName, 'Polarization voltage', 0, 0.5);
assert_delay_configuration(modelName, 'Cell temperature', ...
    customParameters.initial_cell_temp_C, 0.5);
set_param(modelName, 'SimulationCommand', 'update');
customMetrics = compare_model_to_reference(modelName, customReference);
assert(max(customReference.cell_temp_C) > ...
    customReference.cell_temp_C(1), ...
    'Custom case must exercise temperature feedback.');
close_system(modelName, 0);

invalidParameters = battery_thermal_default_parameters();
invalidParameters.cell_mass_kg = 0;
invalidParameterRejected = false;
try
    build_battery_thermal_simulink_model(...
        temporaryDirectory, customProfile, invalidParameters, 0.5);
catch validationError
    invalidParameterRejected = strcmp(validationError.identifier, ...
        'BatteryThermal:Parameters');
end
assert(invalidParameterRejected, ...
    'Builder must preserve thermal parameter validation.');

invalidEntropicParameters = battery_thermal_default_parameters();
invalidEntropicParameters.entropic_soc_breakpoints = [0, 0.7, 0.6, 1];
invalidEntropicTableRejected = false;
try
    build_battery_thermal_simulink_model(...
        temporaryDirectory, customProfile, invalidEntropicParameters, 0.5);
catch validationError
    invalidEntropicTableRejected = strcmp(validationError.identifier, ...
        'BatteryThermal:EntropicTable');
end
assert(invalidEntropicTableRejected, ...
    'Builder must preserve strict entropic lookup validation.');

metricNames = fieldnames(defaultMetrics);
maximumMetrics = struct();
for metricIndex = 1:numel(metricNames)
    metricName = metricNames{metricIndex};
    maximumMetrics.(metricName) = max(...
        defaultMetrics.(metricName), customMetrics.(metricName));
end

fprintf('Native Simulink battery thermal check passed.\n');
fprintf('Peak cell temperature: %.2f degC\n', ...
    max(defaultReference.cell_temp_C));
fprintf('Final cell temperature: %.2f degC\n', ...
    defaultReference.cell_temp_C(end));
fprintf('Reversible heat range: %.2f W to %.2f W\n', ...
    min(defaultReference.reversible_heat_W), ...
    max(defaultReference.reversible_heat_W));
fprintf(['Maximum parity errors: %.3e A, %.3e SOC, %.3e Vrc, ', ...
    '%.3e OCV, %.3e Ohm, %.3e Vterminal, %.3e Qirr, ', ...
    '%.3e dUdT, %.3e Qrev, %.3e Qtotal, %.3e Qcool, ', ...
    '%.3e Qnet, %.3e degC\n'], ...
    maximumMetrics.current_error_A, maximumMetrics.soc_error, ...
    maximumMetrics.polarization_error_V, maximumMetrics.ocv_error_V, ...
    maximumMetrics.resistance_error_Ohm, ...
    maximumMetrics.terminal_error_V, ...
    maximumMetrics.heat_generation_error_W, ...
    maximumMetrics.entropic_coefficient_error_V_per_K, ...
    maximumMetrics.reversible_heat_error_W, ...
    maximumMetrics.total_heat_error_W, ...
    maximumMetrics.cooling_error_W, maximumMetrics.net_heat_error_W, ...
    maximumMetrics.temperature_error_C);

function metrics = compare_model_to_reference(modelName, referenceResult)
simulationOutput = sim(modelName);
current = simulationOutput.get('current_A');
soc = simulationOutput.get('soc');
polarization = simulationOutput.get('v_rc_V');
ocv = simulationOutput.get('ocv_V');
resistance = simulationOutput.get('r0_Ohm');
terminalVoltage = simulationOutput.get('terminal_voltage_V');
heatGeneration = simulationOutput.get('heat_generation_W');
entropicCoefficient = simulationOutput.get(...
    'entropic_coefficient_V_per_K');
reversibleHeat = simulationOutput.get('reversible_heat_W');
totalHeat = simulationOutput.get('total_heat_generation_W');
coolingPower = simulationOutput.get('cooling_power_W');
netHeat = simulationOutput.get('net_heat_W');
temperature = simulationOutput.get('cell_temp_C');

signals = {current; soc; polarization; ocv; resistance; ...
    terminalVoltage; heatGeneration; entropicCoefficient; reversibleHeat; ...
    totalHeat; coolingPower; netHeat; temperature};
for signalIndex = 1:numel(signals)
    signal = signals{signalIndex};
    assert(isa(signal, 'timeseries'), ...
        'Every generated thermal output must be a timeseries.');
    assert(numel(signal.Time) == numel(referenceResult.time_s) && ...
        max(abs(signal.Time(:) - referenceResult.time_s)) < 1e-12, ...
        'Generated thermal outputs must use the reference time grid.');
    assert(all(isfinite(signal.Data(:))), ...
        'Generated thermal outputs must remain finite.');
end

metrics.current_error_A = max(abs(...
    current.Data(:) - referenceResult.current_A));
metrics.soc_error = max(abs(soc.Data(:) - referenceResult.soc));
metrics.polarization_error_V = max(abs(...
    polarization.Data(:) - referenceResult.v_rc_V));
metrics.ocv_error_V = max(abs(ocv.Data(:) - referenceResult.ocv_V));
metrics.resistance_error_Ohm = max(abs(...
    resistance.Data(:) - referenceResult.r0_Ohm));
metrics.terminal_error_V = max(abs(...
    terminalVoltage.Data(:) - referenceResult.terminal_voltage_V));
metrics.heat_generation_error_W = max(abs(...
    heatGeneration.Data(:) - referenceResult.heat_generation_W));
metrics.entropic_coefficient_error_V_per_K = max(abs(...
    entropicCoefficient.Data(:) - ...
    referenceResult.entropic_coefficient_V_per_K));
metrics.reversible_heat_error_W = max(abs(...
    reversibleHeat.Data(:) - referenceResult.reversible_heat_W));
metrics.total_heat_error_W = max(abs(...
    totalHeat.Data(:) - referenceResult.total_heat_generation_W));
metrics.cooling_error_W = max(abs(...
    coolingPower.Data(:) - referenceResult.cooling_power_W));
metrics.net_heat_error_W = max(abs(...
    netHeat.Data(:) - referenceResult.net_heat_W));
metrics.temperature_error_C = max(abs(...
    temperature.Data(:) - referenceResult.cell_temp_C));

assert(metrics.current_error_A < 1e-12, ...
    'Generated model current differs from the reference profile.');
assert(metrics.soc_error < 1e-10, ...
    'Generated model SOC differs from the discrete reference.');
assert(metrics.polarization_error_V < 1e-10, ...
    'Generated model polarization differs from the discrete reference.');
assert(metrics.ocv_error_V < 1e-10, ...
    'Generated model OCV differs from the reference relation.');
assert(metrics.resistance_error_Ohm < 1e-12, ...
    'Generated model resistance differs from the thermal feedback.');
assert(metrics.terminal_error_V < 1e-9, ...
    'Generated model terminal voltage differs from the reference balance.');
assert(metrics.heat_generation_error_W < 1e-8, ...
    'Generated model irreversible heat differs from the reference balance.');
assert(metrics.entropic_coefficient_error_V_per_K < 1e-12, ...
    'Generated model entropic lookup differs from the reference table.');
assert(metrics.reversible_heat_error_W < 1e-8, ...
    'Generated model reversible heat differs from the reference balance.');
assert(metrics.total_heat_error_W < 1e-8, ...
    'Generated model total heat differs from the reference balance.');
assert(metrics.cooling_error_W < 1e-8, ...
    'Generated model cooling differs from the reference balance.');
assert(metrics.net_heat_error_W < 1e-8, ...
    'Generated model net heat differs from the reference balance.');
assert(metrics.temperature_error_C < 1e-9, ...
    'Generated model temperature differs from the discrete reference.');

thermalCapacity_J_per_K = referenceResult.thermal_capacity_J_per_K;
thermalEnergyChange_J = thermalCapacity_J_per_K * ...
    (temperature.Data(end) - temperature.Data(1));
integratedNetHeat_J = sum(netHeat.Data(1:end-1)) * referenceResult.dt_s;
assert(abs(thermalEnergyChange_J - integratedNetHeat_J) < 1e-6, ...
    'Generated model must close the discrete thermal energy balance.');
end

function assert_delay_configuration(...
        modelName, blockName, expectedInitialCondition, expectedSampleTime)
blockPath = [modelName, '/', blockName];
actualInitialCondition = str2double(...
    get_param(blockPath, 'InitialCondition'));
actualSampleTime = str2double(get_param(blockPath, 'SampleTime'));
assert(abs(actualInitialCondition - expectedInitialCondition) < 1e-14 && ...
    abs(actualSampleTime - expectedSampleTime) < 1e-14, ...
    'Generated model contains an incorrect discrete-state configuration.');
end

function assert_connection(modelName, sourceBlock, sourcePort, ...
        destinationBlock, destinationPort)
sourceHandles = get_param([modelName, '/', sourceBlock], 'PortHandles');
destinationHandles = get_param(...
    [modelName, '/', destinationBlock], 'PortHandles');
lineHandle = get_param(destinationHandles.Inport(destinationPort), 'Line');
assert(lineHandle ~= -1 && ...
    get_param(lineHandle, 'SrcPortHandle') == ...
    sourceHandles.Outport(sourcePort), ...
    'Generated thermal model has an incorrect or missing connection.');
end

function clean_generated_model(modelName, temporaryDirectory)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if isfolder(temporaryDirectory)
    rmdir(temporaryDirectory, 's');
end
end
