function modelPath = build_average_buck_simulink_model(outputDirectory, parameters)
%BUILD_AVERAGE_BUCK_SIMULINK_MODEL Generate the native Simulink reference.

if nargin < 1 || isempty(outputDirectory)
    outputDirectory = fullfile(tempdir, 'matlab-simulink-energy-lab');
end
if nargin < 2
    parameters = average_buck_simulink_parameters();
end

validate_output_directory(outputDirectory);
validate_parameters(parameters);
if isempty(ver('simulink')) || ~license('test', 'Simulink')
    error('AverageBuckSimulink:SimulinkUnavailable', ...
        'Building this model requires an available Simulink license.');
end

outputDirectory = char(outputDirectory);
if ~isfolder(outputDirectory)
    [created, message] = mkdir(outputDirectory);
    if ~created
        error('AverageBuckSimulink:OutputDirectory', ...
            'Could not create output directory: %s', message);
    end
end

modelName = 'average_buck_simulink_model';
modelPath = fullfile(outputDirectory, [modelName, '.slx']);
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if isfile(modelPath)
    delete(modelPath);
end

new_system(modelName);
modelCleanup = onCleanup(@() close_model_if_loaded(modelName));
numberText = @(value) sprintf('%.17g', value);

set_param(modelName, ...
    'SolverType', 'Variable-step', ...
    'Solver', 'ode45', ...
    'StartTime', '0', ...
    'StopTime', numberText(parameters.end_time_s), ...
    'MaxStep', numberText(parameters.solver_max_step_s), ...
    'RelTol', numberText(parameters.relative_tolerance), ...
    'AbsTol', numberText(parameters.absolute_tolerance), ...
    'ReturnWorkspaceOutputs', 'on', ...
    'SaveTime', 'on', ...
    'TimeSaveName', 'tout', ...
    'SaveOutput', 'on', ...
    'OutputSaveName', 'yout', ...
    'SaveFormat', 'Dataset');

add_block('simulink/Sources/Constant', [modelName, '/Input voltage'], ...
    'Value', numberText(parameters.input_voltage_V), ...
    'Position', [30, 45, 100, 75]);
add_block('simulink/Sources/Constant', [modelName, '/Duty cycle'], ...
    'Value', numberText(parameters.duty_cycle), ...
    'Position', [30, 105, 100, 135]);
add_block('simulink/Math Operations/Product', ...
    [modelName, '/Average switch voltage'], ...
    'Inputs', '**', ...
    'Position', [145, 60, 185, 120]);
add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Inductor voltage balance'], ...
    'Inputs', '+--', ...
    'Position', [285, 60, 315, 130]);
add_block('simulink/Math Operations/Gain', [modelName, '/One over L'], ...
    'Gain', numberText(1 / parameters.inductance_H), ...
    'Position', [350, 80, 425, 110]);
add_block('simulink/Continuous/Integrator', ...
    [modelName, '/Inductor current'], ...
    'InitialCondition', ...
    numberText(parameters.initial_inductor_current_A), ...
    'Position', [465, 75, 500, 115]);
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Inductor resistance'], ...
    'Gain', numberText(parameters.inductor_resistance_Ohm), ...
    'Position', [175, 160, 245, 190]);

add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Capacitor current balance'], ...
    'Inputs', '+-', ...
    'Position', [285, 230, 315, 290]);
add_block('simulink/Math Operations/Gain', [modelName, '/One over C'], ...
    'Gain', numberText(1 / parameters.capacitance_F), ...
    'Position', [350, 245, 425, 275]);
add_block('simulink/Continuous/Integrator', ...
    [modelName, '/Output voltage'], ...
    'InitialCondition', ...
    numberText(parameters.initial_output_voltage_V), ...
    'Position', [465, 240, 500, 280]);
add_block('simulink/Math Operations/Gain', ...
    [modelName, '/Load conductance'], ...
    'Gain', numberText(1 / parameters.load_resistance_Ohm), ...
    'Position', [175, 325, 245, 355]);

add_block('simulink/Sinks/Out1', [modelName, '/iL'], ...
    'Port', '1', 'Position', [690, 65, 720, 85]);
add_block('simulink/Sinks/Out1', [modelName, '/Vout'], ...
    'Port', '2', 'Position', [690, 235, 720, 255]);
add_block('simulink/Sinks/To Workspace', ...
    [modelName, '/Log inductor current'], ...
    'VariableName', 'inductor_current', ...
    'SaveFormat', 'Timeseries', ...
    'MaxDataPoints', 'inf', ...
    'Decimation', '1', ...
    'Position', [565, 105, 665, 135]);
add_block('simulink/Sinks/To Workspace', ...
    [modelName, '/Log output voltage'], ...
    'VariableName', 'output_voltage', ...
    'SaveFormat', 'Timeseries', ...
    'MaxDataPoints', 'inf', ...
    'Decimation', '1', ...
    'Position', [565, 275, 665, 305]);

add_line(modelName, 'Input voltage/1', 'Average switch voltage/1', ...
    'autorouting', 'on');
add_line(modelName, 'Duty cycle/1', 'Average switch voltage/2', ...
    'autorouting', 'on');
add_line(modelName, 'Average switch voltage/1', ...
    'Inductor voltage balance/1', 'autorouting', 'on');
add_line(modelName, 'Inductor voltage balance/1', 'One over L/1', ...
    'autorouting', 'on');
add_line(modelName, 'One over L/1', 'Inductor current/1', ...
    'autorouting', 'on');
add_line(modelName, 'Inductor current/1', 'Inductor resistance/1', ...
    'autorouting', 'on');
add_line(modelName, 'Inductor resistance/1', ...
    'Inductor voltage balance/3', 'autorouting', 'on');
add_line(modelName, 'Inductor current/1', ...
    'Capacitor current balance/1', 'autorouting', 'on');
add_line(modelName, 'Capacitor current balance/1', 'One over C/1', ...
    'autorouting', 'on');
add_line(modelName, 'One over C/1', 'Output voltage/1', ...
    'autorouting', 'on');
add_line(modelName, 'Output voltage/1', 'Inductor voltage balance/2', ...
    'autorouting', 'on');
add_line(modelName, 'Output voltage/1', 'Load conductance/1', ...
    'autorouting', 'on');
add_line(modelName, 'Load conductance/1', ...
    'Capacitor current balance/2', 'autorouting', 'on');
add_line(modelName, 'Inductor current/1', 'iL/1', 'autorouting', 'on');
add_line(modelName, 'Inductor current/1', 'Log inductor current/1', ...
    'autorouting', 'on');
add_line(modelName, 'Output voltage/1', 'Vout/1', 'autorouting', 'on');
add_line(modelName, 'Output voltage/1', 'Log output voltage/1', ...
    'autorouting', 'on');

set_param(modelName, 'SimulationCommand', 'update');
save_system(modelName, modelPath);
clear modelCleanup;
end

function validate_output_directory(outputDirectory)
isScalarText = ischar(outputDirectory) || ...
    (isstring(outputDirectory) && isscalar(outputDirectory));
if ~isScalarText || strlength(string(outputDirectory)) == 0
    error('AverageBuckSimulink:OutputDirectory', ...
        'Output directory must be a nonempty character vector or string.');
end
end

function validate_parameters(parameters)
requiredFields = {
    'input_voltage_V', ...
    'duty_cycle', ...
    'inductance_H', ...
    'inductor_resistance_Ohm', ...
    'capacitance_F', ...
    'load_resistance_Ohm', ...
    'end_time_s', ...
    'initial_inductor_current_A', ...
    'initial_output_voltage_V', ...
    'solver_max_step_s', ...
    'relative_tolerance', ...
    'absolute_tolerance'
};
if ~isstruct(parameters) || ~all(isfield(parameters, requiredFields))
    error('AverageBuckSimulink:Parameters', ...
        'Parameter structure is missing one or more required fields.');
end
for fieldIndex = 1:numel(requiredFields)
    value = parameters.(requiredFields{fieldIndex});
    if ~isnumeric(value) || ~isscalar(value) || ~isreal(value) || ...
            ~isfinite(value)
        error('AverageBuckSimulink:Parameters', ...
            'Every parameter must be a finite real numeric scalar.');
    end
end

positiveFields = {
    'input_voltage_V', ...
    'inductance_H', ...
    'capacitance_F', ...
    'load_resistance_Ohm', ...
    'end_time_s', ...
    'solver_max_step_s', ...
    'relative_tolerance', ...
    'absolute_tolerance'
};
for fieldIndex = 1:numel(positiveFields)
    if parameters.(positiveFields{fieldIndex}) <= 0
        error('AverageBuckSimulink:Parameters', ...
            'Voltage, components, duration, and solver settings must be positive.');
    end
end
if parameters.inductor_resistance_Ohm < 0
    error('AverageBuckSimulink:Parameters', ...
        'Inductor resistance must be nonnegative.');
end
if parameters.duty_cycle <= 0 || parameters.duty_cycle >= 1
    error('AverageBuckSimulink:Parameters', ...
        'Duty cycle must be strictly between zero and one.');
end
end

function close_model_if_loaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
