%% Native Simulink Averaged Buck Check
% Builds, compiles, simulates, and validates the generated block diagram.

clearvars; clc;

modelDirectory = fileparts(mfilename('fullpath'));
addpath(modelDirectory);

assert(~isempty(ver('simulink')) && license('test', 'Simulink'), ...
    'The native averaged buck check requires Simulink.');

parameters = average_buck_simulink_parameters();
temporaryDirectory = tempname;
mkdir(temporaryDirectory);
modelName = 'average_buck_simulink_model';
cleanup = onCleanup(@() clean_generated_model(modelName, temporaryDirectory));
modelPath = build_average_buck_simulink_model(...
    temporaryDirectory, parameters);

assert(isfile(modelPath), 'The builder must create a real SLX model file.');
load_system(modelPath);

expectedBlocks = {
    'Input voltage', 'Constant'; ...
    'Duty cycle', 'Constant'; ...
    'Average switch voltage', 'Product'; ...
    'Inductor voltage balance', 'Sum'; ...
    'One over L', 'Gain'; ...
    'Inductor current', 'Integrator'; ...
    'Inductor resistance', 'Gain'; ...
    'Capacitor current balance', 'Sum'; ...
    'One over C', 'Gain'; ...
    'Output voltage', 'Integrator'; ...
    'Load conductance', 'Gain'; ...
    'iL', 'Outport'; ...
    'Vout', 'Outport'; ...
    'Log inductor current', 'ToWorkspace'; ...
    'Log output voltage', 'ToWorkspace'
};
for blockIndex = 1:size(expectedBlocks, 1)
    blockPath = [modelName, '/', expectedBlocks{blockIndex, 1}];
    assert(strcmp(get_param(blockPath, 'BlockType'), ...
        expectedBlocks{blockIndex, 2}), ...
        'Generated model contains an unexpected block type.');
end

assert_connection(modelName, 'Input voltage', 1, ...
    'Average switch voltage', 1);
assert_connection(modelName, 'Duty cycle', 1, ...
    'Average switch voltage', 2);
assert_connection(modelName, 'Average switch voltage', 1, ...
    'Inductor voltage balance', 1);
assert_connection(modelName, 'Output voltage', 1, ...
    'Inductor voltage balance', 2);
assert_connection(modelName, 'Inductor resistance', 1, ...
    'Inductor voltage balance', 3);
assert_connection(modelName, 'Inductor current', 1, ...
    'Capacitor current balance', 1);
assert_connection(modelName, 'Load conductance', 1, ...
    'Capacitor current balance', 2);
assert_connection(modelName, 'Inductor voltage balance', 1, ...
    'One over L', 1);
assert_connection(modelName, 'One over L', 1, 'Inductor current', 1);
assert_connection(modelName, 'Capacitor current balance', 1, ...
    'One over C', 1);
assert_connection(modelName, 'One over C', 1, 'Output voltage', 1);

assert(abs(str2double(get_param([modelName, '/One over L'], 'Gain')) - ...
    1 / parameters.inductance_H) < 1e-12, ...
    'The generated inductance gain is incorrect.');
assert(abs(str2double(get_param([modelName, '/One over C'], 'Gain')) - ...
    1 / parameters.capacitance_F) < 1e-12, ...
    'The generated capacitance gain is incorrect.');
assert(abs(str2double(get_param(...
    [modelName, '/Inductor resistance'], 'Gain')) - ...
    parameters.inductor_resistance_Ohm) < 1e-12, ...
    'The generated inductor resistance is incorrect.');
assert(abs(str2double(get_param([modelName, '/Load conductance'], 'Gain')) - ...
    1 / parameters.load_resistance_Ohm) < 1e-12, ...
    'The generated load conductance is incorrect.');

set_param(modelName, 'SimulationCommand', 'update');
simulationOutput = sim(modelName);
inductorCurrent = simulationOutput.get('inductor_current');
outputVoltage = simulationOutput.get('output_voltage');

assert(isa(inductorCurrent, 'timeseries') && ...
    isa(outputVoltage, 'timeseries'), ...
    'Generated model must return timeseries signals for both states.');
time_s = inductorCurrent.Time(:);
inductorCurrent_A = inductorCurrent.Data(:);
outputVoltage_V = outputVoltage.Data(:);
assert(numel(time_s) > 100 && ...
    isequal(time_s, outputVoltage.Time(:)), ...
    'Both logged states must share a sufficiently resolved time grid.');
assert(all(isfinite(inductorCurrent_A)) && ...
    all(isfinite(outputVoltage_V)), ...
    'Simulated states must remain finite.');

systemMatrix = [
    -parameters.inductor_resistance_Ohm / parameters.inductance_H, ...
    -1 / parameters.inductance_H; ...
    1 / parameters.capacitance_F, ...
    -1 / (parameters.load_resistance_Ohm * parameters.capacitance_F)
];
inputVector = [
    parameters.duty_cycle * parameters.input_voltage_V / ...
    parameters.inductance_H; ...
    0
];
initialState = [
    parameters.initial_inductor_current_A; ...
    parameters.initial_output_voltage_V
];
steadyState = -(systemMatrix \ inputVector);
referenceState = zeros(2, numel(time_s));
for sampleIndex = 1:numel(time_s)
    referenceState(:, sampleIndex) = steadyState + ...
        expm(systemMatrix * time_s(sampleIndex)) * ...
        (initialState - steadyState);
end

maximumCurrentError_A = max(abs(inductorCurrent_A - ...
    referenceState(1, :)'));
maximumVoltageError_V = max(abs(outputVoltage_V - ...
    referenceState(2, :)'));
assert(maximumCurrentError_A < 1e-5, ...
    'Simulink inductor current differs from the exact state solution.');
assert(maximumVoltageError_V < 1e-4, ...
    'Simulink output voltage differs from the exact state solution.');
assert(abs(inductorCurrent_A(end) - referenceState(1, end)) < 1e-5 && ...
    abs(outputVoltage_V(end) - referenceState(2, end)) < 1e-4, ...
    'Final states must match the exact transient solution.');
assert(abs(inductorCurrent_A(end) - steadyState(1)) < 1e-4 && ...
    abs(outputVoltage_V(end) - steadyState(2)) < 1e-4, ...
    'Final states must settle to the lossy averaged buck solution.');

invalidParameters = parameters;
invalidParameters.inductance_H = 0;
invalidComponentRejected = false;
try
    build_average_buck_simulink_model(temporaryDirectory, invalidParameters);
catch validationError
    invalidComponentRejected = strcmp(validationError.identifier, ...
        'AverageBuckSimulink:Parameters');
end
assert(invalidComponentRejected, ...
    'Builder must reject a nonpositive electrical component.');

invalidParameters = parameters;
invalidParameters.input_voltage_V = 800 + 1i;
complexParameterRejected = false;
try
    build_average_buck_simulink_model(temporaryDirectory, invalidParameters);
catch validationError
    complexParameterRejected = strcmp(validationError.identifier, ...
        'AverageBuckSimulink:Parameters');
end
assert(complexParameterRejected, ...
    'Builder must reject complex-valued parameters.');

fprintf('Native Simulink averaged buck check passed.\n');
fprintf('Final output voltage: %.3f V\n', outputVoltage_V(end));
fprintf('Final inductor current: %.3f A\n', inductorCurrent_A(end));
fprintf('Maximum exact-state error: %.3e V, %.3e A\n', ...
    maximumVoltageError_V, maximumCurrentError_A);

function assert_connection(modelName, sourceBlock, sourcePort, ...
        destinationBlock, destinationPort)
sourceHandles = get_param([modelName, '/', sourceBlock], 'PortHandles');
destinationHandles = get_param(...
    [modelName, '/', destinationBlock], 'PortHandles');
lineHandle = get_param(destinationHandles.Inport(destinationPort), 'Line');
assert(lineHandle ~= -1 && ...
    get_param(lineHandle, 'SrcPortHandle') == ...
    sourceHandles.Outport(sourcePort), ...
    'Generated model contains an incorrect or missing connection.');
end

function clean_generated_model(modelName, temporaryDirectory)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if isfolder(temporaryDirectory)
    rmdir(temporaryDirectory, 's');
end
end
