%% Native Simulink Averaged Buck Check
% Builds, compiles, simulates, and validates the generated block diagram.

clearvars; clc;

modelDirectory = fileparts(mfilename('fullpath'));
addpath(modelDirectory);

assert(~isempty(ver('simulink')) && license('test', 'Simulink'), ...
    'The native averaged buck check requires Simulink.');

parameters = average_buck_simulink_parameters();
temporaryDirectory = tempname;
mkdir(temporaryDirectory);
modelName = 'average_buck_simulink_model';
modelPath = build_average_buck_simulink_model(...
    temporaryDirectory, parameters);
cleanup = onCleanup(@() clean_generated_model(modelName, temporaryDirectory));

assert(isfile(modelPath), 'The builder must create a real SLX model file.');
load_system(modelPath);

expectedBlocks = {
    'Input voltage', 'Constant'; ...
    'Duty cycle', 'Constant'; ...
    'Average switch voltage', 'Product'; ...
    'Inductor voltage balance', 'Sum'; ...
    'One over L', 'Gain'; ...
    'Inductor current', 'Integrator'; ...
    'Inductor resistance', 'Gain'; ...
    'Capacitor current balance', 'Sum'; ...
    'One over C', 'Gain'; ...
    'Output voltage', 'Integrator'; ...
    'Load conductance', 'Gain'; ...
    'iL', 'Outport'; ...
    'Vout', 'Outport'; ...
    'Log inductor current', 'ToWorkspace'; ...
    'Log output voltage', 'ToWorkspace'
};
for blockIndex = 1:size(expectedBlocks, 1)
    blockPath = [modelName, '/', expectedBlocks{blockIndex, 1}];
    assert(strcmp(get_param(blockPath, 'BlockType'), ...
        expectedBlocks{blockIndex, 2}), ...
        'Generated model contains an unexpected block type.');
end

assert_connection(modelName, 'Input voltage', 1, ...
    'Average switch voltage', 1);
assert_connection(modelName, 'Duty cycle', 1, ...
    'Average switch voltage', 2);
assert_connection(modelName, 'Average switch voltage', 1, ...
    'Inductor voltage balance', 1);
assert_connection(modelName, 'Output voltage', 1, ...
    'Inductor voltage balance', 2);
assert_connection(modelName, 'Inductor resistance', 1, ...
    'Inductor voltage balance', 3);
assert_connection(modelName, 'Inductor current', 1, ...
    'Capacitor current balance', 1);
assert_connection(modelName, 'Load conductance', 1, ...
    'Capacitor current balance', 2);
assert_connection(modelName, 'Inductor voltage balance', 1, ...
    'One over L', 1);
assert_connection(modelName, 'One over L', 1, 'Inductor current', 1);
assert_connection(modelName, 'Capacitor current balance', 1, ...
    'One over C', 1);
assert_connection(modelName, 'One over C', 1, 'Output voltage', 1);

assert(abs(str2double(get_param([modelName, '/One over L'], 'Gain')) - ...
    1 / parameters.inductance_H) < 1e-12, ...
    'The generated inductance gain is incorrect.');
assert(abs(str2double(get_param([modelName, '/One over C'], 'Gain')) - ...
    1 / parameters.capacitance_F) < 1e-12, ...
    'The generated capacitance gain is incorrect.');
assert(abs(str2double(get_param(...
    [modelName, '/Inductor resistance'], 'Gain')) - ...
    parameters.inductor_resistance_Ohm) < 1e-12, ...
    'The generated inductor resistance is incorrect.');
assert(abs(str2double(get_param([modelName, '/Load conductance'], 'Gain')) - ...
    1 / parameters.load_resistance_Ohm) < 1e-12, ...
    'The generated load conductance is incorrect.');

set_param(modelName, 'SimulationCommand', 'update');
simulationOutput = sim(modelName);
inductorCurrent = simulationOutput.get('inductor_current');
outputVoltage = simulationOutput.get('output_voltage');

assert(isa(inductorCurrent, 'timeseries') && ...
    isa(outputVoltage, 'timeseries'), ...
    'Generated model must return timeseries signals for both states.');
time_s = inductorCurrent.Time(:);
inductorCurrent_A = inductorCurrent.Data(:);
outputVoltage_V = outputVoltage.Data(:);
assert(numel(time_s) > 100 && ...
    isequal(time_s, outputVoltage.Time(:)), ...
    'Both logged states must share a sufficiently resolved time grid.');
assert(all(isfinite(inductorCurrent_A)) && ...
    all(isfinite(outputVoltage_V)), ...
    'Simulated states must remain finite.');

systemMatrix = [
    -parameters.inductor_resistance_Ohm / parameters.inductance_H, ...
    -1 / parameters.inductance_H; ...
    1 / parameters.capacitance_F, ...
    -1 / (parameters.load_resistance_Ohm * parameters.capacitance_F)
];
inputVector = [
    parameters.duty_cycle * parameters.input_voltage_V / ...
    parameters.inductance_H; ...
    0
];
initialState = [
    parameters.initial_inductor_current_A; ...
    parameters.initial_output_voltage_V
];
steadyState = -(systemMatrix \ inputVector);
referenceState = zeros(2, numel(time_s));
for sampleIndex = 1:numel(time_s)
    referenceState(:, sampleIndex) = steadyState + ...
        expm(systemMatrix * time_s(sampleIndex)) * ...
        (initialState - steadyState);
end

maximumCurrentError_A = max(abs(inductorCurrent_A - ...
    referenceState(1, :)'));
maximumVoltageError_V = max(abs(outputVoltage_V - ...
    referenceState(2, :)'));
assert(maximumCurrentError_A < 1e-5, ...
    'Simulink inductor current differs from the exact state solution.');
assert(maximumVoltageError_V < 1e-4, ...
    'Simulink output voltage differs from the exact state solution.');
assert(abs(inductorCurrent_A(end) - referenceState(1, end)) < 1e-5 && ...
    abs(outputVoltage_V(end) - referenceState(2, end)) < 1e-4, ...
    'Final states must match the exact transient solution.');
assert(abs(inductorCurrent_A(end) - steadyState(1)) < 1e-4 && ...
    abs(outputVoltage_V(end) - steadyState(2)) < 1e-4, ...
    'Final states must settle to the lossy averaged buck solution.');

invalidParameters = parameters;
invalidParameters.inductance_H = 0;
invalidComponentRejected = false;
try
    build_average_buck_simulink_model(temporaryDirectory, invalidParameters);
catch validationError
    invalidComponentRejected = strcmp(validationError.identifier, ...
        'AverageBuckSimulink:Parameters');
end
assert(invalidComponentRejected, ...
    'Builder must reject a nonpositive electrical component.');

invalidParameters = parameters;
invalidParameters.input_voltage_V = 800 + 1i;
complexParameterRejected = false;
try
    build_average_buck_simulink_model(temporaryDirectory, invalidParameters);
catch validationError
    complexParameterRejected = strcmp(validationError.identifier, ...
        'AverageBuckSimulink:Parameters');
end
assert(complexParameterRejected, ...
    'Builder must reject complex-valued parameters.');

close_system(modelName, 0);
verify_loaded_model_collision(modelName, @(directory) ...
    build_average_buck_simulink_model(directory, parameters), ...
    'AverageBuckSimulink:ModelAlreadyLoaded', 'cleanSaved');
verify_loaded_model_collision(modelName, @(directory) ...
    build_average_buck_simulink_model(directory, parameters), ...
    'AverageBuckSimulink:ModelAlreadyLoaded', 'unsaved');
verify_loaded_model_collision(modelName, @(directory) ...
    build_average_buck_simulink_model(directory, parameters), ...
    'AverageBuckSimulink:ModelAlreadyLoaded', 'dirtySaved');

fprintf('Native Simulink averaged buck check passed.\n');
fprintf('Final output voltage: %.3f V\n', outputVoltage_V(end));
fprintf('Final inductor current: %.3f A\n', inductorCurrent_A(end));
fprintf('Maximum exact-state error: %.3e V, %.3e A\n', ...
    maximumVoltageError_V, maximumCurrentError_A);

function assert_connection(modelName, sourceBlock, sourcePort, ...
        destinationBlock, destinationPort)
sourceHandles = get_param([modelName, '/', sourceBlock], 'PortHandles');
destinationHandles = get_param(...
    [modelName, '/', destinationBlock], 'PortHandles');
lineHandle = get_param(destinationHandles.Inport(destinationPort), 'Line');
assert(lineHandle ~= -1 && ...
    get_param(lineHandle, 'SrcPortHandle') == ...
    sourceHandles.Outport(sourcePort), ...
    'Generated model contains an incorrect or missing connection.');
end

function clean_generated_model(modelName, temporaryDirectory)
close_model_if_owned(modelName, temporaryDirectory);
if isfolder(temporaryDirectory)
    rmdir(temporaryDirectory, 's');
end
end

function verify_loaded_model_collision(modelName, buildFunction, errorId, ...
        fixtureState)
assert(~bdIsLoaded(modelName), ...
    'Collision fixture must not replace a pre-existing caller model.');
sourceDirectory = tempname;
targetDirectory = tempname;
mkdir(sourceDirectory);
mkdir(targetDirectory);
sourcePath = fullfile(sourceDirectory, [modelName, '.slx']);
targetPath = fullfile(targetDirectory, [modelName, '.slx']);
targetBytes = uint8([17, 34, 51, 68]);
write_binary_file(targetPath, targetBytes);
new_system(modelName);
modelHandle = get_param(modelName, 'Handle');
cleanup = onCleanup(@() clean_collision_fixture( ...
    modelName, modelHandle, sourceDirectory, targetDirectory));
isSaved = strcmp(fixtureState, 'cleanSaved') || ...
    strcmp(fixtureState, 'dirtySaved');
hasSentinel = strcmp(fixtureState, 'unsaved') || ...
    strcmp(fixtureState, 'dirtySaved');
sourceBytes = uint8.empty(0, 1);
if isSaved
    save_system(modelName, sourcePath);
    sourceBytes = read_binary_file(sourcePath);
end
if hasSentinel
    add_block('simulink/Sources/Constant', [modelName, '/Caller sentinel'], ...
        'Value', '123', 'Position', [30, 30, 100, 60]);
    modelWorkspace = get_param(modelName, 'ModelWorkspace');
    assignin(modelWorkspace, 'callerSentinel', 42);
end
expectedDirty = get_param(modelName, 'Dirty');
if strcmp(fixtureState, 'cleanSaved')
    assert(strcmp(expectedDirty, 'off'), ...
        'Clean saved collision fixture must start clean.');
else
    assert(strcmp(expectedDirty, 'on'), ...
        'Dirty or unsaved collision fixture must start dirty.');
end

collisionRejected = false;
try
    buildFunction(targetDirectory);
catch buildError
    collisionRejected = strcmp(buildError.identifier, errorId);
end
assert(collisionRejected, ...
    'Builder must reject a same-name model that is already loaded.');
assert(bdIsLoaded(modelName), 'Loaded caller model must remain loaded.');
assert(get_param(modelName, 'Handle') == modelHandle, ...
    'Loaded caller model handle must remain unchanged.');
assert(strcmp(get_param(modelName, 'Dirty'), expectedDirty), ...
    'Loaded caller model dirty state must remain unchanged.');
if isSaved
    assert(strcmpi(get_param(modelName, 'FileName'), sourcePath), ...
        'Loaded caller model path must remain unchanged.');
    assert(isequal(read_binary_file(sourcePath), sourceBytes), ...
        'Loaded caller model file bytes must remain unchanged.');
else
    assert(strcmp(get_param(modelName, 'FileName'), ''), ...
        'Unsaved caller model must remain unsaved.');
    assert(~isfile(sourcePath), ...
        'Unsaved caller model must not gain a source file.');
end
if hasSentinel
    assert(strcmp(get_param([modelName, '/Caller sentinel'], 'Value'), '123'), ...
        'Loaded caller model content must remain unchanged.');
    assert(evalin(modelWorkspace, 'callerSentinel') == 42, ...
        'Loaded caller model workspace must remain unchanged.');
end
assert(isequal(read_binary_file(targetPath), targetBytes(:)), ...
    'Target model file must remain unchanged after rejection.');
clear cleanup;
end

function clean_collision_fixture(modelName, modelHandle, ...
        sourceDirectory, targetDirectory)
if bdIsLoaded(modelName) && ...
        get_param(modelName, 'Handle') == modelHandle
    close_system(modelName, 0);
end
if isfolder(sourceDirectory)
    rmdir(sourceDirectory, 's');
end
if isfolder(targetDirectory)
    rmdir(targetDirectory, 's');
end
end

function close_model_if_owned(modelName, directory)
if ~bdIsLoaded(modelName)
    return;
end
fileName = string(get_param(modelName, 'FileName'));
if strlength(fileName) == 0
    return;
end
rootDirectory = string(fullfile(directory, filesep));
if startsWith(fileName, rootDirectory, 'IgnoreCase', true)
    close_system(modelName, 0);
end
end

function write_binary_file(filePath, bytes)
fileIdentifier = fopen(filePath, 'w');
assert(fileIdentifier > 0, 'Could not create binary fixture file.');
fwrite(fileIdentifier, bytes, 'uint8');
fclose(fileIdentifier);
end

function bytes = read_binary_file(filePath)
fileIdentifier = fopen(filePath, 'r');
assert(fileIdentifier > 0, 'Could not open binary fixture file.');
bytes = fread(fileIdentifier, inf, '*uint8');
fclose(fileIdentifier);
end
