function profiles = bess_dc_reserve_dynamic_profiles()
%BESS_DC_RESERVE_DYNAMIC_PROFILES Return the prescribed request profiles.

profiles = struct( ...
    'id', {"rising_discharge", "interrupted_discharge", "charge_recovery"}, ...
    'request_breakpoints_s', { ...
        [0; 140; 280], [0; 105; 210; 315], [0; 105; 210; 315]}, ...
    'requested_converter_power_W', { ...
        1e3*[150; 250; 325], 1e3*[300; 0; 300; 0], ...
        1e3*[300; -120; 300; 0]}, ...
    'description', { ...
        "Three increasing discharge plateaus", ...
        "Two discharge blocks separated by idle intervals", ...
        "Two discharge blocks separated by prescribed charging"});
end
