%% BESS DC Reserve Prescribed Dynamic-Profile Sensitivity Check
% Verifies nine fixed profile/reserve cases without cross-profile claims.

clearvars;
clc;

modelDirectory = fileparts(mfilename('fullpath'));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory);

parameters = bess_dc_reserve_default_parameters();
profiles = bess_dc_reserve_dynamic_profiles();
reserveLevels = [0.10, 0.15, 0.20];
assert(isequal(string({profiles.id}), ...
    ["rising_discharge", "interrupted_discharge", "charge_recovery"]) && ...
    isequal({profiles.request_breakpoints_s}, ...
    {[0; 140; 280], [0; 105; 210; 315], [0; 105; 210; 315]}) && ...
    isequal({profiles.requested_converter_power_W}, ...
    {1e3*[150; 250; 325], 1e3*[300; 0; 300; 0], ...
    1e3*[300; -120; 300; 0]}) && ...
    isequal(reserveLevels, [0.10, 0.15, 0.20]), ...
    'Profile vectors and reserve floors must retain their preregistered values.');
sensitivity = evaluate_bess_dc_reserve_profile_sensitivity( ...
    parameters, profiles, reserveLevels);
repeatSensitivity = evaluate_bess_dc_reserve_profile_sensitivity( ...
    parameters, profiles, reserveLevels);
assert(isequal(sensitivity, repeatSensitivity), ...
    'Repeated dynamic-profile evaluation must be deterministic.');

profileCount = numel(profiles);
reserveCount = numel(reserveLevels);
expectedIds = repelem(string({profiles.id})', reserveCount);
assert(height(sensitivity) == profileCount*reserveCount && ...
    isequal(sensitivity.profileId, expectedIds) && ...
    all(isfinite(sensitivity{:, 2:end}), 'all'), ...
    'The sensitivity must contain nine finite rows in prescribed order.');
assert(all(sensitivity.minimumReserveSoc == ...
    repmat(reserveLevels', profileCount, 1)), ...
    'Reserve floors must retain their prescribed within-profile order.');

deliveredEnergy_kWh = reshape( ...
    sensitivity.deliveredDischargeEnergy_kWh, reserveCount, profileCount);
curtailedEnergy_kWh = reshape( ...
    sensitivity.curtailedDischargeEnergy_kWh, reserveCount, profileCount);
minimumSoc = reshape(sensitivity.minimumSoc, reserveCount, profileCount);
curtailmentTime_s = reshape( ...
    sensitivity.curtailmentTime_s, reserveCount, profileCount);
assert(all(diff(deliveredEnergy_kWh, 1, 1) <= 1e-12, 'all') && ...
    all(diff(curtailedEnergy_kWh, 1, 1) >= -1e-12, 'all') && ...
    all(diff(minimumSoc, 1, 1) >= -1e-12, 'all') && ...
    all(diff(curtailmentTime_s, 1, 1) >= -1e-12, 'all'), ...
    ['Within each prescribed profile, a higher reserve must trade ', ...
    'delivered discharge energy for retained SOC.']);

requestedDischarge_kWh = reshape( ...
    sensitivity.requestedDischargeEnergy_kWh, reserveCount, profileCount);
requestedCharge_kWh = reshape( ...
    sensitivity.requestedChargeEnergy_kWh, reserveCount, profileCount);
assert(all(abs(diff(requestedDischarge_kWh, 1, 1)) < 1e-12, 'all') && ...
    all(abs(diff(requestedCharge_kWh, 1, 1)) < 1e-12, 'all'), ...
    'Each prescribed request must remain identical across reserve floors.');
assert(max(abs(sensitivity.requestedDischargeEnergy_kWh - ...
    sensitivity.deliveredDischargeEnergy_kWh - ...
    sensitivity.curtailedDischargeEnergy_kWh)) < 1e-10 && ...
    max(abs(sensitivity.requestedChargeEnergy_kWh - ...
    sensitivity.acceptedChargeEnergy_kWh - ...
    sensitivity.curtailedChargeEnergy_kWh)) < 1e-10 && ...
    all(sensitivity.curtailedChargeEnergy_kWh >= -1e-12), ...
    'Delivered/accepted and curtailed energy must partition each request.');

assert(all(sensitivity.peakDischargeCurrent_A <= ...
    parameters.maximum_discharge_current_A + 1e-9) && ...
    all(sensitivity.peakChargeCurrent_A <= ...
    parameters.maximum_charge_current_A + 1e-9) && ...
    all(sensitivity.minimumSoc >= ...
    sensitivity.minimumReserveSoc - 1e-12) && ...
    all(sensitivity.minimumDcVoltage_V >= ...
    parameters.minimum_dc_voltage_V - 1e-9) && ...
    all(sensitivity.maximumDcVoltage_V <= ...
    parameters.maximum_dc_voltage_V + 1e-9), ...
    'Every case must preserve current, SOC, and DC-voltage bounds.');
assert(max(abs(sensitivity.batteryEnergyResidual_J)) < 1e-6 && ...
    max(abs(sensitivity.dcLinkEnergyResidual_J)) < 1e-6 && ...
    max(abs(sensitivity.stateBatteryEnergyResidual_J)) < 1e-6 && ...
    max(abs(sensitivity.stateDcLinkEnergyResidual_J)) < 1e-6, ...
    'Summary and independently state-derived energy balances must close.');

fineParameters = parameters;
fineParameters.sample_time_s = 0.05;
fineSensitivity = evaluate_bess_dc_reserve_profile_sensitivity( ...
    fineParameters, profiles, reserveLevels);
assert(max(abs(fineSensitivity.deliveredDischargeEnergy_kWh - ...
    sensitivity.deliveredDischargeEnergy_kWh)) < 0.005 && ...
    max(abs(fineSensitivity.curtailedDischargeEnergy_kWh - ...
    sensitivity.curtailedDischargeEnergy_kWh)) < 0.005 && ...
    max(abs(fineSensitivity.acceptedChargeEnergy_kWh - ...
    sensitivity.acceptedChargeEnergy_kWh)) < 1e-6 && ...
    max(abs(fineSensitivity.finalSoc - sensitivity.finalSoc)) < 2e-5 && ...
    max(abs(fineSensitivity.curtailmentTime_s - ...
    sensitivity.curtailmentTime_s)) < 0.15 && ...
    max(abs(fineSensitivity.minimumDcVoltage_V - ...
    sensitivity.minimumDcVoltage_V)) < 1e-6 && ...
    max(abs(fineSensitivity.maximumDcVoltage_V - ...
    sensitivity.maximumDcVoltage_V)) < 1e-6, ...
    'All nine cases must converge when the time grid is doubled.');

zeroProfile = struct('id', "zero_request", ...
    'request_breakpoints_s', 0, 'requested_converter_power_W', 0, ...
    'description', "Zero-request identity");
zeroSensitivity = evaluate_bess_dc_reserve_profile_sensitivity( ...
    parameters, zeroProfile, 0.20);
zeroMetrics = [zeroSensitivity.requestedDischargeEnergy_kWh, ...
    zeroSensitivity.deliveredDischargeEnergy_kWh, ...
    zeroSensitivity.curtailedDischargeEnergy_kWh, ...
    zeroSensitivity.requestedChargeEnergy_kWh, ...
    zeroSensitivity.acceptedChargeEnergy_kWh, ...
    zeroSensitivity.curtailedChargeEnergy_kWh, ...
    zeroSensitivity.peakDischargeCurrent_A, ...
    zeroSensitivity.peakChargeCurrent_A, ...
    zeroSensitivity.ohmicLossEnergy_kWh];
assert(all(zeroMetrics == 0, 'all') && ...
    zeroSensitivity.minimumSoc == parameters.initial_soc && ...
    zeroSensitivity.finalSoc == parameters.initial_soc && ...
    zeroSensitivity.minimumDcVoltage_V == parameters.initial_dc_voltage_V && ...
    zeroSensitivity.maximumDcVoltage_V == parameters.initial_dc_voltage_V && ...
    abs(zeroSensitivity.stateBatteryEnergyResidual_J) < 1e-12 && ...
    abs(zeroSensitivity.stateDcLinkEnergyResidual_J) < 1e-12, ...
    'A zero request must preserve exact zero-flow state identity.');

invalidProfiles = profiles;
invalidProfiles(2).id = invalidProfiles(1).id;
assert_error(@() evaluate_bess_dc_reserve_profile_sensitivity( ...
    parameters, invalidProfiles, reserveLevels), ...
    'BessDcProfileSensitivity:Profiles');
invalidProfiles = rmfield(profiles, 'description');
assert_error(@() evaluate_bess_dc_reserve_profile_sensitivity( ...
    parameters, invalidProfiles, reserveLevels), ...
    'BessDcProfileSensitivity:Profiles');
invalidProfiles = profiles(1);
invalidProfiles.requested_converter_power_W = [100e3; 200e3];
assert_error(@() evaluate_bess_dc_reserve_profile_sensitivity( ...
    parameters, invalidProfiles, reserveLevels), ...
    'BessDcProfileSensitivity:Profiles');
invalidProfiles = profiles(1);
invalidProfiles.request_breakpoints_s(2) = 140.05;
assert_error(@() evaluate_bess_dc_reserve_profile_sensitivity( ...
    parameters, invalidProfiles, reserveLevels), ...
    'BessDcReserve:TimeGrid');
assert_error(@() evaluate_bess_dc_reserve_profile_sensitivity( ...
    parameters, profiles, [0.20, 0.15]), ...
    'BessDcEnvelope:ReserveLevels');

fprintf('BESS DC reserve prescribed dynamic-profile check passed.\n');
fprintf('%d cases: %d profiles by %d reserve floors.\n', ...
    height(sensitivity), profileCount, reserveCount);
fprintf('Delivered discharge energy: %.3f to %.3f kWh.\n', ...
    min(sensitivity.deliveredDischargeEnergy_kWh), ...
    max(sensitivity.deliveredDischargeEnergy_kWh));
fprintf('Curtailment time: %.1f to %.1f s.\n', ...
    min(sensitivity.curtailmentTime_s), ...
    max(sensitivity.curtailmentTime_s));

function assert_error(functionHandle, expectedIdentifier)
try
    functionHandle();
catch errorDetails
    assert(strcmp(errorDetails.identifier, expectedIdentifier), ...
        'Expected error %s but received %s.', ...
        expectedIdentifier, errorDetails.identifier);
    return;
end
error('BessDcProfileSensitivity:MissingError', ...
    'Expected error %s was not raised.', expectedIdentifier);
end
