%% BESS DC Reserve Constant-Request Sensitivity Check
% Verifies deterministic saturation trends across reserve assumptions.

clearvars;
clc;

modelDirectory = fileparts(mfilename('fullpath'));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory);

parameters = bess_dc_reserve_default_parameters();
reserveLevels = [0.10, 0.15, 0.20];
requestedPower_W = [0, 100e3, 200e3, 250e3, 300e3, 325e3];
envelope = evaluate_bess_dc_reserve_envelope( ...
    parameters, reserveLevels, requestedPower_W);
repeatEnvelope = evaluate_bess_dc_reserve_envelope( ...
    parameters, reserveLevels, requestedPower_W);
assert(isequal(envelope, repeatEnvelope), ...
    'Repeated operating-envelope evaluation must be deterministic.');
assert(height(envelope) == numel(reserveLevels)*numel(requestedPower_W) && ...
    all(all(isfinite(envelope{:,:}))), ...
    'The envelope must contain one finite row per parameter pair.');

reserveCount = numel(reserveLevels);
requestCount = numel(requestedPower_W);
deliveredEnergy_kWh = reshape( ...
    envelope.deliveredDischargeEnergy_kWh, requestCount, reserveCount)';
curtailedEnergy_kWh = reshape( ...
    envelope.curtailedDischargeEnergy_kWh, requestCount, reserveCount)';
minimumSoc = reshape(envelope.minimumSoc, requestCount, reserveCount)';
socTaperTime_s = reshape( ...
    envelope.socTaperActiveTime_s, requestCount, reserveCount)';
curtailmentTime_s = reshape( ...
    envelope.curtailmentTime_s, requestCount, reserveCount)';
averageDeliveredPower_kW = reshape( ...
    envelope.averageDeliveredPower_kW, requestCount, reserveCount)';

assert(all(diff(deliveredEnergy_kWh, 1, 1) <= 1e-12, 'all') && ...
    all(diff(curtailedEnergy_kWh, 1, 1) >= -1e-12, 'all') && ...
    all(diff(minimumSoc, 1, 1) >= -1e-12, 'all') && ...
    all(diff(curtailmentTime_s, 1, 1) >= -1e-12, 'all'), ...
    'Higher reserve settings must trade delivered energy for retained SOC.');
assert(all(diff(curtailedEnergy_kWh, 1, 2) >= -1e-12, 'all') && ...
    all(diff(socTaperTime_s, 1, 2) >= -1e-12, 'all') && ...
    all(diff(curtailmentTime_s, 1, 2) >= -1e-12, 'all') && ...
    all(diff(minimumSoc, 1, 2) <= 1e-12, 'all'), ...
    'Larger requests must not reduce curtailment or SOC-taper exposure.');
assert(all(averageDeliveredPower_kW <= requestedPower_W/1000 + 1e-9, ...
    'all') && averageDeliveredPower_kW(end, end) < ...
    averageDeliveredPower_kW(end, 4), ...
    ['The sensitivity must retain the high-request saturation result ', ...
    'without claiming delivered energy is monotonic in the request.']);
assert(all(envelope.peakDischargeCurrent_A <= ...
    parameters.maximum_discharge_current_A + 1e-9) && ...
    all(envelope.minimumSoc >= envelope.minimumReserveSoc - 1e-12) && ...
    all(envelope.minimumDcVoltage_V >= ...
        parameters.minimum_dc_voltage_V - 1e-9) && ...
    all(envelope.maximumDcVoltage_V <= ...
        parameters.maximum_dc_voltage_V + 1e-9), ...
    'Every sensitivity case must preserve current, SOC, and DC-voltage bounds.');
assert(max(abs(envelope.requestedDischargeEnergy_kWh - ...
    envelope.deliveredDischargeEnergy_kWh - ...
    envelope.curtailedDischargeEnergy_kWh)) < 1e-10, ...
    'Delivered and curtailed energy must partition the discharge request.');
assert(max(abs(envelope.batteryEnergyResidual_J)) < 1e-6 && ...
    max(abs(envelope.dcLinkEnergyResidual_J)) < 1e-6, ...
    'Every envelope case must close battery and DC-link energy balances.');

fineParameters = parameters;
fineParameters.sample_time_s = 0.05;
fineEnvelope = evaluate_bess_dc_reserve_envelope( ...
    fineParameters, reserveLevels, requestedPower_W);
assert(max(abs(fineEnvelope.deliveredDischargeEnergy_kWh - ...
    envelope.deliveredDischargeEnergy_kWh)) < 0.05 && ...
    max(abs(fineEnvelope.minimumSoc - envelope.minimumSoc)) < 2e-4 && ...
    max(abs(fineEnvelope.curtailmentTime_s - ...
    envelope.curtailmentTime_s)) < 0.2, ...
    'Envelope energy and SOC must converge when the time grid is doubled.');

assert_error(@() evaluate_bess_dc_reserve_envelope( ...
    parameters, [0.20, 0.18], requestedPower_W), ...
    'BessDcEnvelope:ReserveLevels');
assert_error(@() evaluate_bess_dc_reserve_envelope( ...
    parameters, [0.15, parameters.initial_soc], requestedPower_W), ...
    'BessDcEnvelope:ReserveLevels');
assert_error(@() evaluate_bess_dc_reserve_envelope( ...
    parameters, reserveLevels, [100e3, 100e3]), ...
    'BessDcEnvelope:RequestedPower');
assert_error(@() evaluate_bess_dc_reserve_envelope( ...
    parameters, reserveLevels, [-1, 100e3]), ...
    'BessDcEnvelope:RequestedPower');

fprintf('BESS DC reserve constant-request sensitivity check passed.\n');
fprintf('%d cases: reserve %.2f to %.2f, request %.0f to %.0f kW\n', ...
    height(envelope), reserveLevels(1), reserveLevels(end), ...
    requestedPower_W(1)/1000, requestedPower_W(end)/1000);
fprintf('Maximum average delivered power: %.3f kW\n', ...
    max(envelope.averageDeliveredPower_kW));
fprintf('Maximum curtailed discharge energy: %.3f kWh\n', ...
    max(envelope.curtailedDischargeEnergy_kWh));

function assert_error(functionHandle, expectedIdentifier)
try
    functionHandle();
catch errorDetails
    assert(strcmp(errorDetails.identifier, expectedIdentifier), ...
        'Expected error %s but received %s.', ...
        expectedIdentifier, errorDetails.identifier);
    return;
end
error('BessDcEnvelope:MissingError', ...
    'Expected error %s was not raised.', expectedIdentifier);
end
