clear;
close all;
clc;

modelDirectory = fileparts(mfilename('fullpath'));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory);

parameters = bess_dc_reserve_default_parameters();
result = simulate_bess_dc_reserve(parameters);
metrics = summarize_bess_dc_reserve(result);

assert(all(isfinite(result.soc)) && all(isfinite(result.dc_voltage_V)) && ...
    all(isfinite(result.battery_current_A)), ...
    'All states and currents must remain finite.');
assert(all(result.soc >= parameters.minimum_reserve_soc - 1e-12) && ...
    all(result.soc <= parameters.maximum_soc + 1e-12), ...
    'SOC must remain within reserve and maximum bounds.');
assert(all(result.dc_voltage_V >= ...
    parameters.minimum_dc_voltage_V - 1e-9) && ...
    all(result.dc_voltage_V <= ...
    parameters.maximum_dc_voltage_V + 1e-9), ...
    'DC-link voltage must remain within configured bounds.');
assert(all(result.battery_current_A <= ...
    parameters.maximum_discharge_current_A + 1e-9) && ...
    all(result.battery_current_A >= ...
    -parameters.maximum_charge_current_A - 1e-9), ...
    'Battery current must remain within configured limits.');
averageTerminalVoltage_V = 0.5*(result.terminal_voltage_start_V + ...
    result.terminal_voltage_end_V);
assert(max(abs(result.battery_power_W - ...
    averageTerminalVoltage_V.*result.battery_current_A)) < 1e-7, ...
    'Battery terminal power must match average terminal voltage and current.');
assert(metrics.curtailed_discharge_energy_kWh > 1 && ...
    metrics.reserve_limited_time_s > 60, ...
    'Canonical profile must exercise reserve-based power curtailment.');
firstDischargeEnd = find(result.time_s >= 120, 1);
chargeEnd = find(result.time_s >= 240, 1);
assert(result.soc(chargeEnd) > result.soc(firstDischargeEnd) + 0.01, ...
    'The charging interval must recover a measurable amount of SOC.');
assert(abs(metrics.battery_energy_residual_J) < 1e-6 && ...
    abs(metrics.dc_link_energy_residual_J) < 1e-6, ...
    'Battery and DC-link energy balances must close.');

fineParameters = parameters;
fineParameters.sample_time_s = 0.05;
fineResult = simulate_bess_dc_reserve(fineParameters);
fineMetrics = summarize_bess_dc_reserve(fineResult);
assert(abs(fineMetrics.final_soc - metrics.final_soc) < 2e-4 && ...
    abs(fineMetrics.curtailed_discharge_energy_kWh - ...
    metrics.curtailed_discharge_energy_kWh) < 0.05 && ...
    abs(fineMetrics.minimum_dc_voltage_V - ...
    metrics.minimum_dc_voltage_V) < 1, ...
    'Reserve and energy metrics must converge when the time grid is doubled.');

invalidParameters = parameters;
invalidParameters.capacity_Ah = 0;
assert_error(@() simulate_bess_dc_reserve(invalidParameters), ...
    'BessDcReserve:Parameters');
invalidParameters = parameters;
invalidParameters.initial_soc = 0.1;
assert_error(@() simulate_bess_dc_reserve(invalidParameters), ...
    'BessDcReserve:SocLimits');
invalidParameters = parameters;
invalidParameters.minimum_dc_voltage_V = 760;
assert_error(@() simulate_bess_dc_reserve(invalidParameters), ...
    'BessDcReserve:DcLimits');
invalidParameters = parameters;
invalidParameters.maximum_discharge_current_A = 1e6;
assert_error(@() simulate_bess_dc_reserve(invalidParameters), ...
    'BessDcReserve:CurrentLimit');
invalidParameters = parameters;
invalidParameters.dc_energy_feedback_gain_per_s = 11;
assert_error(@() simulate_bess_dc_reserve(invalidParameters), ...
    'BessDcReserve:ControlGain');
invalidParameters = parameters;
invalidParameters.request_breakpoints_s = [0; 120.05; 240; 360];
assert_error(@() simulate_bess_dc_reserve(invalidParameters), ...
    'BessDcReserve:TimeGrid');
invalidParameters = parameters;
invalidParameters.requested_converter_power_W = [1; 2];
assert_error(@() simulate_bess_dc_reserve(invalidParameters), ...
    'BessDcReserve:Profile');

fprintf('BESS DC reserve check passed.\n');
fprintf('SOC: minimum %.4f, final %.4f\n', ...
    metrics.minimum_soc, metrics.final_soc);
fprintf('DC-link voltage: %.2f V to %.2f V\n', ...
    metrics.minimum_dc_voltage_V, metrics.maximum_dc_voltage_V);
fprintf('Delivered/curtailed discharge energy: %.3f / %.3f kWh\n', ...
    metrics.delivered_discharge_energy_kWh, ...
    metrics.curtailed_discharge_energy_kWh);
fprintf('Accepted charge energy: %.3f kWh\n', ...
    metrics.accepted_charge_energy_kWh);
fprintf('Reserve-limited operation: %.1f s\n', ...
    metrics.reserve_limited_time_s);
fprintf('Peak discharge/charge current: %.1f / %.1f A\n', ...
    metrics.peak_discharge_current_A, metrics.peak_charge_current_A);

function assert_error(functionHandle, expectedIdentifier)
try
    functionHandle();
catch errorDetails
    assert(strcmp(errorDetails.identifier, expectedIdentifier), ...
        'Expected error %s but received %s.', ...
        expectedIdentifier, errorDetails.identifier);
    return;
end
error('BessDcReserve:MissingError', ...
    'Expected error %s was not raised.', expectedIdentifier);
end
