function result = simulate_bess_dc_reserve(parameters)
%SIMULATE_BESS_DC_RESERVE Simulate SOC-aware battery and DC-link power flow.
% Positive converter power discharges the battery toward the AC-side plant;
% negative converter power charges it. Current is positive on discharge.

if nargin < 1
    parameters = bess_dc_reserve_default_parameters();
end
parameters = validate_parameters(parameters);

timeStep_s = parameters.sample_time_s;
intervalCount = round(parameters.end_time_s/timeStep_s);
time_s = (0:intervalCount)'*timeStep_s;
intervalTime_s = time_s(1:end-1);
requestedPower_W = requested_power_profile(parameters, intervalTime_s);

soc = zeros(intervalCount + 1, 1);
dcEnergy_J = zeros(intervalCount + 1, 1);
soc(1) = parameters.initial_soc;
dcEnergy_J(1) = 0.5*parameters.dc_link_capacitance_F* ...
    parameters.initial_dc_voltage_V^2;

batteryCurrent_A = zeros(intervalCount, 1);
batteryPower_W = zeros(intervalCount, 1);
converterPower_W = zeros(intervalCount, 1);
openCircuitVoltage_V = zeros(intervalCount, 1);
terminalVoltageStart_V = zeros(intervalCount, 1);
terminalVoltageEnd_V = zeros(intervalCount, 1);
dischargeAvailability = zeros(intervalCount, 1);
chargeAvailability = zeros(intervalCount, 1);
minimumBatteryPower_W = zeros(intervalCount, 1);
maximumBatteryPower_W = zeros(intervalCount, 1);

capacityAs = parameters.capacity_Ah*3600;
minimumDcEnergy_J = 0.5*parameters.dc_link_capacitance_F* ...
    parameters.minimum_dc_voltage_V^2;
maximumDcEnergy_J = 0.5*parameters.dc_link_capacitance_F* ...
    parameters.maximum_dc_voltage_V^2;
referenceDcEnergy_J = 0.5*parameters.dc_link_capacitance_F* ...
    parameters.dc_voltage_reference_V^2;
effectiveResistance_Ohm = parameters.internal_resistance_Ohm + ...
    0.5*parameters.ocv_slope_V_per_soc*timeStep_s/capacityAs;

for intervalIndex = 1:intervalCount
    currentSoc = soc(intervalIndex);
    openCircuitVoltage_V(intervalIndex) = ocv(parameters, currentSoc);
    dischargeAvailability(intervalIndex) = clamp( ...
        (currentSoc - parameters.minimum_reserve_soc)/ ...
        parameters.reserve_taper_width_soc, 0, 1);
    chargeAvailability(intervalIndex) = clamp( ...
        (parameters.maximum_soc - currentSoc)/ ...
        parameters.charge_taper_width_soc, 0, 1);

    dischargeCurrentLimit_A = min( ...
        parameters.maximum_discharge_current_A* ...
        dischargeAvailability(intervalIndex), ...
        max(0, currentSoc - parameters.minimum_reserve_soc)* ...
        capacityAs/timeStep_s);
    chargeCurrentLimit_A = min( ...
        parameters.maximum_charge_current_A* ...
        chargeAvailability(intervalIndex), ...
        max(0, parameters.maximum_soc - currentSoc)* ...
        capacityAs/timeStep_s);
    maximumBatteryPower_W(intervalIndex) = current_to_power( ...
        openCircuitVoltage_V(intervalIndex), effectiveResistance_Ohm, ...
        dischargeCurrentLimit_A);
    minimumBatteryPower_W(intervalIndex) = current_to_power( ...
        openCircuitVoltage_V(intervalIndex), effectiveResistance_Ohm, ...
        -chargeCurrentLimit_A);

    energyError_J = referenceDcEnergy_J - dcEnergy_J(intervalIndex);
    unconstrainedBatteryPower_W = requestedPower_W(intervalIndex) + ...
        parameters.dc_energy_feedback_gain_per_s*energyError_J;
    batteryPower_W(intervalIndex) = clamp( ...
        unconstrainedBatteryPower_W, ...
        minimumBatteryPower_W(intervalIndex), ...
        maximumBatteryPower_W(intervalIndex));
    batteryCurrent_A(intervalIndex) = power_to_current( ...
        openCircuitVoltage_V(intervalIndex), effectiveResistance_Ohm, ...
        batteryPower_W(intervalIndex));

    minimumConverterPower_W = batteryPower_W(intervalIndex) - ...
        (maximumDcEnergy_J - dcEnergy_J(intervalIndex))/timeStep_s;
    maximumConverterPower_W = batteryPower_W(intervalIndex) + ...
        (dcEnergy_J(intervalIndex) - minimumDcEnergy_J)/timeStep_s;
    converterPower_W(intervalIndex) = clamp( ...
        requestedPower_W(intervalIndex), ...
        minimumConverterPower_W, maximumConverterPower_W);

    soc(intervalIndex + 1) = currentSoc - ...
        batteryCurrent_A(intervalIndex)*timeStep_s/capacityAs;
    dcEnergy_J(intervalIndex + 1) = dcEnergy_J(intervalIndex) + ...
        (batteryPower_W(intervalIndex) - ...
        converterPower_W(intervalIndex))*timeStep_s;
    terminalVoltageStart_V(intervalIndex) = ...
        openCircuitVoltage_V(intervalIndex) - ...
        parameters.internal_resistance_Ohm* ...
        batteryCurrent_A(intervalIndex);
    terminalVoltageEnd_V(intervalIndex) = ocv(parameters, ...
        soc(intervalIndex + 1)) - parameters.internal_resistance_Ohm* ...
        batteryCurrent_A(intervalIndex);
end

dcVoltage_V = sqrt(2*dcEnergy_J/parameters.dc_link_capacitance_F);
averageOcv_V = 0.5*(ocv(parameters, soc(1:end-1)) + ...
    ocv(parameters, soc(2:end)));
chemicalPower_W = averageOcv_V.*batteryCurrent_A;
ohmicLossPower_W = parameters.internal_resistance_Ohm* ...
    batteryCurrent_A.^2;

result.time_s = time_s;
result.interval_time_s = intervalTime_s;
result.requested_converter_power_W = requestedPower_W;
result.converter_power_W = converterPower_W;
result.battery_power_W = batteryPower_W;
result.battery_current_A = batteryCurrent_A;
result.soc = soc;
result.dc_energy_J = dcEnergy_J;
result.dc_voltage_V = dcVoltage_V;
result.open_circuit_voltage_V = openCircuitVoltage_V;
result.terminal_voltage_start_V = terminalVoltageStart_V;
result.terminal_voltage_end_V = terminalVoltageEnd_V;
result.discharge_availability = dischargeAvailability;
result.charge_availability = chargeAvailability;
result.minimum_battery_power_W = minimumBatteryPower_W;
result.maximum_battery_power_W = maximumBatteryPower_W;
result.chemical_power_W = chemicalPower_W;
result.ohmic_loss_power_W = ohmicLossPower_W;
result.parameters = parameters;
end

function values = requested_power_profile(parameters, time_s)
values = zeros(size(time_s));
for profileIndex = 1:numel(parameters.request_breakpoints_s)
    values(time_s >= parameters.request_breakpoints_s(profileIndex)) = ...
        parameters.requested_converter_power_W(profileIndex);
end
end
function voltage_V = ocv(parameters, soc)
voltage_V = parameters.ocv_intercept_V + ...
    parameters.ocv_slope_V_per_soc*soc;
end

function power_W = current_to_power(ocv_V, effectiveResistance_Ohm, current_A)
power_W = (ocv_V - effectiveResistance_Ohm*current_A)*current_A;
end

function current_A = power_to_current(ocv_V, effectiveResistance_Ohm, power_W)
discriminant = ocv_V^2 - 4*effectiveResistance_Ohm*power_W;
if discriminant < -1e-8
    error('BessDcReserve:PowerLimit', ...
        'Battery power exceeds the real current-solution boundary.');
end
current_A = (ocv_V - sqrt(max(discriminant, 0)))/ ...
    (2*effectiveResistance_Ohm);
end

function value = clamp(value, lowerBound, upperBound)
value = min(max(value, lowerBound), upperBound);
end

function parameters = validate_parameters(parameters)
requiredScalar = {'sample_time_s'; 'end_time_s'; 'capacity_Ah'; ...
    'initial_soc'; 'minimum_reserve_soc'; 'maximum_soc'; ...
    'reserve_taper_width_soc'; 'charge_taper_width_soc'; ...
    'ocv_intercept_V'; 'ocv_slope_V_per_soc'; ...
    'internal_resistance_Ohm'; 'maximum_discharge_current_A'; ...
    'maximum_charge_current_A'; 'dc_link_capacitance_F'; ...
    'dc_voltage_reference_V'; 'initial_dc_voltage_V'; ...
    'minimum_dc_voltage_V'; 'maximum_dc_voltage_V'; ...
    'dc_energy_feedback_gain_per_s'};
requiredVectors = {'request_breakpoints_s'; ...
    'requested_converter_power_W'};
if ~isstruct(parameters) || ~all(isfield(parameters, ...
        [requiredScalar; requiredVectors]))
    error('BessDcReserve:Parameters', ...
        'Parameter structure is missing one or more required fields.');
end
for fieldIndex = 1:numel(requiredScalar)
    value = parameters.(requiredScalar{fieldIndex});
    if ~isnumeric(value) || ~isscalar(value) || ~isreal(value) || ...
            ~isfinite(value)
        error('BessDcReserve:Parameters', ...
            'Every scalar parameter must be finite and real.');
    end
end
for fieldIndex = 1:numel(requiredVectors)
    value = parameters.(requiredVectors{fieldIndex});
    if ~isnumeric(value) || ~isvector(value) || ~isreal(value) || ...
            isempty(value) || any(~isfinite(value))
        error('BessDcReserve:Parameters', ...
            'Power-profile parameters must be finite real vectors.');
    end
end
positiveFields = {'sample_time_s'; 'end_time_s'; 'capacity_Ah'; ...
    'reserve_taper_width_soc'; 'charge_taper_width_soc'; ...
    'ocv_intercept_V'; 'internal_resistance_Ohm'; ...
    'maximum_discharge_current_A'; 'maximum_charge_current_A'; ...
    'dc_link_capacitance_F'; 'dc_voltage_reference_V'; ...
    'initial_dc_voltage_V'; 'minimum_dc_voltage_V'; ...
    'maximum_dc_voltage_V'; 'dc_energy_feedback_gain_per_s'};
if any(cellfun(@(fieldName) parameters.(fieldName) <= 0, ...
        positiveFields)) || parameters.ocv_slope_V_per_soc < 0
    error('BessDcReserve:Parameters', ...
        'Physical, time, and controller parameters are inconsistent.');
end
if parameters.minimum_reserve_soc < 0 || ...
        parameters.maximum_soc > 1 || ...
        parameters.minimum_reserve_soc >= parameters.initial_soc || ...
        parameters.initial_soc >= parameters.maximum_soc || ...
        parameters.reserve_taper_width_soc > ...
        parameters.maximum_soc - parameters.minimum_reserve_soc || ...
        parameters.charge_taper_width_soc > ...
        parameters.maximum_soc - parameters.minimum_reserve_soc
    error('BessDcReserve:SocLimits', ...
        'SOC initial condition, bounds, and taper widths are inconsistent.');
end
if parameters.minimum_dc_voltage_V >= ...
        parameters.dc_voltage_reference_V || ...
        parameters.dc_voltage_reference_V >= ...
        parameters.maximum_dc_voltage_V || ...
        parameters.initial_dc_voltage_V < ...
        parameters.minimum_dc_voltage_V || ...
        parameters.initial_dc_voltage_V > ...
        parameters.maximum_dc_voltage_V
    error('BessDcReserve:DcLimits', ...
        'DC-link voltage initial condition and limits are inconsistent.');
end
capacityAs = parameters.capacity_Ah*3600;
effectiveResistance_Ohm = parameters.internal_resistance_Ohm + ...
    0.5*parameters.ocv_slope_V_per_soc*parameters.sample_time_s/ ...
    capacityAs;
minimumOcv_V = parameters.ocv_intercept_V + ...
    parameters.ocv_slope_V_per_soc*parameters.minimum_reserve_soc;
if parameters.maximum_discharge_current_A >= ...
        minimumOcv_V/(2*effectiveResistance_Ohm)
    error('BessDcReserve:CurrentLimit', ...
        ['Maximum discharge current must stay on the monotonic ', ...
        'low-current power branch at minimum SOC.']);
end
if parameters.dc_energy_feedback_gain_per_s* ...
        parameters.sample_time_s > 1
    error('BessDcReserve:ControlGain', ...
        'DC-energy feedback gain times sample time must not exceed one.');
end
breakpoints = parameters.request_breakpoints_s(:);
powerValues = parameters.requested_converter_power_W(:);
if numel(breakpoints) ~= numel(powerValues) || breakpoints(1) ~= 0 || ...
        any(diff(breakpoints) <= 0) || breakpoints(end) >= ...
        parameters.end_time_s
    error('BessDcReserve:Profile', ...
        'Power-profile vectors must be paired, ordered, and start at zero.');
end
alignedTimes = [parameters.end_time_s; breakpoints]/ ...
    parameters.sample_time_s;
if any(abs(alignedTimes - round(alignedTimes)) > 1e-10)
    error('BessDcReserve:TimeGrid', ...
        'End time and power breakpoints must align with the sample time.');
end
end
