%% Temperature-Aware Battery Model Check
% Validates state bounds, constitutive relations, and discrete balances.

clear; clc;

modelDirectory = fileparts(mfilename('fullpath'));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory);

profile = battery_thermal_default_profile();
parameters = battery_thermal_default_parameters();
result = simulate_battery_thermal_model(profile, parameters, 1);

assert(numel(result.time_s) == 1801 && result.dt_s == 1, ...
    'Canonical result must cover 1800 seconds at 1 Hz.');
assert(all(isfinite(result.soc)) && all(isfinite(result.v_rc_V)) && ...
    all(isfinite(result.cell_temp_C)) && ...
    all(isfinite(result.terminal_voltage_V)), ...
    'Every state and terminal-voltage sample must remain finite.');
assert(all(result.soc >= 0 & result.soc <= 1), ...
    'SOC must remain within [0, 1].');
assert(all(result.cell_temp_C >= parameters.ambient_temp_C - 1e-9), ...
    'This pulse case should not cool below the fixed ambient temperature.');
assert(max(result.cell_temp_C) > parameters.ambient_temp_C + 5 && ...
    max(result.cell_temp_C) < 45, ...
    'The pulse case must produce a visible but bounded temperature rise.');
assert(min(result.r0_Ohm) < parameters.r0_reference_Ohm, ...
    'Ohmic resistance should decrease as cell temperature rises.');
assert(all(result.heat_generation_W >= -1e-9), ...
    'Irreversible heat should remain nonnegative for this pulse case.');

expectedResistance_Ohm = parameters.r0_reference_Ohm * exp(...
    parameters.resistance_temp_coefficient_per_C * ...
    (parameters.reference_temp_C - result.cell_temp_C));
assert(max(abs(result.r0_Ohm - expectedResistance_Ohm)) < 1e-14, ...
    'Resistance must follow the configured temperature relation.');
expectedOcv_V = parameters.ocv_nominal_V + ...
    parameters.ocv_soc_slope_V * (result.soc - 0.5);
assert(max(abs(result.ocv_V - expectedOcv_V)) < 1e-14, ...
    'OCV must follow the configured affine SOC relation.');
expectedTerminal_V = result.ocv_V - ...
    result.current_A .* result.r0_Ohm - result.v_rc_V;
assert(max(abs(result.terminal_voltage_V - expectedTerminal_V)) < 1e-12, ...
    'Terminal voltage must close the electrical balance at every sample.');
expectedHeat_W = result.current_A .* (...
    result.current_A .* result.r0_Ohm + result.v_rc_V);
assert(max(abs(result.heat_generation_W - expectedHeat_W)) < 1e-12, ...
    'Heat generation must equal the equivalent-circuit loss power.');
expectedCooling_W = parameters.heat_transfer_W_per_K * ...
    (result.cell_temp_C - parameters.ambient_temp_C);
assert(max(abs(result.cooling_power_W - expectedCooling_W)) < 1e-12, ...
    'Cooling must equal conductance times temperature rise.');
assert(max(abs(result.net_heat_W - ...
    (result.heat_generation_W - result.cooling_power_W))) < 1e-12, ...
    'Net heat must equal generation minus ambient cooling.');
assert(abs(result.energy_balance_error_J) < 1e-6, ...
    'Discrete thermal energy balance is inconsistent.');

customProfile = table(...
    [0; 5; 15; 30], ...
    [0; 40; -10; 0], ...
    'VariableNames', {'time_s', 'current_A'});
customParameters = parameters;
customParameters.ambient_temp_C = 20;
customParameters.initial_cell_temp_C = 22;
customParameters.heat_transfer_W_per_K = 2.0;
customResult = simulate_battery_thermal_model(...
    customProfile, customParameters, 0.5);
assert(customResult.dt_s == 0.5 && numel(customResult.time_s) == 61, ...
    'Custom case must use the requested uniform output grid.');
assert(customResult.current_A(11) == 40 && ...
    customResult.current_A(31) == -10 && ...
    customResult.current_A(end) == 0, ...
    'Custom profile must preserve right-continuous current transitions.');
assert(max(customResult.cell_temp_C) > customResult.cell_temp_C(1), ...
    'Custom current pulse must exercise electrical-to-thermal feedback.');

irregularProfile = table(...
    [0; 0.5; 1.5; 2.0], ...
    [5; -2; 3; 0], ...
    'VariableNames', {'time_s', 'current_A'});
irregularResult = simulate_battery_thermal_model(...
    irregularProfile, parameters);
assert(isempty(irregularResult.dt_s) && ...
    isequal(irregularResult.interval_s, diff(irregularProfile.time_s)), ...
    'Native irregular timestamps must remain unchanged.');

invalidParameters = parameters;
invalidParameters.cell_mass_kg = 0;
invalidParameterRejected = false;
try
    simulate_battery_thermal_model(profile, invalidParameters, 1);
catch validationError
    invalidParameterRejected = strcmp(validationError.identifier, ...
        'BatteryThermal:Parameters');
end
assert(invalidParameterRejected, ...
    'Simulator must reject nonpositive cell mass.');

unstableStepRejected = false;
try
    simulate_battery_thermal_model(profile, parameters, 10);
catch validationError
    unstableStepRejected = strcmp(validationError.identifier, ...
        'BatteryThermal:TimeStepStability');
end
assert(unstableStepRejected, ...
    'Simulator must reject an unstable explicit-Euler time step.');

repeatResult = simulate_battery_thermal_model(profile, parameters, 1);
assert(isequal(result.soc, repeatResult.soc) && ...
    isequal(result.v_rc_V, repeatResult.v_rc_V) && ...
    isequal(result.cell_temp_C, repeatResult.cell_temp_C) && ...
    isequal(result.terminal_voltage_V, ...
        repeatResult.terminal_voltage_V), ...
    'Repeated thermal simulation must be deterministic.');

fprintf('Battery thermal check passed.\n');
fprintf('Peak cell temperature: %.2f degC\n', max(result.cell_temp_C));
fprintf('Final cell temperature: %.2f degC\n', result.cell_temp_C(end));
fprintf('Peak irreversible heat: %.2f W\n', ...
    max(result.heat_generation_W));
fprintf('Final SOC: %.3f\n', result.soc(end));
