%% Temperature-Aware Battery Model Check
% Validates state bounds, constitutive relations, and discrete balances.

clear; clc;

modelDirectory = fileparts(mfilename('fullpath'));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory);

profile = battery_thermal_default_profile();
parameters = battery_thermal_default_parameters();
result = simulate_battery_thermal_model(profile, parameters, 1);

assert(numel(result.time_s) == 1801 && result.dt_s == 1, ...
    'Canonical result must cover 1800 seconds at 1 Hz.');
assert(all(isfinite(result.soc)) && all(isfinite(result.v_rc_V)) && ...
    all(isfinite(result.cell_temp_C)) && ...
    all(isfinite(result.terminal_voltage_V)) && ...
    all(isfinite(result.reversible_heat_W)) && ...
    all(isfinite(result.total_heat_generation_W)), ...
    'Every state, voltage, and heat-flow sample must remain finite.');
assert(all(result.soc >= 0 & result.soc <= 1), ...
    'SOC must remain within [0, 1].');
assert(all(result.cell_temp_C >= parameters.ambient_temp_C - 1e-9), ...
    'This pulse case should not cool below the fixed ambient temperature.');
assert(max(result.cell_temp_C) > parameters.ambient_temp_C + 5 && ...
    max(result.cell_temp_C) < 45, ...
    'The pulse case must produce a visible but bounded temperature rise.');
assert(min(result.r0_Ohm) < parameters.r0_reference_Ohm, ...
    'Ohmic resistance should decrease as cell temperature rises.');
assert(all(result.heat_generation_W >= -1e-9), ...
    'Irreversible heat should remain nonnegative for this pulse case.');

expectedResistance_Ohm = parameters.r0_reference_Ohm * exp(...
    parameters.resistance_temp_coefficient_per_C * ...
    (parameters.reference_temp_C - result.cell_temp_C));
assert(max(abs(result.r0_Ohm - expectedResistance_Ohm)) < 1e-14, ...
    'Resistance must follow the configured temperature relation.');
expectedOcv_V = parameters.ocv_nominal_V + ...
    parameters.ocv_soc_slope_V * (result.soc - 0.5);
assert(max(abs(result.ocv_V - expectedOcv_V)) < 1e-14, ...
    'OCV must follow the configured affine SOC relation.');
expectedTerminal_V = result.ocv_V - ...
    result.current_A .* result.r0_Ohm - result.v_rc_V;
assert(max(abs(result.terminal_voltage_V - expectedTerminal_V)) < 1e-12, ...
    'Terminal voltage must close the electrical balance at every sample.');
expectedHeat_W = result.current_A .* (...
    result.current_A .* result.r0_Ohm + result.v_rc_V);
assert(max(abs(result.heat_generation_W - expectedHeat_W)) < 1e-12, ...
    'Irreversible heat must equal the equivalent-circuit loss power.');
expectedEntropicCoefficient_V_per_K = interp1(...
    parameters.entropic_soc_breakpoints, ...
    parameters.entropic_coefficient_V_per_K, result.soc, 'linear');
assert(max(abs(result.entropic_coefficient_V_per_K - ...
    expectedEntropicCoefficient_V_per_K)) < 1e-14, ...
    'Entropic coefficient must follow the configured SOC lookup table.');
expectedReversibleHeat_W = -result.current_A .* ...
    (result.cell_temp_C + 273.15) .* ...
    expectedEntropicCoefficient_V_per_K;
assert(max(abs(result.reversible_heat_W - ...
    expectedReversibleHeat_W)) < 1e-12, ...
    'Reversible heat must follow the signed entropic relation.');
expectedTotalHeat_W = expectedHeat_W + expectedReversibleHeat_W;
assert(max(abs(result.total_heat_generation_W - ...
    expectedTotalHeat_W)) < 1e-12, ...
    'Total heat must equal irreversible plus reversible heat.');
activeReversibleHeat_W = result.reversible_heat_W(result.current_A ~= 0);
assert(any(activeReversibleHeat_W < 0) && ...
    any(activeReversibleHeat_W > 0), ...
    'Canonical pulses must exercise endothermic and exothermic entropic heat.');
expectedCooling_W = parameters.heat_transfer_W_per_K * ...
    (result.cell_temp_C - parameters.ambient_temp_C);
assert(max(abs(result.cooling_power_W - expectedCooling_W)) < 1e-12, ...
    'Cooling must equal conductance times temperature rise.');
assert(max(abs(result.net_heat_W - ...
    (result.total_heat_generation_W - ...
    result.cooling_power_W))) < 1e-12, ...
    'Net heat must equal total generation minus ambient cooling.');
assert(abs(result.energy_balance_error_J) < 1e-6, ...
    'Discrete thermal energy balance is inconsistent.');

limitSummary = summarize_battery_temperature_limits(...
    result, [30; 35; 37; 45]);
assert(isequal(limitSummary.limit_temperature_C, [30; 35; 37; 45]) && ...
    isequal(limitSummary.exceeded, [true; true; false; false]), ...
    'Limit summary must preserve order and classify canonical limits.');
assert(all(diff(limitSummary.first_exceedance_time_s(1:2)) > 0) && ...
    all(diff(limitSummary.time_above_limit_s(1:2)) < 0) && ...
    all(limitSummary.margin_to_limit_C(1:2) < 0) && ...
    all(limitSummary.margin_to_limit_C(3:4) > 0), ...
    'Higher limits must cross later, shorten exposure, and preserve margin sign.');
firstAbove35 = find(result.cell_temp_C > 35, 1, 'first');
previousSample = firstAbove35 - 1;
expectedFirst35_s = result.time_s(previousSample) + ...
    (35 - result.cell_temp_C(previousSample)) / ...
    (result.cell_temp_C(firstAbove35) - ...
    result.cell_temp_C(previousSample)) * ...
    (result.time_s(firstAbove35) - result.time_s(previousSample));
assert(abs(limitSummary.first_exceedance_time_s(2) - ...
    expectedFirst35_s) < 1e-12, ...
    'First exceedance must use linear interpolation between result states.');

syntheticResult.time_s = [0; 5; 20];
syntheticResult.cell_temp_C = [20; 30; 20];
syntheticLimits = summarize_battery_temperature_limits(...
    syntheticResult, [25; 30]);
assert(syntheticLimits.first_exceedance_time_s(1) == 2.5 && ...
    syntheticLimits.time_above_limit_s(1) == 10 && ...
    syntheticLimits.exposure_fraction(1) == 0.5 && ...
    syntheticLimits.margin_to_limit_C(1) == -5, ...
    'Irregular heating and cooling crossings must use actual interval lengths.');
assert(~syntheticLimits.exceeded(2) && ...
    isnan(syntheticLimits.first_exceedance_time_s(2)) && ...
    syntheticLimits.time_above_limit_s(2) == 0 && ...
    syntheticLimits.margin_to_limit_C(2) == 0, ...
    'Touching the peak limit must not count as an exceedance.');

initialHotResult.time_s = [10; 20];
initialHotResult.cell_temp_C = [30; 20];
initialHotLimit = summarize_battery_temperature_limits(...
    initialHotResult, 25);
assert(initialHotLimit.first_exceedance_time_s == 10 && ...
    initialHotLimit.time_above_limit_s == 5, ...
    'An initially hot trace must report the first timestamp and cooling crossing.');

reportPath = [tempname, '.csv'];
writetable(limitSummary, reportPath);
roundTripSummary = readtable(reportPath);
delete(reportPath);
assert(isequal(roundTripSummary.limit_temperature_C, ...
    limitSummary.limit_temperature_C) && ...
    isequal(logical(roundTripSummary.exceeded), limitSummary.exceeded) && ...
    max(abs(roundTripSummary.time_above_limit_s - ...
    limitSummary.time_above_limit_s)) < 1e-9, ...
    'Limit summary must retain its engineering values through CSV export.');

customProfile = table(...
    [0; 5; 15; 30], ...
    [0; 40; -10; 0], ...
    'VariableNames', {'time_s', 'current_A'});
customParameters = parameters;
customParameters.ambient_temp_C = 20;
customParameters.initial_cell_temp_C = 22;
customParameters.heat_transfer_W_per_K = 2.0;
customResult = simulate_battery_thermal_model(...
    customProfile, customParameters, 0.5);
assert(customResult.dt_s == 0.5 && numel(customResult.time_s) == 61, ...
    'Custom case must use the requested uniform output grid.');
assert(customResult.current_A(11) == 40 && ...
    customResult.current_A(31) == -10 && ...
    customResult.current_A(end) == 0, ...
    'Custom profile must preserve right-continuous current transitions.');
assert(max(customResult.cell_temp_C) > customResult.cell_temp_C(1), ...
    'Custom current pulse must exercise electrical-to-thermal feedback.');

irregularProfile = table(...
    [0; 0.5; 1.5; 2.0], ...
    [5; -2; 3; 0], ...
    'VariableNames', {'time_s', 'current_A'});
irregularResult = simulate_battery_thermal_model(...
    irregularProfile, parameters);
assert(isempty(irregularResult.dt_s) && ...
    isequal(irregularResult.interval_s, diff(irregularProfile.time_s)), ...
    'Native irregular timestamps must remain unchanged.');
irregularLimit = summarize_battery_temperature_limits(...
    irregularResult, parameters.initial_cell_temp_C + 0.001);
assert(irregularLimit.exposure_fraction >= 0 && ...
    irregularLimit.exposure_fraction <= 1, ...
    'Irregular simulation exposure fraction must remain bounded.');

invalidParameters = parameters;
invalidParameters.cell_mass_kg = 0;
invalidParameterRejected = false;
try
    simulate_battery_thermal_model(profile, invalidParameters, 1);
catch validationError
    invalidParameterRejected = strcmp(validationError.identifier, ...
        'BatteryThermal:Parameters');
end
assert(invalidParameterRejected, ...
    'Simulator must reject nonpositive cell mass.');

invalidEntropicParameters = parameters;
invalidEntropicParameters.entropic_soc_breakpoints = [0, 0.5, 0.5, 1];
invalidEntropicParameters.entropic_coefficient_V_per_K = ...
    [0, 1e-4, 2e-4, 0];
invalidEntropicTableRejected = false;
try
    simulate_battery_thermal_model(...
        profile, invalidEntropicParameters, 1);
catch validationError
    invalidEntropicTableRejected = strcmp(validationError.identifier, ...
        'BatteryThermal:EntropicTable');
end
assert(invalidEntropicTableRejected, ...
    'Simulator must reject repeated entropic SOC breakpoints.');

mismatchedEntropicParameters = parameters;
mismatchedEntropicParameters.entropic_coefficient_V_per_K = [0, 1e-4];
mismatchedEntropicTableRejected = false;
try
    simulate_battery_thermal_model(...
        profile, mismatchedEntropicParameters, 1);
catch validationError
    mismatchedEntropicTableRejected = strcmp(validationError.identifier, ...
        'BatteryThermal:EntropicTable');
end
assert(mismatchedEntropicTableRejected, ...
    'Simulator must reject unequal entropic lookup vector lengths.');

invalidTemperatureParameters = parameters;
invalidTemperatureParameters.initial_cell_temp_C = -273.15;
invalidTemperatureRejected = false;
try
    simulate_battery_thermal_model(...
        profile, invalidTemperatureParameters, 1);
catch validationError
    invalidTemperatureRejected = strcmp(validationError.identifier, ...
        'BatteryThermal:Parameters');
end
assert(invalidTemperatureRejected, ...
    'Simulator must reject configured temperatures at absolute zero.');

zeroEntropicParameters = parameters;
zeroEntropicParameters.entropic_coefficient_V_per_K(:) = 0;
zeroEntropicResult = simulate_battery_thermal_model(...
    profile, zeroEntropicParameters, 1);
assert(all(zeroEntropicResult.reversible_heat_W == 0) && ...
    isequal(zeroEntropicResult.total_heat_generation_W, ...
    zeroEntropicResult.heat_generation_W), ...
    'Zero entropic coefficients must recover irreversible-only heat exactly.');

unstableStepRejected = false;
try
    simulate_battery_thermal_model(profile, parameters, 10);
catch validationError
    unstableStepRejected = strcmp(validationError.identifier, ...
        'BatteryThermal:TimeStepStability');
end
assert(unstableStepRejected, ...
    'Simulator must reject an unstable explicit-Euler time step.');

invalidLimitCases = {
    rmfield(result, 'cell_temp_C'), 35, ...
        'BatteryThermalLimits:ResultFields';
    setfield(result, 'cell_temp_C', ... %#ok<SFLD>
        result.cell_temp_C(1:end-1)), 35, ...
        'BatteryThermalLimits:SignalShape';
    setfield(result, 'time_s', ... %#ok<SFLD>
        [result.time_s(1); result.time_s(1:end-1)]), 35, ...
        'BatteryThermalLimits:TimeOrder';
    setfield(result, 'cell_temp_C', ... %#ok<SFLD>
        [-273.15; result.cell_temp_C(2:end)]), 35, ...
        'BatteryThermalLimits:TemperatureBounds';
    result, [], 'BatteryThermalLimits:Limits';
    result, [35, NaN], 'BatteryThermalLimits:Limits';
    result, -273.15, 'BatteryThermalLimits:LimitBounds';
    result, [35, 35], 'BatteryThermalLimits:UniqueLimits'
};
for caseIndex = 1:size(invalidLimitCases, 1)
    rejected = false;
    try
        summarize_battery_temperature_limits(...
            invalidLimitCases{caseIndex, 1}, ...
            invalidLimitCases{caseIndex, 2});
    catch validationError
        rejected = strcmp(validationError.identifier, ...
            invalidLimitCases{caseIndex, 3});
    end
    assert(rejected, ...
        'Temperature-limit summary must reject malformed input deterministically.');
end

repeatResult = simulate_battery_thermal_model(profile, parameters, 1);
assert(isequal(result.soc, repeatResult.soc) && ...
    isequal(result.v_rc_V, repeatResult.v_rc_V) && ...
    isequal(result.cell_temp_C, repeatResult.cell_temp_C) && ...
    isequal(result.terminal_voltage_V, ...
        repeatResult.terminal_voltage_V), ...
    'Repeated thermal simulation must be deterministic.');

fprintf('Battery thermal check passed.\n');
fprintf('Peak cell temperature: %.2f degC\n', max(result.cell_temp_C));
fprintf('Final cell temperature: %.2f degC\n', result.cell_temp_C(end));
fprintf('Peak irreversible heat: %.2f W\n', ...
    max(result.heat_generation_W));
fprintf('Reversible heat range: %.2f W to %.2f W\n', ...
    min(result.reversible_heat_W), max(result.reversible_heat_W));
fprintf('Peak total heat: %.2f W\n', ...
    max(result.total_heat_generation_W));
fprintf('Final SOC: %.3f\n', result.soc(end));
