%% Battery Cooling-Sensitivity Study Check
% Validates comparison metrics, ordering, and malformed-input handling.

clear; clc;

modelDirectory = fileparts(mfilename('fullpath'));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(modelDirectory);

profile = battery_thermal_default_profile();
parameters = battery_thermal_default_parameters();
heatTransferValues_W_per_K = [0; 0.6; 1.2; 2.4; 4.8];
limitTemperature_C = 35;
comparison = compare_battery_cooling_sensitivity(...
    profile, parameters, heatTransferValues_W_per_K, ...
    limitTemperature_C, 1);
summary = comparison.summary;

assert(height(summary) == numel(heatTransferValues_W_per_K) && ...
    isequal(summary.heat_transfer_W_per_K, ...
    heatTransferValues_W_per_K), ...
    'The comparison must preserve every requested cooling case in order.');
assert(numel(comparison.results) == height(summary) && ...
    comparison.limit_temperature_C == limitTemperature_C && ...
    comparison.dt_s == 1, ...
    'Comparison metadata or retained case results are incomplete.');
assert(all(isfinite(summary{:,:}), 'all'), ...
    'Every reported cooling-sensitivity metric must be finite.');
assert(all(diff(summary.peak_temperature_C) <= 1e-10) && ...
    all(diff(summary.final_temperature_C) <= 1e-10), ...
    'Increasing cooling must not increase canonical peak or final temperature.');
assert(all(diff(summary.time_above_limit_s) <= 1e-10) && ...
    all(diff(summary.degree_hours_above_limit_C_h) <= 1e-10) && ...
    all(diff(summary.exposure_fraction) <= 1e-12), ...
    'Increasing cooling must not increase canonical temperature-limit exposure.');
assert(summary.net_cooling_energy_Wh(1) == 0 && ...
    all(summary.net_cooling_energy_Wh(2:end) > 0), ...
    'Zero conductance must remove no heat and cooled cases must remove heat.');
assert(max(abs(summary.final_soc - summary.final_soc(1))) < 1e-14, ...
    'Cooling must not alter SOC under this prescribed-current model.');

for caseIndex = 1:numel(comparison.results)
    result = comparison.results{caseIndex};
    assert(result.parameters.heat_transfer_W_per_K == ...
        heatTransferValues_W_per_K(caseIndex), ...
        'A retained case uses the wrong heat-transfer value.');
    assert(abs(max(result.cell_temp_C) - ...
        summary.peak_temperature_C(caseIndex)) < 1e-12, ...
        'The summary peak must match its retained simulation result.');
end

preservedOrderValues = [2.4; 0; 1.2];
preservedOrder = compare_battery_cooling_sensitivity(...
    profile, parameters, preservedOrderValues, limitTemperature_C, 1);
assert(isequal(preservedOrder.summary.heat_transfer_W_per_K, ...
    preservedOrderValues), ...
    'A comparison must not silently sort requested cooling cases.');

invalidCases = {
    [], limitTemperature_C, 'BatteryCoolingStudy:HeatTransferValues';
    [-1; 1], limitTemperature_C, 'BatteryCoolingStudy:HeatTransferValues';
    [1; NaN], limitTemperature_C, 'BatteryCoolingStudy:HeatTransferValues';
    [1; 1], limitTemperature_C, 'BatteryCoolingStudy:HeatTransferValues';
    1, -273.15, 'BatteryCoolingStudy:LimitTemperature';
    1, [30; 35], 'BatteryCoolingStudy:LimitTemperature'
};
for caseIndex = 1:size(invalidCases, 1)
    rejected = false;
    try
        compare_battery_cooling_sensitivity(...
            profile, parameters, invalidCases{caseIndex, 1}, ...
            invalidCases{caseIndex, 2}, 1);
    catch validationError
        rejected = strcmp(validationError.identifier, ...
            invalidCases{caseIndex, 3});
    end
    assert(rejected, ...
        'Cooling-sensitivity study must reject malformed inputs.');
end

fprintf('Battery cooling-sensitivity check passed.\n');
fprintf(['hA (W/K)  Peak (degC)  Final (degC)  Time > %.1f degC (s)  ' ...
    'Degree-hours\n'], limitTemperature_C);
for caseIndex = 1:height(summary)
    fprintf('%8.1f %12.2f %13.2f %21.1f %13.4f\n', ...
        summary.heat_transfer_W_per_K(caseIndex), ...
        summary.peak_temperature_C(caseIndex), ...
        summary.final_temperature_C(caseIndex), ...
        summary.time_above_limit_s(caseIndex), ...
        summary.degree_hours_above_limit_C_h(caseIndex));
end
